### ISSUE TITLE
Prevent Running Commands that Target Windows When the Host OS is not Windows

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1010]
### Describe the bug

Running Briefcase commands for the Windows platform only works when the host OS is Windows. However, Briefcase does not inform the user of this and instead attempts to perform the Command resulting in confusing errors.

Example:
- #1009 

### Steps to reproduce

Run `briefcase build windows` on macOS or Linux.

### Expected behavior

Emit a simple warning informing users.

### Environment

- Operating System: pop os 22.04
- Python version: 3.10.8
- Software versions:
  - Briefcase: `0.3.12.dev251+g6d29ece1`

### Additional context

This behavior changed in `v0.3.9`. Previously, these Commands would have aborted when `WiX` was verified. But `WiX` is only verified now for the Package Command.

**Comment by freakboy3742** [comment]
Definitely an oversight. We've got analogous platform checks on the Linux backends; adding a comparable check to Windows backends definitely makes sense.
