### ISSUE TITLE
AppImage / Allow Updates to `dockerfile_extra_content` Without Requiring the Create Command to Run Again

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1015]
### What is the problem or limitation you are having?

Currently, `Dockerfile` can be augmented by the value of `dockerfile_extra_content` in `pyproject.toml`. However, `dockerfile_extra_content` is only added to `Dockerfile` when AppImage template is created. When `dockerfile_extra_content` is updated, those changes are not reflected in `Dockerfile`.

Therefore, users must run `briefcase create` to manifest changes to `dockerfile_extra_content` in the project.

Similar work:
- #796
- #801 

### Describe the solution you'd like

Changes to `dockerfile_extra_content` should be applied to `Dockerfile` any time the `app_context` tool is instantiated.

### Describe alternatives you've considered

Running `briefcase create` mitigates the issue by recreated `Dockerfile` ensuring it contains `dockerfile_extra_content`.

**Comment by freakboy3742** [comment]
I'm pretty sure this is a variant on #472 - the need to update existing templated content as part of the `update` call (or, at least, without deleting and re-running `create`). Closing as a duplicate.
