### ISSUE TITLE
app icons

### ISSUE THREAD

**Issue by coolcoder613eb** [beeware/briefcase#1035]
### Describe the bug

I have not been able change the default icon for my app,
I have set all icon properties in the pyproject.toml,
and I have changed the icons in src\appname\resources for png, ico and icns.
the icon in the title bar has been changed,
but the icon of the executable has not.

### Steps to reproduce

1. clone https://github.com/coolcoder613eb/beeware-console
2. on the command line, navigate to the `console` directory
3. run `briefcase package -u`
4. run the resulting msi
5. observe the program's start menu shortcut
OR
3. run `briefcase run android -u`
4. exit the program, and observe the program icon

### Expected behavior

the program icon to match the icon I have provided

### Environment

- Operating System:
- windows 11
- Python version:
- 3.10
- Software versions:
  - Briefcase: briefcase==0.3.11
  - Toga: toga-core==0.3.0.dev39
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
You haven't provided the icons required. 

The [docs for the android backend](https://briefcase.readthedocs.io/en/stable/reference/platforms/android.html#icon-format) describe that you need to provide 5 different icon sizes, in 2 different shapes; If you look at the log of `briefcase create android`, you'll see the following:
```
[console] Installing application resources...
Unable to find 48px round variant for application icon; using default
Unable to find 72px round variant for application icon; using default
Unable to find 96px round variant for application icon; using default
Unable to find 144px round variant for application icon; using default
Unable to find 192px round variant for application icon; using default
Unable to find 48px square variant for application icon; using default
Unable to find 72px square variant for application icon; using default
Unable to find 96px square variant for application icon; using default
Unable to find 144px square variant for application icon; using default
Unable to find 192px square variant for application icon; using default
```

If you're on Briefcase 0.3.11, you'll also need a specific Android icon configuration:
```
icon.square = "src/console/resources/console-square"
icon.round = "src/console/resources/console-round"
```
and then provide 10 different icon images, in the required sizes. The filenames will be reported when you run `briefcase update android -r` to update resources.

The upcoming v0.3.12 release cleans this up and you won't need the extra configuration.

**Comment by coolcoder613eb** [comment]
is it possible to have briefcase auto-resize?

**Comment by coolcoder613eb** [comment]
windows is the same problem?

**Comment by freakboy3742** [comment]
It works for me on Windows.

<img width="155" alt="Screen Shot 2023-01-06 at 9 50 38 am" src="https://user-images.githubusercontent.com/37345/210915147-29b86b88-8899-4559-b663-ba789fc70378.png">
<img width="68" alt="Screen Shot 2023-01-06 at 9 50 42 am" src="https://user-images.githubusercontent.com/37345/210915175-e3fea91b-b4f4-4d90-bfe6-ad6304ac40da.png">

Auto-resizing is a feature that has been requested: #386.

**Comment by freakboy3742** [comment]
`briefcase create`. If the icons have been added after initial creation of the project, you may need to run `briefcase update -r` to get the icons to be updated.

**Comment by coolcoder613eb** [comment]
thanks,
i have not run update -r

**Comment by coolcoder613eb** [comment]
the script from https://github.com/beeware/briefcase/issues/386#issuecomment-800547296
was helpful
