### ISSUE TITLE
Android emulator acceleration messages may lead the user to install an incompatible version of HAXM

### ISSUE THREAD

**Issue by MarkusPiotrowski** [beeware/briefcase#1036]
### Describe the bug

The Android emulator fails with the error messages `Failed to sync vcpu reg` when the latest version of Intel's Hardware Accelerated Execution Manager, version 7.8.0, is installed. Installing version 7.7.1 makes it running.

### Steps to reproduce

1. Download version 7.8.0 of HAXM here: https://github.com/intel/haxm/releases/
2. Install on a computer with an Intel processor capable of hardware acceleration (vt, vt-x)
3. Run the Android emulator in a beeware project

### Expected behavior

This report is for documentation only. I would expect that the Android emulator which is installed will work with the latest HAXM version. However, it's not even clear to me if this probably is a specific problem of my computer/setup. 

### Environment

- Operating System: Windows 10
- Python version: 3.8.10
- Software versions:
  - Briefcase: 0.3.11
  - Toga: 0.3.0.dev39
  - Android Emulator:
Pkg.UserSrc=false
Pkg.Revision=31.3.14
Pkg.Path=emulator
Pkg.Desc=Android Emulator
Pkg.BuildId=9322596
  
- Processor Intel Core i7-1165G7

### Logs

```
[xxxx] Starting emulator beePhone...
Starting emulator...
INFO    | Android emulator version 31.3.14.0 (build_id 9322596) (CL:N/A)
emulator: INFO: Found systemPath C:\Users\xxxx\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\system-images\android-31\default\x86_64\
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
INFO    | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.
INFO    | added library vulkan-1.dll
INFO    | configAndStartRenderer: setting vsync to 60 hz
INFO    | Sending adb public key [QAAAALNlKwKFLhrFYSmjYGDv5Qdw5yZnjgD40P7fRpSA2WReBVuC9yFeDrY/Tvu8FpUSrKCM/qKwV5vziFOv/HK88PsH6z7p4ZK5xJI2PAZpnBTU/3V6qJmLDO15xbOma5jgISCE4LyHpDF3uPFENA6ibSNBHy3ejb+0Dwx1yz4V1PUxKnLpn+vMmeEQgW0KfyWOAW4FAjrNUk94yiPvzJypqMFDTT4BYnSkikBh87vKt6XOMAhsxs0zf2VRlhHSnuQru3CYRI3/M35xyBkCz6ka1QF+pLjtiicgkXt181/3YK7O2yXIrnynnQclbQRQd5yuYc/oaCISbPZrNNHwG2b1HbvagF/mLz6WVO8HG5T5ETVVhIPw7gsQu3YYcbtu6tpurETSc3DUN/0VksUuIp4cG/xfxzX6OsxN9oU2LdFyVdZIN3NSbTvss1Y82FkROJhhBp0UhO7FKUPCVRqAhYU/KWS/rIGCM643rtrsvypeOyal7JFV2wcyG7sLfaPgRBoMcd3IfOBClPU4nxF0R0P7r5YRbh2SVLPV4IQKBsCzblEIZbQbFIs/r2gU/s5zDsXGx2g7H9MkmGinSJm4tFIjg8E5SRXz2Au8e92vgsdtiNLFnesOCEFn/t7OFbA1AMzrgkYGzF6TSftZSlDsnMr9dHATCBEWjhduYhaO80bk+njWhNDp3wEAAQA= @unknown]
INFO    | injectedQemuChannel!
INFO    | Informing listeners of injection.
INFO    | Rootcanal has  been activated.
HAX is working and emulator runs in fast virt mode.
WARNING | *** No gRPC protection active, consider launching with the -grpc-use-jwt flag.***
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local, auth: none
INFO    | Advertising in: C:\Users\xxxx\AppData\Local\Temp\avd\running\pid_13900.ini
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
INFO    | setDisplayConfigs w 1080 h 2220 dpiX 420 dpiY 420
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
Failed to sync vcpu reg
VCPU shutdown request
VCPU shutdown request
VCPU shutdown request
INFO    | Closing down rootcanal.

Android emulator was unable to start!

Try starting the emulator manually by running:

    $ C:\Users\xxxx\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\emulator\emulator.exe @beePhone -dns-server 8.8.8.8

Resolve any problems you discover, then try running your app again. You may
find this page helpful in diagnosing emulator problems.

    https://developer.android.com/studio/run/emulator-acceleration#accel-vm
```

[briefcase.2023_01_05-02_10_22.run.log](https://github.com/beeware/briefcase/files/10353452/briefcase.2023_01_05-02_10_22.run.log)

**Comment by freakboy3742** [comment]
Agreed that the "start manually" instructions are probably redundant at this point, and a more direct mention of HAXM problems would be more helpful.

**Comment by MarkusPiotrowski** [comment]
Maybe some comments:

1. When running without hardware acceleration, the log looks like so
```
(beeware) PS D:\beeware\scroll_test> briefcase run android

Select device:

  1) @beePhone (emulator)
  2) Create a new Android emulator

> 1

In future, you can specify this device by running:

    $ briefcase run android -d @beePhone

[scroll_test] Starting emulator beePhone...
Starting emulator...
INFO    | Android emulator version 31.3.14.0 (build_id 9322596) (CL:N/A)
emulator: INFO: Found systemPath C:\Users\xxxxxx\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\system-images\android-31\default\x86_64\
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
ERROR   | x86_64 emulation currently requires hardware acceleration!
CPU acceleration status: HAXM is not installed on this machine
More info on configuring VM acceleration on Windows:
https://developer.android.com/studio/run/emulator-acceleration#vm-windows
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

INFO    | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.

Android emulator was unable to start!

Try starting the emulator manually by running:

    $ C:\Users\xxxxxx\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\emulator\emulator.exe @beePhone -dns-server 8.8.8.8

Resolve any problems you discover, then try running your app again. You may
find this page helpful in diagnosing emulator problems.

    https://developer.android.com/studio/run/emulator-acceleration#accel-vm

Log saved to D:\beeware\scroll_test\logs\briefcase.2023_01_06-12_35_22.run.log

(beeware) PS D:\beeware\scroll_test>
```
[briefcase.2023_01_06-12_35_22.run.log](https://github.com/beeware/briefcase/files/10359863/briefcase.2023_01_06-12_35_22.run.log)

2. In my case, HAXM version 7.7.1 is working, but maybe there are other side effects of that version that I'm not aware of.
3. I'd love to install HAXM via the Android SDK, but the only installation of the SDK on my computer (Win 10) comes from beeware/briefcase and is not 'directly visible' to me, e.g. through the task bar. The 'start manually` instructions were helpful in that regard, that I knew where to look for the SDK binaries.  Still, I couldn't find something like an 'android_sdk.exe'. Is there somewhere sort of 'main' Android SDK binary in this installation, or is this 'just' a collection of command-line tools?
4. Do you think the hardware acceleration issue is worth mentioning in the Android tutorial of the documentation? There is already a box entitled 'The emulator didn't start' where this would fit.

**Comment by mhsmith** [comment]
> I'd love to install HAXM via the Android SDK, but the only installation of the SDK on my computer (Win 10) comes from beeware/briefcase and is not 'directly visible' to me, e.g. through the task bar. The 'start manually` instructions were helpful in that regard, that I knew where to look for the SDK binaries. Still, I couldn't find something like an 'android_sdk.exe'. Is there somewhere sort of 'main' Android SDK binary in this installation, or is this 'just' a collection of command-line tools?

There is no graphical SDK manager in the Briefcase-installed SDK: to get that you would need a full Android Studio installation. However, you can download a HAXM installer through the command-line SDK manager like this:
```
path\to\sdk\cmdline-tools\latest\bin\sdkmanager.bat "extras;intel;Hardware_Accelerated_Execution_Manager"
```
This will create the file `path\to\sdk\extras\intel\Hardware_Accelerated_Execution_Manager\haxm-7.6.5-setup.exe`, which you can then run manually.

Since this is the same sequence of commands as Android Studio itself uses, we should probably recommend that rather than downloading HAXM from GitHub. We could even automate it, though if Android is planning to drop HAXM in the near future, it might not be worth the effort.

> Do you think the hardware acceleration issue is worth mentioning in the Android tutorial of the documentation? There is already a box entitled 'The emulator didn't start' where this would fit.

If the messages from Briefcase itself are clear and actionable, I think it's better not to clutter the tutorial with every single thing that could go wrong. I'm sure a lot of users will already feel intimidated by the size of the tutorial as it is.

**Comment by MarkusPiotrowski** [comment]
Agree that 'if messages from Briefcase are clear and actionable' it's better not to clutter the tutorial.

This is a different issue, but the tutorials are rather simple and straightforward which may invite newbies to start developing on Android, but then they may have to face rather complicated issues. I wouldn't call myself a newbie, but (probably worse) I'm a hobby programmer, and I found the issue worth documenting here because my guess would be that many newbies get trapped in this one.
What I'm missing is a *manual* as a bridge between the rather simplistic tutorials and the API.

**Comment by mhsmith** [comment]
There already is a manual at https://briefcase.readthedocs.io/. But usually I think it's better for Briefcase to detect that the user is facing an issue and display instructions in that context, rather than writing them up on a manual page which is much more difficult to discover.

If there are any other cases which you found confusing, please create separate issues for them, and we'll think about how they could be improved.

**Comment by rmartin16** [comment]
Is this resolved with the changes to the emulator startup errors?

**Comment by mhsmith** [comment]
Yes, I think so.
