### ISSUE TITLE
windows custom install directory

### ISSUE THREAD

**Issue by fbe-work** [beeware/briefcase#104]
I could not find a way to have the installer choose another install path (or let the user choose an alternative) other than the default  `C:\Program Files (x86)\MyApp`. 
(hope I did not miss anything obvious)

As this would require elevated permissions, that the actual application does not need, I would love to be able to make it installable without them, so the tool gets adopted more easily.
Maybe @andrewleech has a hint here? Thank you in advance!
I tried messing with briefcase.wxs TARGETDIR or the setup.py options dir but was not successful.

**Comment by andrewleech** [comment]
As you thought, the install location on windows is controlled by the WIX installer project file that's part of the briefcase template:
https://github.com/pybee/Python-Windows-template/blob/3.5/%7B%7B%20cookiecutter.dir_name%20%7D%7D/briefcase.wxs

Did you see the line below the TARGETDIR declared line, did you try changing `ProgramFilesFolder`?
https://github.com/pybee/Python-Windows-template/blob/3.5/%7B%7B%20cookiecutter.dir_name%20%7D%7D/briefcase.wxs#L44

Also, did you change it in the template, or in the already-built copy in the autogenerated windows/content folder? 
I'm pretty sure any changes made there would be overridden the next build. 
You'll need to clone a copy of the template repo, make changes there then tell briefcase to use it, eg. ` python setup.py windows --build --sanitize-version --clean --template .\\installer`

For our project at work I have a fork of the original template project which is modified and then brought in a submodule (at `.\\installer`) to keep track of it.
I haven't tried changing the install folder though.

Perhaps one of these will help?
https://www.joyofsetup.com/2008/04/01/new-wix-feature-setting-package-installation-scope/
https://wrightfully.com/allowing-the-user-to-select-the-install-folder

**Comment by freakboy3742** [comment]
FWIW - if we need to add a flag/option for managing the install directory, That's OK with me. I'm not completely clear what the use case is, but if it's something that is a common requirement for Windows installers, we should be supporting it (or at least providing it as an option)

**Comment by hdm-dt-fb** [comment]
@andrewleech thank you so much for the extensive help!
Yes the settings got overwritten, so I tried to put it into setup.py or run the wix tools seperately on my modified wxs file, for which I earned a heap of errors - adjusting the template sound way smarter! (thanks for the template pointer!) Will try that.
Thank you also for the links - they look very helpful!

@freakboy3742 For me this question on windows has mainly two facets:
a) security: the app and the installer should ideally have the minimum privilege needed
b) convenience: if the tool runs fine with reduced user privs it also should not be needed to call an admin to get it installed (like portable apps)
My guess would be, that for most users at home the default install directory should be ok (they might not necessarily care for a) or b) ) as they are admins on their machines and would generally not see a problem in giving an installer higher privileges(to access the program directory) than the actual app needs. In terms of security I think it would still be great to have the option in this scenario, too.
When tools get installed in coorporate environments, I would see it as quite beneficial for both reasons a) and b)

**Comment by andrewleech** [comment]
As far as exposing options go, I know it's quite common for installers to ask "install for me" or "install for all users". It'd be good if Wix can show that page on the installer by default which would likely solve this issue. 

Similarly most installers give the option to users to put in a manual installing path (eg I install most big apps to a different drive). It would be nice to have an option to show that. 

Judging by the quick scan of the URL I linked this may not be a standard/trivial thing for Wix, so might be hard to do for everyone.

**Comment by tmontes** [comment]
FYI, just submitted a set of PRs that may address @hdm-dt-fb's needs.

**Comment by freakboy3742** [comment]
I'm going to close this in preference for #382; while complete customisability of the install location is probably possible, in practice "user vs system" is the only real option that is needed for most cases (at least, as I understand it).
