### ISSUE TITLE
Bump OpenJDK Version

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1065]
### Describe the bug

The JDK version has been superseded; putting this out there to consider bumping it.

`src/briefcase/integrations/java.py`
```
        # As of April 10 2020, 8u242-b08 is the current AdoptOpenJDK
        # https://adoptopenjdk.net/releases.html
        self.release = "8u242"
        self.build = "b08"
```

Version `jdk8u362-b09` is available.
Additionally, version 11 is also LTS.

There is also this banner at the [website](https://adoptopenjdk.net/releases.html):
24th July 2021: [AdoptOpenJDK is moving to the Eclipse Foundation](https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/) and rebranding.
Our July 2021 and future releases will come from [Adoptium.net](https://www.adoptium.net/)

### Steps to reproduce

`briefcase run android` will require the jdk.

### Expected behavior

Not entirely sure....but it seems like we want to avoid the JDK getting too old.

### Environment

- Operating System: pop os 22.04
- Python version: 3.11
- Software versions:
  - Briefcase: `0.3.12.dev359+gcf18ae8c.d20230128`

**Comment by mhsmith** [comment]
For discussion about Java 8 vs 11, see #827.

**Comment by freakboy3742** [comment]
Keeping this ticket open as a marker for the specific task of upgrading the Java version; #827 is then the co-dependent task of managing any gradle-plugin changes, and the upgrade path related to that.

**Comment by rmartin16** [comment]
FYI. The GitHub runner sets `JAVA_HOME`; appears to be jdk 11. As with the Windows runner where I recently unset `WiX`, may need to consider unsetting `JAVA_HOME` in CI.

```
*************************************************************************
** WARNING: JAVA_HOME does not point to a Java 8 JDK                   **
*************************************************************************
    Android requires a Java 8 JDK, but the location pointed to by the
    JAVA_HOME environment variable:
    /usr/lib/jvm/temurin-11-jdk-amd64
    isn't a Java 8 JDK (it appears to be Java 11.0.[18](https://github.com/beeware/briefcase/actions/runs/4100113254/jobs/7070712081#step:17:19)).
    Briefcase will use its own JDK instance.
*************************************************************************
[java] The Java JDK was not found; downloading and installing...
```

**Comment by mhsmith** [comment]
Related: #1112.
