### ISSUE TITLE
CI Failures on Windows for Python 3.12.0a5

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1087]
### Describe the bug

CI is [failing]( https://github.com/beeware/briefcase/actions/runs/4126241832/jobs/7129016817) on Windows for (recently released) Python 3.12.0a5.

```
==============================================================================
FAIL: tests/platforms/android/gradle/test_create.py::test_extract_packages[test_sources8-"leading"]
------------------------------------------------------------------------------
test_sources=['//leading']
app.test_sources=['//leading']
{'extract_packages': '""',
 'safe_formal_name': 'First App',
 'version_code': '100'}

Traceback (most recent call last):
  File "C:\Users\user\github\beeware\briefcase\tests\platforms\android\gradle\test_create.py", line 112, in test_extract_packages
    assert context["extract_packages"] == expected
AssertionError: assert '""' == '"leading"'
  - "leading"
  + ""

==============================================================================
FAIL: tests/platforms/android/gradle/test_create.py::test_extract_packages[test_sources21-"leading"]
------------------------------------------------------------------------------
test_sources=['\\\\leading']
app.test_sources=['\\\\leading']
{'extract_packages': '""',
 'safe_formal_name': 'First App',
 'version_code': '100'}

Traceback (most recent call last):
  File "C:\Users\user\github\beeware\briefcase\tests\platforms\android\gradle\test_create.py", line 112, in test_extract_packages
    assert context["extract_packages"] == expected
AssertionError: assert '""' == '"leading"'
  - "leading"
  + ""

------------------------------------------------------------------------------
```
(output augmented to include additional information)

### Steps to reproduce

Run [CI](https://github.com/beeware/briefcase/actions/workflows/ci.yml).

### Expected behavior

CI should succeed.

I believe this CPython [change](https://github.com/python/cpython/pull/100351) is causing this new behavior.

I am not entirely sure what is necessary to resolve this, though. Based on the CPython fix, these are not really valid paths for Windows.

Notably, this CPython fix was [backported](https://github.com/python/cpython/pull/100999) to 3.11.

### Environment

- Operating System: Windows 10
- Python version: `3.12.0a5`
- Software versions:
  - Briefcase: `0.3.13.dev33+g8d503064.d20230208`

**Comment by freakboy3742** [comment]
I'd like @mhsmith's take on this to be certain, but I think your analysis is correct - absolute paths are invalid tests in this case. 

I could even see an argument that *paths* are invalid - it's a list of packages that should be extracted, not a list of paths, to my understanding. I *think* the paths will always be "android local" paths, and relative to the bundled Android app, so referring to them as if they were OS-local paths (and using Pathlib, which will use platform-appropriate separators) seems misleading at best.

**Comment by mhsmith** [comment]
These paths are actually from the project's `test_sources` setting, so they are on the build machine, and may be relative or absolute. Unfortunately it looks like there's been a change in the way Python deals with Windows network shares (also called "UNC" paths), which begin with two slashes. I'll look into this today.
