### ISSUE TITLE
ProcessPoolExecutor causes multiple instances of the app to open

### ISSUE THREAD

**Issue by graphitewindows** [beeware/briefcase#1091]
### Describe the bug

I am working on a Toga application that is mostly async but has a CPU-intensive function I am trying to break out into a separate process with ProcessPoolExecutor so as not to block. When I briefcase dev (or python3 -m applicationname in a non-briefcase setup), it works as expected (additional Python processes start up as needed and end when finished). When I briefcase run or briefcase build and launch the application from the Finder, that code launches multiple additional copies of the GUI instead.

Is this expected behavior, or is it an issue with briefcase/macOS and multiple processes? Or just a problem with my code?

### Steps to reproduce

1. Create a briefcase with the following sample code. (See additional context)
2. Open Activity Monitor and filter on Python processes in the CPU tab.
3. Run briefcase dev.
4. Click the button in the window and see new Python processes appear and disappear, but there is only one instance of the GUI.
5. Open Activity Monitor and filter on processes with the name of your sample application (such as Hello World).
6. Run briefcase run or briefcase build and launch the application in the Finder.
8. Click the button in the window and notice multiple instances of the whole application appear on the screen and in Activity Monitor.

### Expected behavior

I expect the behavior of briefcase run or double-clicking the built application icon in the Finder to be the same as the behavior running briefcase dev. That is, a single instance of the GUI application with additional Python processes started as necessary.

### Environment

- Operating System: macOS Monterey 12.6.3
- Python version: Python 3.10.9
- Software versions:
  - Briefcase: 0.3.12
  - Toga: 0.3.0

### Logs

Before clicking the button:
```
(venv) ~/Developer/toga_issue/helloworld % briefcase run

[helloworld] Starting app...
===========================================================================
Configuring isolated Python...
Pre-initializing Python runtime...
PythonHome: /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib
PYTHONPATH:
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python310.zip
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib/lib-dynload
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/app_packages
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/app
Configure argc/argv...
Initializing Python runtime...
Installing Python NSLog handler...
Running app module: helloworld
---------------------------------------------------------------------------
```

After clicking the button:
```
Configuring isolated Python...
Pre-initializing Python runtime...
PythonHome: /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib
PYTHONPATH:
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python310.zip
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib/lib-dynload
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/app_packages
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/app
Configure argc/argv...
Initializing Python runtime...
Configuring isolated Python...
Pre-initializing Python runtime...
PythonHome: /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib
PYTHONPATH:
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python310.zip
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib/lib-dynload
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/app_packages
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/app
Configure argc/argv...
Initializing Python runtime...
Configuring isolated Python...
Pre-initializing Python runtime...
PythonHome: /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib
PYTHONPATH:
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python310.zip
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/support/python-stdlib/lib-dynload
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/app_packages
- /Users/lab/Developer/toga_issue/helloworld/macOS/app/Hello World/Hello World.app/Contents/Resources/app
Configure argc/argv...
Initializing Python runtime...
Installing Python NSLog handler...
Installing Python NSLog handler...
Running app module: helloworld
Installing Python NSLog handler...
Running app module: helloworld
Running app module: helloworld
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
```

### Additional context

Simplified sample code:

```
import asyncio
from concurrent.futures import ProcessPoolExecutor
import time

import toga

class MyApp(toga.App):
    def startup(self):
        self.main_window = toga.MainWindow(title=self.name)
        self.window_box = toga.Box()
        self.main_window.content = self.window_box
        self.action_button = toga.Button('GO', on_press=self.press_go)
        self.window_box.add(self.action_button)
        self.main_window.show()

    async def press_go(self, button):
        loop = asyncio.get_running_loop()
        with ProcessPoolExecutor() as executor:
            task1 = self.do_calculation_in_separate_process(loop, executor)
            task2 = self.do_calculation_in_separate_process(loop, executor)

            self.gathered_tasks = asyncio.gather(task1, task2)
            await self.gathered_tasks

    async def do_calculation_in_separate_process(self, loop, executor):
        await loop.run_in_executor(executor, calculate)

def calculate():
    time.sleep(10)

def main():
    return MyApp()
```

**Comment by freakboy3742** [comment]
Thanks for the report; this is a known bug/issue with the stub application - see [this issue](beeware/briefcase-macOS-Xcode-template#20) for details.

Three possible workarounds:
* Rewrite your processor function as a co-routine. This probably won't help in your specific case; it would keep all the processing in a single process, without locking the GUI - but if the background work is CPU intensive, I'm guessing you're looking to offload to a separate processing context.
* Use a ThreadPoolExecutor, rather than a ProcessPoolExecutor executor. This may result in your code might be slowed due to GIL issues, but it would allow for parallel execution.
* Instead of using a ProcessPoolExecutor, use multiprocessing in fork mode. Fork-based execution isn't subject to the process re-entrancy problem that spawn-based execution have. (Note that the *default* mode for multiprocessing is `spawn`, so you need to explicitly select `fork` or `forkserver` mode).

I hope that helps; I'm going to close specific ticket as it's not a specific issue with Briefcase but with the app template.
