### ISSUE TITLE
Provide command line option to override app settings

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#1115]
### What is the problem or limitation you are having?

PR #1107 initially failed CI because the verify-app tests require the use of a specific template branch on each repository.

### Describe the solution you'd like

It should be possible to override any app setting at the command line. For example:

```
briefcase create --app-setting template_branch=foobar
```
or
```
briefcase create -S template_branch=foobar
```

would be the equivalent of editing `pyproject.toml` and adding a template_branch setting for the platform being built. 

It should be possible to provide multiple setting overrides:

```
briefcase create -S template=https://example.com/template -S template_branch=foobar
```

Argparse `action="append"` allows for this.

### Describe alternatives you've considered

It is possible to override the template branch by changing the app configuration file. However, it is undesirable to modify a configuration file in a CI context, because the modification will become unnecessary as soon as CI passes.

### Additional context

While the motivating use case for this feature is PRs that require a custom template branch, another use of this feature would be modifying the version at build time. By passing in `--app-setting version=1.2.3`, it would be possible to use CI to control the app version.

PR #1106 adds a `finalize()` method to the base command; the end of this method would seem a reasonable place to apply any overrides. This then guarantees that command line arguments are the final applied values for any app setting.

**Comment by mhsmith** [comment]
I think `--config` would be a more readable spelling of this option, and it's also consistent with the wording used in the [documentation](https://briefcase.readthedocs.io/en/stable/reference/configuration.html). Possibly shortened to `-c` as in the [`git` command](https://git-scm.com/docs/git), though I haven't checked whether that conflicts with any existing option.

**Comment by Ewelina179** [comment]
Hi @freakboy3742 Can I work on this task?

**Comment by freakboy3742** [comment]
@Ewelina179 Absolutely! We don't have a formal process for accepting/assigning tasks; if it's open, it's available to be worked on. Drop a comment on the ticket to indicate that you're working on it (we're about to start the PyCon US sprints, so we need to do a *little* coordination to make sure we don't waste anyone's time); and start hacking!

**Comment by Ewelina179** [comment]
Thanks ;) Great to know. So I'm starting to work on that task.
