### ISSUE TITLE
briefcase build error

### ISSUE THREAD

**Issue by Nriver** [beeware/briefcase#1116]
### Describe the bug

I follow the tutorial in https://docs.beeware.org/en/latest/tutorial/tutorial-3.html
the build can not complete

### Steps to reproduce

1. follow the tutorial and execute `briefcase build`

### Expected behavior

Build success

### Environment

- Operating System: Manjaro
- Python version: 3.10
- Software versions:
  - Briefcase: lastest
  - Toga: lastest
  - ...

### Logs

The docker image is build successfully, but the execution seem to go wrong.

```
Building Docker image... done

[helloworld] Checking for Linuxdeploy plugins...
Using default gtk plugin

[helloworld] Configuring Linuxdeploy plugins...

[helloworld] Building AppImage...

[helloworld] Entering Docker context...
linuxdeploy version 1-alpha (git commit ID 91631c1), GitHub actions build 155 built on 2023-03-01 01:23:00 UTC

WARNING: Copyright files deployment disabled 

-- Creating basic AppDir structure -- 
Creating directory /app/appimage/Hello World/Hello World.AppDir/usr/bin/ 
Creating directory /app/appimage/Hello World/Hello World.AppDir/usr/lib/ 
ERROR: Failed to create directory /app/appimage/Hello World/Hello World.AppDir/usr/lib/ERROR: Failed to create basic AppDir structure
Building...

Error while building app helloworld.

```

**Comment by rmartin16** [comment]
Rootless Docker isn't currently supported.

There are a few options, though:
- Attempt the potential workaround to modify `Dockerfile` documented in #1083.
- [Install](https://docs.docker.com/engine/install/ubuntu/) the "rootful" Docker (although, I would avoid this if you don't feel comfortable managing multiple Docker installations).
- Use the `--no-docker` Briefcase option to avoid using Docker altogether.
- Build a Flatpak package instead with `briefcase <command> linux flatpak`.

Let us know if you encounter other issues in a new issue here or in [Discord](https://beeware.org/bee/chat/).
