### ISSUE TITLE
Improve Error Handling for Invalid Briefcase Template

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1118]
### What is the problem or limitation you are having?

The error state for using an invalid remote repo can be improved. While the "invalid repo" example is completely manufactured, I encountered the non-existent repo one with a typo.

A non-existent repo

```
❯ briefcase new -t https://github.com/beeware/beeware-template.git --template-branch linux-system --no-input

Generating a new application 'Hello World'
Using app template: https://github.com/beeware/beeware-template.git, branch linux-system

Log saved to /home/russell/tmp/beeware/logs/briefcase.2023_03_05-16_19_56.new.log

Traceback (most recent call last):
  File "/home/russell/github/beeware/briefcase/venv-3.10-briefcase/bin/briefcase", line 8, in <module>
    sys.exit(main())
  File "/home/russell/github/beeware/briefcase/src/briefcase/__main__.py", line 20, in main
    command(**options)
  File "/home/russell/github/beeware/briefcase/src/briefcase/commands/new.py", line 528, in __call__
    return self.new_app(
  File "/home/russell/github/beeware/briefcase/src/briefcase/commands/new.py", line 477, in new_app
    self.generate_template(
  File "/home/russell/github/beeware/briefcase/src/briefcase/commands/base.py", line 814, in generate_template
    cached_template = self.update_cookiecutter_cache(
  File "/home/russell/github/beeware/briefcase/src/briefcase/commands/base.py", line 758, in update_cookiecutter_cache
    remote = repo.remote(name="origin")
  File "/home/russell/github/beeware/briefcase/venv-3.10-briefcase/lib/python3.10/site-packages/git/repo/base.py", line 414, in remote
    raise ValueError("Remote named '%s' didn't exist" % name)
ValueError: Remote named 'origin' didn't exist
```

An invalid repo

```
❯ briefcase new -t https://example.com --template-branch linux-system --no-input

Generating a new application 'Hello World'
Using app template: https://example.com, branch linux-system

Log saved to /home/russell/tmp/beeware/logs/briefcase.2023_03_05-16_20_46.new.log

Traceback (most recent call last):
  File "/home/russell/github/beeware/briefcase/venv-3.10-briefcase/bin/briefcase", line 8, in <module>
    sys.exit(main())
  File "/home/russell/github/beeware/briefcase/src/briefcase/__main__.py", line 20, in main
    command(**options)
  File "/home/russell/github/beeware/briefcase/src/briefcase/commands/new.py", line 528, in __call__
    return self.new_app(
  File "/home/russell/github/beeware/briefcase/src/briefcase/commands/new.py", line 477, in new_app
    self.generate_template(
  File "/home/russell/github/beeware/briefcase/src/briefcase/commands/base.py", line 820, in generate_template
    self.tools.cookiecutter(
  File "/home/russell/github/beeware/briefcase/venv-3.10-briefcase/lib/python3.10/site-packages/cookiecutter/main.py", line 69, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "/home/russell/github/beeware/briefcase/venv-3.10-briefcase/lib/python3.10/site-packages/cookiecutter/repository.py", line 106, in determine_repo_dir
    cloned_repo = clone(
  File "/home/russell/github/beeware/briefcase/venv-3.10-briefcase/lib/python3.10/site-packages/cookiecutter/vcs.py", line 72, in clone
    repo_type, repo_url = identify_repo(repo_url)
  File "/home/russell/github/beeware/briefcase/venv-3.10-briefcase/lib/python3.10/site-packages/cookiecutter/vcs.py", line 45, in identify_repo
    raise UnknownRepoType
cookiecutter.exceptions.UnknownRepoType
```

### Describe the solution you'd like

Catch these errors and inform the user to verify the template.

### Describe alternatives you've considered

Interpret the errors myself.

### Additional context

[briefcase.2023_03_05-16_19_56.new.log](https://github.com/beeware/briefcase/files/10892997/briefcase.2023_03_05-16_19_56.new.log)
[briefcase.2023_03_05-16_20_46.new.log](https://github.com/beeware/briefcase/files/10892998/briefcase.2023_03_05-16_20_46.new.log)

**Comment by Kaushal-Dhungel** [comment]
HI, Can I work on this ?

**Comment by freakboy3742** [comment]
@Kaushal-Dhungel Absolutely! We don't have a formal issue assignment or claim process; if an issue is open, it's available to be worked on. Just drop a comment on the ticket to let others know you're looking at it, so we don't end up with duplicated effort.

**Comment by rmblau** [comment]
This will be partially handled by https://github.com/beeware/briefcase/pull/1210

**Comment by tiffanyxiao** [comment]
Hi, I will try to tackle this issue for Pycon2024 🐝

**Comment by rmblau** [comment]
> Hi, I will try to tackle this issue for Pycon2024 🐝

I will be excited to see what you can do to fully handle it!

**Comment by tiffanyxiao** [comment]
After some initial digging around, it looks like the first case no longer triggers the same ValueError but the second still triggers the `cookiecutter.exceptions.UnknownRepoType`. I think its still worthwhile to make the second error message more descriptive, as it took some more digging to understand what a repo "type" is (at least in terms of cookie cutter). Initially while reading this issue, I also wasn't sure what qualified as an invalid repo.

Could I work on writing a more descriptive error message for the UnknownRepoType? What are others thoughts on this?

**Comment by rmartin16** [comment]
FWIW, I think I'd be inclined to simply catch any exception that cookiecutter could throw; I'm not sure there's much value in pushing such exceptions to users who are not likely to even know cookiecutter is involved.

**Comment by sarayourfriend** [comment]
On the latest version, the output from both commands in the issue body are identical:

```
$ briefcase new -t https://example.com --template-branch linux-system --no-input

[helloworld] Generating a new application 'Hello World'
Using app template: https://example.com, branch linux-system
Cloning template 'https://example.com'...

Unable to clone repository 'https://example.com'.

This may be because your computer is offline, or because the repository URL is incorrect.
```

That looks pretty reasonable and seems to have come from this commit: https://github.com/beeware/briefcase/commit/952daf8d95fdd7c1711c6eb128841d1825d0b595. Did that commit already resolve the problem?

**Comment by freakboy3742** [comment]
That would have been an unintended benefit, but it looks like it might have improved the situation.

The only improvement I can see is that it would be desirable to differentiate "repo exists, but branch doesn't" from "repo doesn't exist". As it stands, the first example (referencing a branch that doesn't exist) says it can't clone the *repository*, which isn't *incorrect*, but doesn't point at the actual cause. At a minimum, the error in both cases should warn that the "repository URL or branch is incorrect"; ideally, we'd be able to identify which of the two is actually the culprit.

**Comment by freakboy3742** [comment]
To clarify - I don't think it worth doing a bunch of additional work just to do a full diagnosis of whether it's the branch or the repo. If we're not in a situation where the existing code has 2 obvious branches raising the same error, or there's isn't a simple post-clone check we can perform, then I'd be perfectly happy with a tweaked (but generic) error message.

**Comment by sarayourfriend** [comment]
Okay, that makes sense. And actually I must apologise, I've realised I misunderstood the original issue. The output is _not_ identical when you use a real template repository reference, and only was identical when I tried it because `beeware/beeware-template` is not a repository at all.

When using a real repository reference, with only an incorrect branch specified, the error message is:

```
$ briefcase new -t git@github.com:beeware/python-macos-template.git --template-branch linux-system --no-input

[helloworld] Generating a new application 'Hello World'
Using app template: git@github.com:beeware/python-macos-template.git, branch linux-system
Cloning template 'git@github.com:beeware/python-macos-template.git'...

Could not find a template branch for Briefcase linux-system.
```

So you do get a distinct message when it's just the branch that's the issue. And that makes sense as looking at the code again, they are distinct code paths (each easily found by searching the error string).

However, to your point, the first error case, where the repository was the issue (rather than the branch) does flatten at least a few separate problems into a single message, and I believe you can tell the difference based on the error's `stderr`. You could either try to clone a host that is not a git server at all, a git server that can't find the referenced repository (which would include one you don't have access rights to), or one that's having SSL errors. I'm sure there are other cases as well (I didn't test what happens if you fail SSH authentication, for example).

- SSL issues: `fatal: unable to access 'https://<broken-ssl-host>': OpenSSL/3.2.2: error:0A000438:SSL routines::tlsv1 alert internal error`
- Git server but no access to the repository (either does not exist or you don't have access): `fatal: Could not read from remote repository.`
- Authentication to the git server failed: `fatal: Authentication failed for 'https://github.com/beeware/beeware-template.git/'`
- Not a git server: `fatal: repository 'https://example.com/' not found`

Like I said, `e.stderr` includes that information, so it could be interpolated into the error message. What do you think, @freakboy3742? I've got a draft PR here that implements something that might work to forward git's error to the Briefcase user: https://github.com/beeware/briefcase/pull/2033

**Comment by freakboy3742** [comment]
> Like I said, `e.stderr` includes that information, so it could be interpolated into the error message. What do you think, @freakboy3742? I've got a draft PR here that implements something that might work to forward git's error to the Briefcase user: #2033

Definitely looks like a worthwhile improvement to me; and when combined with the other improvements that have already landed, I'd be happy to call that a fix for this issue. The only (very minor cosmetic) thing I'd flag would be ensuring the error text is title-cased - it looks like git is inconsistent on whether the sentence after the `fatal: ` starts with a capital or not; if we're presenting it to the user in Briefcase livery, we should do what we can to clean it up.

**Comment by sarayourfriend** [comment]
Great! I'll get that PR cleaned up and marked ready-for-review tomorrow.
