### ISSUE TITLE
Stuck at 50% Configuring (Preparing "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)")

### ISSUE THREAD

**Issue by Uxamailyax** [beeware/briefcase#1123]
### Describe the bug

(env_android) D:\PyCharm Projects\Android Python\BeeWare\helloworld>briefcase build android
[helloworld] Building Android APK...

> Configure project :app
Checking the license for package NDK (Side by side) 21.4.7075529 in C:\Users\Talha\.briefcase\tools\android_sdk\licenses
License for package NDK (Side by side) 21.4.7075529 accepted.
Preparing "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)".
<======-------> 50% CONFIGURING [35m 33s]
> :app
![image](https://user-images.githubusercontent.com/32153869/223433201-e6922ec4-0aa4-4f71-afa1-8a4a3f389bda.png)

### Steps to reproduce

Steps

### Expected behavior

The configuration never finishes. it should finish and produce APK.

### Environment

- Operating System: Windows
- Python version: 3.7
- Software versions:
  - Briefcase: 
  - Toga: 
  - ...

### Logs

```

```

**Comment by mhsmith** [comment]
The NDK is very large, so if you have a slow internet connection it may take 30 minutes or longer to download.

However, the good news is that the newest version of Briefcase doesn't need the NDK anymore. Make sure you're on Briefcase 0.3.12 or newer, rerun `briefcase create android`, and then build your app again. It should go much faster this time.

**Comment by freakboy3742** [comment]
Noticing one small detail from your bug report - you've reported your on Python3.7. If that is accurate, it would explain why you won't have Briefcase 0.3.12, as we dropped Python 3.7 support approximately 6 months ago. If you upgrade to a more recent Python version, the default Briefcase version should be more recent.
