### ISSUE TITLE
Problem Occurs When Configuring Root Project Android

### ISSUE THREAD

**Issue by josarn18** [beeware/briefcase#114]
The issue occurs when gradlew is run in the android directory of my project. The project is just the HelloWorld example.

'Could not get unknown property "packageDebug" for root project "android" of type org.gradle.api.Project'

I'm using Gradle 4.2.1 because the newer version gave me an error.

Any information would be greatly appreciated?

**Comment by josarn18** [comment]
I believe it's also worth mentioning that 'python setup.py android' runs successfully, but then moving into the android directory and running gradlew is where the issue begins.

**Comment by ant9000** [comment]
I have the same problem - it boils down to the fact that gradlew is not able to find *voc*.
A quick and dirty solution is to edit android/build.gradle and substitute the full path whenever the command is used.

**Comment by freakboy3742** [comment]
We've formally marked our Android backend as broken; this should hopefully be addressed in the near future thanks to a grant from the Python Software Foundation Education Grants committee. In the meantime, there's no point maintaining an open ticket, Android is effectively (for now) an unsupported platform.
