### ISSUE TITLE
Support aiohttp on Android for Python 3.11

### ISSUE THREAD

**Issue by fastfading** [beeware/briefcase#1174]
### Describe the bug

import openai
xxxx some code xxxx 

briefcase build android
----------
building 'aiohttp._websocket' extension
  error: CCompiler.compile: Chaquopy cannot compile native code

### Steps to reproduce

m1 mac   python 3.11.2
import openai
xxxx some code xxxx 

briefcase build android
----------
building 'aiohttp._websocket' extension
  error: CCompiler.compile: Chaquopy cannot compile native code

### Expected behavior

build with no error 

### Environment

- Operating System:  m1 mac
- Python version:  3.11
- Software versions:
  - Briefcase:  last version
  - Toga:  last version
  - ...

### Logs

```

```

**Comment by rmartin16** [comment]
Versions of `aiohttp` are [available](https://chaquo.com/pypi-7.0/aiohttp/) for Python 3.8 -> 3.10.

You should be able to get past this error using one of those Python versions.

**Comment by fastfading** [comment]
> Versions of `aiohttp` are [available](https://chaquo.com/pypi-7.0/aiohttp/) for Python 3.8 -> 3.10.
> 
> You should be able to get past this error using one of those Python versions.

thanks , I am new to beeware
how to set briefcase python version ?

**Comment by rmartin16** [comment]
Welcome :)

Briefcase uses whatever version of Python it is run with. So, if you create a virtual environment using Python 3.10 or earlier and install & run Briefcase, it will use that same version to build for Android.

**Comment by freakboy3742** [comment]
Changing ticket description since it's a feature request to support aiohttp on Android for Python 3.11

**Comment by fastfading** [comment]
@rmartin16    not working , I change the python to 3.10  , do all step again.  still the same error 

which python                                                                                                                                                         ─╯
python: aliased to /opt/homebrew/bin/python3.10
which python3                                                                                                                                                        ─╯
python3: aliased to /opt/homebrew/bin/python3.10
cat ../beeware-venv/pyvenv.cfg                                                                                                                                       ─╯
home = /opt/homebrew/opt/python@3.10/bin
include-system-site-packages = false
version = 3.10.10

**Comment by mhsmith** [comment]
After changing your Python version, you'll need to rerun `briefcase create android` to update your app.

If that doesn't work,  it's possible that you're trying to install a version of aiohttp that we don't yet support. In which case, please post the following:
* The `requires` section of your pyproject.toml file
* The complete build log

**Comment by rmartin16** [comment]
`aiohttp` is available for Python 3.8 -> 3.11.

https://chaquo.com/pypi-13.1/aiohttp/
