### ISSUE TITLE
Support for lxml

### ISSUE THREAD

**Issue by dip-m** [beeware/briefcase#1194]
### What is the problem or limitation you are having?

I am currently developing an app which integrates ebaysdk as its dependency. This works for the windows MSI but fails when building android with the following error message:
```
  running build_ext
  building 'lxml.etree' extension
  error: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
ERROR: Failed to install lxml from https://files.pythonhosted.org/packages/06/5a/e11cad7b79f2cf3dd2ff8f81fa8ca667e7591d3d8451768589996b65dec1/lxml-4.9.2.tar.gz#sha256=2455cfaeb7ac70338b3257f41e21f0724f4b5b0c0e7702da67ee6c3640835b67 (from ebaysdk->-r requirements.txt (line 3)).
```

### Describe the solution you'd like

I understand lxml comes with binaries and is hence not supported by default yet. Can we please have this supported and/or ways to have this sorted?

### Describe alternatives you've considered

Instructions to download and sort through the binary dependencies so this dependency can be resolved for android builds would also be great.

**Comment by freakboy3742** [comment]
As [described in the FAQ](https://briefcase.readthedocs.io/en/latest/background/faq.html#can-i-use-third-party-python-packages-in-my-app), we maintain independent pip-compatible repositories with pre-built binaries for *some* packages on PyPI.

lxml *is* on that list for Android, but not every version of lxml that is on PyPI has a binary android wheel; ebaySDK appears to be requesting v4.9.2, but we only provide v4.4.2 and v4.6.3.

There are two possible workarounds:

1) Explicitly pin the version of lxml to [one that is provided by Beeware](https://chaquo.com/pypi-7.0/lxml/). That explicit version pin *might* be sufficient to work around

2) Build the wheel yourself. As there's already a recipe for lxml, it *may* be a relatively straightforward task to update that recipe for 4.9.2; the [Chaquopy packaging README](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md) gives instructions on how to build a package. Once you have a locally compiled version of the wheel, you can add an explicit reference to that wheel in your requires list.

If you take path (2) and you're successful, it would be worthwhile submitting your changes as a PR; that way we can publish an updated LXML wheel for everyone to use.

**Comment by dip-m** [comment]
I went with option #1. Worked a charm with python 3.8 for the windows
install (although android run is broken now). However, on the case of
getting further, thanks very much!

**Comment by mhsmith** [comment]
Actually ebaysdk [does not require any particular version of lxml](https://github.com/timotheus/ebaysdk-python/blob/7ef8ba432332657258038ce86c6da2b02da0681f/setup.py#L40), so the problem is more likely to be that we only have Android builds of lxml for Python 3.8 (https://github.com/chaquo/chaquopy/issues/816).

To change your app's Python version, create a new virtual environment with the desired version, install Briefcase into it, then rerun `briefcase create android`.

**Comment by mhsmith** [comment]
For updates on Android lxml support, please follow the Chaquopy issue linked in my previous comment.
