### ISSUE TITLE
Make the author name an optional part of the MSI install path

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#1199]
### What is the problem or limitation you are having?

When an MSI installer runs, it installs the app in an `AppData/<author name>/<app name>` path. This follows the preferred scheme for Microsoft packaging, but it isn't *required*. 

It's not uncommon to see apps packaged in an `AppData/<app name>` path; and, if a solo developer is building the app, it may be preferable to use this scheme, rather than putting the author's name into the path.

### Describe the solution you'd like

A new option  `use_full_install_path` (open to suggestions for a better name) should exist for MSI installers. This will default to `True`; but if a value of `False` is specified, the author name will be excluded from the install path.

### Describe alternatives you've considered

1. Do nothing; require the fully qualified install path
2. Instead of a boolean option, let the user configure everything after the AppData path. e.g., have a `install_path` setting that defaults to `{app.author_name}/{app.formal_name}`, but can be explicitly set to anything else the user may want.

I've suggested the boolean option rather than the fully-customised option because the need isn't for *full* customisation - the install path should always be the app's formal name; it's only a question of whether the author name is included as well.

### Additional context

Requested by @davidfokkema on Discord.

**Comment by davidfokkema** [comment]
I implemented a fix in beeware/briefcase-windows-app-template#11, but have not yet documented it in briefcase.

**Comment by freakboy3742** [comment]
@davidfokkema The app template modification looks great; there's a need for an analogous fix on the VisualStudio template.

**Comment by freakboy3742** [comment]
@davidfokkema Looks like the only piece left is documentation - are you intending to tackle that, or should I open it up for a PyCon US sprint contributor?

**Comment by davidfokkema** [comment]
> @davidfokkema Looks like the only piece left is documentation - are you intending to tackle that, or should I open it up for a PyCon US sprint contributor?

I'm looking into that right now!

**Comment by davidfokkema** [comment]
Thanks for accepting my PRs!
