### ISSUE TITLE
Parallelise calls to app signing

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#1201]
### What is the problem or limitation you are having?

When signing a macOS app, briefcase needs to sign each individual .so file. This is currently being done sequentially, which can take a while.

### Describe the solution you'd like

Briefcase should parallelise the calls to sign individual files in the bundle, with the degree of parallelisation reflecting the number of CPUs available on the machine.

### Describe alternatives you've considered

Do nothing. Single threading works; it's just slower.

### Additional context

[ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) should be a fairly approachable way to implement this.

**Comment by xairos** [comment]
I'd like to sprint on this!
