### ISSUE TITLE
overly aggressive restriction on bundle identifiers restricts my idiom

### ISSUE THREAD

**Issue by glyph** [beeware/briefcase#1212]
### Describe the bug

All my apps have bundle IDs of the form `im.glyph.and.this.is.<app name>` but that doesn't work with `briefcase new`, due to this error:

```
Bundle Identifier [com.example]: im.glyph.and.this.is.examplecase

Invalid value; 'im.glyph.and.this.is.examplecase' is not a valid bundle identifier.

The bundle should be a reversed domain name. It must contain at least 2
dot-separated sections; each section may only include letters, numbers,
and hyphens; and each section may not contain any reserved words (like
'switch', or 'while').
```

### Steps to reproduce

Just run `briefcase new` and use the aforementioned bundle id.

### Expected behavior

It accepts the input.

### Environment

- Operating System: ```
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```
- Python version: Python 3.11.3
- Software versions:
  - Briefcase: 0.3.14


### Logs

```

```


### Additional context

_No response_

**Comment by Cimbali** [comment]
It seems `io` falls into this as well. where `https://${project}.github.io/` are often used for project github pages, which makes `io.github.${project}` a natural candidate for bundle identifier.

**Comment by freakboy3742** [comment]
@Cimbali Thanks for the heads up on that one - definitely looks like we should relax the validation for the parts the bundle identifier. We're currently doing the same validation on each individual part of the bundle identifier, mostly out of simplicity than out of any specific concern. Clearly we are able to relax the name checks on all but the last token (which is the app name, and is therefore critical that it doesn't collide).

**Comment by mas192** [comment]
bundle application identifiers restrict ca (Canada) too.
![ca_domain_valiation_bug_2024-05-20 06-34-15](https://github.com/beeware/briefcase/assets/21248222/03eb872a-2cce-4167-9267-50aa86d99adb)
 Canada too

**Comment by mhsmith** [comment]
In this case I think it's `test` rather than `ca`, because `test` is the standard library's self-test module. However, as mentioned above, this check should only be done on the app's Python package name, not every element in the bundle ID.

**Comment by mas192** [comment]
I have requested a PR to address this issue
https://github.com/beeware/briefcase/pull/1824

**Comment by freakboy3742** [comment]
This wasn't actually fixed by #1819 - the text of PR comment triggered Github's auto closer.

**Comment by glyph** [comment]
Aww. Well thanks for the work regardless :)

**Comment by freakboy3742** [comment]
@glyph Oh - there's a fix about to land - just waiting for CI.

**Comment by glyph** [comment]
Yay again!

**Comment by glyph** [comment]
Hooray… for real?

**Comment by freakboy3742** [comment]
@glyph Yes, you may now celebrate 😀
