### ISSUE TITLE
Support Kivy on Android

### ISSUE THREAD

**Issue by FANOSTEAM** [beeware/briefcase#1250]
### Describe the bug

when I tried 
to pakage this app to ubuntu executable it work well in seconds plus it worked in dev mode well .
But when i tried to create and build for android the building process ended up resulting error when Building wheel for kivy (PEP 517)
but with toga it builded a functional android app the only reason I want kivy with briefcase, is that  kivy offers a lot of functionality and docs commpared to toga. so when i added all my development requirment to the pyproject .toml requires section but it didnot worked . 
And i got this on this repo https://github.com/beeware/briefcase/issues/452#issuecomment-659173371

### Steps to reproduce

my app is very basic that it shows 1 button on its screen so there shouldn't be any steps for it 

### Expected behavior

it should give me apk file right?

### Screenshots

[Screencast from 04-30-2023 05:49:41 AM.webm](https://user-images.githubusercontent.com/123820574/235346799-24219988-71a1-4e71-be19-9387515fa2f2.webm)

### Environment

- Operating System:ubuntu 22.04
- Python version:3.10
- Software versions:
  - Briefcase:0.3.14
  - kivy:2.1.0
  - ...

### Logs

```
this is the log 
```
[briefcase.2023_04_30-05_12_51.build.log](https://github.com/beeware/briefcase/files/11361002/briefcase.2023_04_30-05_12_51.build.log)

**Comment by freakboy3742** [comment]
At least for now, Kivy isn't officially supported by Briefcase on Android. 

We'd definitely *like* to support Kivy on Android (and iOS for that matter); but the nature of Android and iOS integrations is such that it's not a simple matter of building a wheel - there's deep integration required with the Android runtime. If someone wants to investigate, we're interesting in accomodating any requirements that may exist.

**Comment by mhsmith** [comment]
For now, if anyone wants to use Kivy's UI toolkit, they should use [Kivy's recommended packaging tools](https://kivy.org/doc/stable/guide/packaging.html).

**Comment by freakboy3742** [comment]
I'm going to close this in favor of #1484, which is a broader umbrella version of this request.
