### ISSUE TITLE
pyproject.toml dynamic version support

### ISSUE THREAD

**Issue by andrewleech** [beeware/briefcase#1277]
### What is the problem or limitation you are having?

I'm a firm believer of aiming to always have a "single source of truth", and when it comes to project version numbers the git tag is the source of choice!

As such I loath having to manually set a version number in a file, then commit said file, then create a matching git tag - now there's two separate places the version is set, as well as slowing down the release process for a project!

Dynamic version numbering with `setuptools_scm` has been a pypa supported tool for many years and is now a first-class feature in pyproject.toml: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata

### Describe the solution you'd like

Could we please add support for the official dynamic metadata to briefcase, with version being my primary feature need.

### Describe alternatives you've considered

I'm sure it would be possible to make a separate tool that automates modifying the toml file to match the version output from setuptools_scm, but that is a pretty messy workaround.

### Additional context

Currently I've tried to configure my pyproject.toml to use `dynamic = ["version"]` but briefcase complains with:
```
Briefcase configuration error: Global configuration is incomplete (missing 'version')
```

**Comment by freakboy3742** [comment]
You won't get any disagreement that this is a feature we should support; it's already logged as #474.

**Comment by andrewleech** [comment]
Ah sorry, I hunted / searched for issues/pr's relating to version, didn't find it (all the bump version: pr's did make it hard to see)
