### ISSUE TITLE
how to remove the title bar for android app

### ISSUE THREAD

**Issue by Jzhenli** [beeware/briefcase#1320]
### What is the problem or limitation you are having?

if it's possible to remove the title bar for the Android app?

![image](https://github.com/beeware/briefcase/assets/42105688/a2d3b419-2c5a-4195-95fc-6ec7a22f6035)

### Describe the solution you'd like

remove the title bar for the Android app

### Describe alternatives you've considered

remove the title bar for the Android app

**Comment by freakboy3742** [comment]
Closing, for two reasons:

* Firstly, this isn't an issue with Briefcase. It's an issue with the widget toolkit used to build the app being deployed.
* Secondly, it's an open feature request on Toga: beeware/toga#1870
