### ISSUE TITLE
Platform support pages dont run 

### ISSUE THREAD

**Issue by auwsom** [beeware/briefcase#1321]
### Describe the bug

https://briefcase.readthedocs.io/en/latest/reference/platforms/web.html

In the above link, the pages for Web and Android dont mention needing to use `breifcase run web` or `breifcase run android` respectively. (only found this searching the GH issues by chance).

**Comment by freakboy3742** [comment]
I'm not sure I understand why they would. The page you've referenced is the documentation for the web platform; a similar page exists for the Android platform. As such, it's a guide to the additional options that exist when using the Web platform as a target.

The documentation for the [create command](https://briefcase.readthedocs.io/en/latest/reference/commands/create.html) (and every other command that takes a platform) describes that the platform as an option that can be passed in, and the `--help` option on every command does the same.

This functionality is also covered by the [BeeWare tutorial](https://docs.beeware.org).

**Comment by auwsom** [comment]
@freakboy3742 thanks for the reply.. i talked with you before about getting the web and mobile versions working.. so glad to see they are!

I thought before there were direct links in the side bar for mobile or web. I don't see them, so i searched and found the platforms page.

I don't see it in the first two pages of the tutorial. I'm a person that likes to work backwards. So as soon as I ran the dev command, I wanted to make sure the Android and web versions work. I don't see a direct path to doing that. Maybe it's at the end of the tutorial. It would be nice to have a quick start for those. Then I can go back in and do "Improvements".

**Comment by mhsmith** [comment]
There are direct links to "Mobile" and "Web" in the sidebar of the tutorial; perhaps that's what you remembered:

<img width="282" alt="Screenshot 2023-06-17 at 11 25 20" src="https://github.com/beeware/briefcase/assets/166954/7335287c-7b12-4278-aafe-da2fd171aafe">
