### ISSUE TITLE
briefcase run android - Unable to create Android emulator 

### ISSUE THREAD

**Issue by ivan9394** [beeware/briefcase#1338]
### Describe the bug

Here is a user from china again, when I first time to run 'briefcase run android', i stuck at 
![Image](https://github.com/beeware/briefcase/assets/41772312/4c993a76-9fd0-461c-87a0-b5d4c174518e)

after a long time there was no progress and i kill it.

While i rerun 'briefcase run android' the second time.
i came to 
```
Emulator name [beePhone]:
>>> Device skin 'pixel_3a' already exists.

>>> Running Command:
>>>     'C:\Users\26742\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\cmdline-tools\latest\bin\avdmanager.bat' --verbose create avd --name beePhone --abi x86_64 --package 'system-images;android-31;default;x86_64' --device pixel
>>> Working Directory:
>>>     C:\Users\26742\jump
>>> Environment Overrides:
>>>     ANDROID_SDK_ROOT=C:\Users\26742\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk
>>>     JAVA_HOME=C:\Users\26742\AppData\Local\BeeWare\briefcase\Cache\tools\java
>>> Command Output:
>>>     Loading local repository...
>>>     [=========                              ] 25% Loading local repository...
>>>     [=========                              ] 25% Fetch remote repository...
>>>     [=======================================] 100% Fetch remote repository...
>>>     Error: Package path is not valid. Valid system image paths are:
>>>     null
>>> Return code: 1
Creating Android emulator beePhone...

Unable to create Android emulator
```
```
>>> Extra information:

>>> Running Command:
>>>     'C:\Users\26742\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\cmdline-tools\latest\bin\sdkmanager.bat' --list_installed
>>> Working Directory:
>>>     C:\Users\26742\jump
>>> Environment Overrides:
>>>     ANDROID_SDK_ROOT=C:\Users\26742\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk
>>>     JAVA_HOME=C:\Users\26742\AppData\Local\BeeWare\briefcase\Cache\tools\java
>>> Command Output:
>>>     Loading package information...
>>>     Loading local repository...
>>>     [=========                              ] 25% Loading local repository...
>>>     [=========                              ] 25% Fetch remote repository...
>>>     [=======================================] 100% Fetch remote repository...
>>>     Installed packages:
>>>       Path                 | Version | Description                    | Location
>>>       -------              | ------- | -------                        | -------
>>>       build-tools;30.0.2   | 30.0.2  | Android SDK Build-Tools 30.0.2 | build-tools\30.0.2
>>>       emulator             | 32.1.14 | Android Emulator               | emulator
>>>       patcher;v4           | 1       | SDK Patch Applier v4           | patcher\v4
>>>       platform-tools       | 34.0.3  | Android SDK Platform-Tools     | platform-tools
>>>       platforms;android-33 | 2       | Android SDK Platform 33        | platforms\android-33
>>>
>>> Return code: 0
Log saved to C:\Users\26742\jump\logs\briefcase.2023_06_30-16_19_22.run.log
```
### Expected behavior

So how to get through, thanks a lot!

### Environment

- Operating System: windows
- Python version: 3.10.11
- Software versions:
  - Briefcase: 0.3.14
  - Toga: 0.3.1

### Logs

```

```

**Comment by rmartin16** [comment]
Related recent issue:
- #1337

Briefcase checks that the file path for the system image for the emulator exists before trying to use it. This error, as in #1337, suggests that the Android SDK install of the image did not complete properly.

You can try to delete the `C:\Users\26742\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\system-images\android-31` directory and run Briefcase again. If it fails again, then please upload the _entire_ Briefcase log file when the install of the system image is attempted by Android SDK.

**Comment by ivan9394** [comment]
Thanks a lot~~
It works.
but after run the emulator, my app was not installed
and i drag the app_debug.apk to the emulator, it also cant be installed... mybe there another problem with my app
i should try to rebuild it? so how to delete the app i created and rebuild it...

**Comment by rmartin16** [comment]
>  i should try to rebuild it? so how to delete the app i created and rebuild it...

I would certainly try this. You can either run `briefcase run android -ur` or delete the `build` directory and run `briefcase run android` again.

Although, please upload the Briefcase log file for your errors. We cannot assess what is going wrong unless we know what happened.

**Comment by ivan9394** [comment]
here is the log... maybe the problem is my app?
I use opencv, mediapipe, tkinter libs, can these libs run is beeware?


[jump] Following device log output (type CTRL-C to stop log)...
===========================================================================
--------- beginning of main
07-01 00:20:25.555  3155  3155 I om.example.jum: Late-enabling -Xcheck:jni
07-01 00:20:25.566  3155  3155 W om.example.jum: Unexpected CPU variant for X86 using defaults: x86_64
07-01 00:20:25.623  3155  3155 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10105; state: ENABLED
07-01 00:20:25.654  3155  3155 V GraphicsEnvironment: ANGLE Developer option for 'com.example.jump' set to: 'default'
07-01 00:20:25.655  3155  3155 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
07-01 00:20:25.656  3155  3155 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
07-01 00:20:25.657  3155  3155 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
07-01 00:20:25.665  3155  3177 D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
07-01 00:20:25.667  3155  3177 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
07-01 00:20:25.669  3155  3177 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
07-01 00:20:25.709  3155  3155 D MainActivity: onCreate() start
07-01 00:20:25.768  3155  3155 W om.example.jum: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
07-01 00:20:25.769  3155  3155 W om.example.jum: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
07-01 00:20:25.779  3155  3155 D MainActivity: Starting Python
07-01 00:20:25.821  3155  3186 W native.stderr: Could not find platform independent libraries <prefix>
07-01 00:20:25.821  3155  3186 W native.stderr: Could not find platform dependent libraries <exec_prefix>
07-01 00:20:25.821  3155  3186 W native.stderr: Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
07-01 00:20:25.944  3155  3155 W asset   : seek out of range: want -20, end=22
07-01 00:20:25.982  3155  3155 D MainActivity: Running main module jump
07-01 00:20:26.065  3155  3155 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-01 00:20:26.066  3155  3155 E AndroidRuntime: FATAL EXCEPTION: main
07-01 00:20:26.066  3155  3155 E AndroidRuntime: Process: com.example.jump, PID: 3155
07-01 00:20:26.066  3155  3155 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.jump/org.beeware.android.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'tkinter'
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7839)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-01 00:20:26.066  3155  3155 E AndroidRuntime: Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'tkinter'
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.java.chaquopy.import_override(import.pxi:20)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.java.chaquopy.import_override(import.pxi:60)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.jump.app.<module>(app.py:7)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.java.chaquopy.import_override(import.pxi:60)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.__main__.<module>(__main__.py:1)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.runpy._run_code(runpy.py:86)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.runpy._run_module_code(runpy.py:96)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.runpy.run_module(runpy.py:224)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at org.beeware.android.MainActivity.onCreate(MainActivity.java:85)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8051)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8031)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
07-01 00:20:26.066  3155  3155 E AndroidRuntime:        ... 12 more
07-01 00:20:26.085  3155  3155 I Process : Sending signal. PID: 3155 SIG: 9

**Comment by rmartin16** [comment]
Those packages are not completely supported as they are not pure-python packages; third party package support is discussed more [here](https://briefcase.readthedocs.io/en/latest/background/faq.html#can-i-use-third-party-python-packages-in-my-app). There is a build of [`opencv-python`](https://chaquo.com/pypi-7.0/opencv-python/) for Python 3.8; however, builds of `mediapipe` are not available. While `tkinter` is a part of the Python `stdlib`, it isn't generally available in the Python that BeeWare uses....although, at least in theory, such a Python could be used with BeeWare.

Feel free to ask additional questions as [discussions](https://github.com/beeware/briefcase/discussions) or join us in the BeeWare [discord](https://beeware.org/bee/chat/). Closing this issue since we've resolved the originating problems.

**Comment by pb-413** [comment]
I ran into something similar when my drive space ran out. Log from that: 
[briefcase.2024_05_22-11_28_58.run.log](https://github.com/beeware/briefcase/files/15406199/briefcase.2024_05_22-11_28_58.run.log)

Subsequent runs looked similar to this issue. Example log:
[briefcase.2024_05_22-12_18_16.run.log](https://github.com/beeware/briefcase/files/15406206/briefcase.2024_05_22-12_18_16.run.log)

The work around step mentioned above by @rmartin16 (delete `~\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\system-images\android-31`) seemed to work for me (after I cleaned up the drive to create more available space!) got me past this error situation (avdmanager.bat ...-> ERROR: Package path is not valid. Valid system image paths are: null).
