### ISSUE TITLE
RTD `latest` build is labeled as `Briefcase 0.1.dev299+gbeda029`

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1339]
### Describe the bug

RTD labeled the recent `latest` build from `main` with a strange version: `Briefcase 0.1.dev299+gbeda029`.

### Steps to reproduce

Visit https://briefcase.readthedocs.io/en/latest/ or https://readthedocs.org/projects/briefcase/builds/21114896/.

Re-creating the RTD build environment:
```
mkdir briefcase-tmp && cd briefcase-tmp
git clone --no-single-branch --depth 50 https://github.com/beeware/briefcase .
git checkout --force origin/main
git clean -d -f -f
python -m venv venv
source venv/bin/activate
python -m pip install --upgrade --no-cache-dir pip setuptools
python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 'alabaster>=0.7,<0.8,!=0.7.5' commonmark==0.9.1 recommonmark==0.5.0 'sphinx<2' 'sphinx-rtd-theme<0.5' 'readthedocs-sphinx-ext<2.3' 'jinja2<3.1.0'
python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .[dev,docs]
```

The last successful build determined the proper version: https://readthedocs.org/projects/briefcase/builds/21050962/

### Expected behavior

The RTD `latest` tag should show the Briefcase SCM version for the most recent commit added to `main`.

### Environment

- Operating System: RTD
- Python version: 3.11.0
- Software versions: 
  - Briefcase: 
  - Toga:
  - ...

### Additional context

Because of #1182, I thought https://briefcase.readthedocs.io was redirecting to `latest`....although, it appears to be going to `stable` which still shows docs for `0.3.13`.

**Comment by rmartin16** [comment]
This seems to be an artifact of how RTD is checking out the Briefcase repo and limiting it to a depth of 50.

related:
- https://github.com/readthedocs/readthedocs.org/issues/1888
- https://github.com/readthedocs/readthedocs.org/pull/4939

**Comment by rmartin16** [comment]
Sooo....looking at the history of https://github.com/readthedocs/readthedocs.org/issues/5031, it appears to situation is we have to request that RTD admins disable shallow checkouts...at least, as recently as dec 2022, some projects were doing this.

Nonetheless, https://github.com/readthedocs/readthedocs.org/issues/5989 appears to have [added](https://docs.readthedocs.io/en/latest/config-file/v2.html#build-jobs) a `post_checkout` hook to `readthedocs.yaml` where users can `unshallow` the repo.

**Comment by freakboy3742** [comment]
Ah dangit - I forgot about #1182 - we had a recent support question about the ANDROID_SDK_ROOT variable, and I noticed that it was pointing at latest rather than stable, but I forgot the reason why - I got it confused with Toga, where it was pointing at latest to ensure that the dev version of the developer guide was there by default for the PyCon US sprints. I'll switch it back.
