### ISSUE TITLE
Android build: code changes not picked up unless I delete "build" folder

### ISSUE THREAD

**Issue by derzhavets** [beeware/briefcase#1342]
### Describe the bug

I created HelloWorld application, successfully built and run it on Android and everything works. However, when I make changes in code and rebuild the app, it builds initial version without the changes I just made. 

### Steps to reproduce

1. Build and run briefcase HelloWorld app: "briefcase build android", "briefcase run android". Let's call it code v1.
2. Make changes it code. Let's call it code v2.
3. Build and run android app again.
4. Code changes from v2 are not picked up, I see the version is built from code v1

### Expected behavior

I expect it to pick the code changes each time I do build for android.

### Environment

- Operating System: Windows
- Python version: 3.9
- Software versions:
  - Briefcase: 0.3.14

**Comment by rmartin16** [comment]
Adding the `-u\--update` switch to either `briefcase build` or `briefcase run` will update the source used to build the app. I think this request is encapsulated within the larger perspective of #807.

**Comment by freakboy3742** [comment]
Closing on the basis that the issue appears to be understood. If the suggested resolution doesn't work, let us know and we can re-open and investigate further.
