### ISSUE TITLE
Error importing 'yaml' from standard library with python 3.11?

### ISSUE THREAD

**Issue by PH-Tools** [beeware/briefcase#1343]
### Describe the bug

I am running into an issue importing the `yaml` library when using Python 3.11? 

Following the tutorials exactly, all works as expected with no issues. 
However, if I add a single import statement to `helloworld\src\helloworld\app.py`:

`import yaml`

while the app continues to run fine with `briefcase dev`, it now causes the `briefcase run` command to fail with the message:

```ModuleNotFoundError: No module named 'yaml'```

<img width="616" alt="image" src="https://github.com/beeware/briefcase/assets/69652712/e1e3135b-a08b-4e69-8ff8-c8fb93533a94">

I tried to add 'yaml' to the `pyproject.toml` config file as follows:

```
requires = [
    "pyside6~=6.2", "yaml"
]
```

but that did not change the error.

I was under the impression `yaml` was part of the standard library in python 3.11, so not sure if I need to do something different to ensure it is loaded properly? Note that when I use other standard library modules such as `collections`, I do not get this error. It appears to happen only with `yaml` ? Wondering if there is a known solution for this library or if I am doing something incorrectly? Should I continue to use PyYaml or some other 3rd party library in place of the standard library module?

### Steps to reproduce

1. Follow the [tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-1.html) and build a PySide6 based app
2. Add the line `import yaml` to `app.py`
3. Run `briefcase update`
4. Run `briefcase build`
5. Run `briefcase run`: Error

### Expected behavior

I expected to be able to import yaml and have the app run.

### Screenshots

<img width="1033" alt="image" src="https://github.com/beeware/briefcase/assets/69652712/f166eeac-d16a-472f-85fa-210190f950ae">

<img width="1647" alt="image" src="https://github.com/beeware/briefcase/assets/69652712/143320cc-9bc7-47d7-8ff0-40304b5b44e6">

### Environment

- Operating System: MacOS Monterey 12.5.1
- Python version: 3.11.0
- Software versions:
  - Briefcase: 0.3.14

### Logs

```
briefcase run    

[helloworld] Starting app...
===========================================================================
Configuring isolated Python...
Pre-initializing Python runtime...
PythonHome: /Users/em/Desktop/test_yaml/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/support/python-stdlib
PYTHONPATH:
- /Users/em/Desktop/test_yaml/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/support/python311.zip
- /Users/em/Desktop/test_yaml/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/support/python-stdlib
- /Users/em/Desktop/test_yaml/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/support/python-stdlib/lib-dynload
- /Users/em/Desktop/test_yaml/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/app_packages
- /Users/em/Desktop/test_yaml/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/app
Configure argc/argv...
Initializing Python runtime...
Installing Python NSLog handler...
Running app module: helloworld
---------------------------------------------------------------------------
Application quit abnormally (Exit code -6)!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/em/Desktop/test_yaml/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/app/helloworld/__main__.py", line 1, in <module>
    from helloworld.app import main
  File "/Users/em/Desktop/test_yaml/helloworld/build/helloworld/macos/app/Hello World.app/Contents/Resources/app/helloworld/app.py", line 15, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "Hello World.app/Contents/Resources/app/helloworld/__main__.py", line 1, in <module>
    from helloworld.app import main
  File "Hello World.app/Contents/Resources/app/helloworld/app.py", line 15, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by rmartin16** [comment]
Support for YAML parsing isn't in the Python standard library....and I doubt there's any plans to add it due to its complexity.

That said, `briefcase dev` is working because `PyYAML` is a transitive dependency for Briefcase and your app is running from the same environment that Briefcase is running from; therefore, `import yaml` works for `briefcase dev`.

For any Briefcase-packaged app, you'll need to specify a third-party YAML parsing package. You can use `briefcase run -r` to have the requirements (including any new ones) installed before building and running your app.

**Comment by PH-Tools** [comment]
Thank you @rmartin16, my mistake: I must have gotten confused. I will use PyYaml from now on.
