### ISSUE TITLE
briefcase_home option in pyproject.toml

### ISSUE THREAD

**Issue by MosGeo** [beeware/briefcase#1355]
### What is the problem or limitation you are having?

I am trying to setup a project with the following requirements:

1. Must be able to be packaged offline.
2. Must be able to easily tranfer between computers and onboard new people easily.

I am currently have the tools, support_package, and template in the project folder. Currently, it is easy to set the support_package and template using the pyproject.toml. So they work perfectly when the project is transferred. For setting the briefcase_home, this has to be set with an envrionmental variable which is not ideal in this case.

### Describe the solution you'd like

Have the option to set briefcase_home in pyrproject.toml file. So the order of search for it is:
1. pyproject.toml file.
2. Environmental variable.
3. Default value base on the platform

### Describe alternatives you've considered

Creating scripts to build and package the application and including an initial line to set the environmental variable for the session. It works but i am not a fan of it.

### Additional context

Because there are workarounds, I consider this a low impact issue.

**Comment by freakboy3742** [comment]
Thanks for the suggestion. I can definitely appreciate the use case; I've had similar difficulties when running a tutorial in a classroom setup. When the first step in the tutorial is "download Android Studio", you can essentially schedule a long lunch break while you wait for a room of Android installs to complete.

However, I'm not sure the idea you're proposing here is viable. `BRIEFCASE_HOME` is an inherently machine-specific setting - if I set `BRIEFCASE_HOME` to `~/my_projects/test_project`, you would need to put the project in  *exactly* the same path on your machine. If I use `/Users/rkm/my_projects/test_project` that may not even be possible.

Essentially, the only path for which this *is* viable is `.` (or a similarly local path). This might lead you to suggest a setting like `local_tools=True` which defaults to downloading tools into the local project folder, but then we hit the next problem: the tools that we're talking about are *large* and primarily binaries, so they're not well suited to being added to version control. 

There's also some legal questions about the redistributability of some of these artefacts; it *might* be legal to distribute a .zip file or installer, distributing a "working" tools folder might be problematic. I haven't dug into the legalities in detail, but the fact that there are licenses that need to be accepted for some tools at least gives me pause.

That said - I *do* accept the use case. See #738 for an alternate proposal (or, at least, a more generic representation of the problem, looking for a concrete proposal for a solution). I'll close this ticket as I don't think this *specific* solution is viable, but I'd encourage you to make suggestions (or document your use case) on #738.
