### ISSUE TITLE
No such file or directory when run in android

### ISSUE THREAD

**Issue by hieupham1103** [beeware/briefcase#1358]
### Describe the bug

I got this error when `briefcase run android -d "@beePhone" `
This happens
`E/AndroidRuntime: Caused by: com.chaquo.python.PyException: FileNotFoundError: [Errno 2] No such file or directory:'/data/data/com.example.hakoreader/files/chaquopy/AssetFinder/app/hakoreader/storage'`

My project look like this:
![image](https://github.com/beeware/briefcase/assets/62142713/276d98b0-3b3d-428f-baee-bb2f6e068c69)

I want to create some files in **storage** folder when the app is running through **hako module**

![image](https://github.com/beeware/briefcase/assets/62142713/ec7c90c0-9565-45d0-975a-e3e6c6f569d9)

When I run it with **briefcase dev**, it works well.
I had added the required lib to **pyprojects.toml** file

### Steps to reproduce

1.  run **`briefcase run android -d "@beePhone"**
2. Error appears

### Expected behavior

the storage folder doesn't exit when run in android

### Environment

- Operating System: Windows 11 (run in android vm)
- Python version: 3.10

**Comment by rmartin16** [comment]
If you want to access relevant locations in the file system, use Toga's [Paths](https://toga.readthedocs.io/en/latest/reference/api/resources/app_paths.html#toga.paths.Paths). This will ensure you are using the correct file system location for an arbitrary platform. The imageview Toga example [demonstrates](https://github.com/beeware/toga/blob/f7dc1c8abe4344155cb039ec2752e8de44de8e84/examples/imageview/imageview/app.py#L49) accessing an asset that ships with the app.

However, the `paths.app` file path is not intended for writing; persistent data should be stored in `paths.data`, `paths.cache`, etc.

Additionally, be sure to run `briefcase update android` or `briefcase run android -u` to be sure the additional directory is packaged with the app build.

Let me know if this addresses the issue for you.

**Comment by hieupham1103** [comment]
> If you want to access relevant locations in the file system, use Toga's [Paths](https://toga.readthedocs.io/en/latest/reference/api/resources/app_paths.html#toga.paths.Paths). This will ensure you are using the correct file system location for an arbitrary platform. The imageview Toga example [demonstrates](https://github.com/beeware/toga/blob/f7dc1c8abe4344155cb039ec2752e8de44de8e84/examples/imageview/imageview/app.py#L49) accessing an asset that ships with the app.
> 
> However, the `paths.app` file path is not intended for writing; persistent data should be stored in `paths.data`, `paths.cache`, etc.
> 
> Additionally, be sure to run `briefcase update android` or `briefcase run android -u` to be sure the additional directory is packaged with the app build.
> 
> Let me know if this addresses the issue for you.

I just tried it like you said and it said: **No module named stub**

**Comment by rmartin16** [comment]
> I just tried it like you said and it said: **No module named stub**
> I have added **stub** to **requires** in **pyproject.toml**

You can use the `-r` switch to install the new requirements; such as `briefcase run android -r`.

**Comment by freakboy3742** [comment]
To clarify - is stubs a Python package, or just a folder of data? If it's just a folder of data, there's no need to include it in `requires` - `requires` is a list of python packages to install.

If `stubs` is a subfolder of data that is a subdirectory of your `hakoreader` app, then there's no configuration update required; you only need to run an updated build (`briefcase update` then `briefcase run`, or `briefcase run -u`) to make sure the new folder has been copied into your app.

**Comment by hieupham1103** [comment]
> To clarify - is stubs a Python package, or just a folder of data? If it's just a folder of data, there's no need to include it in `requires` - `requires` is a list of python packages to install.
> 
> If `stubs` is a subfolder of data that is a subdirectory of your `hakoreader` app, then there's no configuration update required; you only need to run an updated build (`briefcase update` then `briefcase run`, or `briefcase run -u`) to make sure the new folder has been copied into your app.

it now can run in windows and dev but when I try in android, it worked fine at first but after I used it for a while it crashed
`F/libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 19229 (Binder:19213_1), pid 19213 (mple.hakoreader)
`

**Comment by freakboy3742** [comment]
If "it worked fine at first" but then stopped working, then I suggest that whatever you did to the code after it was working is probably the cause.

However you haven't provided any details about what you've done to reproduce the problem, and the only clue we have to work with is a single line from the logs that you've chosen to share with us - so there's not much more help we can provide.

If you want help diagnosing a problem, it's kind of important to provide enough details for us to reproduce the problem, or at least understand what it is that you've done. A full log file would be a start, as would a complete list of *everything* you've done between it working and it not working.

**Comment by hieupham1103** [comment]
> If "it worked fine at first" but then stopped working, then I suggest that whatever you did to the code after it was working is probably the cause.
> 
> However you haven't provided any details about what you've done to reproduce the problem, and the only clue we have to work with is a single line from the logs that you've chosen to share with us - so there's not much more help we can provide.
> 
> If you want help diagnosing a problem, it's kind of important to provide enough details for us to reproduce the problem, or at least understand what it is that you've done. A full log file would be a start, as would a complete list of _everything_ you've done between it working and it not working.

I has used the example in website

```
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class hakoreader(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def say_hello(self, widget):
        print(f"Hello, {self.name_input.value}")


def main():
    return hakoreader()
```

It works in both **windows** and **android**
But when I add label and button it crash
```
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class hakoreader(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        name_label = toga.Label(
            "Your name: ",
            style=Pack(padding=(0, 5))
        )
        self.name_input = toga.TextInput(style=Pack(flex=1))

        name_box = toga.Box(style=Pack(direction=ROW, padding=5))
        name_box.add(name_label)
        name_box.add(self.name_input)

        button = toga.Button(
            "Say Hello!",
            on_press=self.say_hello,
            style=Pack(padding=5)
        )

        main_box.add(name_box)
        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def say_hello(self, widget):
        print(f"Hello, {self.name_input.value}")


def main():
    return hakoreader()

```
https://cdn.discordapp.com/attachments/939956002114113627/1128894649977806858/2023-07-13_10-41-59.mp4

**Comment by freakboy3742** [comment]
You've provided source code for an application that *doesn't involve any use of files*, so whatever problem you've having here, it's completely unrelated to everything you've been asking about previously on this ticket.

The video you've provided confirms that yes, the application is crashing. But it provides almost no additional information. All the *useful* information is in the log - the text that scrolls past at the bottom of the screen. *That* is the detail that will help us diagnose what is going on here. 

Briefcase will normally generate a log file when an app crashes; it looks like that isn't happening in this case, but you should be able to force a log to be created by passing in `--log`  when you invoke `briefcase run`. If you provide that, we might be able to work out what is going on here.

**Comment by hieupham1103** [comment]
> Bạn đã cung cấp mã nguồn cho một ứng dụng không liên quan đến bất kỳ việc _sử dụng tệp nào_, vì vậy bất kỳ vấn đề nào bạn gặp phải ở đây, nó hoàn toàn không liên quan đến mọi thứ bạn đã hỏi trước đây trên vé này.
> 
> Video bạn đã cung cấp xác nhận rằng có, ứng dụng đang gặp sự cố. Nhưng nó hầu như không cung cấp thêm thông tin. Tất cả các thông tin _hữu ích_ đều có trong nhật ký - văn bản cuộn qua ở cuối màn hình. _Đó_ là chi tiết sẽ giúp chúng tôi chẩn đoán những gì đang xảy ra ở đây.
> 
> Cặp thường sẽ tạo tệp nhật ký khi ứng dụng gặp sự cố; Có vẻ như điều đó không xảy ra trong trường hợp này, nhưng bạn sẽ có thể buộc nhật ký được tạo bằng cách truyền vào khi bạn gọi . Nếu bạn cung cấp điều đó, chúng tôi có thể tìm ra những gì đang xảy ra ở đây.`--log``briefcase run`

[briefcase.2023_07_13-11_04_17.run.log](https://github.com/beeware/briefcase/files/12035247/briefcase.2023_07_13-11_04_17.run.log)

my log is here

**Comment by freakboy3742** [comment]
Thanks - there's clearly something going very badly wrong here; as far as I can work out, it's nothing to do with your code. We'll need to investigate further.

**Comment by hieupham1103** [comment]
> Thanks - there's clearly something going very badly wrong here; as far as I can work out, it's nothing to do with your code. We'll need to investigate further.

i think you will need all my code
https://github.com/hieupham1103/HakoReader

**Comment by freakboy3742** [comment]
Can we be clear here - which app is crashing? Is the log you provided from the app described in [this message](https://github.com/beeware/briefcase/issues/1358#issuecomment-1633503772), or the one from the Github repo you have linked?

**Comment by hieupham1103** [comment]
the app described in https://github.com/beeware/briefcase/issues/1358#issuecomment-1633503772 and the one from the Github repo Ihave linked is one

**Comment by mhsmith** [comment]
To make certain you're running the current version of your app, please run it again with `-ur` instead of just `-r`.

Also, you previously mentioned this line:

`F/libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 19229 (Binder:19213_1), pid 19213 (mple.hakoreader)`

But that doesn't appear in your most recent log. Are you still able to reproduce it?

**Comment by hieupham1103** [comment]
I have tried this command **briefcase run android -r -d @beePhone --log**
![image](https://github.com/beeware/briefcase/assets/62142713/251a20c5-e5b5-4d31-9291-3d066b938ee6)
[briefcase.2023_07_13-14_41_23.run.log](https://github.com/beeware/briefcase/files/12036721/briefcase.2023_07_13-14_41_23.run.log)

**Comment by mhsmith** [comment]
I can't work out what the cause of the crash is, but it seems to be connected to the OS rather than any of our code. The only suggestion I can think of is to reinstall the Android tools. Delete `C:\Users\phamd\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk`, then run `briefcase run android` again.

Alternatively, you could try running your app on a physical device. Follow the instructions [here](https://developer.android.com/studio/run/device#setting-up), then connect the device to your computer with a USB cable, and it should appear in the device list when running `briefcase run android` without the `-d` option.
