### ISSUE TITLE
Briefcase data directory is still being mounted in to containers for `brutus` user when `root` is used

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1374]
### Describe the bug

With #1331, the user in Docker containers can now be `root` as well as `brutus`; however, Briefcase always mounts the data directory in to `.cache` directory for `brutus`. This doesn't appear to be having adverse effects right now....but it should probably be reconciled.

### Steps to reproduce

1. Using Docker Desktop, run `briefcase open linux --target debian`
2. Run `whoami` to see current user
3. Run `ls -lh /home/brutus/.cache/`

### Expected behavior

I suppose it doesn't _actually_ hurt anything to leave this as is....but it seems a lot more consistent if we use a user-agnostic location to bind mount the Briefcase data directory given we're not always using the `brutus` user now.

### Environment

- Operating System: pop os 22.04
- Python version: 3.10.12
- Software versions:
  - Briefcase: `0.3.16.dev20+g8b020d6c`

**Comment by freakboy3742** [comment]
@rmartin16 AFAICT, this should have been fixed by beeware/briefcase-linux-system-template#7 and beeware/briefcase-linux-appimage-template#34 - am I correct, or is there something else going on here? If it is fixed, do we need to add changenote-only PR to announce the bug fix?

**Comment by rmartin16** [comment]
This is a little different; here, I'm pointing out that we're still using `/home/brutus/.cache/briefcase` when the `brutus` user does not exist in the image; such as when using Docker Desktop on Linux and `root ` is used in the image.

It's not an inherent problem....it's just a bit strange...especially without any context/history.

I think a more consistent approach would put the Briefcase data directory in `root`'s home directory in this case or use a dedicated location in the filesystem like `/briefcase`.
