### ISSUE TITLE
Support running tools with verbose/debug output enabled

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1384]
### What is the problem or limitation you are having?

Many, if not all, of the underlying tools support enhanced logging. Briefcase's logging could conditionally activate this logging for tools. While not commonly necessary, it may help reveal issues stemming from the underlying tools in users' environments. Although, selfishly, I often just need this during development of Briefcase itself.

For instance, the LinuxDeploy GTK plugin supports verbose logging via the environment variable `DEBUG`.

### Describe the solution you'd like

Enable verbose/debug tool logging via a new switch. Perhaps `-vv` or since this is distinctly different from Briefcase logging, a new switch entirely.

### Describe alternatives you've considered

Occasionally, this can be achieved with exporting environment variables prior to running Briefcase. Otherwise, I just update Briefcase source wherever it's installed.

**Comment by freakboy3742** [comment]
Agreed this is a potentially useful feature, if only for our own internal development.

Is this an argument for `-vvv`? Is there any reason you'd want to turn on verbose logging for the tools, but *not* for briefcase itself?

**Comment by rmartin16** [comment]
Added in #1389.
