### ISSUE TITLE
Windows console output encoding corruption

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1407]
### Describe the bug

Something is getting lost in translation when Briefcase streams `subprocess` calls.

For instance, if a user adds `print("Année")` to their app, then `briefcase dev` and `briefcase run` will ostensibly attempt to print `utf-8` characters to the console and you end up with something like `Ann├⌐e`. Since `é` is a two-byte char in UTF-8, it gets translated to `├` and `⌐` in cp437.

### Steps to reproduce

Add `print("Année")` to a Briefcase app and run `briefcase dev`.

### Expected behavior

Encodings should be managed properly.

This seems to be an outcome from Briefcase output streaming where Briefcase attaches a pipe to the subprocess' `stdout`, reads it in, and writes it to the console via Rich. One of these steps must be making an error about the encoding to use.

Interesting, if you just use Rich directly, it will say the console is UTF-8 while it is actually a msft code page...but still print the text correctly:
```console
❯ python -c 'from rich.console import Console; console=Console(); console.print("Année"); print(console.encoding)'
Année
utf-8

❯ python -c 'import sys, os; print(os.device_encoding(sys.__stdout__.fileno()))'
cp437
```

### Environment

- Operating System: Windows 11
- Python version: python 3.10.11
- Software versions:
  - Briefcase: `0.3.16.dev103+g48fc4baa.d20230820`

### Logs

<details>
<summary>Briefcase Log</summary>

```
Date/Time:       2023-08-19 18:48:32 
Command line:    C:\Users\user\github\beeware\briefcase\venv-3.10-briefcase\Scripts\briefcase dev --log

OS Release:      Windows 10
OS Version:      10.0.22621
Architecture:    AMD64
Platform:        Windows-10-10.0.22621-SP0

Python exe:      C:\Users\user\github\beeware\briefcase\venv-3.10-briefcase\Scripts\python.exe
Python version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Virtual env:     True
Conda env:       False

Briefcase:       0.3.16.dev103+g48fc4baa
Target platform: windows
Target format:   None

Environment Variables:
    ALLUSERSPROFILE=C:\ProgramData
    APPDATA=C:\Users\user\AppData\Roaming
    COMMONPROGRAMFILES=C:\Program Files\Common Files
    COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
    COMMONPROGRAMW6432=C:\Program Files\Common Files
    COMPUTERNAME=VM-WIN11
    COMSPEC=C:\Windows\system32\cmd.exe
    DRIVERDATA=C:\Windows\System32\Drivers\DriverData
    FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
    FPS_BROWSER_USER_PROFILE_STRING=Default
    HOMEDRIVE=C:
    HOMEPATH=\Users\user
    LOCALAPPDATA=C:\Users\user\AppData\Local
    LOGONSERVER=\\VM-WIN11
    NUMBER_OF_PROCESSORS=4
    ONEDRIVE=C:\Users\user\OneDrive
    OS=Windows_NT
    PATH=C:\Users\user\github\beeware\briefcase\venv-3.10-briefcase\Scripts;C:\Program Files\PowerShell\7;C:\Users\user\.pyenv\pyenv-win\shims;C:\Users\user\.pyenv\pyenv-win\versions\3.9.13;C:\Users\user\.pyenv\pyenv-win\versions\3.8.10;C:\Users\user\.pyenv\pyenv-win\versions\3.10.11;C:\Users\user\.pyenv\pyenv-win\versions\3.11.3;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;;C:\Program Files\dotnet\;C:\Program Files\starship\bin\;C:\Program Files\PowerShell\7\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\user\.pyenv\pyenv-win\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\.dotnet\tools;C:\Users\user\.dotnet\tools;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin
    PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
    POWERSHELL_DISTRIBUTION_CHANNEL=MSI:Windows 10 Pro
    PROCESSOR_ARCHITECTURE=AMD64
    PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
    PROCESSOR_LEVEL=25
    PROCESSOR_REVISION=2100
    PROGRAMDATA=C:\ProgramData
    PROGRAMFILES=C:\Program Files
    PROGRAMFILES(X86)=C:\Program Files (x86)
    PROGRAMW6432=C:\Program Files
    PSMODULEPATH=C:\Users\user\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
    PUBLIC=C:\Users\Public
    PYENV=C:\Users\user\.pyenv\pyenv-win\
    PYENV_HOME=C:\Users\user\.pyenv\pyenv-win\
    PYENV_ROOT=C:\Users\user\.pyenv\pyenv-win\
    STARSHIP_SESSION_KEY=********************
    STARSHIP_SHELL=pwsh
    SYSTEMDRIVE=C:
    SYSTEMROOT=C:\Windows
    TEMP=C:\Users\user\AppData\Local\Temp
    TMP=C:\Users\user\AppData\Local\Temp
    USERDOMAIN=vm-win11
    USERDOMAIN_ROAMINGPROFILE=vm-win11
    USERNAME=user
    USERPROFILE=C:\Users\user
    VIRTUAL_ENV=C:\Users\user\github\beeware\briefcase\venv-3.10-briefcase
    VIRTUAL_ENV_DISABLE_PROMPT=1
    WINDIR=C:\Windows
    WSLENV=WT_SESSION::WT_PROFILE_ID
    WT_PROFILE_ID={574e775e-4f2a-5b96-ac1e-a2962a402336}
    WT_SESSION=f5d14929-bfdc-4438-b46d-323336b15bc0
    _OLD_VIRTUAL_PATH=C:\Program Files\PowerShell\7;C:\Users\user\.pyenv\pyenv-win\shims;C:\Users\user\.pyenv\pyenv-win\versions\3.9.13;C:\Users\user\.pyenv\pyenv-win\versions\3.8.10;C:\Users\user\.pyenv\pyenv-win\versions\3.10.11;C:\Users\user\.pyenv\pyenv-win\versions\3.11.3;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;;C:\Program Files\dotnet\;C:\Program Files\starship\bin\;C:\Program Files\PowerShell\7\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\user\.pyenv\pyenv-win\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\.dotnet\tools;C:\Users\user\.dotnet\tools;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin

Briefcase Log:
[18:48:29]                                                                                                                                                                dev.py:208
           [helloworld] Starting in dev mode...                                                                                                                           dev.py:208
                                                                                                                                                                   subprocess.py:705
           >>> Running Command:                                                                                                                                    subprocess.py:706
           >>>     'C:\Users\user\github\beeware\briefcase\venv-3.10-briefcase\Scripts\python.exe' -u -X dev -X utf8 -c 'import runpy,                             subprocess.py:707
           sys;sys.path.pop(0);sys.argv.extend([]);runpy.run_module("helloworld", run_name="__main__", alter_sys=True)'                                                             
           >>> Working Directory:                                                                                                                                  subprocess.py:714
           >>>     C:\Users\user                                                                                                                                   subprocess.py:715
           >>> Environment Overrides:                                                                                                                              subprocess.py:724
           >>>     PYTHONPATH=C:\Users\user\github\beeware\briefcase\tmp\helloworld\src                                                                            subprocess.py:726
           >>>     PYTHONMALLOC=default                                                                                                                            subprocess.py:726
           ===========================================================================                                                                                    run.py:160
           Ann├⌐e                                                                                                                                                  subprocess.py:675
```

</details>

**Comment by rmartin16** [comment]
As a start to the investigation, I was curious which Unicode characters are read out by Briefcase while streaming:
```
[helloworld] Starting in dev mode...
===========================================================================
output_line='Ann├⌐e\n'
[hex(ord(c)) for c in output_line]=['0x41', '0x6e', '0x6e', '0x251c', '0x2310', '0x65', '0xa']
Ann├⌐e
```

So, this demonstrates the the corruption is happening before Briefcase even reads in the data since we getting [0x251c](https://www.compart.com/en/unicode/U+251C) and [0x2310](https://www.compart.com/en/unicode/U+2310) back.

If I disable setting the encoding for `stdout` for the subprocess call:
```
[helloworld] Starting in dev mode...
===========================================================================
output_line='AnnÃ©e\n'
[hex(ord(c)) for c in output_line]=['0x41', '0x6e', '0x6e', '0xc3', '0xa9', '0x65', '0xa']
AnnÃ©e
```

Here, we can see the UTF-8 encoding of é (i.e. 0xc3e9) has become two separate characters when Briefcase reads it.

Finally, if i set the encoding for `stdout` to UTF-8:
```
[helloworld] Starting in dev mode...
===========================================================================
output_line='Année\n'
[hex(ord(c)) for c in output_line]=['0x41', '0x6e', '0x6e', '0xe9', '0x65', '0xa']
Année
```

Now, we finally get Unicode [0xe9](https://www.compart.com/en/unicode/U+00E9) for é.

I think this implies that setting the encoding for `stdout` is dependent on whether it's being piped back to Python or not.

**Comment by rmartin16** [comment]
Thoughts after reviewing this some more....

## Background
The encoding that's passed to `subprocess.Popen()` is only relevant when the standard IO handles/descriptors aren't being used by the spawned child process and instead its IO is redirected to pipes. For simplicity, we'll only consider `stdout` here.

Specifically, the encoding is used to decode the bytes read from the pipe written to by the child process' `stdout`.

As a note, the constant presence of the `encoding` argument for `Popen()` makes defaulting `text=True` superfluous since an encoding implies text instead of bytes is desired.

If an encoding is not specified, then `Popen()` will use the "default encoding" for the system (unless UTF-8 mode is enabled...then its UTF-8...which is kinda bonkers because the _user_ determines if UTF-8 mode is used).

## Status Quo
The current implementation of setting encoding:
```python
# If we're in text/universal_newlines mode, ensure that there is
# an encoding specified. If encoding isn't specified, default to
# the system's stdout encoding.
# This is for the benefit of Windows, which uses cp437 for console
# output when the system encoding is cp1252.
# `__stdout__` is used because rich captures and redirects `sys.stdout`.
# The fallback to "UTF-8" is needed to catch the case where stdout
# is redirected to a non-tty (e.g. during pytest conditions)
if kwargs.get("text") or kwargs.get("universal_newlines", False):
    kwargs.setdefault(
        "encoding", os.device_encoding(sys.__stdout__.fileno()) or "UTF-8"
    )
```

This all came about from #772; previously, on Windows, `Popen()` would default to using the system encoding of cp1252 to read the pipe when really the data in the pipe is cp437.

So, this change updates Briefcase's use of `Popen()` to "use the encoding that Python is using to write to `stdout` instead of whatever the default may be".

## Speculation
But...I am wondering about the implicit assumptions being made here...

Specifically, this is assuming that the data in the pipe will be using the same encoding that Python is using to write to the console....but I'm not sure if there's anything backing up why this would be true...

If we consider #770 (the issue that initiated setting `encoding` in the first place), we see that the output of `light.exe` was indeed using cp437. Although, it isn't entirely clear to me why.....given that its `stdout` isn't even connected to a console...

Nonetheless, we can determine that using cp437 for data in a pipe is not a generic property of Windows processes writing to `stdout`. The two commands below demonstrate that Python will put data with two different encodings in to the pipe:
```console
python -c "import subprocess, sys; print(subprocess.run([sys.executable, '-X', 'utf8', '-c', 'print(\'Année\')'], stdout=subprocess.PIPE).stdout.decode('utf8'))"
```
```console
python -c "import subprocess, sys; print(subprocess.run([sys.executable, '-c', 'print(\'Année\')'], stdout=subprocess.PIPE).stdout.decode('cp1252'))"
```

## Situation
I think there's a few things this means:

- We cannot safely assume the encoding of the data we're receiving from `Popen()` calls...
  - But a decision on which encoding to assume is being used must be made nonetheless...
  - The encoding that a specific executable uses for text in a pipe is inherently dependent on that executable.
  - Assuming an arbitrary executable will encode data in the pipe using an encoding that's relevant to the platform is not a guarantee. At best, it may just be a reasonable guess....but I'm not sure if there's rationale to believe `stdout` data will inherently be encoded for the console encoding if `stdout` isn't attached to a console
    - I'm definitely willing to hear opposition to this....I just can't find much supporting evidence I guess
  - Therefore, I propose:
    - Update `briefcase.integrations.subprocess` to always default to UTF-8
    - Update the usage of specific executables to set `encoding` at the point that executables are run by Briefcase
      - I haven't done the full research to understand what this means for Briefcase on Windows
      - That is....I don't actually know which encoding all of the third party tools are actually using in the pipe
      - But...I'm willing to bet it currently doesn't really matter whether we're expecting UTF-8, cp437, cp1252, or even GB-18030....since they're all compatible with 1-btye ASCII...and that's basically all the output.
- Always run `sys.executable` in UTF-8 mode
  - Currently, `briefcase dev` runs Python in UTF-8 mode....and that's kinda what sparked this whole thing since Briefcase was expecting to see cp437 data from running `sys.executable` when we're configuring it to return UTF-8 data
  - And PEP 686 is going to make UTF-8 the default anyway in the relatively near future
  - This involves updating:
    - `pip` installs in `create.py`
    - `pip` installs in `dev.py`
    - building sdists in `linux/__init__.py`
    - building wheels in `web/static.py`
- Set `errors` explicitly when calling `subprocess` so it doesn't default to `strict`
  - In light of the fact we can't guarantee the encoding is correct, it may be prudent to set `errors` when calling `subprocess` so it can't raise an uncaught exception for the wrong encoding is used.
  - This would mask when the wrong encoding is being used....but it wouldn't prevent users from using Briefcase
  - I'm currently undecided on actually doing this, though

**Comment by freakboy3742** [comment]
As always, a very thorough diagnosis.

>   * Therefore, I propose:
>     
>     * Update `briefcase.integrations.subprocess` to always default to UTF-8

This seems like reasonable default for almost all "well behaved" tooling.

>     * Update the usage of specific executables to set `encoding` at the point that executables are run by Briefcase
>       
>       * I haven't done the full research to understand what this means for Briefcase on Windows

This is the one that makes me nervous - but I'm not sure I have a better suggestion. Windows is the only platform that seems to be seriously lagging when it comes to UTF-8 adoption - Linux distros have been moving away from "C locale", and macOS X has always been UTF-8; but Windows has enough legacy that cp1252 and cp437 (and others) seem like they're going to linger indefinitely. 

Making things worse, we have no way to know for certain which specific tools are using which encoding, since this is generally badly documented (if at all), and in particular on Windows, tools aren't really set up for piping (at least, it's not as fundamental to workflow as it in on Unix). I guess the best we can do is to try and work out what encoding each tool is using, and accommodate that.

>       * That is....I don't actually know which encoding all of the third party tools are actually using in the pipe
>       * But...I'm willing to bet it currently doesn't really matter whether we're expecting UTF-8, cp437, cp1252, or even GB-18030....since they're all compatible with 1-btye ASCII...and that's basically all the output.

This is the saving grace - they're all 100% compatible on 7-bit ASCII, and 95% compatible on 8-bit ASCII. The unfortunate thing is that the failure mode is "languages the core team don't use on a daily basis", which means inconvenient bugs. 

> * Always run `sys.executable` in UTF-8 mode

Again - this seems like the right thing - especially since we can generally ensure that Python *will* do the right thing.

> * Set `errors` explicitly when calling `subprocess` so it doesn't default to `strict`
>   
>   * In light of the fact we can't guarantee the encoding is correct, it may be prudent to set `errors` when calling `subprocess` so it can't raise an uncaught exception for the wrong encoding is used.
>   * This would mask when the wrong encoding is being used....but it wouldn't prevent users from using Briefcase
>   * I'm currently undecided on actually doing this, though

I think this is likely worth it. In most cases, the output is cosmetic - we're not reading the app/path name from the output; so a "replace" or "ignore" strategy on encoding errors will lead to messy output, but not a crash. That seems preferable to a hard crash because of an incompatibility we can't easily accommodate.

**Comment by rmartin16** [comment]
> > * Update the usage of specific executables to set `encoding` at the point that executables are run by Briefcase
> >   
> >   * I haven't done the full research to understand what this means for Briefcase on Windows
> 
> 
> This is the one that makes me nervous - but I'm not sure I have a better suggestion. Windows is the only platform that seems to be seriously lagging when it comes to UTF-8 adoption - Linux distros have been moving away from "C locale", and macOS X has always been UTF-8; but Windows has enough legacy that cp1252 and cp437 (and others) seem like they're going to linger indefinitely.
> 
> Making things worse, we have no way to know for certain which specific tools are using which encoding, since this is generally badly documented (if at all), and in particular on Windows, tools aren't really set up for piping (at least, it's not as fundamental to workflow as it in on Unix). I guess the best we can do is to try and work out what encoding each tool is using, and accommodate that.

Yeah; I think I'll implement a weaker form of this. I'll leave the default behavior of expecting whichever encoding that Python is currently using for `stdout` but I'll add the `encoding` parameter to `subprocess` calls where it is known. In practice, I think this will only affect the calls to `sys.executable` where `-Xutf8` will be enforced now.
