### ISSUE TITLE
Where to start reading?

### ISSUE THREAD

**Issue by cdeil** [beeware/briefcase#142]
I'm new to this and wanted to try out briefcase for the first time.

From the README I found two links:

https://briefcase.readthedocs.io/en/latest/background/getting-started.html
https://briefcase.readthedocs.io/en/latest/background/quickstart.html

```
Quickstart
A quickstart guide can be found at Quickstart.

Documentation
Documentation for Briefcase can be found on Read The Docs.
```

But actually I think this is the best place to start, no?
https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html

Suggestion:

Rename this to something like "installation":
https://briefcase.readthedocs.io/en/latest/background/getting-started.html

With this I'm not sure, it's pretty confusing to newcomers 
https://briefcase.readthedocs.io/en/latest/background/quickstart.html
and the content seems to be covered in a better way here:
https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html

**Comment by freakboy3742** [comment]
Thanks for the feedback. 

I agree the "quick start" guide isn't *that* helpful for a first time reader; it's intended more of a cheat sheet guide for someone who already knows how the project works. De-emphasisng that part of the README would make sense.

As for Tutorial-0 as a better starting point - the first thing the tutorial does is link to the getting started guide; and the last thing in the getting started guide is a link to the tutorial. So, the wording in the README may need some fine tuning, but I think the Getting Started guide is the right destination.

**Comment by hnarasaki** [comment]
I'd like to make some changes to the README to clarify where users of different experience levels can get started.
