### ISSUE TITLE
Force decoding `briefcase.toml` as UTF-8

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1430]
### Describe the bug

Currently, decoding `briefcase.toml` is deferred to `tomllib` and it uses the system's default encoding. The `briefcase.toml` file is encoded with UTF-8 via cookiecutter.

### Steps to reproduce

1. Configure the Linux locale to en_us.ISO-8859-1 (`dpkg-reconfigure locales` may be useful)
2. Run `briefcase build linux appimage` with a project named Année

### Expected behavior

`briefcase.toml` is decoded with UTF-8 regardless of the system's default encoding.

`tomli` provides a `loads()` API so Briefcase should be able to do the decode itself first instead of using the `load()` API.

### Environment

- Operating System: ubuntu 22.04
- Python version: 3.11.4
- Software versions:
  - Briefcase: `0.3.16.dev171+g4afaffba.d20230901`

**Comment by freakboy3742** [comment]
I would like it on record that all computers should be thrown in to the sea. :-)

**Comment by rmartin16** [comment]
It turns out that the default encoding for converting a string <=> bytes versus decoding a file to a string work differently.

Without an specified encoding, [`str.encode()`](https://docs.python.org/3.11/library/stdtypes.html#str.encode) will use UTF-8. Additionally, [`bytes.decode()`](https://docs.python.org/3.11/library/stdtypes.html#bytes.decode) works the same way and defaults to UTF-8.

However, [`Path.open()`](https://github.com/python/cpython/blob/e7de0c5901b85a5241386a33f98c27a4e08d5384/Lib/pathlib.py#L961), without a specified encoding, will use [`io.text_encoding()`](https://docs.python.org/3/library/io.html#io.text_encoding) to choose an encoding. If Python is running in UTF-8 mode, this will choose UTF-8; otherwise, it will be the locale for the system.

This means that `tomllib` and `tomli_w` are already doing the right thing and always reading and writing TOML files as UTF-8....which makes sense given the spec requires UTF-8 for TOML.

P.S. I've also discovered [`-X warn_default_encoding`](https://docs.python.org/3/using/cmdline.html#cmdoption-X) which may help detect situations where a default encoding is being used to read a file. I'll experiment with it to see if it can't be incorporated in to CI.

**Comment by mhsmith** [comment]
So creating a project named Année actually doesn't cause any problems? Or are the problems caused by something else?

**Comment by rmartin16** [comment]
> So creating a project named Année actually doesn't cause any problems? Or are the problems caused by something else?

There's definitely still a problem for creating an AppImage in Docker when the host system isn't using UTF-8.

The immediate cause of the issue is using `é` in the file and directory names for AppImage and then building it in Docker.

For instance, here is `briefcase.toml`:
```toml
[paths]
app_path = "Année.AppDir/usr/app"
app_packages_path = "Année.AppDir/usr/app_packages"
support_path = "Année.AppDir/usr"
```

However, the problems do not stem from reading `briefcase.toml`; there is something going on with how the directory names are being passed in to Docker. Namely, when `pip` installs the app packages during `briefcase create linux appimage` within Docker, it does so in to a mojibake directory name:

![image](https://github.com/beeware/briefcase/assets/387848/58935e8b-6b45-493f-ab3c-04603c65b5c4)

(I can't paste the text because copying from the console puts ISO-8859 encoding text in to the clipboard and the paste across the VM boundary tries to decode it as UTF-8).

Additionally, though, I still haven't been able to get `subprocess` to properly decode the output from Docker; when I try to use `encoding="utf-8"` for the Docker calls, the output streamer thread literally disappears as soon as a non-ASCII character is written to `stdout` and Briefcase forcibly kills Docker. (I was also able to replicate this running the Flatpak build process with `encoding="utf-8"`...when `pip` tries to print its download progress bar, the streamer just disappears...)

And even if you manage to just get past these errors (without resolving them), linuxdeploy creates a final AppImage with mojibake in the filename.

I've spent a little bit of time trying to understand where these decodes are going wrong....but so much is going wrong, its hard to separate the problems.

The easier solution would probably be to align AppImage with how Flatpak and System packages work; i.e. use the NFKD normalized name.
