### ISSUE TITLE
Support of Dynamic Metadata in configuration file

### ISSUE THREAD

**Issue by DaloroAT** [beeware/briefcase#1432]
### What is the problem or limitation you are having?

Hello Briefcase Team! Thank you for your great project ❤️ 

I have my own project where I'm using [Dynamic Metadata](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata) for the version field. `pyproject.toml` looks like

```yaml
[project]
name = "my-project"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {file = "my-project/VERSION"}
```

I have the file `VERSION` in the source folder of `my-project` with a version value as a plain string. During package installation, this version was substituted.

When I run `briefcase create` I got an error `Briefcase configuration error: Global configuration is incomplete (missing 'version')`. 

### Describe the solution you'd like

Please add support for dynamic values in `pyproject.toml` . At least for the default `setuptools` build system.

### Describe alternatives you've considered

No other solution. 

Right now, as a workaround, I will write the version explicitly in `[tool.briefcase]` section and add the test in CI that values in `tool.briefcase.version` and `my-project/VERSION` are the same.

**Comment by mhsmith** [comment]
Thanks for the request; let's discuss this as part of #474.
