### ISSUE TITLE
some error from build android 

### ISSUE THREAD

**Issue by d0kyuan** [beeware/briefcase#144]
if i use voc==0.1.5 toga==0.2.15 apk will stuck in presplash
if i use voc==0.1.4 toga==0.2.15 apk will crash and show error `java.lang.RuntimeException: Unable to start activity ComponentInfo{s.s.helloworld/android.PythonActivity}: AttributeError: 'NoneType' object has no attribute '_impl'`

if i use voc==0.1.5 or 0.1.4 toga==0.3.0.dev8 `Problem occurred in toga/handlers.py
Node: YieldFrom(value=Call(func=Attribute(value=Name(id='asyncio', ctx=Load(), lineno=19, col_offset=23), attr='sleep', ctx=Load(), lineno=19, col_offset=23), args=[
    Name(id='delay', ctx=Load(), lineno=19, col_offset=37),
  ], keywords=[], lineno=19, col_offset=23), lineno=19, col_offset=12)
  File "/usr/local/lib/python3.5/dist-packages/voc/python/ast.py", line 160, in visit
    super().visit(node)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/local/lib/python3.5/dist-packages/voc/python/ast.py", line 49, in dec
    fn(self, node, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/voc/python/ast.py", line 1756, in visit_YieldFrom
    raise NotImplementedError('No handler for YieldFrom')
NotImplementedError: No handler for YieldFrom
:buildPythonDebug FAILED`

All step follow 'https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html'

How to build android apk ?!

**Comment by UncleGoogle** [comment]
I'm getting similar issue with toga==0.3.0.dev14:

```
         self.interface.main_window._impl.native.Controls.Add(menubar)
AttributeError: 'NoneType' object has no attribute '_impl'
```

**Comment by freakboy3742** [comment]
We've formally marked our Android backend as broken; this should hopefully be addressed in the near future thanks to a grant from the Python Software Foundation Education Grants committee. In the meantime, there's no point maintaining an open ticket, Android is effectively (for now) an unsupported platform.
