### ISSUE TITLE
Can I package my existing pyqt code using Briefcase?

### ISSUE THREAD

**Issue by nickzsche** [beeware/briefcase#1469]
### What is the problem or limitation you are having?

I need to turn my Python code into a exe file. But pyinstaller is marked as a virus. I also discovered briefcase today. I have a QT application that I wrote before. Can I pack this with Briefcase? My English may be a little bad, sorry.

### Describe the solution you'd like

Pyqt5 to run file 

### Describe alternatives you've considered

Another file extensions

**Comment by freakboy3742** [comment]
Yes. Briefcase can package any GUI  framework, provided that framework is distributed as wheels without external dependencies.

The Briefcase new project wizard contains options for both PySide 2 and 6. However, there's no reason I'm aware of that PyQt apps wouldn't work; pick "non framework" in the wizard, then add the code and requirement manually.
