### ISSUE TITLE
Removing Standalone Python's clang dependency for Flatpak builds breaks on non-x86-64 hardware

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1511]
### Describe the bug

With the 20231002 release of Standalone Python, it was necessary to remove a dependency on clang via https://github.com/beeware/briefcase-linux-flatpak-template/pull/22. This change only accounts for Python for x86-64. Therefore, attempting to build a Flatpak for aarch64 now fails.

```
[pygametest] Building Flatpak...
Downloading sources
Initializing build dir
Committing stage init to cache
Starting build of com.example.pygametest
========================================================================
Building module cpython in /home/russell/tmp/beeware/pygametest/build/pygametest/linux/flatpak/.flatpak-builder/build/cpython-1
========================================================================
Running: mkdir -p /app/bin
Running: cp -r support/python/bin/* /app/bin
Running: mkdir -p /app/include
Running: cp -r support/python/include/* /app/include
Running: mkdir -p /app/lib
Running: cp -r support/python/lib/* /app/lib
Running: sed -e "s/-fdebug-default-version=4//g" support/python/bin/python3-config > /app/bin/python3-config
Running: sed -e "s/-fdebug-default-version=4//g" support/python/bin/python3.10-config > /app/bin/python3.10-config
Running: sed -e "s/-fdebug-default-version=4//g" support/python/lib/python3.10/_sysconfigdata__linux_x86_64-linux-gnu.py > /app/lib/python3.10/_sysconfigdata__linux_x86_64-linux-gnu.py
sed: can't read support/python/lib/python3.10/_sysconfigdata__linux_x86_64-linux-gnu.py: No such file or directory
Error: module cpython: Child process exited with code 2
Building...

Error while building app pygametest.
```

### Steps to reproduce

Using Briefcase v0.3.16, run `briefcase build linux flatpak` on aarch64 hardware.

### Expected behavior

Flatpak builds successfully on aarch64 hardware.

### Environment

- Operating System: Debian Bullseye 11
- Python version: 3.10.6
- Software versions:
  - Briefcase: `0.3.17.dev12+g4a061041`

### Logs

[briefcase.2023_10_24-18_42_25.run.log](https://github.com/beeware/briefcase/files/13132944/briefcase.2023_10_24-18_42_25.run.log)

**Comment by freakboy3742** [comment]
Ugh. Computers were a mistake. :-)

I guess the same support package reversion is called for here as well. We won't be able to support Python 3.12 on ARM, but that's better than nothing, I suppose.

**Comment by freakboy3742** [comment]
(or, I suppose we could try to make the sed fix robust for any architecture...)

**Comment by freakboy3742** [comment]
The format of the `_sysconfigdata` filename is essentially fixed - it's part of how sysconfigdata works at runtime. To get a different filename, you'd need to be passing in completely different compiler flags (e.g., using musl rather than the GNU Cl library) - but at that point, you're going to be hitting all sorts of other compatibility problems as well. Within the constraints of manylinux compatibility, we can essentially guarantee the location of the file, and the `__linux_<arch>-linux-gnu` suffix.
