### ISSUE TITLE
Unexpected icons for Pygame app

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1532]
### Describe the bug

When I run a Pygame based helloworld BeeWare app, this is the icon I see most places:

![image](https://github.com/beeware/briefcase/assets/387848/4c8a4452-b9bd-4edf-bac5-fb9c833a6ec6)

### Steps to reproduce

1. Create a Pygame=based BeeWare app
2. Run `briefcase dev` or `briefcase run`
3. See app icon in Alt Tab menu, title bar, start menu, etc.

### Expected behavior

Expected brutus icons.

### Environment

- Operating System: pop os 22.04, windows 11 (and presumably macOS)
- Python version: 3.10.13
- Software versions:
  - Briefcase: `0.3.17.dev54+g39040475.d20231112`
  - Toga: `0.4.0`

**Comment by freakboy3742** [comment]
To confirm - are you seeing this on *running* apps, or in locations where it's packaged/installed? If it's the former, then it's an issue with the PyGame app template requiring a call to [set_icon](https://www.pygame.org/docs/ref/display.html#pygame.display.set_icon); if it's the latter, then there's a much deeper issue. I can't think of any reason why a PyGame bundle would appear with the default PyGame icon in a "static" location (such as the installer, or the appearance on the filesystem when not running.

**Comment by rmartin16** [comment]
I am not seeing this image in the app layout in the file system during packaging or after it is installed. I only see it presented in the app's UI as well as the OS's UI relevant to the app.

**Comment by freakboy3742** [comment]
I'm not sure I can reproduce what you're describing (or, at least, what I understand you to be describing). What I'm seeing are the places where Briefcase is in charge of the icon, it's working:

* macOS: <img width="110" alt="Screenshot 2023-11-13 at 6 42 35 am" src="https://github.com/beeware/briefcase/assets/37345/4af87cf2-f027-4519-b41e-c973f0a1195d"> <img width="245" alt="Screenshot 2023-11-13 at 6 51 13 am" src="https://github.com/beeware/briefcase/assets/37345/dda68458-dcc6-4dc6-914e-af63fb37b06a"> <img width="149" alt="Screenshot 2023-11-13 at 6 53 20 am" src="https://github.com/beeware/briefcase/assets/37345/e190264e-9872-4164-8929-8b8de55817d8">


* Windows: <img width="97" alt="Screenshot 2023-11-13 at 6 47 33 am" src="https://github.com/beeware/briefcase/assets/37345/e594b90f-0401-4e57-a690-2ffb46993cbc"> <img width="179" alt="Screenshot 2023-11-13 at 6 49 54 am" src="https://github.com/beeware/briefcase/assets/37345/72dd9775-19f8-4b09-8c50-722b4b365b51">

* Linux <img width="291" alt="Screenshot 2023-11-13 at 6 55 07 am" src="https://github.com/beeware/briefcase/assets/37345/b552e5e4-1b8f-44d9-81b4-bba51a58c9e8">

But the places where it's being displayed at runtime, it's (mostly) the PyGame icon:

* Windows: <img width="94" alt="Screenshot 2023-11-13 at 6 41 35 am" src="https://github.com/beeware/briefcase/assets/37345/760db1ae-b1e4-493c-911c-4217d46a7265">

* Ubuntu 22.04 <img width="76" alt="Screenshot 2023-11-13 at 6 42 06 am" src="https://github.com/beeware/briefcase/assets/37345/31428e36-859a-4cba-9ca2-cafa5f237539">

* macOS <img width="77" alt="Screenshot 2023-11-13 at 6 48 50 am" src="https://github.com/beeware/briefcase/assets/37345/056c31a3-ab16-48a0-a189-08203cbbafbd">

The one exception is the Window taskbar icon for some reason: <img width="62" alt="Screenshot 2023-11-13 at 6 41 28 am" src="https://github.com/beeware/briefcase/assets/37345/dd2889cc-b9b6-4466-a082-a41d9ad2fc4d">

Those PyGame icon uses are all runtime uses. Are you seeing something different?

**Comment by rmartin16** [comment]
> Those PyGame icon uses are all runtime uses. Are you seeing something different?

That's quite similar to my experience. It's just seeing a cartoon dinosaur with a game controller in its mouth at all was not something I was expecting in the helloworld app 😃 if that should be expected, then we can probably close this issue.

**Comment by freakboy3742** [comment]
It's expected in the sense that the template doesn't currently do anything to set the runtime icon. It's *fixable* though - we just need to add a call to `set_icon()` in the pygame template.

**Comment by rmartin16** [comment]
- Resolved in https://github.com/beeware/briefcase/pull/1547
