### ISSUE TITLE
"Could not find com.android.tools.build:gradle:8.0.1" when building APK file

### ISSUE THREAD

**Issue by AbRamazani** [beeware/briefcase#1558]
### Describe the bug

I wrote a simple python app with beeware and toga.
Now I want to build a APK file from this app.
I ran `briefcase create android` and then `briefcase build android` but I see this error:
```
[newapp] Updating app metadata...
Setting main module... done

[newapp] Building Android APK...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'New App'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:8.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.0.1/gradle-8.0.1.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/8.0.1/gradle-8.0.1.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Building...

Error while building project.


```

### Steps to reproduce

1. Start a new app with `briefcase`
2. Develop a simple app with toga.
3. Run `briefcase build android`

### Expected behavior

I expected to have a APK file from my app.

### Environment

- Operating System: Debian GNU/Linux 12 (bookworm)
- Python version: 3.11.2
- Software versions:
  - Briefcase: 0.3.16
  - Toga: 0.4.0

**Comment by rmartin16** [comment]
Please upload the full logfile created by Briefcase for the error; if a logfile was not created, running `briefcase build android --log` will ensure one is created.

**Comment by AbRamazani** [comment]
> Please upload the full logfile created by Briefcase for the error; if a logfile was not created, running `briefcase build android --log` will ensure one is created.

this is the log file...
[briefcase.2023_11_29-20_17_34.build.log](https://github.com/beeware/briefcase/files/13503764/briefcase.2023_11_29-20_17_34.build.log)

**Comment by rmartin16** [comment]
Thanks.

I notice you have a proxy configuration:
```
    all_proxy=socks://169.254.1.1:10808/
    http_proxy=http://169.254.1.1:10809/
    https_proxy=http://169.254.1.1:10809/
    no_proxy=localhost,127.0.0.0/8,::1
```
Given this, I'd first check if Briefcase can run Gradle properly if you remove this configuration before running `briefcase build android` again.

**Comment by freakboy3742** [comment]
Closing due to lack of response from the original reporter.
