### ISSUE TITLE
pywebview on macOS

### ISSUE THREAD

**Issue by idbeny** [beeware/briefcase#1570]
### What is the problem or limitation you are having?

Executing the command `briefcase dev` on macOS displays an error
```
File "/Users/ben/Work/Code/BW/Example/beeware-venv/lib/python3.9/site-packages/webview/platforms/cocoa.py", line 70, in BrowserView
    class AppDelegate(AppKit.NSObject):
objc.error: AppDelegate is overriding existing Objective-C class
```

### Describe the solution you'd like

I can use pywebview, toga, and briefcase together on platform(macOS, iOS, android, windows).

### Describe alternatives you've considered

PyInstaller abd Buildozer

### Additional context

```
pip install pywebview
```

Add to requirees in pyproject.toml:
```
requires = [
    "pywebview",
]
```

Executing `briefcase dev` on macOS:
```
File "/Users/ben/Work/Code/BW/Example/beeware-venv/lib/python3.9/site-packages/webview/platforms/cocoa.py", line 70, in BrowserView
    class AppDelegate(AppKit.NSObject):
objc.error: AppDelegate is overriding existing Objective-C class
```

Executing `briefcase run ios` on iOS:
```
Unable to launch app mspyshell.
```

**Comment by freakboy3742** [comment]
What GUI toolkit did you specify when you created your app? If you've specified Toga - that's your problem. PyWebView *is* a GUI toolkit - it expects to take full control of the app lifecycle. It's not going to be compatible with Toga, which *also* expects to take control of the app lifecycle.

If you want a "Web app inside a Toga app shell", you're looking for the Positron examples, either [static](https://github.com/beeware/toga/tree/main/examples/positron-static) or [Django](https://github.com/beeware/toga/tree/main/examples/positron-django) (other web frameworks could be used as well; we just haven't provided explicit examples).

**Comment by freakboy3742** [comment]
Reading this report a little closer - it seems like you *are* using Toga *and* PyWebView, and hoping that will also allow you to deploy to iOS.

This can't work.

If you want to target macOS, you've got to pick either PyWebView or Toga... not both.

If you want to target iOS, PyWebView isn't the tool you need.

Closing on that basis; If I've misunderstood what you're doing, I'm happy to re-open the issue.
