### ISSUE TITLE
briefcase run Android hiccup

### ISSUE THREAD

**Issue by retoxing** [beeware/briefcase#1591]
### Describe the bug

`$ briefcase run Android`
would fail with the following error in the log:

> Error: Package path is not valid. Valid system image paths are: 
> null
> Return code: 1

To get past this I had to open a terminal at:
`~/.cache/briefcase/tools/android_sdk/cmdline-tools/9.0/bin`

and run the command:
`./sdkmanager "system-images;android-31;default;x86_64"`

Posted here in case it's useful to somebody else ...

### Steps to reproduce

$ briefcase run Android

### Expected behavior

(install) launch an Android emulator

### Environment

- Operating System: MX Linux (Debian bullseye)
- Python version: 3.9
- Software versions:
  - Briefcase: 0.3.16
  - Toga: 0.4.1
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
The presentation of the error suggests that there was a network error at some point during the install process (possibly one that Briefcase ignored; but possibly one that that you ignored) resulting in the system package not being installed.

When Briefcase fails, it produces log files. Have you got the log files for the runs up to the point where this error was generated? They will be stored in the `logs` folder of your project.

**Comment by freakboy3742** [comment]
Closing due to lack of response from the original reporter.
