### ISSUE TITLE
Hello World tutorial build fails for iOS at command line, but makes a good xcodeproj

### ISSUE THREAD

**Issue by mlewis1973** [beeware/briefcase#160]
macOS 10.13.6 -> Anaconda-> python 3.5 virtualenv
python setup.py ios -s

* Building XCode project for iPad Pro (10.5-inch) iOS 11.4...
=== BUILD TARGET Hello World OF PROJECT Hello World WITH CONFIGURATION Debug ===
No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=x86_64, VALID_ARCHS=arm64).
** BUILD FAILED **

according to Google, this is because ONLY_ACTIVE_ARCH=YES.
it evidently would work if NO.
the outputted xcodeproj builds and simulates fine in Xcode 9.4.1

any way to fix this?

**Comment by STOIE** [comment]
Yeah, I have the exact same failure and don't know how to proceed... any help?

**Comment by deepvoice** [comment]
#1

**Comment by freakboy3742** [comment]
The mechansim for starting xcodebuild has changed in the 0.3 branch; if you're still seeing this problem, please open a new ticket with deatils.
