### ISSUE TITLE
Tutorial 0 error 

### ISSUE THREAD

**Issue by PShivani07** [beeware/briefcase#161]
$ python3 -m helloworld
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shivani/pycon/helloworld/helloworld/__main__.py", line 1, in <module>    from helloworld.app import main
  File "/home/shivani/pycon/helloworld/helloworld/app.py", line 2, in <module>
    import toga
ImportError: No module named 'toga'

**Comment by Tadaboody** [comment]
What installation configuration did you use?

**Comment by PShivani07** [comment]
pip

**Comment by Tadaboody** [comment]
In the tutorial it tells you to run ``python setup.py <OS>`. what OS did you put in?

**Comment by PShivani07** [comment]
linux...i tried that but i got
$ python3 setup.py linux 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'linux'

**Comment by Tadaboody** [comment]
Could you show your `setup.py`?

**Comment by PShivani07** [comment]
$ cat setup.py
#!/usr/bin/env python
import io
import re
from setuptools import setup, find_packages
import sys

with io.open('./helloworld/__init__.py', encoding='utf8') as version_file:
    version_match = re.search(r"^__version__ = ['\"]([^'\"]*)['\"]", version_file.read(), re.M)
    if version_match:
        version = version_match.group(1)
    else:
        raise RuntimeError("Unable to find version string.")


with io.open('README.rst', encoding='utf8') as readme:
    long_description = readme.read()


setup(
    name='helloworld',
    version=version,
    description='say helloworld',
    long_description=long_description,
    author='Shivani',
    author_email='yoamazing007@gmail.com',
    license='BSD license',
    packages=find_packages(
        exclude=[
            'docs', 'tests',
            'windows', 'macOS', 'linux',
            'iOS', 'android',
            'django'
        ]
    ),
    classifiers=[
        'Development Status :: 1 - Planning',
        'License :: OSI Approved :: BSD license',
    ],
    install_requires=[
    ],
    options={
        'app': {
            'formal_name': 'Hello World',
            'bundle': 'org.beeware'
        },

        # Desktop/laptop deployments
        'macos': {
            'app_requires': [
                'toga-cocoa==0.3.0.dev9',
            ]
        },
        'linux': {
            'app_requires': [
                'toga-gtk==0.3.0.dev9',
            ]
        },
        'windows': {
            'app_requires': [
                'toga-winforms==0.3.0.dev9',
            ]
        },

        # Mobile deployments
        'ios': {
            'app_requires': [
                'toga-ios==0.3.0.dev9',
            ]
        },
        'android': {
            'app_requires': [
                'toga-android==0.3.0.dev9',
            ]
        },

        # Web deployments
        'django': {
            'app_requires': [
                'toga-django==0.3.0.dev9',
            ]
        },
    }
)

**Comment by PShivani07** [comment]
showing the same error:
error: invalid command 'linux'

**Comment by Tadaboody** [comment]
Sorry 😕 Maybe try bringing it to the [gitter chat](https://gitter.im/pybee/general)

**Comment by PShivani07** [comment]
Okay, thank you.

**Comment by PShivani07** [comment]
I tried this,
>>sudo python3 setup.py linux -s
running linux
 * Writing application template...
Project template: https://github.com/pybee/Python-Linux-template.git
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'toga-django==0.3.0.dev9',
  File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/dist-packages/briefcase/app.py", line 477, in run
    self.install_platform_requirements()
  File "/usr/local/lib/python3.5/dist-packages/briefcase/app.py", line 298, in install_platform_requirements
    stderr=subprocess.STDOUT,
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pip', 'install', '--upgrade', '--force-reinstall', '--target=/home/shivani/pycon/helloworld/linux/app_packages', 'toga-gtk==0.3.0.dev9']' returned non-zero exit status 2

I don't understand what is wrong

**Comment by meichthys** [comment]
@PShivani07  Have you installed toga? if so, what version? You need to install v0.3.0.dev3 like:
`pip install toga==0.3.0.dev3`
or if you use pipenv:
`pipenv install toga==0.3.0.dev3`

That should get you up and going. Hopefully soon the dev version will be released as an official 0.3.0 version so this hiccup doesn't keep plaguing folks.. 
@freakboy3742  Do you think we can release the v0.3.0.dev3 version on pypi as a non-dev release?

**Comment by keinagae** [comment]
i am having same issue on windows as  error: invalid command 'Windows'

**Comment by freakboy3742** [comment]
There's nowhere near enough detail in this ticket to make any meaningful suggestions on how to address it. 

If this is your first time trying Briefcase, we recommend working through the tutorial; if you hit problems, let us know what errors you're seeing, and we can help.

**Comment by OgiBalboa** [comment]
> try uninstalling briefcase with `pip uninstall briefcase` and installing it with
> `pip install git+https://github.com/pybee/briefcase`.
> And then running `python setup.py linux` again

I solved my problem thanks to you !
