### ISSUE TITLE
briefcase run android

### ISSUE THREAD

**Issue by LeonardoKassama** [beeware/briefcase#1612]
### Describe the bug

when I run the `briefcase run android` command on the **vs code**  it rises the `Error while building project` error , interrupting  the process  of  **Building Android APK...** 

### Steps to reproduce

1. Go to 'your **BeeWare** project folder'
2. Run `briefcase run android`

### Expected behavior

not raising any error, and launching the android emulator.

### Screenshots

![Captura de ecrã de 2024-01-18 23-04-24](https://github.com/beeware/briefcase/assets/146578724/2798bad6-d153-43ee-b177-ded66d9e82dd)

### Environment

- Operating System: **Debian 12**
- Python version:  **3.11.2**
- Software versions:
  - Briefcase: **0.3.16**
  - Toga: **0.4.1**

### Logs

[briefcase.2024_01_18-21_19_05.run.log](https://github.com/beeware/briefcase/files/13982501/briefcase.2024_01_18-21_19_05.run.log)
[briefcase.2024_01_18-20_57_59.run.log](https://github.com/beeware/briefcase/files/13982502/briefcase.2024_01_18-20_57_59.run.log)

**Comment by rmartin16** [comment]
Can you try deleting the ZIP file at `/home/leonardo/.gradle/wrapper/dists/gradle-8.0-all/a2o1xoguejy6msdh0lk99lxza/gradle-8.0-all.zip` and running `briefcase build android` again?

**Comment by LeonardoKassama** [comment]
I tried, it does the same process until crashing at the same error

**Comment by rmartin16** [comment]
Hmm...can you tell what the file at `/home/leonardo/.gradle/wrapper/dists/gradle-8.0-all/a2o1xoguejy6msdh0lk99lxza/gradle-8.0-all.zip` is? Can you open it manually?

Or what if you try to download the ZIP file manually and open it? Are you able to see the files it contains?
- https://services.gradle.org/distributions/gradle-8.0-all.zip

Ultimately, the Gradle bootstrapping process can't read the ZIP file it is downloading....so, we'll need to understand what it is downloading and why it isn't the expected ZIP file.

**Comment by LeonardoKassama** [comment]
Thanks Man! I downloaded it manually, and now it runs smoothly
