### ISSUE TITLE
This repository does not seem to support Python 3.12 on Android

### ISSUE THREAD

**Issue by lihuaming07** [beeware/briefcase#1625]
### Describe the bug

Because the available versions of Gradle library  are [3.8, 3.9, 3.10, 3.11], I can't use this repository  on the Venv of python3.12

Exception Details:

> 
> [aixuexi] Building Android APK...
> Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'D:\Python\Learning_helper\aixuexi\build\aixuexi\android\gradle\app\build.gradle' line: 25
> 
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Invalid Python version '3.12'. Available versions are [3.8, 3.9, 3.10, 3.11].
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 

### Steps to reproduce

1. Create a project by python 3.12
2. run commend  "briefcase run android -u -r"
3. See error

### Expected behavior

I Have to Restart the programme with Python 3.11 likely with no chocie. Luckily, several codes are finished.

### Screenshots

![image](https://github.com/beeware/briefcase/assets/71958128/c823afcf-6213-4b17-9629-78b7808aa926)

### Environment

- Operating System: Windows 11
- Python version: 3.12.1
- Software versions:
  - Briefcase: 0.3.16
  - Toga: 0.4.1
  - ...

### Logs

I can't paste the log since the github suggest the following error.
`There was an error creating your Issue: body is too long (maximum is 65536 characters).`

**Comment by freakboy3742** [comment]
@mhsmith I agree we're overdue for a release; once we've got the Toga OptionContainer and Camera APIs locked in, I think a release of both Toga and Briefcase is called for.

**Comment by AgostinhoMartins** [comment]
> @mhsmithConcordo que já estamos atrasados ​​para um lançamento; assim que tivermos as APIs Toga OptionContainer e Camera bloqueadas, acho que é necessário um lançamento do Toga e do Briefcase.



> @mhsmith I agree we're overdue for a release; once we've got the Toga OptionContainer and Camera APIs locked in, I think a release of both Toga and Briefcase is called for.

The "briefcase" 0.3.17 is already out. Can we now use it with Python 3.12 on Android?

**Comment by rmartin16** [comment]
@AgostinhoMartins, yes. Briefcase v0.3.17 includes support to create Android apps using Python 3.12.

**Comment by AgostinhoMartins** [comment]
I had to install this to work, it's still not working without it

pip install git+https://github.com/beeware/briefcase

**Comment by rmartin16** [comment]
That is not necessary; you can just install [v0.3.17](https://pypi.org/project/briefcase/0.3.17/) from PyPI.

If you already have briefcase installed, you'll need to upgrade it:
```
python -m pip install -U briefcase
```
Or install v0.3.17 specifically:
```
python -m pip install briefcase==0.3.17
```

**Comment by AgostinhoMartins** [comment]
I uninstalled "briefcase", I installed the latest stable version of briefcase (0.3.17), now it works fine on Android, thanks @rmartin16
