### ISSUE TITLE
[Fedora] Mistake in prompt for installing rpm-build

### ISSUE THREAD

**Issue by Pairman** [beeware/briefcase#1636]
### Describe the bug

When rpm-build is not present on Fedora, ```briefcase package``` will prompt for installing rpm-build via ```sudo dnf install rpmbuild```, whose package name is wrong. The correct package name is ```rpm-build```, installed via ```sudo dnf install rpm-build```.

### Steps to reproduce

1. Fresh install Fedora and use ```briefcase package```
2. Briefcase prompts ```sudo dnf install rpmbuild```
3. DNF cannot find package ```rpmbuild``` with the given command

### Expected behavior

1. Fresh install Fedora and use ```briefcase package```
2. Briefcase prompts ```sudo dnf install rpm-build```
3. DNF installs ```rpm-build``` successfully.

### Environment

OS: Fedora 39

**Comment by freakboy3742** [comment]
Thanks for the report! Care to try your hand at a pull request to fix it? The line of code in question [is here]( https://github.com/beeware/briefcase/blob/main/src/briefcase/platforms/linux/system.py#L855).
