### ISSUE TITLE
failed to build android version of 'Hello World!' app

### ISSUE THREAD

**Issue by dleecn** [beeware/briefcase#166]
hi,

I'm a newbie of brifecase. I follow the tutorial-0 
https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html

I have changed the toga-android version from 0.3.0.dev9 to 0.2.15 as Russell said in Gitter
        'android': {
            'app_requires': [
                # 'toga-android==0.3.0.dev9',
                'toga-android==0.2.15',
            ]
        },
and execute the command
python3 setup.py android -s

but unfortunately the build process failed, the log is here:
[build.log](https://github.com/pybee/briefcase/files/2392685/build.log)

How can I solve this problem?

**Comment by jvmaia** [comment]
same issue here, I tried to compile the voc by myself with the lines [33-37] of build-android.xml commented (lines that compile the stdlib), but I got other error, full log: https://gist.github.com/jvmaia/c8922585763860c17a26f737c340d3b4.
this workaround I tried is the same I use when writing android apps with the template: https://github.com/eliasdorneles/beeware-android-template.

**Comment by freakboy3742** [comment]
We've formally marked our Android backend as broken; this should hopefully be addressed in the near future thanks to a grant from the Python Software Foundation Education Grants committee. In the meantime, there's no point maintaining an open ticket, Android is effectively (for now) an unsupported platform.
