### ISSUE TITLE
Include `pyproject.toml` in the log file

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1674]
### What is the problem or limitation you are having?

When the Briefcase log file doesn't provide information I'm interested in, it will likely be in the project's `pyproject.toml`. For instance, what `requires` is set to.

### Describe the solution you'd like

Append the contents of `pyproject.toml` to the log file.

An alternative to this would be dumping the `AppConfig` object.

### Describe alternatives you've considered

Continue requesting such information specifically.

**Comment by freakboy3742** [comment]
Huge +1 on this. It's obvious detail to include.
