### ISSUE TITLE
Adding more Intents to Android App

### ISSUE THREAD

**Issue by jvmaia** [beeware/briefcase#168]
Is there any method to add Intents to an Android app? (e.g. open app's other pages, open the camera)

**Comment by jvmaia** [comment]
I would like to try to implement that, but this month I don't have the time needed to do it. Is there anything else that I can do to improve the android things?

**Comment by jvmaia** [comment]
Do you know if there is missing in the @MarkusH work? I tested it and it was successful with one modification: I cloned the VOC project, commented the lines 33-37 in build-android.xml (lines that compile the stdlib), generated the new python-android-support.jar and used it in the new template.

**Comment by freakboy3742** [comment]
If you used those commands as described, then you didn't use @MarkusH's template - you would have used the default template. You'll need to clone Markus' repository and checkout his testing branch to get his new code.

I get the following problems:

* Gradlew starts a build daemon that idles with 200% CPU
* Every VOC task is executed on every gradle invocation, not just build - so both debug and release VOC invocations are performed, even when you ask for `gradlew tasks`.
* The run task is disabled (so `--start` won't work)

That's on top of the compilation of stdlib issue that you identified - that will be a problem with VOC. From the investigation I've done so far, VOC is producing slightly incorrect bytecode, resulting in DEX failures on some classes. Someone needs to investigate to establish the problem (and, ideally, put some sort of build protection in place so we can't cut a VOC release which is producing an invalid standard library)

**Comment by jvmaia** [comment]
Ooh, thanks for the help, now I got the same problems, I'll continue to dig into it, and report any news here.

**Comment by jvmaia** [comment]
update 1: I got the app installed in my phone running:
1 - python setup.py android
2 - paste the voc file modified
3 - ./gradlew installDebug

**Comment by jvmaia** [comment]
Hey @freakboy3742 do you know any sources/documentation that @MarkusH's was using to fix the template? it would help a lot!

**Comment by freakboy3742** [comment]
@jvmaia Unfortunately, I don't. IIRC, he said he was going to "start from scratch" - i.e., build a "hello world" app using Android's own native tools, and then retrofit what we needed to strip out and template to make that project a Python project - but I don't know what Markus was using to guide that.

**Comment by jvmaia** [comment]
Ook, thanks @freakboy3742

**Comment by freakboy3742** [comment]
We've formally marked our Android backend as broken; this should hopefully be addressed in the near future thanks to a grant from the Python Software Foundation Education Grants committee. In the meantime, there's no point maintaining an open ticket, Android is effectively (for now) an unsupported platform.
