### ISSUE TITLE
build CLI application

### ISSUE THREAD

**Issue by Jzhenli** [beeware/briefcase#1682]
### What is the problem or limitation you are having?

Run a CLI application based on typer lib.

### Describe the solution you'd like

Hi, I have a CLI application based on typer lib, when to run it with "briefcase dev" command, I don't know how to add the args, do u have any suggestions, thanks.

### Describe alternatives you've considered

Run CLI application with "briefcase dev" command, and can add the args.

**Comment by freakboy3742** [comment]
Thanks for the suggestion - this is a feature request that has existed for a while: #556.

Closing this ticket as a duplicate; follow the older ticket for any updates and for details on how this could be implemented.
