### ISSUE TITLE
llama-cpp-python for beeware 

### ISSUE THREAD

**Issue by krecicki** [beeware/briefcase#1685]
### What is the problem or limitation you are having?

I am running llama-cpp-python in 'briefcase dev' without a problem. Whenever I try to compile to a stand alone: Android, iOS or .dmg -- it fails to install llama-cpp-python. 

We are trying to make our app into an .apk but this is stopping us. This guy https://github.com/Bip-Rep/sherpa/tree/main/android was able to figure something out, but I'm not that smart. These guys also sorted it out https://github.com/Mobile-Artificial-Intelligence/maid

### Describe the solution you'd like

Be able to make an android build with llama-cpp-python to get an .apk to upload to the play store.

Be able to make a iOS build with llama-cpp-python to upload it to the Google App Store.

### Describe alternatives you've considered

I am not sure what to do.

**Comment by freakboy3742** [comment]
The Briefcase FAQ details the [state of support for third party packages](https://briefcase.readthedocs.io/en/stable/background/faq.html#can-i-use-third-party-python-packages-in-my-app)

I know nothing about llama-cpp-python, but based on the name and PyPI description, it seems highly likely this is a package that contains a compiled binary component. In that case, someone will need to develop a build recipe for iOS and Android - see the [Android](https://briefcase.readthedocs.io/en/stable/reference/platforms/android/gradle.html#android-third-party-packages) and [iOS](https://briefcase.readthedocs.io/en/stable/reference/platforms/iOS/xcode.html#ios-third-party-packages) pages linked in the FAQ entry.

Closing on the basis that this isn't a Briefcase issue.
