### ISSUE TITLE
Add documentation describing manual signing requirement for Android packages

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#1703]
### What is the problem or limitation you are having?

It is possible to use `briefcase package android` to produce an APK or AAB file for distribution; however, this file is not usable as is - it must be signed. While Briefcase has documentation for how to sign your application bundle for Android, this documentation isn't linked from the Android/Gradle reference page. 

### Describe the solution you'd like

The [Platform Quirks](https://briefcase.readthedocs.io/en/stable/reference/platforms/android/gradle.html#platform-quirks) section should mention the manual code signing requirement, linking to the [Android publication HOWTO](https://briefcase.readthedocs.io/en/stable/how-to/publishing/android.html#sign-the-android-app-bundle). 

### Describe alternatives you've considered

-

### Additional context

There's two use cases to consider here:
1. Publication to the Play Store 
2. Ad-hoc distribution via APK

The documentation that is added should be clear that it doesn't matter *how* you distribute your app - you need to sign it.

**Comment by ashleyplusplus** [comment]
at pycon2024 working on this!

**Comment by freakboy3742** [comment]
Fixed in #1813
