### ISSUE TITLE
add instructions for codesigning

### ISSUE THREAD

**Issue by glyph** [beeware/briefcase#174]
Having just bumped into [this](https://mail.python.org/pipermail/pythonmac-sig/2018-October/024335.html) I now have no future-looking way to distribute a Python-based mac app to my users.  I was thinking of trying out briefcase to see what it does, but it doesn't seem to include any information about codesigning, so (as far as I can tell?) I can't distribute its output.

Perhaps this is just a documentation issue, though?

**Comment by freakboy3742** [comment]
You're correct - briefcase doesn't currently do anything with code signing. Its on the list of things that I want to look at, but I haven't had time to do.

**Comment by glyph** [comment]
@freakboy3742 is already aware of this, but if others are possibly interested in this, I wrote up a basic set of instructions for modern codesigning practices for Python at https://glyph.twistedmatrix.com/2019/10/catalina-notarize-python.html

Please turn this into a for-real feature of Briefcase, or something adjacent, so I can delete those shell scripts...

**Comment by freakboy3742** [comment]
FYI: Briefcase 0.3 now does code *signing*, but not *notarization*. Making the appropriate command line invocations shouldn't be too difficult, but getting a good UX experience around the email notification process will require some design work.

**Comment by freakboy3742** [comment]
I'm going to close this ticket in favour of a more specific series of tickets that cover code signing on different platforms, and notarization on macOS specifically (#365).
