### ISSUE TITLE
Creating a new project using quoted inputs results in an invalid pyproject.toml

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1746]
### Describe the bug

Several of the user inputs for the `briefcase new` command are inserted verbatim in to the `pyproject.toml`. This TOML document uses double quotes to enclose these strings; therefore, if the user inputs contain double quotes, the TOML will be invalid.

While entering text with double quotes in to the prompts wouldn't normally be expected, at least for some of the fields, such as name (perhaps for a quoted nickname) or the description, this character should be supported.

### Steps to reproduce

1. Run `briefcase new`
2. For the author, enter `Harald "Bluetooth" Gormsson`
3. Run `briefcase dev` in the project

### Expected behavior

`pyproject.toml` is valid.

A similar tactic to https://github.com/beeware/briefcase-template/pull/66 seems reasonable.

### Environment

- Operating System: pop os 22.04
- Python version: 3.10.14
- Software versions:
  - Briefcase: `0.3.18.dev206+g38fbb22b.d20240422`

### Logs

```console
❯ briefcase dev

Briefcase configuration error: Invalid pyproject.toml: Expected newline or end of document after a statement (at line 8, column 19)
```

**Comment by mfreydavis** [comment]
Working on this at PyconUS 2024 sprints.

**Comment by mfreydavis** [comment]
The supporting template pull request is [https://github.com/beeware/briefcase-template/pull/125](https://github.com/beeware/briefcase-template/pull/125)

**Comment by mhsmith** [comment]
Can we close this issue, or are some more changes required?

**Comment by freakboy3742** [comment]
@mhsmith This also needs #1811, which is currently waiting for CI to complete.
