### ISSUE TITLE
Failed to build ios with Sonoma on M1 and Python 3.9.6

### ISSUE THREAD

**Issue by spyke555** [beeware/briefcase#1767]
### Describe the bug

Setting up a Mac Mini development environment and I've been able to get the macos and andoird builds working using a new helloworld app, however ios build are failing.

Looks like the build is failing at the code signing step. I've followed suggestions provided here without success:

[Code Sign Error in macOS Monterey, Xcode - resource fork, Finder information, or similar detritus not allowed](https://stackoverflow.com/questions/39652867/code-sign-error-in-macos-monterey-xcode-resource-fork-finder-information-or)

I did also try building in xcode which seemed to work but helloworld app would not run in simulator.

I have seen others mention issues with Sonoma but they were using Python 3.12, should I consider upgradeing to that? Any other suggestions / guidance would be appreciated.

### Steps to reproduce

On an M1 Mac Mini:

1) Update OS to Sonoma 14.4.1
2) Update Xcode to 15.3
3) Follow MacOS tutorials 0 and 1 to confirm development environment setup
4) Create IOS app with: briefcase create ios
5) Build IOS app with: briefcase build ios

### Expected behavior

Per tutorial 5, would expect build to complete. Would expect some form of error message indicating what needs to be corrected to move forward.

### Screenshots

![Screenshot 2024-05-02 at 6 15 09 AM](https://github.com/beeware/briefcase/assets/4167761/11eb6036-171a-4d89-b622-91f371b317fa)

### Environment

- Operating System: MacOS Sonoma 14.4.1, Xcode 15.3
- Python version: 3.9.6
- Software versions:
  - Briefcase: 0.3.17

### Logs

[briefcase.2024_05_02-06_06_19.build.log](https://github.com/beeware/briefcase/files/15186720/briefcase.2024_05_02-06_06_19.build.log)

**Comment by rmartin16** [comment]
FWIW, I cannot reproduce this after upgrading to 14.4.1 and Xcode 15.3. Notably, though, I'm running Sonoma in a VM on Intel hardware.

Adding error text for seo.
```
           [helloworld] Building Xcode project...                                                                                                                       xcode.py:393
                                                                                                                                                                   subprocess.py:711
           >>> Running Command:                                                                                                                                    subprocess.py:711
           >>>     xcodebuild build -project '/Users/sandy/Documents/Programming/BeeWare/helloworld/build/helloworld/ios/xcode/Hello World.xcodeproj' -destination subprocess.py:711
           'platform="iOS Simulator"' -configuration Debug -arch arm64 -sdk iphonesimulator -quiet                                                                                  
           >>> Working Directory:                                                                                                                                  subprocess.py:711
           >>>     /Users/sandy/Documents/Programming/BeeWare/helloworld                                                                                           subprocess.py:711
[06:06:19] /Users/sandy/Documents/Programming/BeeWare/helloworld/build/helloworld/ios/xcode/build/Debug-iphonesimulator/Hello World.app: resource fork, Finder     subprocess.py:681
           information, or similar detritus not allowed                                                                                                                             
           Command CodeSign failed with a nonzero exit code                                                                                                        subprocess.py:681
           note: Run script build phase 'Purge Python Binary Modules for Non-Target Platforms' will be run during every build because the option to run the script subprocess.py:681
           phase "Based on dependency analysis" is unchecked. (in target 'Hello World' from project 'Hello World')                                                                  
           note: Run script build phase 'Sign Python Binary Modules' will be run during every build because the option to run the script phase "Based on           subprocess.py:681
           dependency analysis" is unchecked. (in target 'Hello World' from project 'Hello World')                                                                                  
           ** BUILD FAILED **                                                                                                                                      subprocess.py:681
                                                                                                                                                                   subprocess.py:681
           >>> Return code: 65                                                                                                                                     subprocess.py:711
           Building...                                                                                                                                                  xcode.py:418
                                                                                                                                                                      __main__.py:44
           Unable to build app helloworld.                                                                                                                            __main__.py:45
```

**Comment by spyke555** [comment]
Thanks martin16,

This machine is used for development only, so will try a full wipe and reinstall and report back if that helped. At least it's possible with this OS version. Appreciate the feedback.

**Comment by freakboy3742** [comment]
Sorry to hear you're having problems; unfortunately, I'm in the same boat as rmartin16 - I can't reproduce what you're seeing.

A couple of avenues for exploration:
* Try running `briefcase open iOS`; this will open Xcode on your project, and allow you to use Xcode directly to run the project (look for the play button in the top bar, and the list of devices; select an iOS simulator). That might give more detail on how/why the codesign is failing. It might even be a case of not accepting a license agreement somewhere - there's a couple of things that get done the *very* first time you run Xcode, and it's possible you're missing one of those. It might also help to clean the project before a build (Product > Clean build folder from the menu)
* It's possible one of the downloads was corrupted - either the project template, or the binary support package. If you delete `~/Library/Caches/org.beeware.briefcase/support`  and `~/.cookiecutters/briefcase-iOS-Xcode-template`, then re-generate the project (delete the build folder, then re-run `briefcase run iOS), it will re-download those artefacts. Keep an eye out for any messages about download issues.
* It looks like you're using the Python that ships with Xcode; I haven't heard any reports of this being a problem, but it's not *impossible*. Try installing an official Python.org release, recreate your venv, re-install briefcase, then re-generate the project.

**Comment by spyke555** [comment]
Thank you for the feedback guys! 

I've gone nuclear and erased the Mac mini and did an OS re-install to start fresh. Installed Xcode only and then briefcase. From there did a new > dev which worked. Then did create iOS > build iOS > run iOS and after the command line tools downloaded at the build step Simulator came up and started the hello world app.

So it was definitely an issue with my config / downloads but not sure which.
