### ISSUE TITLE
Inconsistent behaviour between Android emulator on different platforms

### ISSUE THREAD

**Issue by JaxkDev** [beeware/briefcase#1779]
### Describe the bug

So on my Macbook Air M1 I made some android specific functions to take videos
(this works in both environments, and uses `MediaStore.ACTION_VIDEO_CAPTURE`)

However when I made the choosing pictures and videos from gallery it worked perfectly on my mac emulators, using `MediaStore.ACTION_PICK_IMAGES`.

When then testing it on windows, It comes up saying `ACTION_PICK_IMAGES` doesn't exist...

### Steps to reproduce

Code used to 'pick an image' from the phones gallery:

```python
from android.content import Intent # type: ignore
from android.provider import MediaStore # type: ignore

def file_chosen(code, data):
    print("tmp")

intent = Intent(MediaStore.ACTION_PICK_IMAGES)
intent.setTypeAndNormalize("image/*") #Takes a MIME type to filter the users choices
self.app._impl.start_activity(intent, on_complete=file_chosen)
```

### Expected behavior

The choose a picture/video pop up to show, as shown below.

### Screenshots

Expected Result (As on Mac M1): 
<img width="399" alt="Screenshot 2024-05-06 at 21 12 31" src="https://github.com/beeware/briefcase/assets/25908768/b2e681c6-8d37-4b2f-998e-f953e3a456cf">

Actual Result (As on Win11 machine):
<img width="357" alt="Screenshot 2024-05-06 at 21 13 30" src="https://github.com/beeware/briefcase/assets/25908768/cddbbcf5-b9d1-48ad-934e-360024728925">

(Notification showing it 'would' crash)
```python
if(not hasattr(MediaStore, 'ACTION_PICK_IMAGES')):
    self.app.main_window.error_dialog("Unsupported Device", "Unfortunately this device does not allow access to gallery.\nTo test this functionality use the default emulator that comes as standard.")
```

### Environment

Working Version:
- Operating System: Macbook Air M1 2020
- Python version: 3.8.18
- Software versions:
  - Briefcase: 0.3.17 & 0.3.18
  - Toga: 0.4.2 & 0.4.3

Not Working Version:
- Operating System: Windows11 x64
- Python Version: 3.8.10
- Software:
  - Briefcase: 0.3.17 & 0.3.18
  - Toga: 0.4.2 & 0.4.3

### Logs

Working Macbook Air log: 
[briefcase.2024_05_06-21_20_58.run.log](https://github.com/beeware/briefcase/files/15226068/briefcase.2024_05_06-21_20_58.run.log)

Not Working Windows log:
[briefcase.2024_05_06-21_21_39.run.log](https://github.com/beeware/briefcase/files/15226080/briefcase.2024_05_06-21_21_39.run.log)

### Additional context

Attempted updating android sdk as suggested in discord, no updates available.

**Comment by mhsmith** [comment]
Are you absolutely certain? The top screenshot has rounded corners and no navigation buttons at the bottom, while the bottom screenshot has square corners and navigation buttons, which suggests it's older. Check the Android version number in "Settings > About phone".

**Comment by JaxkDev** [comment]
I shall check now, I know the top is def 34 confirmed in android studio, havent got android studio installed on windows so went off name which said 34

May take a few to check apologies.

**Comment by JaxkDev** [comment]
Interesting while i was setting up again,

It seems this might all have been because of a stupid typo in the android sdk.

(Running briefcase run android with absolutely nothing on system)

Obviously you have to accept a load of tos and it installs the sdk emulator etc.
And the default device it lists:

```
Select device:

  1) @INFO    | Storing crashdata in: C:\Users\COMPUT~1\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.2.13.db, detection is enabled for process: 14724 (emulator)
  2) @Pixel_3a_API_34_extension_level_7_x86_64 (emulator)
  3) Create a new Android emulator

> 2

In future, you can specify this device by running:

    $ briefcase run android -d "@Pixel_3a_API_34_extension_level_7_x86_64"

```

However it then goes to download I assume the API 30 based off this next line:

```
[android_sdk] Downloading the 'system-images;android-30;google_apis_playstore;x86_64' Android system image...
```

So i do have a feeling it is indeed the wrong API

**Comment by JaxkDev** [comment]
<img width="346" alt="Screenshot 2024-05-07 at 16 10 17" src="https://github.com/beeware/briefcase/assets/25908768/5adafd33-41e2-4915-80f0-a2c4cb6319fd">

@mhsmith

**Comment by JaxkDev** [comment]
<img width="374" alt="Screenshot 2024-05-07 at 16 13 46" src="https://github.com/beeware/briefcase/assets/25908768/ce4385cc-efd3-494c-b917-b3c4ddbbd392">
Yup, apologies everyone.

Issue was just a stupid type from Android...
