### ISSUE TITLE
Clarify format of `requires` and `test_requires` settings

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#1786]
### What is the problem or limitation you are having?

The documentation describes the existence of the `requires` and `test requires` settings, but doesn't indicate the format these settings should take.

### Describe the solution you'd like

The documentation for [`requires`](https://briefcase.readthedocs.io/en/latest/reference/configuration.html#requires) and [`test_requires`](https://briefcase.readthedocs.io/en/latest/reference/configuration.html#test_requires) should indicate that any PEP 508 version specifier is legal, and provide some explicit examples:

* Bare pacakge name
* Package name with version specifier
* Git repository
* Local directory
* Local wheel file.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by spa51273** [comment]
pycon24, takeing a look at this. Thanks!
