### ISSUE TITLE
Add console app builds/testing to CI

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#1866]
### What is the problem or limitation you are having?

We aren't building and testing Console apps in CI like we do Toga, PySide, and Pygame. Should we be?

### Describe the solution you'd like

Console apps are exercised in CI like other formats/toolkits.

### Describe alternatives you've considered

status quo

**Comment by freakboy3742** [comment]
Should we? Absolutely. The test doesn't need to be fancy - we don't need to test any text-mode GUI frameworks, for example - but given we have a different stub binary, and other non-trivial execution paths, we should definitely be testing console startup.
