### ISSUE TITLE
fatal error: 'Python.h' file not found

### ISSUE THREAD

**Issue by TheCraftsmen** [beeware/briefcase#188]
hi! i have next problem when i test the helloworld example. I use macOS and python 3.6

(venv) Nicolass-MacBook-Air:test blascastro$ python setup.py ios -s
running ios

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-ios==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/36/f1/a5e2f2390b3129768e2399d6c8a2e5ef3ffb2bf82f4e5e33b6bf7842dc7d/toga_iOS-0.3.0.dev11-py3-none-any.whl
Collecting toga-core==0.3.0.dev11 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting rubicon-objc>=0.3.0 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/ce/55/b7fbfd72cbd3d18322d94305179c6c1805fe4b5e10619d6954adf7f1d6a3/rubicon_objc-0.3.0-py2.py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: travertino, toga-core, rubicon-objc, toga-ios
Successfully installed rubicon-objc-0.3.0 toga-core-0.3.0.dev11 toga-ios-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /Users/blascastro/Documents/python-test/test
Building wheels for collected packages: test
  Running setup.py bdist_wheel for test ... done
  Stored in directory: /private/var/folders/sf/g6njpn2d2bv5q4ycsfpmgvm80000gp/T/pip-ephem-wheel-cache-ftu92wm6/wheels/e3/21/5f/22e3f5d152455100da358de8badd0ff6d222e42c5cc55e40c0
Successfully built test
Installing collected packages: test
Successfully installed test-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Building for iOS 11.0...

Available devices:
  [1] iPhone 5s
  [2] iPhone 6
  [3] iPhone 6 Plus
  [4] iPhone 6s
  [5] iPhone 6s Plus
  [6] iPhone 7
  [7] iPhone 7 Plus
  [8] iPhone SE
  [9] iPhone 8
  [10] iPhone 8 Plus
  [11] iPhone X
  [12] iPad Air
  [13] iPad Air 2
  [14] iPad (5th generation)
  [15] iPad Pro (9.7-inch)
  [16] iPad Pro (12.9-inch)
  [17] iPad Pro (12.9-inch) (2nd generation)
  [18] iPad Pro (10.5-inch)
Which device do you want to target: 7
 * Building XCode project for iPhone 7 Plus iOS 11.0...
NOTE: Xcode project 'test' was written by a newer Xcode version (50) -- temporarily downgrading it (without modifying project file)

=== BUILD TARGET test OF PROJECT test WITH CONFIGURATION Debug ===
/Users/blascastro/Documents/python-test/test/iOS/test/main.m:8:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.
** BUILD FAILED **

Starting app on iPhone 7 Plus iOS 11.0
 * Starting simulator...
instruments[56641]: Waiting for device to boot...
 * Uninstalling old app version...

**Comment by nricklin** [comment]
I have the same issue.  Any update?

**Comment by nricklin** [comment]
I had some luck removing spaces from the "Hello World" name in both setup.py (the ```formal_name```) and in app.py (```return Helloworld('HelloWorld', 'com.example.helloworld')```)

**Comment by freakboy3742** [comment]
It sounds like this may be related to spaces in app/identifier names; this is now tested as part of the in-development 0.3 version of briefcase.
