### ISSUE TITLE
Does the mechanism of briefcase not yet support displaying toga GUI for services, and only supports displaying toga GUI for activities?  strange error “Failed to create image decoder with message 'unimplemented'”

### ISSUE THREAD

**Issue by andy4lee** [beeware/briefcase#1956]
### Describe the bug

I need a permanent floating window, so I have to use Android services to implement it instead of Android activities (toga can display normally，but not permanent)

Android services call Python through chaquo (Android activity is normal), strange error “skia    : --- Failed to create image decoder with message 'unimplemented'” , but i didn't use skia

Does the mechanism of briefcase not yet support displaying toga GUI for services, and only supports displaying toga GUI for activities?

java code:（only show the simple toga GUI，activity calls is normal, service calls is abnormal） All code in Additional context
```
private void updateFloatingWindowContent(TextView textView) {
        // Make sure Python is initialized
        if (!Python.isStarted()) {
            AndroidPlatform platform = new AndroidPlatform(this);
            platform.redirectStdioToLogcat();
            Python.start(platform);
        }
        Python py = Python.getInstance();
        Log.d(TAG, "Running Python code to update floating window content");

        // Call Python function to get content
        py.getModule("runpy").callAttr(
                "run_module",
                "uiapp.__main__",
                new Kwarg("run_name", "__main__"),
                new Kwarg("alter_sys", true)
        );
        // Update the view (run on UI thread)
        //textView.post(() -> textView.setText(content));
    }
```

toga code:（simple window）

```
import toga
from toga import App, Box, Label, Button
from toga.style import Pack
from toga.style.pack import COLUMN, ROW, CENTER, LEFT, RIGHT

class TogaUI(toga.App):
    def startup(self):
        left_box = Box(style=Pack(direction=COLUMN, padding=0, alignment=CENTER))

        poker_labels = ['D', 'X', '2', 'A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3']
        poker_box = Box(style=Pack(direction=ROW, padding=0))
        for poker in poker_labels:
            label = Label(poker, style=Pack(padding=0, width=15, text_align=CENTER, background_color='transparent'))
            poker_box.add(label)
        left_box.add(poker_box)

        count_box = Box(style=Pack(direction=ROW, padding=0))
        for _ in poker_labels:
            label = Label('4', style=Pack(padding=0, width=15, text_align=CENTER, background_color='transparent'))
            count_box.add(label)
        left_box.add(count_box)

        right_box = Box(style=Pack(direction=COLUMN, padding=0, alignment=RIGHT))

        button2 = Button('start', on_press=self.on_start_press, style=Pack(padding=0))
        button2.style.background_color = 'transparent'
        button3 = Button('stop', on_press=self.on_stop_press, style=Pack(padding=0))
        button3.style.background_color = 'transparent'
        right_box.add(button2)
        right_box.add(button3)

        main_box = Box(style=Pack(direction=ROW))
        main_box.add(left_box)
        main_box.add(right_box)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.size = (50, 50)

        self.main_window.show()

    def on_start_press(self, widget):
        print('Starting auto mode')

    def on_stop_press(self, widget):
        print('Stopping mode')

if __name__ == '__main__':
    app = TogaUI(formal_name='game helper', app_id='com.example.MyApp')
    app.main_loop()
```

### Steps to reproduce

1. Go to ' app '
2. Click on 'initButton'  （The main logic is MainActivity -> FloatingWindowService.onCreate() ）
3. Scroll down to ''
[38;5;75mD/MainActivity: onActivityResult() start[0m
[38;5;75mD/MainActivity: onActivityResult() complete[0m
[38;5;75mD/FloatingWindowService: FloatingWindowService onCreate()[0m
[38;5;166mW/native.stderr: Could not find platform independent libraries <prefix>[0m
[38;5;166mW/native.stderr: Could not find platform dependent libraries <exec_prefix>[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Ljava/util/LinkedHashMap$LinkedHashIterator;->hasNext()Z (light greylist, JNI)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/content/Context;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (light greylist, JNI)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/content/ContextWrapper;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (light greylist, JNI)[0m
[38;5;166mW/asset   : seek out of range: want -20, end=22[0m
[38;5;75mD/FloatingWindowService: Running Python code to update floating window content[0m
[38;5;40mI/python.stdout: init python GUI[0m
[38;5;40mI/python.stdout: WARNING: Can't find app icon; falling back to default icon[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Ljava/io/FileDescriptor;->setInt$(I)V (light greylist, JNI)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/os/Handler;-><init>(Landroid/os/Looper;Landroid/os/Handler$Callback;Z)V (light greylist, JNI)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/os/Handler;-><init>(Z)V (light greylist, JNI)[0m
[38;5;40mI/python.stdout: Python app launched & stored in Android Activity class[0m
[38;5;40mI/m.example.uiap: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)[0m
[38;5;75mD/skia    : --- Failed to create image decoder with message 'unimplemented'[0m
[38;5;196mE/FloatingWindowService: mMediaProjection created: android.media.projection.MediaProjection@29ae0b[0m
[38;5;75mD/EGL_adreno: eglMakeCurrent: 0x7fff7293f100: ver 3 1 (tinfo 0x7fff729d1100)[0m
[38;5;75mD/MainActivity: onStop() start[0m
[38;5;40mI/python.stdout: Toga app: onStop[0m
[38;5;75mD/MainActivity: onStop() complete[0m
[38;5;75mD/MainActivity: onDestroy() start[0m
[38;5;40mI/python.stdout: Toga app: onDestroy[0m
[38;5;75mD/MainActivity: onDestroy() complete[0m

### Expected behavior

show the simple toga GUI

![image](https://github.com/user-attachments/assets/4af010ea-bf19-4b75-bd47-026371d93958)

### Screenshots

![image](https://github.com/user-attachments/assets/6f82dc3b-be78-485e-90d0-6bfe9c6d3647)

### Environment

- Operating System: android 9
- Python version: 3.11.2
- Software versions:
  - Briefcase: 0.3.18
  - Toga: 0.4.5
  - ...

### Logs

D:\softwareData\PycharmProjects\beewareapp\uiapp>briefcase run android -d emulator-5554

[uiapp] Starting app on mate70 (emulator-5554) (device ID emulator-5554)

[uiapp] Installing app...
Stopping old versions of the app... done
Installing new app version... done
Launching app... done

[uiapp] Following device log output (type CTRL-C to stop log)...
===========================================================================
--------- beginning of main
[38;5;40mI/Zygote  : seccomp disabled by setenforce 0[0m
[38;5;40mI/m.example.uiap: Late-enabling -Xcheck:jni[0m
[38;5;75mD/nativebridge: call UnloadNativeBridge! state=1[0m
[38;5;166mW/m.example.uiap: Accessing hidden field Landroid/os/Trace;->TRACE_TAG_APP:J (light greylist, reflection)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (light greylist, reflection)[0m
[38;5;75mD/AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found[0m
[38;5;75mD/MainActivity: onCreate() start[0m
[38;5;166mW/m.example.uiap: Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)[0m
[38;5;166mW/m.example.uiap: Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)[0m
[38;5;166mW/m.example.uiap: Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)[0m
[38;5;166mW/m.example.uiap: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)[0m
[38;5;75mD/MainActivity: onCreate() complete[0m
[38;5;75mD/MainActivity: onStart() start[0m
[38;5;75mD/MainActivity: onStart() complete[0m
[38;5;75mD/MainActivity: onResume() start[0m
[38;5;75mD/MainActivity: onResume() complete[0m
[38;5;75mD/OpenGLRenderer: Skia GL Pipeline[0m
[38;5;40mI/HostConnection: HostConnection::HostConnection: pid=31535, tid=31574, this=0x7fff6a7c7980[0m
[38;5;40mI/        : fastpipe: Connect success[0m
[38;5;75mD/HostConnection: HostRPC::connect sucess: app=com.example.uiapp, pid=31535, tid=31574, this=0x7fff5a5c8f00[0m
[38;5;75mD/HostConnection: queryAndSetGLESMaxVersion select gles-version: 3.1 hostGLVersion:46 process:com.example.uiapp[0m
[38;5;40mI/        : fastpipe: Connect success[0m
[38;5;75mD/HostConnection: recv ProcessPuidReply name=com.example.uiapp puid=56 g_u64CapsFlag=1d[0m
[38;5;40mI/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0[0m
[38;5;40mI/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0[0m
[38;5;40mI/OpenGLRenderer: Initialized EGL, version 1.4[0m
[38;5;75mD/OpenGLRenderer: Swap behavior 1[0m
[38;5;40mI/EGL_adreno: eglCreateContext request GLES major-version=2[0m
[38;5;75mD/EGL_adreno: eglCreateContext: 0x7fff7293f100: maj 3 min 1 rcv 4[0m
[38;5;75mD/EGL_adreno: eglMakeCurrent: 0x7fff7293f100: ver 3 1 (tinfo 0x7fff729d1100)[0m
[38;5;75mD/HostConnection: ExtendedRCEncoderContext GL_VERSION return OpenGL ES 3.1[0m
[38;5;196mE/eglCodecCommon: glUtilsParamSize: unknow param 0x00008c29[0m
[38;5;166mW/GLESv2_enc: no support GL_NUM_PROGRAM_BINARY_FORMATS[0m
[38;5;75mD/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.[0m
[38;5;75mD/vndksupport: Loading /vendor/lib64/hw/gralloc.default.so from current namespace instead of sphal namespace.[0m
[38;5;196mE/EGL_adreno: tid 31574: eglSurfaceAttrib(1346): error 0x3009 (EGL_BAD_MATCH)[0m
[38;5;166mW/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fff729f7280, error=EGL_BAD_MATCH[0m
[38;5;75mD/EGL_adreno: eglMakeCurrent: 0x7fff7293f100: ver 3 1 (tinfo 0x7fff729d1100)[0m
[38;5;40mI/RenderThread: type=1400 audit(0.0:3592): avc: denied { ioctl } for path="/dev/fastpipe" dev="tmpfs" ino=7187 ioctlcmd=6867 scontext=u:r:untrusted_app:s0:c127,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1[0m
[38;5;40mI/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (light greylist, reflection)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (light greylist, reflection)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/os/Trace;->traceCounter(JLjava/lang/String;I)V (light greylist, reflection)[0m
[38;5;75mD/ProfileInstaller: Installing profile for com.example.uiapp[0m
[38;5;75mD/MainActivity: onPause() start[0m
[38;5;75mD/MainActivity: onPause() complete[0m
[38;5;75mD/MainActivity: onActivityResult() start[0m
[38;5;75mD/MainActivity: onActivityResult() complete[0m
[38;5;75mD/FloatingWindowService: FloatingWindowService onCreate()[0m
[38;5;166mW/native.stderr: Could not find platform independent libraries <prefix>[0m
[38;5;166mW/native.stderr: Could not find platform dependent libraries <exec_prefix>[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Ljava/util/LinkedHashMap$LinkedHashIterator;->hasNext()Z (light greylist, JNI)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/content/Context;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (light greylist, JNI)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/content/ContextWrapper;->getSharedPreferences(Ljava/io/File;I)Landroid/content/SharedPreferences; (light greylist, JNI)[0m
[38;5;166mW/asset   : seek out of range: want -20, end=22[0m
[38;5;75mD/FloatingWindowService: Running Python code to update floating window content[0m
[38;5;40mI/python.stdout: init python GUI[0m
[38;5;40mI/python.stdout: WARNING: Can't find app icon; falling back to default icon[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Ljava/io/FileDescriptor;->setInt$(I)V (light greylist, JNI)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/os/Handler;-><init>(Landroid/os/Looper;Landroid/os/Handler$Callback;Z)V (light greylist, JNI)[0m
[38;5;166mW/m.example.uiap: Accessing hidden method Landroid/os/Handler;-><init>(Z)V (light greylist, JNI)[0m
[38;5;40mI/python.stdout: Python app launched & stored in Android Activity class[0m
[38;5;40mI/m.example.uiap: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)[0m
[38;5;75mD/skia    : --- Failed to create image decoder with message 'unimplemented'[0m
[38;5;196mE/FloatingWindowService: mMediaProjection created: android.media.projection.MediaProjection@29ae0b[0m
[38;5;75mD/EGL_adreno: eglMakeCurrent: 0x7fff7293f100: ver 3 1 (tinfo 0x7fff729d1100)[0m
[38;5;75mD/MainActivity: onStop() start[0m
[38;5;40mI/python.stdout: Toga app: onStop[0m
[38;5;75mD/MainActivity: onStop() complete[0m
[38;5;75mD/MainActivity: onDestroy() start[0m
[38;5;40mI/python.stdout: Toga app: onDestroy[0m
[38;5;75mD/MainActivity: onDestroy() complete[0m

### Additional context

FloatingWindowService.java :
    package org.beeware.android;

import static android.content.ContentValues.TAG;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.res.Configuration;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.PixelFormat;
import android.hardware.display.DisplayManager;
import android.hardware.display.VirtualDisplay;
import android.media.Image;
import android.media.ImageReader;
import android.media.projection.MediaProjection;
import android.media.projection.MediaProjectionManager;
import android.os.Build;
import android.os.Handler;
import android.os.IBinder;
import android.util.DisplayMetrics;
import android.util.Log;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.view.MenuItem;
import android.view.Menu;

import android.view.WindowManager;
import android.widget.Button;
import android.widget.TextView;

import androidx.annotation.Nullable;

import java.util.Arrays;
import java.util.Objects;

import com.chaquo.python.Kwarg;
import com.chaquo.python.PyException;
import com.chaquo.python.Python;
import com.chaquo.python.PyObject;
import com.chaquo.python.android.AndroidPlatform;
import com.example.uiapp.R;

public class FloatingWindowService extends Service {
	
	public static final String TAG = "FloatingWindowService";
    private WindowManager windowManager;
    private ViewGroup floatView;
    private int LAYOUT_TYPE;
    private WindowManager.LayoutParams floatWindowLayoutParam;
	private static PyObject pythonApp;
		
	@SuppressWarnings("unused")
    public static void setPythonApp(IPythonApp app) {
        pythonApp = PyObject.fromJava(app);
    }

    public void onCreate() {
        super.onCreate();
        Log.d(TAG, "FloatingWindowService onCreate()");
        updateFloatingWindowContent(null);
		//createFloatingWindow();
		//startTogaActivity();
		userCode("onCreate");
    }
	private void updateFloatingWindowContent(TextView textView) {
        // Make sure Python is initialized
        if (!Python.isStarted()) {
            AndroidPlatform platform = new AndroidPlatform(this);
            platform.redirectStdioToLogcat();
            Python.start(platform);
        }
        Python py = Python.getInstance();
        Log.d(TAG, "Running Python code to update floating window content");

        // Call Python function to get content
        py.getModule("runpy").callAttr(
                "run_module",
                "uiapp.__main__",
                new Kwarg("run_name", "__main__"),
                new Kwarg("alter_sys", true)
        );
        // Update the view (run on UI thread)
        //textView.post(() -> textView.setText(content));
    }
	
	private void startTogaActivity() {
		Intent intent = new Intent(this, TogaActivity.class);
		intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
		startActivity(intent);
    }
	private int mScreenWidth;
    private int mScreenHeight;

    private void createFloatingWindow() {
		LayoutInflater inflater = (LayoutInflater) getBaseContext().getSystemService(LAYOUT_INFLATER_SERVICE);
        floatView = (ViewGroup) inflater.inflate(R.layout.activity_main, null);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            LAYOUT_TYPE = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
        } else {
            LAYOUT_TYPE = WindowManager.LayoutParams.TYPE_TOAST;
        }
		
        WindowManager windowManager = (WindowManager) getSystemService(WINDOW_SERVICE);
		
		DisplayMetrics metrics = new DisplayMetrics();
        windowManager.getDefaultDisplay().getMetrics(metrics);
        mScreenWidth = metrics.widthPixels;
        mScreenHeight = 200;

        // Determine the correct window type
        WindowManager.LayoutParams layoutParams;
        if (android.os.Build.VERSION.SDK_INT >= 26) {
            // For Android 8.0 and above
            layoutParams = new WindowManager.LayoutParams(
                    mScreenWidth,
                    mScreenHeight,
                    LAYOUT_TYPE,
                    WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL,
                    android.graphics.PixelFormat.TRANSLUCENT
            );
        } else {
            // For below Android 8.0
            layoutParams = new WindowManager.LayoutParams(
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.TYPE_PHONE,
                    WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL,
                    android.graphics.PixelFormat.TRANSLUCENT
            );
        }

		layoutParams.gravity = Gravity.TOP | Gravity.CENTER;
        layoutParams.x = 0;
        layoutParams.y = 0;

        // Create a placeholder view
        TextView textView = new TextView(this);
        textView.setText("Loading...");

        // Add the view to the window
        windowManager.addView(textView, layoutParams);
		Log.d(TAG, "Add the view to the window");
        // Initialize Python and request content
        updateFloatingWindowContent(textView);
    }

    

    MediaProjectionManager mediaProjectionManager;
    MediaProjection mMediaProjection;

    @Override
    public int onStartCommand(final Intent intent, int flags, int startId) {
        createNotificationChannel();
        int mResultCode = intent.getIntExtra("code", -1);
        Intent mResultData = intent.getParcelableExtra("data");
        mediaProjectionManager = (MediaProjectionManager)getSystemService(Context.MEDIA_PROJECTION_SERVICE);
        mMediaProjection = mediaProjectionManager.getMediaProjection(mResultCode, Objects.requireNonNull(mResultData));
        Log.e(TAG, "mMediaProjection created: " + mMediaProjection);
        return super.onStartCommand(intent, flags, startId);
    }
	
	private void createNotificationChannel() {
        Notification.Builder builder = new Notification.Builder(this.getApplicationContext()); 
        Intent nfIntent = new Intent(this, MainActivity.class); 
        builder.setContentIntent(PendingIntent.getActivity(this, 0, nfIntent, PendingIntent.FLAG_IMMUTABLE)) 
                .setLargeIcon(BitmapFactory.decodeResource(this.getResources(), R.mipmap.ic_launcher)) 
                .setSmallIcon(R.mipmap.ic_launcher) 
                .setContentText("is running......") 
                .setWhen(System.currentTimeMillis()); 
 
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            builder.setChannelId("notification_id");
        }

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationManager notificationManager = (NotificationManager)getSystemService(NOTIFICATION_SERVICE);
            NotificationChannel channel = new NotificationChannel("notification_id", "notification_name", NotificationManager.IMPORTANCE_LOW);
            notificationManager.createNotificationChannel(channel);
        }
        Notification notification = builder.build(); 
        notification.defaults = Notification.DEFAULT_SOUND; 
        startForeground(110, notification);
    }
	

    public void onConfigurationChanged(Configuration newConfig) {
        Log.d(TAG, "onConfigurationChanged() start");
        super.onConfigurationChanged(newConfig);
        userCode("onConfigurationChanged", newConfig);
        Log.d(TAG, "onConfigurationChanged() complete");
    }

    public boolean onOptionsItemSelected(MenuItem menuitem) {
        Log.d(TAG, "onOptionsItemSelected() start");
        PyObject pyResult = userCode("onOptionsItemSelected", menuitem);
        boolean result = (pyResult == null) ? false : pyResult.toBoolean();
        Log.d(TAG, "onOptionsItemSelected() complete");
        return result;
    }

    public boolean onPrepareOptionsMenu(Menu menu) {
        Log.d(TAG, "onPrepareOptionsMenu() start");
        PyObject pyResult = userCode("onPrepareOptionsMenu", menu);
        boolean result = (pyResult == null) ? false : pyResult.toBoolean();
        Log.d(TAG, "onPrepareOptionsMenu() complete");
        return result;
    }

    private PyObject userCode(String methodName, Object... args) {
        if (pythonApp == null) {
            // Could be a non-graphical app such as Python-support-testbed.
            return null;
        }
        try {
            if (pythonApp.containsKey(methodName)) {
                return pythonApp.callAttr(methodName, args);
            } else {
                // Handle the case where the method doesn't exist
                return null;
            }
        } catch (PyException e) {
            if (e.getMessage().startsWith("NotImplementedError")) {
                return null;
            }
            throw e;
        }
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}
MainActivity.java: 

package org.beeware.android;

import androidx.appcompat.app.AppCompatActivity;

import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.res.Configuration;
import android.content.Intent;
import android.content.SharedPreferences;

import android.media.projection.MediaProjectionManager;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.util.Log;
import android.view.View;
import android.view.WindowManager;
import android.view.Gravity;
import android.view.Menu;
import android.view.MenuItem;

import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.chaquo.python.Kwarg;
import com.chaquo.python.PyException;
import com.chaquo.python.PyObject;
import com.chaquo.python.Python;
import com.chaquo.python.android.AndroidPlatform;

import java.util.Objects;
import com.example.uiapp.R;

public class MainActivity extends AppCompatActivity {

    private static final String TAG = "MainActivity";
	public static MainActivity singletonThis;
	private static PyObject pythonApp;
	private WindowManager windowManager;
    //private View decorView;
    private boolean isViewAdded = false;
	private AlertDialog dialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
		Log.d(TAG, "onCreate() start");
        super.onCreate(savedInstanceState);
		singletonThis = this;
		setContentView(R.layout.activity_main);
		
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (!Settings.canDrawOverlays(this)) requestOverlayDisplayPermission();
			Button initButton = findViewById(R.id.myButton); 
			initButton.setOnClickListener(v -> initMediaProjectionManager());
        }
        userCode("onCreate");
        Log.d(TAG, "onCreate() complete");
    }
	
	private void requestOverlayDisplayPermission() {
        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setCancelable(true);
        builder.setTitle("1111");
        builder.setMessage("666666666");
        builder.setPositiveButton("--open setting--", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, Uri.parse("package:" + getPackageName()));
                startActivityForResult(intent, RESULT_OK);
            }
        });
        dialog = builder.create();
        dialog.show();
    }
	
	MediaProjectionManager mediaProjectionManager;
    public static final int REQUEST_MEDIA_PROJECTION = 18;

    private void initMediaProjectionManager() {
        if (mediaProjectionManager != null) return;
        mediaProjectionManager = (MediaProjectionManager)getSystemService(Context.MEDIA_PROJECTION_SERVICE);
        startActivityForResult(mediaProjectionManager.createScreenCaptureIntent(), REQUEST_MEDIA_PROJECTION);
    }
	
    private void createFloatingWindow() {
        
        WindowManager.LayoutParams layoutParams = new WindowManager.LayoutParams(
                WindowManager.LayoutParams.MATCH_PARENT,
                WindowManager.LayoutParams.MATCH_PARENT,
                WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL,
                android.graphics.PixelFormat.TRANSLUCENT
        );
        layoutParams.gravity = Gravity.TOP | Gravity.CENTER;
		
		if (!isViewAdded) {
			getWindow().setAttributes(layoutParams);
			isViewAdded = true;
			Log.d(TAG, "View added to window manager.");
		} else {
			Log.d(TAG, "View is already added to window manager.");
		}

        if (!Python.isStarted()) {
            AndroidPlatform platform = new AndroidPlatform(this);
            platform.redirectStdioToLogcat();
            Python.start(platform);
        }
		Python py = Python.getInstance();
        Log.d(TAG, "Running Python code to start Toga GUI");

        py.getModule("runpy").callAttr(
                "run_module",
                "uiapp.__main__",
                new Kwarg("run_name", "__main__"),
                new Kwarg("alter_sys", true)
        );
    }
	
	@SuppressWarnings("unused")
    public static void setPythonApp(IPythonApp app) {
        pythonApp = PyObject.fromJava(app);
    }
	
	protected void onStart() {
        Log.d(TAG, "onStart() start");
        super.onStart();
        userCode("onStart");
        Log.d(TAG, "onStart() complete");
    }

    protected void onResume() {
        Log.d(TAG, "onResume() start");
        super.onResume();
        userCode("onResume");
        Log.d(TAG, "onResume() complete");
    }

    protected void onPause() {
        Log.d(TAG, "onPause() start");
        super.onPause();
        userCode("onPause");
        Log.d(TAG, "onPause() complete");
    }

    protected void onStop() {
        Log.d(TAG, "onStop() start");
        super.onStop();
        userCode("onStop");
        Log.d(TAG, "onStop() complete");
    }
    protected void onDestroy() {
        Log.d(TAG, "onDestroy() start");
        super.onDestroy();
        userCode("onDestroy");
        Log.d(TAG, "onDestroy() complete");
    }
    protected void onRestart() {
        Log.d(TAG, "onRestart() start");
        super.onRestart();
        userCode("onRestart");
        Log.d(TAG, "onRestart() complete");
    }
    public void onTopResumedActivityChanged (boolean isTopResumedActivity){
        Log.d(TAG, "onTopResumedActivityChanged() start");
        super.onTopResumedActivityChanged(isTopResumedActivity);
        userCode("onTopResumedActivityChanged", isTopResumedActivity);
        Log.d(TAG, "onTopResumedActivityChanged() complete");
    }

    protected void onActivityResult(int requestCode, int resultCode, Intent data)
    {
        Log.d(TAG, "onActivityResult() start");
        super.onActivityResult(requestCode, resultCode, data);
		if (resultCode == RESULT_OK && data != null) {
            Intent intent = new Intent(MainActivity.this, FloatingWindowService.class);
            intent.putExtra("code", resultCode);
            intent.putExtra("data", data);
            startForegroundService(intent);
            finish();
        }else {
            Toast.makeText(this, "not working", Toast.LENGTH_SHORT).show();
        }
        userCode("onActivityResult", requestCode, resultCode, data);
        Log.d(TAG, "onActivityResult() complete");
    }

    public void onConfigurationChanged(Configuration newConfig) {
        Log.d(TAG, "onConfigurationChanged() start");
        super.onConfigurationChanged(newConfig);
        userCode("onConfigurationChanged", newConfig);
        Log.d(TAG, "onConfigurationChanged() complete");
    }

    public boolean onOptionsItemSelected(MenuItem menuitem) {
        Log.d(TAG, "onOptionsItemSelected() start");
        PyObject pyResult = userCode("onOptionsItemSelected", menuitem);
        boolean result = (pyResult == null) ? false : pyResult.toBoolean();
        Log.d(TAG, "onOptionsItemSelected() complete");
        return result;
    }

    public boolean onPrepareOptionsMenu(Menu menu) {
        Log.d(TAG, "onPrepareOptionsMenu() start");
        PyObject pyResult = userCode("onPrepareOptionsMenu", menu);
        boolean result = (pyResult == null) ? false : pyResult.toBoolean();
        Log.d(TAG, "onPrepareOptionsMenu() complete");
        return result;
    }

    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults)
    {
        Log.d(TAG, "onRequestPermissionsResult() start");
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        userCode("onRequestPermissionsResult", requestCode, permissions, grantResults);
        Log.d(TAG, "onRequestPermissionsResult() complete");
    }

    private PyObject userCode(String methodName, Object... args) {
        if (pythonApp == null) {
            // Could be a non-graphical app such as Python-support-testbed.
            return null;
        }
        try {
            if (pythonApp.containsKey(methodName)) {
                return pythonApp.callAttr(methodName, args);
            } else {
                // Handle the case where the method doesn't exist
                return null;
            }
        } catch (PyException e) {
            if (e.getMessage().startsWith("NotImplementedError")) {
                return null;
            }
            throw e;
        }
    }
}

**Comment by freakboy3742** [comment]
Closing on the basis that you've already posed this question on the Toga repository. If you want to continue the debugging process, please post follow ups to that discussion thread.
