### ISSUE TITLE
Проблема с октрытием файла через OpenFileDialog

### ISSUE THREAD

**Issue by SnayperTihCreator** [beeware/briefcase#1986]
### Describe the bug

При запуске программы и попытке запустить OpenFileDialog выдает ошибку что данный класс не реализован
![Снимок экрана 2024-09-06 181144](https://github.com/user-attachments/assets/c1fdca7a-a05d-4883-bbfd-924273cec880)

### Steps to reproduce

Я не знаю почему это так срабатывает

### Expected behavior

Хотелось бы чтобы он работал и можно использовать было все наследники Dialog

### Environment

-PyCharm
-Toga

**Comment by freakboy3742** [comment]
Closing on the basis that it's not clear what the report is describing.

If the "bug" is that "OpenFileDialog" doesn't work on Android - that's (a) not a problem with Briefcase, and (b) a documented limitation, which the error message is describing accurately - OpenFileDialog isn't implemented on Android.
