### ISSUE TITLE
so file can not work on the android

### ISSUE THREAD

**Issue by Jzhenli** [beeware/briefcase#1996]
### Describe the bug

Hi, I compile the toga code to so file with nuitka, but it canno work on the android.

Test toga code  app.py as follows

`import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW

class testtoga(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        name_label = toga.Label(
            "Your name: ",
            style=Pack(padding=(0, 5)),
        )
        self.name_input = toga.TextInput(style=Pack(flex=1))

        name_box = toga.Box(style=Pack(direction=ROW, padding=5))
        name_box.add(name_label)
        name_box.add(self.name_input)

        button = toga.Button(
            "Say Hello!",
            on_press=self.say_hello,
            style=Pack(padding=5),
        )

        main_box.add(name_box)
        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def say_hello(self, widget):
        self.main_window.info_dialog(
            f"Hello, {self.name_input.value}",
            "Hi there!",
        )

def main():
    return testtoga()
`

the output info is:
`E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.example.testtoga, PID: 4322
E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testtoga/org.beeware.android.MainActivity}: com.chaquo.python.PyException: ImportError: dlopen failed: cannot locate symbol "_Py_FalseStruct" referenced by "/data/data/com.example.testtoga/files/chaquopy/AssetFinder/app/testtoga/app.so"...
E/AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3751)
E/AndroidRuntime:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3919)
E/AndroidRuntime:   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime:   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime:   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
E/AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime:   at android.os.Looper.loopOnce(Looper.java:238)
E/AndroidRuntime:   at android.os.Looper.loop(Looper.java:357)
E/AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:8089)
E/AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
E/AndroidRuntime: Caused by: com.chaquo.python.PyException: ImportError: dlopen failed: cannot locate symbol "_Py_FalseStruct" referenced by "/data/data/com.example.testtoga/files/chaquopy/AssetFinder/app/testtoga/app.so"...
E/AndroidRuntime:   at <python>.java.android.importer.extension_create_module_override(importer.py:734)
E/AndroidRuntime:   at <python>.java.chaquopy.import_override(import.pxi:20)
E/AndroidRuntime:   at <python>.java.chaquopy.import_override(import.pxi:60)
E/AndroidRuntime:   at <python>.__main__.<module>(__main__.py:1)
E/AndroidRuntime:   at <python>.runpy._run_code(runpy.py:86)
E/AndroidRuntime:   at <python>.runpy._run_module_code(runpy.py:96)
E/AndroidRuntime:   at <python>.runpy.run_module(runpy.py:224)
E/AndroidRuntime:   at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
E/AndroidRuntime:   at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
E/AndroidRuntime:   at org.beeware.android.MainActivity.onCreate(MainActivity.java:85)
E/AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:8232)
E/AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:8212)
E/AndroidRuntime:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1331)
E/AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3724)
E/AndroidRuntime:   ... 12 more`

### Steps to reproduce

build the app.py to so file wih nutika:
python -m nuitka --module app.py

then run "briefcase package  -u" to install the apk on android device. 

### Expected behavior

should works ,but crash.

### Environment

python 3.10 
briefcase 0.3.19
toga 0.4.6

### Logs

```

```

**Comment by freakboy3742** [comment]
Nuitka is a framework for compiling Python code; unless Nuitka contains logic for compiling *for Android*, then any binary that has been produced won't work on Android. To the best of my knowledge, Nuitka doesn't have Android support.

**Comment by Jzhenli** [comment]
@freakboy3742  I also test with Cython, it can not work either.
Output log is :
`E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.example.testtoga, PID: 20395
E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testtoga/org.beeware.android.MainActivity}: com.chaquo.python.PyException: ImportError: dlopen failed: library "libandroid-support.so" not found: needed by /data/data/com.example.testtoga/files/chaquopy/AssetFinder/app/testtoga/app.so in namespace classloader-namespace
E/AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3751)
E/AndroidRuntime:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3919)
E/AndroidRuntime:   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime:   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime:   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
E/AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime:   at android.os.Looper.loopOnce(Looper.java:238)
E/AndroidRuntime:   at android.os.Looper.loop(Looper.java:357)
E/AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:8089)
E/AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
E/AndroidRuntime: Caused by: com.chaquo.python.PyException: ImportError: dlopen failed: library "libandroid-support.so" not found: needed by /data/data/com.example.testtoga/files/chaquopy/AssetFinder/app/testtoga/app.so in namespace classloader-namespace
E/AndroidRuntime:   at <python>.java.android.importer.extension_create_module_override(importer.py:734)
E/AndroidRuntime:   at <python>.java.chaquopy.import_override(import.pxi:20)
E/AndroidRuntime:   at <python>.java.chaquopy.import_override(import.pxi:60)
E/AndroidRuntime:   at <python>.__main__.<module>(__main__.py:1)
E/AndroidRuntime:   at <python>.runpy._run_code(runpy.py:86)
E/AndroidRuntime:   at <python>.runpy._run_module_code(runpy.py:96)
E/AndroidRuntime:   at <python>.runpy.run_module(runpy.py:224)
E/AndroidRuntime:   at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
E/AndroidRuntime:   at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
E/AndroidRuntime:   at org.beeware.android.MainActivity.onCreate(MainActivity.java:85)
E/AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:8232)
E/AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:8212)
E/AndroidRuntime:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1331)
E/AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3724)
E/AndroidRuntime:   ... 12 more`

build scritps setup.py:
`from setuptools import setup
from Cython.Build import cythonize

setup(
    ext_modules=cythonize("app.py")
)`

**Comment by freakboy3742** [comment]
Yes - because Cython is a tool that compiles code to a binary, so it needs to be compile a binary *for Android*.  Binaries are *platform specific*. Compiling them requires *specific* allowances for cross-platform compilation. If you're invoking Nuitka, Cython, or any other binary-generation tool, and you're not explicitly configuring a compiler and cross-compilation environment, and producing *at least 2* binaries (one for x86_64, and one for ARM64), then *your binary will not work*.

I know that Cython *can* be used compile code for Android - several of the [published binary wheels](https://chaquo.com/pypi-13.1/) use Cython as part of their build process. However, it requires a very specific build setup - you can't just run "cython myapp.py" and expect it to work. You *might* be able to adapt [Chaquopy's build tooling](https://github.com/chaquo/chaquopy/tree/master/server/pypi) to compile your app's code - but it won't be as simple as "just call cython".
