### ISSUE TITLE
Fail to build on Android with Pillow as dependency

### ISSUE THREAD

**Issue by SoranaBaciu** [beeware/briefcase#2058]
### Describe the bug

I have a working beeWare project, including on Andoid, and I need to include a pillow-based feature.

`briefcase build android` fails => Execution failed for task ':app:generateDebugPythonRequirements'.

Traceback:

```
 File "Local\Temp\pip-build-env-1bifjy9v\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 923, in find_library_file
      raise NotImplementedError
  NotImplementedError
  ----------------------------------------
ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow which use PEP 517 and cannot be installed directly
```

### Steps to reproduce

1. Update pyproject.toml
[tool.briefcase.app.gen_mj.android]
requires = [
    "toga-android~=0.4.5",
    "pillow==10.4.0",
]

2. Run `briefcase create android` : all good
3. Run `briefcase build android` => fails

### Expected behavior

Ability to install pillow as a dependency, and run on android.

### Environment

- Operating System for dev: windows 
- Python version: venv 3.8
- Software versions:
  - Briefcase:  0.3.19
  - Toga: toga-android~=0.4.5

### Logs

```

```

### Additional context

Same behavior for pillow-simd .

**Comment by mhsmith** [comment]
Not every version of Pillow is supported on mobile platforms. Remove the version number in your `requires` list, and it'll install the newest version available.

**Comment by somarariana** [comment]
> Not every version of Pillow is supported on mobile platforms. Remove the version number in your `requires` list, and it'll install the newest version available.

Thank you @mhsmith :)

To followup on the resolution, besides removing the precise version, needed to tell PIP not to used cached versions.

Commands:
* `briefcase create android`
* `set PIP_NO_CACHE_DIR=false`
* `briefcase build android`
* `briefcase run android`

**Comment by mhsmith** [comment]
I don't think PIP_NO_CACHE_DIR is relevant here – pip only caches the downloaded package files, not its decisions about which one to install.

However, Briefcase will only update the requirements list if you pass the `-r` option to `briefcase update`, `build` or `run`, or if you re-run `briefcase create`, as you did here. For discussion of improving this behavior, see #807.

**Comment by SoranaBaciu** [comment]
Without `set PIP_NO_CACHE_DIR=false` it used the cached version 10.4.0, which was not compatible.
