### ISSUE TITLE
Briefcase's attempt to set the URL for the `origin` remote for templates can fail with certain Git config

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#2077]
### Describe the bug

The configuration below can cause Briefcase to fail to roll out templates.
```ini
[url "ssh://git@github.com/"]
    insteadOf = https://github.com/
```
```console
❯ briefcase new --no-input -vvv

[helloworld] Generating a new application 'Hello World'
Using app template: https://github.com/beeware/briefcase-template, branch v0.3.20
DEBUG git.util: Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'No such file or directory')
DEBUG git.cmd: Popen(['git', 'remote', 'set-url', '--', 'origin', 'https://github.com/beeware/briefcase-template', 'https://github.com/beeware/briefcase-template'], cwd=/Users/rmartin/Library/Caches/org.beeware.briefcase/templates/briefcase-template, stdin=None, shell=False, universal_newlines=False)

Unable to check out template branch.

This may be because your computer is offline, or because the template repository
is in a weird state. If you have a stable network connection, try deleting:

    /Users/rmartin/Library/Caches/org.beeware.briefcase/templates/briefcase-template

and retrying your command.

Log saved to /Users/rmartin/tmp/beeware/logs/briefcase.2024_12_08-11_33_10.new.log
```
This is the actual error from Git:
```console
GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git remote set-url -- origin https://github.com/beeware/briefcase-template https://github.com/beeware/briefcase-template
  stderr: 'fatal: No such URL found: https://github.com/beeware/briefcase-template'
```

### Steps to reproduce

1. Add the configuration above to `~/.gitconfig`
2. Run `briefcase new --no-input`

### Expected behavior

Briefcase should not fail to use templates because it cannot update the URL of the `origin` remote....especially since this was added largely for the benefit of Briefcase developers...

Instead:
1) Briefcase should log a warning and move on using the template
2) Briefcase could try to update the URL without specifying an "old url"

As for number 2, specifying the "old url" is optional. Given that Briefcase is supposed to be managing these cloned repos, it seems like it should be fine to just blindly update the URL for the `origin` remote.

### Environment

- Operating System: Sequoia
- Python version: 3.12.7
- Software versions:
  - Briefcase: `0.3.20`

### Logs

[briefcase.2024_12_08-11_33_10.new.log](https://github.com/user-attachments/files/18053171/briefcase.2024_12_08-11_33_10.new.log)

**Comment by freakboy3742** [comment]
Good catch. 

For completeness - two more possible solutions: 
3. Abort the run, with instructions on how to delete the template that is in conflict and retry.
4. Delete the problem template (after confirmation), and re-try the template clone from a clean state.

That said: I'm trying to work out if being explicit about the old URL is actually providing *any* protection at all. The use case in the related docstring talks about forked templates - but in that case, you'd update the repo origin, fetch the new origin, get a whole lot of new SHAs and branches, and then check out the one that has been explicitly requested. 

Even if the template shared no common history... I think it would still work? It would end up being a mess of a repo, but it should *work*. The worst case I can think of would be a fork where the branch name contains inconsistent/incompatible changes - in which case, the worst case I can foresee is that the checkout fails because of the inconsistency. We should ensure the error handling is more helpful than "you may be offline", but enforcing the old origin URL could actually be preventing us from recoverable situations.

Am I missing a case where specifying the old URL is providing any real protection?

**Comment by rmartin16** [comment]
> For completeness - two more possible solutions:
> 3. Abort the run, with instructions on how to delete the template that is in conflict and retry.
> 4. Delete the problem template (after confirmation), and re-try the template clone from a clean state.

This is what happens now, though....but no amount of re-cloning will get rid of this specific problem.

> Am I missing a case where specifying the old URL is providing any real protection?

As long as `set-url` only runs for cloned templates in Briefcase's cache directory, I think it'd be fine. Basically, we'd just be saying, "no matter what, `origin` is at this URL now".....which would either be a user-provided URL or the default Briefcase one.

And if I were to guess, I think the actual purpose of specifying an "old url" is because I think Git supports multiple URLs for some of these settings for a remote; so, you'd be able to replace a specific URL for the setting.

**Comment by freakboy3742** [comment]
> > For completeness - two more possible solutions:
> > 3. Abort the run, with instructions on how to delete the template that is in conflict and retry.
> > 4. Delete the problem template (after confirmation), and re-try the template clone from a clean state.
> 
> This is what happens now, though....but no amount of re-cloning will get rid of this specific problem.

That delete-and-re-clone behavior is only enacted if the repo is in a fundamentally invalid state - not in the "origin mismatch" case - or am I missing something?
 
> > Am I missing a case where specifying the old URL is providing any real protection?
> 
> As long as `set-url` only runs for cloned templates in Briefcase's cache directory, I think it'd be fine. Basically, we'd just be saying, "no matter what, `origin` is at this URL now".....which would either be a user-provided URL or the default Briefcase one.

That's a fairly safe assumption here - the first thing `update_cookiecutter_cache()` does is establish a cache path that is in `data_path`. A backend *could* override `template_cache_path()`, but I'd be happy flagging as documentation that the path returned by that method should be "briefcase specific", not a cache directory that is likely be to used by others.

**Comment by rmartin16** [comment]
> That delete-and-re-clone behavior is only enacted if the repo is in a fundamentally invalid state - not in the "origin mismatch" case - or am I missing something?

Oh, right; Briefcase won't automatically delete the cloned repo in this case. I just meant Briefcase already outputs an error asking the user to manually delete the template repo and try again. But in this case, we must change how the `set-url` command is handled; either don't specify the "old url" or don't abort if it errors (since in 99% of cases, the repo won't need any updates to `origin` anyway).
