### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by knyghty** [beeware/briefcase#215]
@freakboy3742 

As we've talked about, I've been working on a first pass of a tree shaker. The shaker and test project can be found here: https://github.com/knyghty/shaker

The test project runs, but it's likely missing some ways to import things to test with, and no whitelist for dynamic imports is implemented. The code also feels a bit like spaghetti for just a couple hundred lines.

I'm not sure what the next step is, but I'm guessing the following would be useful:

- Cleaning up empty directories
- Implementing a module whitelist
- Testing with more complex projects

But any direction here would be useful.

**Comment by freakboy3742** [comment]
I'm going to close this in favour of #550. While automated tree shaking would be great, it's inevitably going to be  error prone. A manual specification approach allows the developer to be explicit about what isn't needed.
