### ISSUE TITLE
Add more information to tutorial steps

### ISSUE THREAD

**Issue by rixx** [beeware/briefcase#218]
The briefcase tutorial is trying (and mostly: succeeding) to be very helpful in setting the developer up to get started on a project. What I'm missing, though, is some explanation of what is going on.

E.g. in [Tutorial 0](https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html), the Android step reads 

> To create and run the application, run:
>
>     $ python setup.py android -s
>
>This will produce an android subdirectory that contains a Gradle project. It will also launch the app on the first Android device or simulator that can be found running on (or attached to) your computer.

While technically correct, a lot of things are happening when that command is executed, and since they are pretty magic, a more detailed explanation would be great. Explaining

- What is going to happen?
     - A couple of files are going to be downloaded the first time round
     - This will take some time
     - …
- Where it is going to happen? Yes, in the end there will be an `android` directory, but:
    - What's in there?
    - What's the structure like? or:
    - Where can we read more about that?
- Why it is going to happen? How can this workflow be adapted?

**Comment by freakboy3742** [comment]
+1 to almost all of this. I'm a little hesitant to get into "how can this be adapted" in a tutorial 0 - overloading a new user with information that isn't relevant until later - but there's definitely a place for it *somewhere* on the tutorial trail. 

However, more details on what is happening and why could even help diagnose what's going wrong - for example, a lot of failures are due to corrupted/incomplete downloads of support packages. Knowing that a large download is part of the build process might help a user diagnose when things go wrong when we can't.

**Comment by aidlearning** [comment]
i think the git can help u running python on android:
https://github.com/aidlearning/AidLearning-FrameWork
_AidLearning is a Linux system with GUI running on Android for AI programming. When it is installed, your Android owned a Linux system which can run AI program use python. Now we support Caffe, Tensorflow, Mxnet, ncnn, Keras, cv2, Git/SSH powerfully. we created an AI coding develop tool named Aid_code. It can provide you a visual AI programming experience by using Python from zero on our framework!the Aid_code can run python online and show the euro or logs. Android+Linux + AI 3in1_

**Comment by freakboy3742** [comment]
I've just added some major elaboration of these points in the updated, [unified BeeWare tutorial](https://beeware.readthedocs.io/en/latest/); the relevant changes occur around [step 3](https://beeware.readthedocs.io/en/latest/tutorial/tutorial-3.html#scaffolding-your-application).

Interested to hear if you feel this clarifies what is going on (and, for that matter, if the new tutorial makes any sense!)

**Comment by freakboy3742** [comment]
We've added a lot of detail since this ticket was opened, so I'm going to close this ticket; if there are any specific suggestions for further detail we can add, we can open new tickets.
