### ISSUE TITLE
Make setup.py return code != 0 if a build error occurred

### ISSUE THREAD

**Issue by rixx** [beeware/briefcase#219]
Having a correct return code would be great for debugging (and to stop me from being excited seeing the 'python setup.py finished with status code 0' notification).

**Comment by freakboy3742** [comment]
True - we should definitely be honoring status codes, if only for integration with larger CI systems.

In terms of actually fixing this - I suspect the solution will be a larger scale teardown. I'm starting to think that briefcase may need to move from being a distutils extension to being a standalone build tool. `setup.py` is really optimized for *library* distribution, not application distribution; and there seems to be  general trend to move away from distutils towards custom build tools (see PEP518, etc).

**Comment by freakboy3742** [comment]
This has been addressed in the 0.3 development branch that has just landed.
