### ISSUE TITLE
Next button logic on Getting Started

### ISSUE THREAD

**Issue by zanebclark** [beeware/briefcase#222]
The "Next" button on [Getting Started ](https://briefcase.readthedocs.io/en/latest/background/getting-started.html) leads to the [Quickstart ](https://briefcase.readthedocs.io/en/latest/background/quickstart.html) page where a setup.py file is expected to exist. I found the [Tutorial 0](https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html) to be a more logical next step.

**Comment by jcmcdon7** [comment]
I was unable to replicate this issue on my end. Though the link that you have provided on Getting Started leads to a non existent page, I was able to get to the Getting Started page by going to the Tutorial 0 page and clicking on the Previous button. Upon clicking the Next button on the Getting Started page, it lead me back to the Tutorial 0 page and not the Quickstart page.

**Comment by freakboy3742** [comment]
👍 Thanks for checking
