### ISSUE TITLE
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):

### ISSUE THREAD

**Issue by Ellegarden1219** [beeware/briefcase#245]
hello, 

When I try to create ios app, it gives me an error and error said, 

"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to lookup in current state: Shutdown
 * Installing new app version...
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to lookup in current state: Shutdown
 * Launching app...
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to lookup in current state: Shutdown
"

could you tell me how I can resolve this issue?

thanks

**Comment by freakboy3742** [comment]
Thanks for the report! That's a new error for me - so having some more detail about your situation would be helpful. 

* What version of macOS are you running? 
* What version of XCode are you running? 
* What app are you trying to run? If you're running your own app - can you reproduce the same problem with tutorial 0 (the simplest possible "just an app" app)?
* Were you given the option to select a simulator? If so, which one did you choose?
* When you get this error, is the simulator already running?  

The more details we have, the easier it will be to diagnose the problem you are seeing.

**Comment by Ellegarden1219** [comment]
Hello Thank you for your reply! and when I tried again, the previous error did not happen but I got another error and it said, 
"
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.example.Hello-World" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.example.Hello-World" is unknown to FrontBoard").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
	The operation couldn’t be completed. Application "com.example.Hello-World" is unknown to FrontBoard.
	Application "com.example.Hello-World" is unknown to FrontBoard.
"


What version of macOS are you running?
ver 10.13.6
What version of XCode are you running?
ver 9.4.1
What app are you trying to run? If you're running your own app - can you reproduce the same problem with tutorial 0 (the simplest possible "just an app" app)?
Im just trying to run with tutorial 0.

Were you given the option to select a simulator? If so, which one did you choose?
I chose ios 8 plus

When you get this error, is the simulator already running?
simulator was running fine, but I could not find the project, and today there was an project icon but after I clicked app seems trying to run it, but it did not run

**Comment by freakboy3742** [comment]
Thanks for those details - unfortunately, those extra error messages aren't familar to me either.

My guess is that this is related to the changes in the interface to starting the simulator that were introduced somewhere around XCode 10. 

If upgrading XCode is an option, that would be my first suggestion; however that obviously won't be an option for everyone, so it would be good to get to the bottom of this. If you're up for some debugging, [this change](https://github.com/beeware/briefcase/commit/4d54d7f1cbe5b87ef8d4d4ccacdd8b6b3f47dbd2#diff-0418921baf0534a7605268fa0ffee724R244) is where we changed the way we start the app on the simulator; I would be interested to see if the old syntax works for you.

**Comment by magic-lantern** [comment]
I'm seeing a similar error on newer versions of macOS (10.14.4) and Xcode (10.2.1). While I'm running newer macOS and Xcode than @Ellegarden1219 the errors I receive appear similar.

I'm following the simple tutorial at https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-0.html

I've noticed that I get different errors when running with an iOS simulator already started vs not started. However, in either case, the end result is the simulator is running, but the app does not deploy to the simulator.

Here's the full output I receive when running `python setup.py ios -s` with no simulator already started

```
running ios

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-ios==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/36/f1/a5e2f2390b3129768e2399d6c8a2e5ef3ffb2bf82f4e5e33b6bf7842dc7d/toga_iOS-0.3.0.dev11-py3-none-any.whl
Collecting rubicon-objc>=0.3.0 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/c7/1d/ef53fc55e035f4502a120d722d05b612830ffb0a5e923440f83bea091c7b/rubicon_objc-0.3.1-py2.py3-none-any.whl
Collecting toga-core==0.3.0.dev11 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: rubicon-objc, travertino, toga-core, toga-ios
Successfully installed rubicon-objc-0.3.1 toga-core-0.3.0.dev11 toga-ios-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /Users/seth/OneDrive/Documents/Development/beeware/helloworld
Installing collected packages: helloworld
  Running setup.py install for helloworld ... done
Successfully installed helloworld-0.0.1
 * Skipping creation of launch scripts.
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.

Available iOS versions:
  [1] iOS 11.1
  [2] iOS 11.2
  [3] iOS 12.1
  [4] iOS 12.2
Which iOS version do you want to target: 4

Available devices:
  [1] iPhone 5s
  [2] iPhone 6
  [3] iPhone 6 Plus
  [4] iPhone 6s
  [5] iPhone 6s Plus
  [6] iPhone 7
  [7] iPhone 7 Plus
  [8] iPhone 8
  [9] iPhone 8 Plus
  [10] iPhone SE
  [11] iPhone X
  [12] iPhone Xs
  [13] iPhone Xs Max
  [14] iPhone Xʀ
  [15] iPad Air (3rd generation)
  [16] iPad Air
  [17] iPad Air 2
  [18] iPad (5th generation)
  [19] iPad Pro (9.7-inch)
  [20] iPad Pro (12.9-inch)
  [21] iPad Pro (12.9-inch) (2nd generation)
  [22] iPad Pro (10.5-inch)
  [23] iPad (6th generation)
  [24] iPad Pro (11-inch)
  [25] iPad Pro (12.9-inch) (3rd generation)
Which device do you want to target: 4
 * Building XCode project for iPhone 6s com.apple.CoreSimulator.SimRuntime.iOS-12-2...
xcodebuild: error: SDK "iphonesimulatorcom.apple.CoreSimulator.SimRuntime.iOS-12-2" cannot be located.

Starting app on iPhone 6s com.apple.CoreSimulator.SimRuntime.iOS-12-2
 * Starting simulator...
 * Uninstalling old app version...
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to lookup in current state: Shutdown
 * Installing new app version...
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
 * Launching app...
com.example.Hello-World: -1
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.example.Hello-World" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.example.Hello-World" is unknown to FrontBoard").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
	The operation couldn’t be completed. Application "com.example.Hello-World" is unknown to FrontBoard.
	Application "com.example.Hello-World" is unknown to FrontBoard.

App started.
```

The end part is changed when a simulator is already running:

```
...
 * Building XCode project for iPhone 6s com.apple.CoreSimulator.SimRuntime.iOS-12-2...
xcodebuild: error: SDK "iphonesimulatorcom.apple.CoreSimulator.SimRuntime.iOS-12-2" cannot be located.

Starting app on iPhone 6s com.apple.CoreSimulator.SimRuntime.iOS-12-2
 * Starting simulator...
 * Uninstalling old app version...
 * Installing new app version...
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
 * Launching app...
com.example.Hello-World: -1
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.example.Hello-World" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.example.Hello-World" is unknown to FrontBoard").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
	The operation couldn’t be completed. Application "com.example.Hello-World" is unknown to FrontBoard.
	Application "com.example.Hello-World" is unknown to FrontBoard.

App started.
```

I can however manually open the project in Xcode and successfully build and deploy to an iOS simulator with no changes necessary.

**Comment by freakboy3742** [comment]
Thanks for those logs - they're very helpful.

For me, the telling thing is the error in the middle of the logs:
```
xcodebuild: error: SDK "iphonesimulatorcom.apple.CoreSimulator.SimRuntime.iOS-12-2" cannot be located.
```
That suggests that:
1. We're not catching errors correctly, and stopping the deploy process when we detect them
2. There's still something not quite right in the way we're identifying simulators...

**Comment by magic-lantern** [comment]
So, I'm new to the beeware code base. I know the identification of available iOS versions is in ios.py. Where would error catching from this problem be located?

Of course, if someone on the beeware core team has an idea on solving this, I'm happy to just be a tester.

**Comment by freakboy3742** [comment]
@magic-lantern The code in question is all in [the startapp() method for the iOS backend](https://github.com/beeware/briefcase/blob/master/src/briefcase/ios.py). At the moment, there's pretty much *no* error handling. Even adding in basic "return error code != 0" from each of the subprocess calls would likely be a major improvement. If we can interpret *what* those error codes mean, that would be even better (but will probably require spelunking in the docs for iOS command line tools, which are generally woefully documented).

**Comment by freakboy3742** [comment]
I believe that this was related to a change in the format for iOS simulator identifiers introduced somewhere around Xcode 10; Briefcase now has much more extensive checks for simulator ID handling.
