### ISSUE TITLE
Tutorial 0: No iOS device simulators found

### ISSUE THREAD

**Issue by magic-lantern** [beeware/briefcase#246]
Following the Hello World Tutorial and there seems to be some missing instructions for the ios simulator step:

```
python setup.py ios -s
running ios

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-ios==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/36/f1/a5e2f2390b3129768e2399d6c8a2e5ef3ffb2bf82f4e5e33b6bf7842dc7d/toga_iOS-0.3.0.dev11-py3-none-any.whl
Collecting toga-core==0.3.0.dev11 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting rubicon-objc>=0.3.0 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/c7/1d/ef53fc55e035f4502a120d722d05b612830ffb0a5e923440f83bea091c7b/rubicon_objc-0.3.1-py2.py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: travertino, toga-core, rubicon-objc, toga-ios
Successfully installed rubicon-objc-0.3.1 toga-core-0.3.0.dev11 toga-ios-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /Users/me/OneDrive - The University of Colorado Denver/Documents/Development/beeware/helloworld
Installing collected packages: helloworld
  Running setup.py install for helloworld ... done
Successfully installed helloworld-0.0.1
 * Skipping creation of launch scripts.
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
No iOS device simulators found
```

I didn't get any prompt about which simulator to use, nor any other prompts. I can however manually open the project in Xcode 10.2.1, select an iOS simulator and run the app.

I'm running macOS 10.14.4, Python 3.7.2.

**Comment by freakboy3742** [comment]
I think this may be a duplicate of the problem that #210 is trying to fix. At some point in the recent past, Apple changed the format of the string used to identify the simulators. 

I don't know if @ahter has plans to continue working on his patch; if you don't hear from him in the next day or so, and you want to contribute, feel free to fork off his patch and bring it to completion.

**Comment by ahter** [comment]
Hello,

Yes it's the same issue. Apologies it has been very chaotic few weeks, I didn't have time to look at the patch. I will submit it today. 

@magic-lantern, after I submit the patch I will let you know and you can perhaps try again.

**Comment by magic-lantern** [comment]
Sounds great. Happy to test once the patch is available.

Duplicate of #210
