### ISSUE TITLE
Briefcase and Android fixed yet?

### ISSUE THREAD

**Issue by lschaupp** [beeware/briefcase#248]
What are the latest news on this?
I saw some corresponding issue (altough much older).
I have tried it myself with gradle 5.4.1 but receiving 

> Could not find method leftShift() for arguments [build_yxpjlbt6imwl4fbmjymm6dgr$_run_closure1@46f77c3f] on task ':buildPythonDebug' of type org.gradle.api.DefaultTask.

myself with the helloworld tutorial.

cheers

**Comment by freakboy3742** [comment]
Unfortunately, there hasn't been any progress. BeeWare isn't a full time job (or even a *part* time job) for anyone working on the project. It is a spare time project - and speaking for myself, I literally haven't had any signifiant spare time to dedicate to *any* FLOSS project in a couple of months. I also haven't been inundated with people with Android experience looking to help.

I completely understand that this is frustrating. Believe me - I'm frustrated too.

**Comment by freakboy3742** [comment]
We've formally marked our Android backend as broken; this should hopefully be addressed in the near future thanks to a grant from the Python Software Foundation Education Grants committee. In the meantime, there's no point maintaining an open ticket, Android is effectively (for now) an unsupported platform.
