### ISSUE TITLE
Directory /Users/USERNAME/.cookiecutters/Python-Android-template isn't a valid template (no cookiecutter.json found) when running setup.py android -s

### ISSUE THREAD

**Issue by zurgeg** [beeware/briefcase#250]
I run ```python3.7 setup.py android -s``` and am met with the error in the title.

**Comment by freakboy3742** [comment]
This error is caused because we haven't published a 3.7 support template for Android yet. The error could definitely be handled better, though.

**Comment by zurgeg** [comment]
thanks!!

**Comment by jlamoure** [comment]
Any update on this, or suggestion for best practice? I don't want to use Python 2.

**Comment by zurgeg** [comment]
@jlamoure I know it's been awhile but use 3.6 or something.

**Comment by freakboy3742** [comment]
The good news is that we have someone actively working on Android support right now; with any luck, we should have Android support restored in *briefcase* within a week or so, and support in *Toga* in a month.
