### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by ubuntume** [beeware/briefcase#259]
I had a working beeware setup once before now all I get is Podium errors for my linux build. I even went through and only installed briefcase and same issue. I'd love to be put a message for a working guide to use this set of tools.

**Comment by freakboy3742** [comment]
Thanks for the report - but it's a little difficult to action this. It's not clear what you're done, what you tried, or what errors/output you're seeing. Are you able to provide specific details of the errors or behavior you're seeing, and what you've done to generate that behavior?

**Comment by ubuntume** [comment]
What I want to know is what are your specifics if you have a working setup? Linux OS, OS Version, Python Version, dependencies, etc. Not to make any comparison but kivy has a VM ready to build. I have hit a miss with beeware and it depends on so many factors.

**Comment by ubuntume** [comment]
SN: I dont like the development feel of kivy. I have made some cool apps with beeware, but again. If one ingredient is off it fails. Ive used the pip version of beeware and have been able to build before, but again recently beeware wont run the hello world due to a podium error - which is a new error based on previous builds and usage.

**Comment by freakboy3742** [comment]
Again: "I get an error" *isn't helpful feedback*. We need to see the *actual* error. The *text* of the message. Unless we know *what* error you're getting, we can't advise how to fix it, or identify what we can do to avoid that error in future.

*Briefcase* just needs a Python 3.5+ install. It's a pure Python tool; everything it needs is pip installable, and should be automatically installed when you install briefcase.

*Podium* uses Toga, and Toga has a couple of system dependencies - the GTK/Gnome libraries, GObject-introspect, and Webkit2 Gobject bindings. These requirements are documented as part of [Toga's docs](https://toga.readthedocs.io/en/latest/how-to/contribute.html), but they're all available as part of the default OS packaging. 

The patches to make Podium work on Linux only landed this previous weekend, so I'm not sure how you had it "working" previously. Regardless, both tools are *extremely* pre-1.0 - and the documentation is one of those areas that we know needs improvement. This is especially true on Linux, which has highly variable packaging requirements. 

But, once again: We can't fix *anything*, or provide *any* advice, if we don't know the *actual* errors people are getting.
