### ISSUE TITLE
No module named <app_name> on launch script

### ISSUE THREAD

**Issue by humrochagf** [beeware/briefcase#260]
Every time at the end of the build from the Linux packaging process I got this error:

```
Installation complete.
Starting Pyxel-Lander
/home/humrochagf/.virtualenvs/pyxel/bin/python3: No module named pyxel-lander

App started.
```

After some digging, I discovered that the problem is at this line:
https://github.com/beeware/briefcase/blob/master/src/briefcase/app.py#L241

The build process assumes the `app_name` as being the parameter `name` passed to the `setup()` function at the `setup.py` file but this isn't always right.

Some cases when we name our packages using dash "-" as spacing it is valid as package name but it isn't a valid python module name.

So, for example, if we have a `long-package-name` package, it's common to their module be called as `long_package_name` or sometimes `longpackagename` and even something else.

Maybe `app_name` being possible to be customized could be a good idea to solve this cases.

**Comment by humrochagf** [comment]
I think I can do it, my first assumption is that if I sanitize the app_name at the (L241)[https://github.com/beeware/briefcase/blob/master/src/briefcase/app.py#L241] it will work out, but I'll check its usage on the other templates as well.

**Comment by freakboy3742** [comment]
This edge case is now tested as part of the new development version. If you still see problems, please open a new ticket.
