### ISSUE TITLE
More targets?

### ISSUE THREAD

**Issue by jtrakk** [beeware/briefcase#263]
I keep coming back to [glyph's tweet](https://twitter.com/glyph/status/1158434894915072001): 

> If you're making a packaging tool for Python, stop trying to make single-file executables. They are a pointless technical flourish. You need to build:
> • .app bundles
> • .deb/.rpm/flatpack packages
> • Docker images
> • .msi installers
> • Homebrew formulæ
> • a codesigning pipeline

I'd love to have a CLI like

```
$ briefcase build macos --foo deb --bar rpm --baz flatpack --quux docker -x msi -y homebrew -z
```

Do these targets fit into your vision for briefcase?

**Comment by freakboy3742** [comment]
Not in that invocation; but most of target list - yes. 

It's difficult (if not impossible) to make an RPM package while on macOS, or an MSI while on linux, so a "single build command that does everything if you just give it enough switches" won't work in practice. However, I *would* envisage the following would be valid (assuming you were on a platform that supported them at the time):

* Build the default app target for the current platform
``` 
$ briefcase build
```
* Run (building if needed) the app using the current platform's default app format.
``` 
$ briefcase run
```
* Build a macOS app in Homebrew format (while on a platform other than macOS)
```
$ briefcase build --platform macos  --format homebrew
```
* Build a Linux app in RPM, AppImage and FlatPak formats
```
$ briefcase build  --format rpm --format appimage --format flatpak
```
* Publish a macOS app to the app_store
```
$ briefcase publish app_store
```

**Comment by jtrakk** [comment]
Cool.

The reason I arrived at that invocation is that I expect each target will need its own options, and I tend to feel like [subcommands](https://click.palletsprojects.com/en/7.x/commands/) are the best way to achieve that. Otherwise I end up either mixing options together or needing to do the awkward dance of hyphen-namespacing like

```
build --format rpm --rpm-args --foo --format deb --deb-args --bar
```

Subcommands allow a more natural segmentation of the namespace:


```
build rpm --foo deb --bar
```

**Comment by freakboy3742** [comment]
The 0.3 branch (just landed in master) implements this feature.
