### ISSUE TITLE
macOS | DMG creation capabilities

### ISSUE THREAD

**Issue by tmontes** [beeware/briefcase#273]
## Context
After #271 and #272 -- which add version information to the DMG file and volume name -- I figured a few improvements could be considered in `briefcase`'s DMG creation capabilities. Given that work is in progress towards a revamped `briefcase` in #266, and per @freakboy3742's suggestion, I'm sharing those ideas here, instead of directly going for one or more PRs.

## Disclaimer
Not being 100% familiar with `briefcase`, maybe some/all of these are already possible. If that is the case, then I have nothing to add at the moment, other than the fact that, as a [Mu Editor](https://github.com/mu-editor/mu/) contributor, I'll gladly test out `briefcase` as the new code comes into shape.

## Facts
* `briefcase` uses [`dmgbuild`](https://github.com/al45tair/dmgbuild) to create macOS DMG files, when passed the `--build` / `-b` command line argument.
* The resulting DMG file includes the packaged macOS application bundle and a soft-link to the `/Applications/` directory -- a common pattern to induce/help users "install" the application onto their system, by dragging the application icon onto the `/Applications/` directory.
* Such "drag to copy and install" process is often facilitated by laying out the two icons in a particular visual layout -- say application on the left, soft-link to `/Applications/` on the right -- which is then complemented with a background image containing a visual "arrow" between one and the other.
* `briefcase` does support creating DMG files with a custom background image. It does not, however, allow the specification of the locations for the icons.
* `dmgbuild`, however, does support such customisations and more.

## Proposed improvements
* Let's improve the "default" DMG such that the application icon is on the left, the `/Applications/` soft-link is on the right, and there is a visual arrow from one to the other - this is a matter of invoking `dmgbuild` with slightly different settings, including asking it to use its builtin `'builtin-arrow'` background image. The current behaviour produces this:
![current](https://user-images.githubusercontent.com/1912206/66123092-2866cb00-e5d9-11e9-8e16-5e6dc44c61a3.png)
  And I consider this to be an improvement (albeit a simple and, granted, subjective one):
![proposed](https://user-images.githubusercontent.com/1912206/66123292-88f60800-e5d9-11e9-9ff1-1d623cc8513f.png)
* Let's then allow users to specify [arbitrary `dmgbuild` settings](https://dmgbuild.readthedocs.io/en/latest/settings.html) when invoking `briefcase` - such settings would add to and/or override the default ones.
* Maybe simplify the inclusion of a license file in the DMG [1] -- something that will be easily doable with the previous item's capability, but that requires setting a bunch of things. Having a "shortcut" like *use this <file-here> as the DMG license file* would be nice.

[1] By "license file in the DMG" I do not mean bundling it in as a third icon/file when the DMG is mounted/explored (even though that could be considered, too). I'm referring to a native DMG capability that will display such license when the file is mounted. Again, this is supported by `dmgbuild` even though there's an [oldish PR pending merge](https://github.com/al45tair/dmgbuild/pull/14) to have that work on Python 3).

PS: I have a WIP branch with some of the above in place, as a fork off of the current master. I haven't looked at the code for the revamped `briefcase` in #266, but I suppose integrating in these capabilities will be simple and easy, once the general foundation of "how does a user tell `briefcase` what to do" is layed down.

**Comment by freakboy3742** [comment]
👏 to all these suggestions. The background image and icon positioning is a clear win, and having more configurability of the `dmgbuild` process is something that the new configuration mechanisms in #266 should make a lot easier. I'll keep these ideas in mind as I keep working on #266, and I'll make sure I loop you in as that code gets closer to production ready.

**Comment by tmontes** [comment]
@freakboy3742, two somehow interrelated questions:

* What's your plan / expectation for the timeline of the revamped `briefcase` in #266?
* Given that you tagged this issue as "up-for-grabs", I'm wondering if you were thinking of having all/some of these suggestions implemented in the current version: something I'll will gladly contribute.

**Comment by freakboy3742** [comment]
The timeline is difficult to predict, but I'd like to think it will be a month or two before we've got at least a workable beta.

I tagged this as up-for-grabs on the basis that it's something I'm interested in adding; but formally adding it to the existing codebase is likely to be more work that it's worth. However, if you can work out what changes are needed, it should be a relatively straightfoward matter to integrate those changes into the new codebase once it's ready.

**Comment by freakboy3742** [comment]
Background images are now supported in the 0.3 development version (which just landed in master) - although we don't currently ship with a default background image. 

Adding other features (such as license files) should be a lot easier to accomodate.

**Comment by freakboy3742** [comment]
Closing on the basis that I think the features requested by this ticket have all been addressed. If there are any outstanding, they can be opened as new feature requests.
