### ISSUE TITLE
No module named helloworld

### ISSUE THREAD

**Issue by LewisGaul** [beeware/briefcase#274]
Note: This issue seems similar and potentially the same as https://github.com/beeware/briefcase/issues/260 - feel free to close it if it turns out to be the same!

When following the tutorial 0 steps (on Windows 10 and on WSL Ubuntu) I get the following output towards the end:
```
Installation complete.
Starting Hello World
/mnt/c/Users/legaul/Documents/personal/beeware-tutorial/.venv/bin/python3: No module named helloworld
```

When discussing with @danyeaw he realised a workaround for this is to change the 'formal name' in setup.py from "Hello World" to "helloworld". However, Dan pointed out that it should be possible to have the formal name be different to the short app name.

**Comment by freakboy3742** [comment]
Thanks for the report! 

I don't think this is the same as #260 - that is an issue with the Linux template; this one is a Windows template issue. @Danyea is absolutely correct in saying that it should be possible to have a formal name and a short name that is different - that's the whole point of having two names :-) - it sounds like we're either:
1) using the formal name somewhere that the short should be used.
2) failing to wrap the formal name in quotes if it *is* the right name.

The underlying idea around the naming: 
* The short name is the name of the "python module" (so, letters, numbers and underscores, with dashes normalized to underscores); 
* the formal name is the "human" name (so any character is fair game).

The short name should be used wherever it's something being referred to by code; the formal name where it's something the end user will see (e.g., file paths for the application bundle, or the final installer name).

**Comment by LewisGaul** [comment]
FWIW it's not confined to Windows, I also saw this issue on Linux. I think the executable is being given the human-friendly name rather than the python-friendly name, but I could be remembering wrong.

If you can point me to where a change is needed I'll be happy to open a PR for the issue :)

**Comment by freakboy3742** [comment]
If that's the case, there are 2 different issues; a Linux problem, and a Windows problem. The fixes will be in two completely different repositories.

* Linux: https://github.com/beeware/Python-Linux-template/
* Windows: https://github.com/beeware/Python-Windows-template/

Two things you should be aware if you're interested in looking into these bugs:

1) The Linux template, at present, is extremely barebones. My intention is to replace it with a versions that produce AppImage packages (with Flatpak and Snap packages also a possible option). So, I wouldn't worry *too* much about the Linux template, unless you're also interested in digging into setting up a proper AppImage template.

2) I'm in the middle of a [big rewrite of Briefcase](#266) at the moment that should provide a lot more flexibility for Briefcase application templating. This rewrite was prompted, in part, by some difficulties I hit trying to write an AppImage template for Linux. One of the side effects of this rewrite is that we should end up with better error handling around "illegal character in app name" type problems, and a better defined set of primitive to use *in* templates. 

Hopefully, those two points won't scare you off contributing - we definitely need as much help as we can get, and changes to the "old" templates will still be useful - if only as a guide for what features we need to include in the rewrite.

**Comment by freakboy3742** [comment]
I should also add: the templates themselves can be tested and validated without needing briefcase at all. Briefcase uses cookiecutter to unroll the templates, and you can use cookiecutter directly to use/test the templates.

**Comment by LewisGaul** [comment]
I realised I don't think I did see it on Windows at all, but here I have a fix for the Linux template: https://github.com/beeware/Python-Linux-template/pull/8

**Comment by LewisGaul** [comment]
Also it turns out this is a duplicate of https://github.com/beeware/Python-Linux-template/issues/7, so I'm closing the issue.
