### ISSUE TITLE
briefcase Debian 9 

### ISSUE THREAD

**Issue by llabans** [beeware/briefcase#278]
Hi, I am debian user and I had this problem: 
 ` pip install briefcase`

`Collecting briefcase
  Downloading https://files.pythonhosted.org/packages/d4/07/5897ba0439265343343a2b3fcb554262a9a1014b71c1928db03882c2d31c/briefcase-0.2.1.tar.gz (149kB)
        ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lHfK6_/briefcase/
`

**Comment by freakboy3742** [comment]
That's... a weird error message (and, unfortunately, not very helpful...)

My guesses would be:
* An old/stale version of pip and/or setuptools
* A permissions issue associated with the environment where you're installing
* An incomplete/corrupted download (least likely, but worth mentioning as a possibility)

Can you confirm:
* Your current version of pip and setuptools
* Are you're using the "system" pip/setuptools, or a version that has been installed from PyPI
* Are you using a virtual environment, or are you installing into the system Python?

**Comment by llabans** [comment]
- pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
- system pip
- virtual environment

**Comment by freakboy3742** [comment]
What about the setuptools version?

**Comment by llabans** [comment]
Hi, the problem was with the pip version. Everything is fine when using
`pip3 install briefcase`

**Comment by freakboy3742** [comment]
In which case, I'll close the ticket! Happy briefcasing!
