### ISSUE TITLE
[DOC] Typo in text generated from briefcase new

### ISSUE THREAD

**Issue by beckernick** [beeware/briefcase#287]
Looks like there may be a small typo in the auto-generated new application text after typing `briefcase new`.

```
...
Author'S Email [nick@example.com]: ...
```

The [docs](https://beeware.readthedocs.io/en/latest/tutorial/tutorial-1.html#bootstrap-a-new-project) for this segment also have a small typo and look to be missing the end of a sentence:

```
Author email - Enter your own email address. This wil only appear in the
```

**Comment by freakboy3742** [comment]
Well *that* is annoying :-)

Turns out it's because `str.title()` capitalizes letters after an apostrophe. We'll have to change the usage to `str.capitalize()` (line 212 of src/briefcase/commands/new.py if you fancy submitting a pull request!)
