### ISSUE TITLE
iOS: Can I create library/framework using briefcase?

### ISSUE THREAD

**Issue by sadiqueshannure** [beeware/briefcase#298]
Hi Team,
Thanks for this project, really appriciate your efforts.
I would like to know whether I can write an algorithm in Python & convert it to .framework library so that I can import it in an iOS application using briefcase?

Thanks & Regrads,
Sadique

**Comment by freakboy3742** [comment]
@sadiqueshannure Hi Sadique! It's possibly to write your own Python code and distribute it as part of your iOS application. 

However, you wouldn't generally wrap up your code as an iOS framework - you'd use Python-native distribution mechanism (i.e., PyPI distribution, or at least a setuptools configuration on a Python project). The only part that needs to be distributed as a framework is the Python support library itself (i.e., the bit that starts the Python runtime).

If you want an example of how this works in practice, I suggest running through the [BeeWare tutorial](https://beeware.readthedocs.io); that shows how one specific project can be deployed on iOS, and the resulting XCode project will give you an idea of how you could distribute your own code.

**Comment by sadiqueshannure** [comment]
Thanks @freakboy3742 !

**Comment by freakboy3742** [comment]
If there's no follow up, I'll close this question.
