### ISSUE TITLE
Identify when XCode command line tools are missing, but XCode is installed

### ISSUE THREAD

**Issue by hlovatt** [beeware/briefcase#299]
Hi,

Following the Hello World tutorial I got the error "Xcode is not installed." when trying to build the iOS version of the Hello World App. The problem turned out to be that Xcode does not by default install the command line tools and you have to go to Preferences -> Locations -> Command Line Tools and select the tools (in my case "Xcode 11.3.1").

Probably an idea to add this to the tutorial.

Keep up the good work,

 -- Howard.

**Comment by freakboy3742** [comment]
Thanks for the report! That's really helpful to know; and it's one of those things that's really hard to identify and test for once you've fixed the problem :-)

I completely agree that we should add this note to the error message that is reported. 

Better still would be to differentiate between Xcode *actually* not being installed, and the command line tools being missing. 

Even better still would be to automatically (after prompting for permission) to download the command line tools. I *think* I've seen another tool do this...
