### ISSUE TITLE
Add browser/web support (via brython? pypy.js? batavia? all of the above?)

### ISSUE THREAD

**Issue by glyph** [beeware/briefcase#3]
It would be really awesome if briefcase could build a minified, combined JS bundle for deploying into a browser, as well.

**Comment by freakboy3742** [comment]
Interesting - what's the use case here? Would this mean shipping a standalone "single site browser" app, or are you thinking of something else?

**Comment by glyph** [comment]
Right now, I can write some Python code to run in a browser with Brython. But when it comes time to actually deploy that code to a site, it's not clear what to do.  Presently it's something like [https://github.com/brython-dev/brython/issues/119](install a bunch of junk in a virtualenv using CPython 3.something, then serve site-packages over HTTP somewhere).  But in this configuration, [import is excruciatingly slow](https://github.com/brython-dev/brython/issues/222).

Briefcase would have to do a bit of inventing a deployment format here (how should the javascript be smashed together? what does the bootstrapping look like? how does your HTML that calls `brython()` find out about the right `sys.path`)? But the idea would be to automate all the steps (get all the dependencies, compile them to JS with the brython toolchain, concatenate them together properly) that a "production" application might be shipped.

Of course if you could jam this into an [Electron](http://electron.atom.io) container as a front-end, combined with back-end PyPy or CPython code, that would be even more awesome!  But that's probably a separate ticket, although it depends on this.
