### ISSUE TITLE
Android still supported? Any updates here?

### ISSUE THREAD

**Issue by eruvanos** [beeware/briefcase#302]
Hi,
I checked the tutorial at https://docs.beeware.org/en/latest/tutorial/tutorial-5/android.html

Which says, that the Android part is coming "soon".
I also found an archived cookiecutter template for android.

Is there any update or roadmap if Android will be supported again?

Regards

**Comment by freakboy3742** [comment]
Android will most definitely be supported again - very soon. We've [currently got a contractor](https://beeware.org/news/buzz/we-have-a-contractor-for-our-android-contract/) working on the the problem, paid for by a PSF Education grant. You can see the work in progress on his Github account (@paulproteus); we make small announcements on Twitter, and are expecting to make a larger progress announcement on the blog next week. (To be clear - Briefcase won't be fully enabled for Android next week, but we'll be able to show that we've got Android support working again)

Closing this question as answered; If you've got any follow up questions, let us know!
