### ISSUE TITLE
Briefcase fails under Python 3.5 due to Jinja2 dependency

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#305]
Briefcase uses Cookiecutter, which in turn uses Jinja2. Jinja2 3.0a1 (released Feb 6 2020) dropped support for Python 3.5; but for some reason, the "python-requires" marker on the Jinja2 package isn't being honored by pip.

We need to pin Jinja2 at <3.0 until we drop Python 3.5 support.

**Comment by eredhan** [comment]
Jinja2 3.0 is now out, thus pip ping-ponging of versions is happening.  Might it be time to revisit this (3.5 support vs. restricting Jinja ver)?
