### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#306]
Python 3.5 becomes EOL in October 2020.  Once that happens, we can consider dropping support for Python3.5.

Checklist of things that can be updated:
* Python-requires definition can be updated 
* Packaging metadata tag can be updated
* Pinned version of Jinja2 can be released
* Documentation references to 3.5+ support can be updated.
* Uses of `format()` can be replaced with f-strings
* Some str() casting of paths can be removed.
* Update CI to remove Python 3.5 builds, and do smoke builds on 3.6

**Comment by freakboy3742** [comment]
To be clear - this isn't something we should be working on *now* - it's a placeholder for work to be done around October 2020.

**Comment by saroad2** [comment]
Maybe make this a Github milestone for version 3.1.0 or something,

**Comment by freakboy3742** [comment]
We've dropped support for 3.5 and 3.6, so I think we can call this done. `str()` casting has been addressed, and format strings are in the process of being fixed as code is updated.
