### ISSUE TITLE
Cannot find package when run 'briefcase dev'

### ISSUE THREAD

**Issue by saroad2** [beeware/briefcase#308]
I have the following pyproject.toml file:
```
[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Fit GUI"
bundle = "com.fitgui"
version = "0.0.1"
url = "https://fitgui.com/FitGui"
license = "Apache Software License"
author = 'Sagi Shadur'
author_email = "saroad2@gmail.com"
sources = ['src/lab_util']

[tool.briefcase.app.fitgui]
formal_name = "Fit GUI"
description = "Fitting GUI for laboratory experiments"
icon = "src/fitgui/resources/FitGui"
sources = ['src/fitgui']
requires = [
    'numpy>=1.18.1',
    'scipy>=1.4.1',
    'matplotlib>=3.1.3',
    'pandas>=1.0.1',
    'prettytable>=0.7.2',
    'xlrd>=1.2.0',
]


[tool.briefcase.app.fitgui.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev18',
]

[tool.briefcase.app.fitgui.linux]
requires = [
    'toga-gtk>=0.3.0.dev18',
]

[tool.briefcase.app.fitgui.windows]
requires = [
    'toga-winforms>=0.3.0.dev18',
]

# Mobile deployments
[tool.briefcase.app.fitgui.iOS]
requires = [
    'toga-iOS>=0.3.0.dev18',
]

[tool.briefcase.app.fitgui.android]
requires = [
    'toga-android>=0.3.0.dev18',
]
```

When I try to run "briefcase dev" I get the following error:

```
c:\users\saroa\repositories\lab_util\venv\scripts\python.exe: No module named fitgui

Unable to start application 'fitgui'
```

Do you have any idea why?
I am working on a windows computer.

**Comment by saroad2** [comment]
No problem, I'll fix the bug.

However, There is something else here: I want to separate the GUI package from the logic package (lab_util is the logic and fitgui is the gui). when I use 2 sources it looks it tries to run them both with "python -m".
I suggest we add a "main" option in the .toml file so one can specify the main they want to run and which are pure library sources.

Agree?

**Comment by freakboy3742** [comment]
Where you're getting the impression that it's trying to run multiple modules? The only module that it should be trying to start is the app module - so, in your example, the app name is "fitgui", so it will be trying to run `python -m fitgui`. Unless I'm missing something, there shouldn't be a need for a separate configuration item to disambiguate which module is the "main".
