### ISSUE TITLE
issue in creating xcode project when requirements include audiostream (depends on a CythonRecipe)

### ISSUE THREAD

**Issue by srsridharan** [beeware/briefcase#31]
When using briefcase to create an xcode project from python code which uses [audiostream](https://github.com/kivy/audiostream) - the build goes through fine but when the xcode project is run the following error is encountered
```
("No module named 'audiostream.core'",)
```
This occurs at the line
```
        from audiostream import get_input
```
Suspected reason:  The audiostream directory has core.c, core.pyx  which would need CythonRecipe as indicated at [the kivy-ios page](https://github.com/kivy/kivy-ios)

Note: as audiostream is not recognized by default when added to *app_requires* in setup.py despite being installable via pip (not sure why), I worked around it by 
- downloading the audiostream project
- modifying the setup.py script since it had print statements in python 2.7 format instead of python 3.4
- creating a zip file 
- adding the complete path to this zip file to the app_requires section

Other details
- python 3.4,
- compiling for iOS
- the setup.py and app to reproduce the issue are as attached.

[app.py.txt](https://github.com/pybee/briefcase/files/924209/app.py.txt)
[setup.py.txt](https://github.com/pybee/briefcase/files/924210/setup.py.txt)

**Comment by freakboy3742** [comment]
The problem of installing Python packages definitely exists; however addressing it is somewhat outside the scope of Briefcase. There is a larger problem in the Python packaging ecosystem that needs to be addressed - that of cross-platform install targeting. 

For now, I'm going to close this ticket, and address the problem with documentation from Briefcase's perspective.
