### ISSUE TITLE
Add Windows support for Android target

### ISSUE THREAD

**Issue by paulproteus** [beeware/briefcase#330]
The Android target in #321 crashes on Windows.

Implementation notes:

- `sdkmanager` must be called as `sdkmanager.bat`. We can adjust the `briefcase` code accordingly.

- Windows lacks a Java 8, and therefore `sdkmanager.bat` fails to launch. We can print a helpful message about how to fix this if actually downloading Java 8 is too much of a bother. Presumably we'd recommend AdoptOpenJDK as a source of Java 8 binaries.

**Comment by freakboy3742** [comment]
Fixed by #336
