### ISSUE TITLE
Add support for Flask as a web target.

### ISSUE THREAD

**Issue by GNHua** [beeware/briefcase#35]
Is briefcase able to package a flask web app?

**Comment by freakboy3742** [comment]
Not at present; however, we'd certainly like to add that functionality.

**Comment by GNHua** [comment]
Sometimes it is nice to use light web framework, like flask, to build apps just for local use. But there seems no good way to do the packaging. I am now using docker to achieve that. But I don't think docker is the best solution for it.

**Comment by freakboy3742** [comment]
Closing on the basis that we don't support Web at all at present, so #3 needs to be addressed first.
