### ISSUE TITLE
Error HEAT5052. Unable to generate manifest for app.

### ISSUE THREAD

**Issue by ianharris-hub** [beeware/briefcase#355]
Hello there, _I am a beginner so I sincerely hope I am not wasting your time!_

I'm stumped as I go through the tutorial. I have triple checked each step but am stuck at "briefcase package".

**
(beeware-venv) C:\Windows\System32\beeware-tutorial\helloworld>briefcase package windows

[helloworld] Building MSI...

Compiling application manifest...
heat.exe : error HEAT5052 : The directory 'C:\Windows\System32\beeware-tutorial\helloworld\windows\Hello World\src' could not be found.
Unable to generate manifest for app helloworld.
**
It seems that the directory location does exist and I have "created", "built" & "run" as the tutorial walks me through.

Thank you in advance!

**Comment by freakboy3742** [comment]
Thanks for the report - that's definitely odd. 

I notice you're running in the `C:\Windows\System32` folder. That's a system folder, so it's possible you might be hitting a permission problem with running an executable in a semi-protected location. 

Could I get you to re-run the tutorial, but starting by creating the beeware-tutorial directory in your home directory (i.e., `C:\Users\<your username>`)?

(Also - I'm interested why/how you ended up in that location to start with; when I start cmd.exe, I am dropped into `C:\Users\<my username>`. Can you think of any reason your session may have started in the system folder?)

**Comment by ianharris-hub** [comment]
> Could I get you to re-run the tutorial, but starting by creating the beeware-tutorial directory in your home directory (i.e., `C:\Users\<your username>`)?
> 
Yes! When I open elevated CMD that the default location it sends me. I guess before I didn't even think of changing that. Even though I did try to allow full permission before I posted, that didn't work either.

Changing my location to my Documents was a success and it was able to package successfully!

**
(beeware-venv) C:\Users\ianha\Documents\beeware-tutorial\helloworld>briefcase package

[helloworld] Building MSI...

Compiling application manifest...

Compiling application installer...
helloworld.wxs
helloworld-manifest.wxs

Linking application installer...

[helloworld] Packaged windows\Hello World-0.0.1.msi
**

> (Also - I'm interested why/how you ended up in that location to start with; when I start cmd.exe, I am dropped into `C:\Users\<my username>`. Can you think of any reason your session may have started in the system folder?)

**When I run command prompt as Administrator, it opens under system32. However, when I run command prompt not as Administrator, it puts me in C:\Users\.**

I could imagine more issues similar to this being related to OneDrive because it has replaced the directory of a lot of my folders.

**Comment by freakboy3742** [comment]
Ah - that's good to know; and I'm glad you were able successfully complete the tutorial! 

Sounds like we should add a note to the tutorial warning Windows users not to create the project directory in System32.

**Comment by ianharris-hub** [comment]
> Ah - that's good to know; and I'm glad you were able successfully complete the tutorial! 
> 
> Sounds like we should add a note to the tutorial warning Windows users not to create the project directory in System32.

Thanks for helping me through this issue!
