### ISSUE TITLE
Add Flatpak Packaging

### ISSUE THREAD

**Issue by AstraLuma** [beeware/briefcase#359]
Add support for [Flatpak](https://www.flatpak.org/)

**Comment by freakboy3742** [comment]
Yes - we'd love to add Flatpak support.

See https://github.com/beeware/briefcase/issues/94#issuecomment-362077925 for some initial work that has been done in this area.

**Comment by freakboy3742** [comment]
See also [this blog post](https://www.loganasherjones.com/2018/05/using-flatpak-with-python/), which specifically talks about BeeWare.

**Comment by freakboy3742** [comment]
Closed by #802.
