### ISSUE TITLE
Add code notarization to the macOS package command

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#365]
macOS apps can be code signed; but Catalina requires an additional *notarization* step.

The mechanics of the process are covered well by [this blog post](https://glyph.twistedmatrix.com/2018/01/shipping-pygame-mac-app.html). 

See #174 for an older ticket about this feature.

**Comment by LinasNas** [comment]
Hi, 

I wanted to ask if someone is already working on implementing the code notarization. If not, here is one way how I could try to do it, but I'm also very open to feedback for any improvements:

Starting with Xcode 13, Apple has introduced a command called ```notarytool``` which replaces the command [```altool```](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow?preferredLanguage=occ) and simplifies the process of notarizing applications. Its use is well covered in this [blogpost](https://scriptingosx.com/2021/07/notarize-a-command-line-tool-with-notarytool/). 

The command to notarize the application would be: 
```
xcrun notarytool submit <filepath> \
                   --keychain-profile <profilename> \
                   --wait
```

The argument ```<profilename>``` is the name of the app-specific credentials stored in the keychain. The one-time procedure for creating these credentials is to call the following command, documented in Apple's notarization workflow [here](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow?preferredLanguage=occ):

```
xcrun notarytool store-credentials "AC_PASSWORD"
               --apple-id "AC_USERNAME"
               --team-id <WWDRTeamID>
               --password <secret_2FA_password>
```

Finally, once the app is notarized, the notarization ticket needs to be stapled with the following command: 
```xcrun stapler staple <filepath>```

My idea was to submit a pull request(s) with the following changes:
1. Add documentation on:
- creating a codesign identity on Apple (can't be automated)
- storing app-specific credentials in Keychain (it's a one-time step with a single command, and it requires going to Apple ID page to get an app-specific password, which can't be automated)

2. Add code notarization functionality to the [```init.py```](https://github.com/beeware/briefcase/blob/4ff10af5344348fa24b9e70db60be81a32532d18/src/briefcase/platforms/macOS/__init__.py) function for macOS:
- add a new function called ```notarize()``` which would execute the ```xcrun notarytool submit``` command, taking as arguments the filepath and the keychain profile.
- edit the ```package_app()``` function to implement the ```notarize``` command. 

Does this workflow sound reasonable, and would you have any feedback on the implementation? It's also completely understandable if you're already working on a different way to implement this.

**Comment by freakboy3742** [comment]
Nobody is working on this to my knowledge, so yes - any assistance would be appreciated!

The broad approach you describe (documenting how to get a code sign identity - we have a [placeholder](https://briefcase.readthedocs.io/en/latest/how-to/code-signing/macOS.html) already) - and then adding notarisation to `package`) makes sense.

One question I've got is about the notarisation process. As I understand it, there's a 2-pass approach needed here - one to initiate the notarisation process, and one to "staple" the notarisation results. I'm imaging something like:

```

$ briefcase package
... calls notary tool ...

... you get notification (via email?) that the app has been notarised...

$ briefcase package --notarize <path to ticket>
```

Anything we can do to automate (or assist) the process of creating credentials would also be valued - even it's at the level of a "wizard" that asks you questions, runs whatever commands can be run locally, and then provides links in-terminal (or directly opens webpages with `webbrowser.open()`) to assist the user to register credentials. That could/should include `xcrun notarytool store-credentials` if possible - if there's any way to "register on first use" (which would mean either tracking whether they *have* been used, or always attempting registering and catching the error if they've already been registered) then we should do that too. 

We may want to tackle this as 3 separate projects/PRs:

1. Document how to get/register credentials as a manual process.
2. Automate the process of notarising an app given known credentials
3. (Semi) Automate the process of creating credentials.

**Comment by LinasNas** [comment]
I've just submitted a pull request which updates the documentation for creating a macOS code signing identity in [docs/how-to/code-signing](https://github.com/beeware/briefcase/tree/master/). 

Any feedback would be greatly appreciated!

**Comment by LinasNas** [comment]
I definitely agree with the general workflow you've described as a 3-PR-process. I also wanted to ask your opinion about a few things you've mentioned:

Regarding: 
 > One question I've got is about the notarisation process. As I understand it, there's a 2-pass approach needed here - one to initiate the notarisation process, and one to "staple" the notarisation results. I'm imaging something like:

You are right about the two-step process involved in the notarization: 
1. Submitting the app for notarization to Apple
2. Stapling the notarization ticket to the notarized app

From my experience of using Xcode to notarize applications, both steps are combined together. The process of stapling the notarization ticket is done automatically if the notarization was successful. 

That's why I think it would make sense to implement both of these functions under the same command. If you agree with this idea, I could implemented the notarization feature in one of two different ways :

I. ```briefcase package --notarize <path to the application>```

This command would sequentially call the functions of:
1. signing the app
2. notarizing the app
3. and stapling the notarization ticket to the app

It would essentially provide a single-command tool for users to both sign and notarize their app. 

Or the notarization function could be implemented separately:

II. ```briefcase notarize <path to the signed application>```

This version of the workflow would mean that users would first call the ```package``` command to sign the app, and then later call the ```notarize``` command. 


Regarding: 
> Anything we can do to automate (or assist) the process of creating credentials would also be valued 

It definitely seems possible to automate the ```xcrun notarytool store-credentials``` command. As far as I understand, it would be implemented as a separate command, e.g. ```beeware store-credentials```?

**Comment by freakboy3742** [comment]
> You are right about the two-step process involved in the notarization:
> 
> 1. Submitting the app for notarization to Apple
> 2. Stapling the notarization ticket to the notarized app
> 
> From my experience of using Xcode to notarize applications, both steps are combined together. The process of stapling the notarization ticket is done automatically if the notarization was successful.

Ah - my understanding (which sounds like it is either outdated, or was entirely wrong to start with), was that there was an "wait for an email" step in the middle of this process - that you could *submit* the app for notarisation, but that you then needed to wait a nebulous period of time for a notification before you could proceed to the next step of stapling (and possibly that the email contained the thing you needed to staple?). If that's not the case, then doing both steps as part of a single invocation of the `package` command would be preferable.

> I. `briefcase package --notarize <path to the application>`

"Path to the application" shouldn't ever be required; briefcase is a project-specific tool, so the path to the application is always internally known. 

My understanding is also that notarisation is something that is essentially required for *every* macOS app; so the high level task of "package my app for macOS" necessarily includes notarisation. Having a `--notarize` option isn't a requirement. 

Having a `--no-notarize` option that skips the entire notarisation process, would probably be a good idea, though; there's always going to be some edge case where you can't easily (or don't want to) notarise. But the default behaviour for packaging should be to notarise, unless there's a good reason not to, because an unnotarized app is essentially useless for distribution purposes.

> This command would sequentially call the functions to:
> 
> 1. sign the app (already implemented)
> 2. notarize the app
> 3. and staple the notarization ticket to the app
> 
> It would essentially provide a single-command tool for users to both sign and notarize their app.

Confirming - this sounds like the preferred option to me.

> Or the notarization function could be implemented separately:
> 
> II. `briefcase notarize <path to the signed application>`
> 
> This version of the workflow would mean that users would first call the `briefcase package` command to sign the app (already implemented), and then later call a new `briefcase notarize` command, which would:

As a broader statement of principle, I'd like to avoid adding additional commands if at all possible, unless that step in the process is truly "universal" to all platforms. *Every* app, regardless of platform, needs to be created, and built, and run. "Notarisation" is a macOS specific requirement with no analog on (any?) other platforms. 

In terms of "user stories" - a user doesn't care if an app is "notarised" - they care if they can give their app to someone else. We should be aiming to hide as much of the detail of that process as possible.

> > Anything we can do to automate (or assist) the process of creating credentials would also be valued
> 
> It definitely seems possible to automate the `xcrun notarytool store-credentials` command. As far as I understand, it would be implemented as a separate command, e.g. `beeware store-credentials`?

Storing credentials is something that probably crosses that threshold of "universal", warranting introducing a new common. Signing credentials are something you need in some form on every platform, so providing a convenient wrapper to those tools with a common interface would be highly desirable. 

However, before we commit to a specific design for this piece, I'd like to do a little more exploration of what parts of this process can be automated. How close to "our computer only has one button, and we press it for you at the factory" can we get when it comes to process(es) of managing signing credentials? If it can't be *fully* automated, how much can we simplify, or add a wizard-like interface around the steps required?

In terms of project procedures, I'd suggest treating this as a separate feature request.

**Comment by freakboy3742** [comment]
The comments in #690 have some useful notes about the notarisation process.
