### ISSUE TITLE
Ensure Windows applications present to the task manager correctly

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#368]
Windows applications currently present themselves to the Task Manager as "python.exe". The "Hello World" app should expose itself as "hello_world.exe" (or, ideally, as "Hello World"). This is because the process that actually runs is "python -m hello_world". 

We need to find a way to package the app so that the process that is started isn't *literally* python.exe. This may involve introducing a stub "starter" application; or, it may be possible to use a tool like [Windows Resource Hacker](http://www.angusj.com/resourcehacker/) to tweak the metadata of the python.exe that is packaged so that it *reports* as hello_world.

**Comment by voltagex** [comment]
Just making some notes, please let me know and I'll delete if there's too much here.


You may want to avoid modifying pythonw.exe here, it's a signed binary:

![image](https://user-images.githubusercontent.com/159567/80273116-e63add80-8712-11ea-9afc-47ddf28f1145.png)

Renaming the binary gets us some of the way there
![image](https://user-images.githubusercontent.com/159567/80273151-46318400-8713-11ea-925e-9031fd16585d.png)

![image](https://user-images.githubusercontent.com/159567/80273167-62352580-8713-11ea-94cc-809e5bb07e6a.png)

Interestingly, there's a parameter for the `start` command that sets the "window title", but I think we're already doing that by spawning a Form.
![Uploading image.png…]()

**Comment by voltagex** [comment]
The options for "solving" this that I can see:

* We rename the pythonw.exe binary before running Wix - this gets us an easy win, especially if people are running more than one Python application at once

* We have a stub application that embeds the python interpreter and launches the application - this seems like something that could have lots of unintentional side effects, but it'd be cool to see if it works. It's also probably overkill

* We change the resources - this definitely breaks the signature

![image](https://user-images.githubusercontent.com/159567/80273541-4d0dc600-8716-11ea-8ca1-84b5a6c7acdd.png)

**Comment by freakboy3742** [comment]
Renaming the .exe before running WiX is an entirely viable option; we can integrate that as part of the `package` step in the MSI backend.

Regarding the signature - we want to add in code signing anyway (#366); so if it's possible to re-signing the binary after tweaking metadata, that could fix the problem here, too.

The one upside to the stub application is that it lets us do other things like stdout redirection and splash screens. However, I agree that this isn't an option to take on lightly (unless we can produce a binary as part of the template, and do the same renaming/metadata trick, but on a binary under our control).

**Comment by voltagex** [comment]
#366 doesn't quite cover this - you can have a signed MSI that installs an unsigned application for example

**Comment by freakboy3742** [comment]
Understood. I'd guess that once we've got certificates set up, though, the actual signing process will relatively straightforward whether it's an MSI or an exe - so is there any reason not to sign both?

**Comment by voltagex** [comment]
You're right - we'd sign both.

**Comment by freakboy3742** [comment]
This will be addressed by #629 - closing on the basis that has a better description of the problem.
