### ISSUE TITLE
The WIX environment variable does not point to an install of the WiX Toolset.

### ISSUE THREAD

**Issue by hebersarmiento** [beeware/briefcase#373]
I keep trying to do a briefcase update and it is not letting me do it. briefcase dev is working but the update command keeps sending me error message:

The WIX environment variable does not point to an install of the WiX Toolset.
Current value: WindowsPath('.')

Now I have manually installed wix, but still no results.

**Comment by freakboy3742** [comment]
Interesting - is it just update that is failing? Do the build/run/package work?

Also - what version of Python are you using? If it's Python 3.5, that might explain the problem. It's still a bug, but that would at least explain the source of the problem and the likely fix.

**Comment by freakboy3742** [comment]
Also - have you restarted your terminal session after installing WiX? Briefcase will be looking for a `WIX` environment variable, which won't be set in any terminal session that was created *before* you installed WiX. If that's the case, you may find that starting a new terminal, activating the virtual environment, and running `briefcase update` will work.

**Comment by hebersarmiento** [comment]
You were right. All I had to do was to close the command window and restart again.
