### ISSUE TITLE
Use appdirs to determine download cache directory instead of hardcoding ~/.briefcase

### ISSUE THREAD

**Issue by dgelessus** [beeware/briefcase#374]
For reference, this has been mentioned before in #324.

For certain operations, Briefcase needs to download extra support files, which are cached on the filesystem to avoid redownloading them on every run. Currently, this cache is always located in the directory `.briefcase` in the user's home directory.

This is not a very good location for the cache. The name follows the old Unix convention of "dot files/directories in user's home directory", but this is no longer the preferred location for application data files on *any* current platform:

* Most modern Unix software follows the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (i. e. `~/.local`, `~/.config`, `~/.cache`) instead of using old-style dot files/directories.
* macOS has its own `~/Library` structure, which is preferred by Mac-native apps (although many non-Mac-specific tools use regular Unix conventions instead).
* Windows has `%HOME%\AppData` (name varies on older Windowses). On Windows, dot files/directories were never an acceptable convention - Windows is not a Unix, so files starting with a dot aren't considered hidden, meaning that Unix-style dot files/directories create visible clutter in the home directory.

In addition, all of these native locations have a standard structure that separates "temporary" files (like caches) from "permanent" files (like configs and other user-created data files). This difference is relevant for some automated processes, such as backup tools or Windows's roaming profiles, which only want to back up/synchronize actual user data and not auto-generated cache files. With old-style Unix dot files/directories there is no well-known convention like this, so Briefcase's cache is incorrectly recognized as important user data and will be backed up, roamed, etc.

Thankfully, there's a Python library called [appdirs](https://pypi.org/project/appdirs/) which provides convenient access to platform-native cache, config, data, etc. directories, so there's no need to worry about most of these details. You only need to choose the correct directory kind (config, user data, cache, etc.) depending on the situation, and `appdirs` will return the appropriate path for the current platform. So far, Briefcase seems to only use the `~/.briefcase` directory for caches, so it should be okay to use `appdirs.user_cache_dir` everywhere.

**Comment by freakboy3742** [comment]
Briefcase should definitely be a "well behaved" citizen wherever it runs; so adhering to platform standards like this would be a good idea.

It's mildly annoying that appdirs doesn't support pathlib (although [it has been discussed](ActiveState/appdirs#120)); but given the surface that we need to use is fairly small, it's not a big deal to wrap that usage.

Migration from old to new format is also a small concern; it's "only" cache directories, but given these caches can be large, and can have some useful configuration (like Android emulator configs), it would be desirable to migrate the old ~/.briefcase caches to the new location.

**Comment by dgelessus** [comment]
(Working link to the appdirs `pathlib` issue: ActiveState/appdirs#120)

**Comment by freakboy3742** [comment]
Unfortunately, it looks like we have to at least partially revert #777. Android tools don't like being in a path with spaces, and the default macOS AppDir has a space in it.
