### ISSUE TITLE
iOS simulator raises "Failed to create IXPromisedInMemoryData" installing app

### ISSUE THREAD

**Issue by zblouf** [beeware/briefcase#379]
On a fresh Xcode install [Version 11.3.1 (11C504)]
'briefcase run iOS' failed with the following message:

[traveltips] Starting app on an iPhone 8 running iOS iOS 13.3 (device UDID 10B93891-E299-4179-A4EB-DFC19540259F)
Booting iPhone 8 simulator running iOS iOS 13.3...
Opening iPhone 8 simulator running iOS iOS 13.3...
[traveltips] Uninstalling old app version...
[traveltips] Installing new app version...
An error was encountered processing the command (domain=IXErrorDomain, code=2):
Failed to create IXPromisedInMemoryData for icon for com.keith-magee.traveltips
Failed to create promise.
Unable to install new version of app traveltips.

After manually opening the TravelTips project in Xcode and running the app in Simulator from Xcode, 'briefcase run iOS' works fine.

**Comment by freakboy3742** [comment]
Thanks for the report. From our conversation online, this appears to be an annoying bug for which the fix isn't obvious, but "starting XCode" fixes it... 

We're unfortunately going to need to narrow down on this one slowly over time as others find it. If anyone is able to reliably reproduce this problem, that will be the key to fixing it.

**Comment by freakboy3742** [comment]
Closing on the basis that we haven't had any additional reports of this problem; it may have been addressed by an Xcode update.
