### ISSUE TITLE
User installable MSI packages?

### ISSUE THREAD

**Issue by tmontes** [beeware/briefcase#382]
The Mu Editor MSI file I managed to produce in the context of #381 requires administrative privileges for installation.

It would be very nice if `briefcase` had the option to produce user installable MSI files (assuming there is such a thing -- I suppose/hope so, given that lots of software is user installable, nowadays). If not, that could be considered a user-experience regression with respect to Mu users...

Which of user-install/system-install should be the default is a secondary thing for now.

Thoughts?

**Comment by tmontes** [comment]
PS: Related to #104?

**Comment by freakboy3742** [comment]
Completely agreed that it should be possible for Briefcase-generated MSIs to be user-installable - and they should probably be user-installable by default. There should probably be an *option* to force them to be system-install only, but that would be opt-in.

I haven't done anything deliberately to make the installer require a system install. The question for  research is to work out what WiX setting is making them system installable only. 

The WiX configuration file is generated from [this template](https://github.com/beeware/briefcase-windows-msi-template/).

**Comment by tmontes** [comment]
Sharing some potentially useful links on how this supported / can be implemented:

- https://docs.microsoft.com/en-us/archive/blogs/windows_installer_team/authoring-a-single-package-for-per-user-or-per-machine-installation-context-in-windows-7
- https://docs.microsoft.com/en-us/windows/win32/msi/single-package-authoring?redirectedfrom=MSDN

I skimmed through these and figured they’d be useful to support the change. In short: it certainly is possible and doesn’t seem difficult to implement with adjustments to the WIX input file.

**Comment by tmontes** [comment]
## Progress

* Managed to create a user-installable MSI package.
* Can be installed for all users (per-machine installation) via command line invokation.

## How I did it

1. Hand added the following XML snippet to the `.wxs` WiX file in my local template copy, right after the closing `/>` of the `<Package>` element, near the top:
    ```
    <Property Id="ALLUSERS" Value="2" />
    <Property Id="MSIINSTALLPERUSER" Value="1" />
    ```

2. Installing "normally" by double clicking the MSI file leads to a per-user installation, with no elevation prompt asking for privileges.

3. Installing for all users / per-machine works on the CLI with:
    ```
    C:\...> msiexec /i the-msi-file.msi MSIINSTALLPERUSER=""
    ```
    In this case, the system privilege elevation prompt is displayed and, after authentication the package is successfully installed.

Quick preliminary experiments show that, In both cases, the start menu entry is put in place and launching the application works.

## Next

Will explore how to add a UI installer "thing" -- for the lack of a better name -- that supports interactive per-user/per-machine target selection, at install time.

Thoughts:
* No idea if it will be trivial or horribly difficult.
* Side-concerned with installer localization, wondering if what's in place now is English-only or if it automatically adjusts to the user's localization preferences.
* Wondering how the two things relate: adding UI to installer vs. its localization.

**Comment by tmontes** [comment]
## Progress

Invested 30 minutes in exploring how the per-user/per-machine UI selection could be implemented. Found out:

* Non-trivial for someone like me, with little WiX experience and ~zero MSI innards knowledge.
* [This guide](https://www.firegiant.com/wix/tutorial/) seems to have all (most?) of what is needed to accomplish that, including apparent answers to the localization concerns I mentioned.
* Will need more time/energy than what I have now. ;)

## Question

Would a partial solution, like the one I mentioned in my previous comment, be useful/acceptable as a PR towards [the briefcase-windows-msi-template](https://github.com/beeware/briefcase-windows-msi-template/)s `briefcase` uses?

The result would be:
* GUI based installation per-user.
* CLI based installation can be per-user / per-machine.

Those would be matched with a `briefcase` doc PR of sorts, explaining that.

I see this as a step in the right direction by itself and am happy to submit the PR set needed to bring this in, if acceptable at this stage. :)

**Comment by freakboy3742** [comment]
Your "per-user by GUI, all users by command line" approach sounds like a completely acceptable option to me. It's a significant improvement on the behavior right now, and the other option exists should it be needed.

I'd be completley comfortable with adding an "install for all users" checkbox to be raised as an issue that can be addressed by future work (if anyone is motivated enough to pursue it).

**Comment by tmontes** [comment]
Thanks for the openness to such an intermediate solution.

PRs on their way...

**Comment by tmontes** [comment]
Submitted these PRs to [briefcase-windows-msi-template](https://github.com/beeware/briefcase-windows-msi-template):

* https://github.com/beeware/briefcase-windows-msi-template/pull/1
* https://github.com/beeware/briefcase-windows-msi-template/pull/2
* https://github.com/beeware/briefcase-windows-msi-template/pull/3
* https://github.com/beeware/briefcase-windows-msi-template/pull/4
* https://github.com/beeware/briefcase-windows-msi-template/pull/5

And this briefcase document update PR:

* #387

**Comment by freakboy3742** [comment]
Confirming: I've merged the initial changes to make "user-install" the default. Adding an "install for all users" checkbox into the installer is the outstanding portion of this issue.
