### ISSUE TITLE
Use a managed install of WiX on Windows

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#389]
The Windows MSI backend uses WiX to compile the MSI installer. 

The existence of WiX is detected based on the existence of a WiX environment variable; if WiX isn't present, the user is provided an error message that tells them where to download WiX. Installation is then left up to the user.

However, it should be possible for Briefcase to manage the WiX install in the same way that Java is managed for the Android build, by using the .ZIP installer rather than the .MSI installer - that is:
* Look for the environment variable; if it is present and points at an install of WiX, use it.
* If WiX isn't defined, download the .zip installer from the WiX website, and unpack it in the `~/.briefcase/tools` directory, and use that version.

**Comment by MisterAwesome23** [comment]
Hey. I just completed (the well documented) tutorial and got my windows app running 

>However, it should be possible for Briefcase to manage the WiX install

and understand this WIX issue and would like to work on this. 
Also, waiting eagerly for Android, IOS and Web additions to the tutorial.

**Comment by freakboy3742** [comment]
@MisterAwesome23 Awesome! Go right ahead - I look forward to seeing a PR! 

You may find it easiest to add a `src/integrations/wix.py` module to coordinate verifying/downloading WiX. The Java and Android SDK integrations in the same directory should give an indication of the sort of code that is required. (And don't forget to add tests in `tests/integrations`!)

As for iOS version of the tutorial - that is already there in place - iOS is a fully supported platform. Android should be added shortly; Web is lagging behind, but I'm hoping to have something there before long.

**Comment by freakboy3742** [comment]
Oh - and if you have any questions, or need any pointers, let us know; either as a comment on this ticket, or in our [chat room](https://gitter.im/beeware/general)

**Comment by MisterAwesome23** [comment]
Thank you for the clarification.

> The Java and Android SDK integrations in the same directory should give an indication of the sort of code that is required. 

The Java one helped a lot and I have a lot more clarity now.

Since I have not patched something like this before we might need a few extra iterations, but to structure it the integration wix.py should-
1. Check if there is a path variable with path pointing to Wix installation.
2. If not, throw a message saying "Briefcase was unable to interpret and will continue by downloading and using its own Wix installation and point to it.

Also, I have joined the Gitter chatroom (@MisterAwesome23), thanks for inviting : )

**Comment by freakboy3742** [comment]
It's a *little* more complex than that; the full decision tree is something like:

* Check if there's a WIX environment variable
* If there is, and there's are valid WiX binaries, use that path
* If there is, and we can be certain that there *aren't* valid WiX binaries, raise an error
* If there is, and it's not possible to determine if the WiX binaries are valid, output a warning and use the path
* If there isn't, determine if WiX has already been downloaded into the briefcase tools folder
* If it has, use that path
* If it hasn't, download the WiX ZIP file from the WiX website, unpack it, and use that path.
