### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by moridius** [beeware/briefcase#390]
```
$ python --version
Python 3.8.2
$ briefcase build android
Found Python version 3.8. Android packaging currently
requires Python 3.7.
```

Is there a good reason why Python 3.8 is not supported or is it just a whitelist that has to be edited?

**Comment by freakboy3742** [comment]
There is - we haven't completed porting the support package for Python 3.8 yet. Our Android support is under active development right now, thanks to a grant from the PSF; and porting the support package to Python 3.5, 3.6 and 3.8 is on our TODO list.

I'm going to close this ticket on the grounds that this behavior is "working as designed" for the moment.
