### ISSUE TITLE
Re-installing an Android app sometimes fails

### ISSUE THREAD

**Issue by paulproteus** [beeware/briefcase#395]
@freakboy3742 ran into an issue where, if the device is clean, it starts fine.

However, if the app already exists on the device, it fails:

```
Unable to install APK /Users/rkm/projects/beeware/demo/traveltips/android/Travel Tips/app/build/outputs/apk/debug/app-debug.apk on KAPHN4G9AA1513
```

I can't reproduce this yet, but I'd like to get to the bottom of it.

**Comment by freakboy3742** [comment]
Some more details:
* I'm running TravelTips.
* `briefcase run android` first run builds and starts the app fine
* Second run (no rebuild - just run) fails with the error in the original report.
* Looking at the task list, it looks like the app has been partially stopped: it's still on the task list, but if you pick it from the task list it boots again.
* If you manually kill the app, and re-run; the same error occurs.
* If you manually *delete* the app, and re-run, it re-installs and runs fine.
* The whole process works fine on the emulator. It only fails on my physical device (a Kogan Agora 9)

**Comment by sarthaksharma058439** [comment]
Check this video .....he make calculator in beeware and deploy to android device

https://youtu.be/RllR6FRdG6w
