### ISSUE TITLE
Error message is misleading if XCode is installed by Cmdline tools are active

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#397]
Originally reported as a [PR on beeware](https://github.com/beeware/beeware/pull/49)

I was following the beeware tutorial and I got the following error

```
(beeware-venv) $ briefcase create iOS
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  Xcode is not installed.

  You should be shown a dialog prompting you to install Xcode and the
  command line tools. Select "Get Xcode" to install Xcode from the app store.
  You can install Xcode from the macOS App Store.
  Re-run Briefcase once that installation is complete.
```

It took me a while to figure out how to solve this because I already had Xcode installed.

The solution was:
```
(beeware-venv) $ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

The problem is that the XCode *is* installed, but the command line tools are currently the active install. 

The error message needs to differentiate between:
* XCode command line tools are installed, but XCode isn't installed
* XCode command line tools *and* XCode are installed, but command line tools are active.

and present an appropriate error message in both cases.

**Comment by MoetheNeuron** [comment]
Hi @freakboy3742,

I would really like to offer help here. As I am completely new to contributing to open source projects, I might need some guidance down the road :-).

So, I did some research after checking the code of xcode.py. It seems to me, it is safe to make the assumption that `$ xcodebuild -version`, invoked when checking Xcode version in `ensure_xcode_is_installed()`, should only fail when the active instance isn't Xcode (at this point, whether Xcode exists has been already checked before by `path().exists()`). Do you think, it is a safe assumption to make? I could be missing something here, so I thought it's safer to check first.

Last thing, it says in the docstring of `verify_xcode_install()` that it checks whether iOS simulator is installed; however, I think this isn't -yet- part of the function logic, right?

Thanks!

**Comment by freakboy3742** [comment]
> I would really like to offer help here. As I am completely new to contributing to open source projects, I might need some guidance down the road :-).

No problem! We're here to provide us much help as we can!

> So, I did some research after checking the code of xcode.py. It seems to me, it is safe to make the assumption that `$ xcodebuild -version`, invoked when checking Xcode version in `ensure_xcode_is_installed()`, should only fail when the active instance isn't Xcode (at this point, whether Xcode exists has been already checked before by `path().exists()`). Do you think, it is a safe assumption to make? I could be missing something here, so I thought it's safer to check first.

I believe this is correct. The error message that was reported can only occur if the call to `xcodebuild --version` returns a non-zero return code. The trick is to differentiate between the "`xcodebuild --version` failed in some way" error and the "`xcodebuild --version` told you that  it's not a full Xcode build" error. This *might* be possible using the return code of the call to xcodebuild - you'll need to verify that.

> Last thing, it says in the docstring of `verify_xcode_install()` that it checks whether iOS simulator is installed; however, I think this isn't -yet- part of the function logic, right?

You're correct - this looks like an overenthusiastic comment. I think it's safe to delete the comment; a full Xcode build *should* always contain a simulator.
