### ISSUE TITLE
Ubuntu missing dependencies (libcairo2-dev, libgirepository1.0-dev)

### ISSUE THREAD

**Issue by massenz** [beeware/briefcase#398]
Following the tutorial, it fails to mention a couple of dependencies that need installing for Ubuntu, or the `briefcase dev` step fails.

The (not particularly helpful) error is:
```
    Package cairo was not found in the pkg-config search path.
    Perhaps you should add the directory containing `cairo.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'cairo' found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
```
even though the `cairo` package is already installed (Ubuntu 20.4).

As it took some researching to figure out what was what, I thought I'd report it here, and maybe you may want to update the `Linux` section of the tutorial:
```
sudo apt-get install libcairo2-dev libgirepository1.0-dev
```

**Comment by freakboy3742** [comment]
Those exact dependencies (and others) are listed [in the "Install dependencies" step of the BeeWare tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-0.html#install-dependencies).

Can you clarify which tutorial you were following to get this error?

**Comment by massenz** [comment]
LoL - you are absolutely correct!
My bad, I saw the first part of the command, assumed it was just to install Python 3 and just skipped over.

Apologies for the confusion.

**Comment by freakboy3742** [comment]
No problem at all! 

If you've got any suggestions for how we could restructure or reword that section to help others avoid making the same error, we're open to suggestions.
