### ISSUE TITLE
expose dmg "size" (or other) settings for build_dmg?

### ISSUE THREAD

**Issue by tlambert03** [beeware/briefcase#406]
when building on macOS, I am continually getting a "no space left" error during the build phase:
```
No space left on device: '/Applications' -> '/Volumes/napari 0.3.0/Applications'
```

I can fix it if I manually increase the "`size`" key in the `dmg_settings` variable here:
https://github.com/beeware/briefcase/blob/ed4931d0a0f2daa0b6277c69d2d9d5bf8ebb9ae1/src/briefcase/platforms/macOS/dmg.py#L126-L130

but there doesn't seem to be any way to do that without manually editing briefcase source... (and dmgbuild doesn't take any environment variables overrides).  Suggestions?

**Comment by freakboy3742** [comment]
Thanks for the report! I haven't seen this error myself - I wasn't even aware the `size` option existed. 

My read of the [dmgbuild docs](https://dmgbuild.readthedocs.io/en/latest/settings.html#size) suggests that dmgbuild should be determining "an appropriate size" - so I'm interested in what exactly is different about your app that is causing problems for dmgbuild. It might even be a bug in dmgbuild itself.

Worst case, we will need to expose the ability to manually set the dmg size - but I'd rather avoid that if we can.

**Comment by tlambert03** [comment]
Yeah, I agree this seems to be a bug in the “autodetermining” of size in dmgbuild, and I haven’t yet figured out what it is about our app that breaks it (but I have seen it on multiple different computers now).  Let me dig into their source and see what I cam learn

**Comment by GenevieveBuckley** [comment]
I see this happen on my computer as well. It doesn't seem to have had any negative effect on our packaged app, as far as I can tell. It does make me uneasy that a problem might crop up later on though.

**Comment by freakboy3742** [comment]
Oh - wait - you're saying it's not a critical error that stops the DMG from building, just a (admittedly disturbing) warning message? 

Any possibility either of you can narrow down a "minimal reproduction case" for this?

**Comment by tlambert03** [comment]
For me the app packaging failed... I plan to look at the size calculation before working on a minimal reproduction

**Comment by tlambert03** [comment]
ok, found the issue:  in [this line](https://github.com/al45tair/dmgbuild/blob/fc1d8014e6c373c0fefc8fe023e73f805e10ead9/dmgbuild/core.py#L401) of `dmgbuild.core`, when it converts `total_size` to a string version with the "K" suffix, it needs to divide by 1000 instead of 1024,  this works:
```
total_size = str(max(total_size / 1000, 1000)) + 'K'
```
(otherwise the size is undercalculated by just a few megabytes in a 1.2GB image)
will open an issue there.

**Comment by tlambert03** [comment]
PR at dmgbuild: https://github.com/al45tair/dmgbuild/pull/18

**Comment by tlambert03** [comment]
PR is merged so this should be fixed with the next release!

**Comment by freakboy3742** [comment]
Nicely done! Congrats on finding and fixing that one upstream!
