### ISSUE TITLE
Windows bundled python.exe ignoring PYTHONPATH environment variable

### ISSUE THREAD

**Issue by tlambert03** [beeware/briefcase#418]
In my bundled app, I'm trying to run the bundled python.exe in a subprocess, as a (toy) example:
```python
import sys, subprocess
subprocess.run([sys.executable, '-c', 'import sys; print(sys.path)'])
```
I'm finding that, on Windows (but not on Mac), the bundled python.exe is ignoring environment variables... even if I run it directly on the cmd shell (not as a python subprocess):

```sh
# regular python
> where python
C:\..miniconda3\python.exe
> python -c "import sys; print(sys.path)"
# ... outputs the current path

# bundled python.exe
> C:\Users\<username>\AppData\Local\Programs\<app_name>\python\python.exe -c "import sys; print(sys.path)"
# ... outputs the expected path for the bundled app, including <app_name>\app & app_packages

# good so far... but if I add something to PYTHONPATH:
> set PYTHONPATH=C:\some\new\path
# it shows up with the miniconda python executables (and others I tried):
> python -c "import sys; print(sys.path)"
# C:\some\new\path is in there...
# but some\new\path is NOT present in sys.path from the bundled python.exe
```

if I do that some experiment  (`export PYTHONPATH=/some/new/path`) on mac/linux, the bundled python.exe picks up the variable.

Any idea why this would be and whether there's a workaround?

**Comment by tlambert03** [comment]
actually, to slightly refine the issue, it's not that environment variables are being ignored: If I repeat the example above using `import os; print(os.environ)`, then it's clear that the bundled exe is also seeing the `PYTHONPATH` environment variable... but it looks like it's being clobbered/ignored:  i.e. `sys.path` is untouchable on windows.

**Comment by tlambert03** [comment]
agh ... I should have dug deeper.  I see now that this is due to the `._pth` file included in the windows bundle:

https://github.com/beeware/briefcase/blob/0accfc9837219edc2e5f59dfbae21e4d144e75eb/src/briefcase/platforms/windows/msi.py#L132-L145

I can modify that after `briefcase create` to meet my needs... which is to add `.\\Lib\\site-packages` to that file.  (For context: we are bundling pip to enable the user to install "plugins" into the bundle after packaging).  You can close this comment if you'd like, unless you think it's worth including `.\\Lib\\site-packages` in the `_pth` file (I'm aware of the delicateness of bundling pip, and that you may not want to add that path)

**Comment by freakboy3742** [comment]
FWIW, I don't believe that briefcase apps should come with `pip` support out of the box (if only because it's a potential attack vector) - but you're not the first person to request it, either. 

I think this is something we *should* support; however, there are some interesting design questions to answer. I've openedSupporting `pip` in an opt-in basis is definitely something that we *should* support. 

To that
