### ISSUE TITLE
Windows Store version of pip is incompatible with Briefcase

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#441]
Reported via Gitter, using Windows 10 x64, pip 20.1.1, and Python 3.7 x64 installed via the Window Store.

Running `briefcase create` generates the error:

    ERROR: Can not combine '--user' and '--target'
    Unable to install dependencies. This may be because one of your dependencies is invalid, or because pip was unable to connect to the PyPI server.

This is caused by the request to install app dependencies. When Briefcase installs dependencies (`CreateCommand.install_app_dependencies()`), it internally makes a call to:

    python -m pip install --upgrade --target <app location> <package list>

With a "vanilla" pip, this works fine. However, in order to accomodate per-user site-packages, the Windows Store version of `pip` injects a `--user` argument. This argument is incompatible with `--target`, raising the error.

This *doesn't* occur with the official Python installer, as `pip` doesn't use the implied `--user` argument.

**Comment by zooba** [comment]
This is https://github.com/pypa/pip/issues/4390 again, so not specific to Windows or the Store install (I only skimmed, but it looks like _all_ the other complaints on the pip thread are to do with Linux distros adding default pip configuration).

The `--system` workaround doesn't apply here. That's part of a Debian(?) patch.

**Comment by zooba** [comment]
FYI, there's an (undocumented) `--no-user` option that you should be able to safely use whenever you use `--target`.
