### ISSUE TITLE
Error during briefcase run android, emulator failing to start.

### ISSUE THREAD

**Issue by amgfleh** [beeware/briefcase#444]
I was following tutorial 5 and when it finished download I got the following error after running `briefcase run android`
![2020-07-07 10_21_08-Command Prompt](https://user-images.githubusercontent.com/66208635/86713380-a5791200-c03b-11ea-821f-8d51aae3a3ed.jpg)

I cannot manually start the emulator either. emulator-crash-service.exe tells me I am missing the following dll files: qt5coreandroidemu, qt5widgetsandroidemu, qt5guiandroidemu, which I cannot file online.
Please help!

**Comment by freakboy3742** [comment]
Thanks for the report - and sorry to hear you've had problems!

It looks like your android tools are returning content that wasn't expected. Can I get you to run the following:
```
c:\users\amogh\.briefcase\tools\android_sdk\platform-tools\adb devices -l
```
and report what is output?

Also; can you let us know if you've ever done any Android devlopment on this machine previously? Have you ever installed Android Studio, or done any other Android development on this computer?

**Comment by amgfleh** [comment]
Hey!
I ran and got the following output:
![2020-07-07 10_51_55-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/66208635/86717667-00ad0380-c040-11ea-8d24-d292f5d10e7a.jpg)

No, I have not done any android development before this, nor installed Android Studio.

**Comment by freakboy3742** [comment]
Ok - it may be blank, but I suspect there may be some whitespace there that is causing confusion. Can I get you to run the following from a Python prompt:
```
import subprocess
print(self.command.subprocess.check_output(
    ["c:\users\amogh\.briefcase\tools\android_sdk\platform-tools\adb", "devices", "-l"],
    universal_newlines=True,
    stderr=subprocess.STDOUT,
).strip().split('\n'))
```

**Comment by amgfleh** [comment]
![2020-07-07 11_12_46-Python 3 6 8 Shell](https://user-images.githubusercontent.com/66208635/86720774-f9d3c000-c042-11ea-84af-e431c3ad6dbb.jpg)
I get the following errors? Did I do it wrong?

**Comment by freakboy3742** [comment]
Aaargh! Sorry - that's my fault: I copied and pasted something and didn't check it fully. Try this instead:
```
import subprocess
print(subprocess.check_output(
    ["c:\users\amogh\.briefcase\tools\android_sdk\platform-tools\adb", "devices", "-l"],
    universal_newlines=True,
    stderr=subprocess.STDOUT,
).strip().split('\n'))
```

**Comment by amgfleh** [comment]
That's alright!
I got this:

![2020-07-07 11_22_14-Python 3 6 8 Shell](https://user-images.githubusercontent.com/66208635/86722207-508dc980-c044-11ea-96bf-14f759b22b08.jpg)

**Comment by freakboy3742** [comment]
Ok - that's really weird. If that's all the output you're getting, I can't explain how you got the error you've described (or even how 

If you re-run `briefcase run android` - do you still get the same error?

**Comment by amgfleh** [comment]
No, like I've shown in the original screenshot, it gives me an option to run the emulator but i get "Android emulator was unable to start!"
Nor does it start manually. When I checked emulator-crash-service.exe, it tells me I am missing the following dll files: qt5coreandroidemu, qt5widgetsandroidemu, qt5guiandroidemu, which I cannot find online.
I deleted the emulator folder and ran `briefcase run android` again to redownload the files but no ValueError this time. Emulator still didn't start.

**Comment by freakboy3742** [comment]
Ok - that's not what your original screenshot shows, though - it shows the "Create a new emulator" option, but no *selectable* emulators. Is there more detail that isn't in your screenshot?

(Also as a general tip: It's a lot more helpful to use text, rather than images when copying console output - text is searchable, and will usually include special characters like tabs, whereas screenshots hide that detail. It also means your console output can run much longer than a displayed page. If you're able to copy and paste the content, rather than images, it's really helpful to do so)

**Comment by amgfleh** [comment]
After I got the "Create a new emulator" option, I tried to go through with to see if it worked but while I got the default beePhone as an option it doesn't start.

(My bad! I will keep that in mind the next time. Sorry)

**Comment by freakboy3742** [comment]
Ok - so you're saying that you *have* created a beePhone emuator, but it won't start; but you're no longer getting the original "ValueError: not enough values to unpack" error from the original screenshot?

Can you show us what you're seeing when you try to start the beePhone emulator? 

If you create another *new* emulator - does that one start?

Next; lets see if we can convince the Android tools to update themselves; maybe that will fix the missing pieces. From a command prompt, run:
```
set JAVA_HOME=c:\users\amogh\.briefcase\tools\java
c:\users\amogh\.briefcase\tools\android_sdk\tools\bin\sdkmanager "platforms;android-28" "system-images;android-28;default;x86" "emulator" "platform-tools"
```

**Comment by amgfleh** [comment]
Yes, I did not get the original error again anymore.
I'm still trying to run the emulator and it's not working. A new emulator can be created but it's the same thing.

`
(beeware-venv) D:\Work\App Dev\beeware-trial\helloworld>briefcase run android

Select device:

  1) @beePhone (emulator)
  2) @beePhone2 (emulator)
  3) Create a new Android emulator

> 1

In future, you can specify this device by running:

    briefcase run android -d @beePhone


Starting emulator beePhone...

Waiting for emulator to start.....
Android emulator was unable to start!

Try starting the emulator manually by running:

    C:\Users\Amogh\.briefcase\tools\android_sdk\emulator\emulator.exe @beePhon
-dns-server 8.8.8.8

Resolve any problems you discover, then try running your app again. You may
find this page helpful in diagnosing emulator problems.

    https://developer.android.com/studio/run/emulator-acceleration#accel-vm


(beeware-venv) D:\Work\App Dev\beeware-trial\helloworld>
`

I ran the update and got the following:

`(beeware-venv) D:\Work\App Dev\beeware-trial\helloworld>set JAVA_HOME=c:\users\a
mogh\.briefcase\tools\java

(beeware-venv) D:\Work\App Dev\beeware-trial\helloworld>c:\users\amogh\.briefcas
e\tools\android_sdk\tools\bin\sdkmanager "platforms;android-28" "system-images;a
ndroid-28;default;x86" "emulator" "platform-tools"
Loading package information...
Loading local repository...
[                                       ] 3% Loading local repository...
[                                       ] 3% Fetch remote repository...
[                                       ] 3% Fetch remote repository...
[=                                      ] 3% Fetch remote repository...
[=                                      ] 4% Fetch remote repository...
[=                                      ] 4% Fetch remote repository...
[=                                      ] 4% Fetch remote repository...
[=                                      ] 4% Fetch remote repository...
[=                                      ] 5% Fetch remote repository...
[=                                      ] 5% Fetch remote repository...
[=                                      ] 5% Fetch remote repository...
[=                                      ] 5% Fetch remote repository...
[=                                      ] 5% Fetch remote repository...
[=                                      ] 5% Fetch remote repository...
[==                                     ] 5% Fetch remote repository...
[==                                     ] 5% Fetch remote repository...
[==                                     ] 5% Fetch remote repository...
[==                                     ] 5% Fetch remote repository...
[==                                     ] 5% Fetch remote repository...
[==                                     ] 5% Fetch remote repository...
[==                                     ] 5% Fetch remote repository...
[==                                     ] 6% Fetch remote repository...
[==                                     ] 6% Fetch remote repository...
[==                                     ] 6% Fetch remote repository...
[==                                     ] 6% Fetch remote repository...
[==                                     ] 6% Fetch remote repository...

Warning: File C:\Users\Amogh\.android\repositories.cfg could not be loaded.
[==                                     ] 6% Fetch remote repository...
[==                                     ] 6% Computing updates...
[===                                    ] 8% Computing updates...
[===                                    ] 8% Computing updates...
[===                                    ] 10% Computing updates...
[=======================================] 100% Computing updates...

(beeware-venv) D:\Work\App Dev\beeware-trial\helloworld>briefcase run android

Select device:

  1) @beePhone (emulator)
  2) @beePhone2 (emulator)
  3) @beePhone3 (emulator)
  4) Create a new Android emulator

> 1

In future, you can specify this device by running:

    briefcase run android -d @beePhone


Starting emulator beePhone...

Waiting for emulator to start.....
Android emulator was unable to start!

Try starting the emulator manually by running:

    C:\Users\Amogh\.briefcase\tools\android_sdk\emulator\emulator.exe @beePhone
-dns-server 8.8.8.8

Resolve any problems you discover, then try running your app again. You may
find this page helpful in diagnosing emulator problems.

    https://developer.android.com/studio/run/emulator-acceleration#accel-vm


(beeware-venv) D:\Work\App Dev\beeware-trial\helloworld>briefcase run android

Select device:

  1) @beePhone (emulator)
  2) @beePhone2 (emulator)
  3) @beePhone3 (emulator)
  4) Create a new Android emulator

> 4

You need to select a name for your new emulator. This is an identifier that
can be used to start the emulator in future. It should follow the same naming
conventions as a Python package (i.e., it may only contain letters, numbers,
hyphens and underscores). If you don't provide a name, Briefcase will use the
a default name 'beePhone4'.


Emulator name [beePhone4]:

Creating Android emulator beePhone4...

Device skin 'pixel_3a' already exists
Adding extra device configuration...

Android emulator 'beePhone4' created.

In future, you can specify this device by running:

    briefcase run android -d @beePhone4

Starting emulator beePhone4...

Waiting for emulator to start......
Android emulator was unable to start!

Try starting the emulator manually by running:

    C:\Users\Amogh\.briefcase\tools\android_sdk\emulator\emulator.exe @beePhone4
 -dns-server 8.8.8.8

Resolve any problems you discover, then try running your app again. You may
find this page helpful in diagnosing emulator problems.

    https://developer.android.com/studio/run/emulator-acceleration#accel-vm


(beeware-venv) D:\Work\App Dev\beeware-trial\helloworld>
`

**Comment by freakboy3742** [comment]
Ok - so It's starting to look like there's a problem with your computer running the Android emulator *at all*. 

And just to confirm - this is a native Windows machine, not a VM or anything like that, right?

Have you gone to the link that has been provided and followed the diagnostic steps there?

**Comment by amgfleh** [comment]
Yes,  its a native machine, not a VM.
But since it seems like its not a BeeWare /Briefcase problem, I will close it.
Thanks!

**Comment by ibrahimhalici** [comment]
hi there. i dont know if this a good place to ask. but i have encountered an error like above.

briefcase run android

Select device:

  1) @beePhone (emulator)
  2) @deee (emulator)
  3) Create a new Android emulator

> 1

In future, you can specify this device by running:

    briefcase run android -d @beePhone


Starting emulator beePhone...

Waiting for emulator to start.....
Android emulator was unable to start!

Try starting the emulator manually by running:

    C:\Users\ibrahim.halici\.briefcase\tools\android_sdk\emulator\emulator.exe @beePhone -dns-server 8.8.8.8

Resolve any problems you discover, then try running your app again. You may
find this page helpful in diagnosing emulator problems.

    https://developer.android.com/studio/run/emulator-acceleration#accel-vm



C:\Users\ibrahim.halici\.briefcase\tools\andr
oid_sdk\emulator\emulator.exe '@beePhone'
INFO    | Android emulator version 31.2.8.0 (build_id 8143646) (CL:N/A)
ERROR   | x86 emulation currently requires hardware acceleration!
CPU acceleration status: HAXM is not installed on this machine
More info on configuring VM acceleration on Windows:
https://developer.android.com/studio/run/emulator-acceleration#vm-windows
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.


then i checked the website attached. i need to install intel haxm. but the link refers to use sdkmanager. is there a sdkmanager that i can use for this problem ?

**Comment by AetherUnbound** [comment]
I'm also encountering this issue on Ubuntu 22.04 😮 @amgfleh were you able to find a resolution for this?

**Comment by AetherUnbound** [comment]
Update: It turns out this was because the Android device was set to "No data transfer", I changed it to "File transfer / Android Auto" and it worked perfectly!
