### ISSUE TITLE
I have tried the first HelloWorld sample app in briefcase but the output window keep on loading. 

### ISSUE THREAD

**Issue by kravikumars444** [beeware/briefcase#448]
Output App keeps on loading and says "Not Responding". I kept the system idle for more than 20 minutes but it's loading still.

![image](https://user-images.githubusercontent.com/39218009/87219915-e72bf480-c37c-11ea-8bc3-20375e980aa7.png)

Note: No error on the cmd(console) everything is working fine.

**Comment by freakboy3742** [comment]
You're on Windows; and although you don't say this, I'm going to guess you're using Python 3.8. This is [documented in the tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-0.html) - The libraries we need to work on Windows don't currently work with Python 3.8.

Closing on that basis. If you're *not* on Python 3.8, let us know and I'll reopen the ticket.

**Comment by kravikumars444** [comment]
I'm working on Python 3.7. let me know if you need any further information.

**Comment by freakboy3742** [comment]
Are you 100% sure about that? Because the behaviour you're describing is 100% consistent with a (now resolved) known behavior on Python 3.8, but not on Python 3.7.

**Comment by kravikumars444** [comment]
Yes, I'm on 3.7.6 - Today it's working fine, I don't know why it is working now. Thanks,
