### ISSUE TITLE
can't use Pillow with briefcase 0.3.3 on linux

### ISSUE THREAD

**Issue by jgirardet** [beeware/briefcase#458]
**Describe the bug**
running an app with pillow crashes with the following error
```
[helloworld] Starting app...

Traceback (most recent call last):
  File "/tmp/.mount_Hello_dZoYVA/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_Hello_dZoYVA/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_Hello_dZoYVA/usr/app/helloworld/__main__.py", line 4, in <module>
    main()
  File "/tmp/.mount_Hello_dZoYVA/usr/app/helloworld/app.py", line 9, in main
    from PIL import Image
  File "/tmp/.mount_Hello_dZoYVA/usr/app_packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: libxcb-2dfad6c3.so.1.1.0: ELF load command address/offset not properly aligned
```

**To Reproduce**
1. clone https://github.com/jgirardet/briefpil
2. create env, activate, pip install briefcase
3. briefcase create && briefcase build && briefcase run

**Environment:**
 - Operating System: ubuntu 19.10
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.3
   - Pillow: 7.2

**Additional context**
adding  line 184 https://github.com/beeware/briefcase/blob/2259199dbe8b3049a92eccd27a7b94e6e6e558e0/src/briefcase/platforms/linux/appimage.py#L184:
```
so_folders.remove(self.appdir_path(app) / "usr/app_packages/PIL")
```
fixes the crash, I have no clear idea why.
full log: [scratch_1.txt](https://github.com/beeware/briefcase/files/4960467/scratch_1.txt)

**Comment by freakboy3742** [comment]
Thanks for the report. The error suggests that the library adjustment process implemented by AppImage isn't working correctly. 

I'm a little surprised that removing the path from so_folders fixes the problem - that suggests that the contents of the app_packages folder may not need to be relocated. I'm not sure why that would be, though.

**Comment by freakboy3742** [comment]
A random thought - Pillow is installed from a manylinux1 wheel; I wonder if manylinux wheels are already delocalised in some way (or have been processed in a way that is incompatible with the relocation mechanism that AppImage is using). If that's the case, we'll need to find a way to differentiate between so files installed from manylinux wheels, and ones installed and compiled from source, and only relocate so files that are *not* from a manylinux wheel.

**Comment by jgirardet** [comment]
not sure pyside2 and kivy are also manylinux wheels, and there is no problem with them

**Comment by gambhiro** [comment]
Perhaps it helps to debug, I ran into the same `offset not properly aligned` error in the AppImage, with the `libtiff` library for Pillow 9.0.0, using briefcase 0.3.5.

[Going back](https://github.com/beeware/briefcase/issues/618#issuecomment-1019269414) to Pillow 7.2.0 solved it. Perhaps differences between the old and new Pillow version offer a clue as to what goes wrong.

**Comment by freakboy3742** [comment]
I'm going to close this issue to consolidate the general problem of "Linux AppImage deployment has problems" under a single issue (#718).
