### ISSUE TITLE
On Android, if your app is called `x.y.switch`, it fails to build

### ISSUE THREAD

**Issue by paulproteus** [beeware/briefcase#460]
**Describe the bug**

If you call your app `switch` (or another Java reserved word), you will be unable to build it on Android.

**To Reproduce**

You can reproduce by creating an app whose module_name is `switch`. For example, you can use a Toga demo app.

1. Download the toga source code, then `cd` into `examples/switch`
2. Run `briefcase create android && briefcase build android`
3. Wait for the build to complete (about 60 seconds if you've used Briefcase on this system to make Android apps)
4. See an error:

```
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Package 'org.beeware.switch' from AndroidManifest.xml is not a valid Java package name as 'switch' is a Java keyword.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
15 actionable tasks: 15 executed

Error while building project.
```

**Expected behavior**

The app should build or briefcase should print an error at the `briefcase new` phase, or briefcase should print an error before trying to run `briefcase create android`.

**Environment:**
 - Operating System: macOS 10.15
 - Python version: 3.7
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: current git (0.3.0pre21)

**Additional context**

**Comment by freakboy3742** [comment]
Agreed that this is an edge case we need to catch - probably very early in the process.

App names will also be restricted by Python reserved words - you couldn't name your app "def" or "import" for example.

We also need to validate the parts of the bundle ID - `org.switch.goodname` will also be a problem on Android.

**Comment by sarthaksharma058439** [comment]
Check this video .....he make calculator in beeware and deploy to android device

https://youtu.be/RllR6FRdG6w

**Comment by junefish** [comment]
Hello!  I would like to try fixing this.

**Comment by freakboy3742** [comment]
@junefish By all means - go ahead! If you need any pointers or suggestions, let us know!

**Comment by KabirAcharya** [comment]
I believe my fork should fix this issue.
