### ISSUE TITLE
Punctuation allowed in Briefcase but not with Gradle

### ISSUE THREAD

**Issue by ProgrammAbel** [beeware/briefcase#462]
**Describe the bug**
When creating an application, you are allowed to use punctuation for project names. However, when building for Android, the usage of `/, \, :, <, >, ", ?, *, |` are prohibited with Gradle.

**To Reproduce**
1. Create an application with the name containing any one of the above characters.
2. Build for Android.

**Expected behavior**
For the application to build successfully.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/51785314/89106449-e0474d80-d421-11ea-842e-95ad672eda8c.png)

**Environment:**
 - Operating System: Linux 5.7.10-arch1-1
 - Python version:  Python 3.8.4
 - Software versions:
   - Briefcase: 0.3.3

**Additional context**
This is somewhat related to #460.

**Comment by freakboy3742** [comment]
Which "name" are you referring to - the "app name" or the "formal name"? The app name should be the only one that has restrictions; `briefcase new` and `briefcase create` both validates that your app name is PEP508 compliant (which rejects most 'special' characters). The Formal name should only be used for display purposes, and *shouldn't* be anywhere that is "special character sensitive".

So - what names were you using? Can you share your `pyproject.toml?`

**Comment by ProgrammAbel** [comment]
Hi, thank you for your time. I'm not referring to either - I'm talking about the "project name", which allows punctuation and defaults to your formal name unless you set it as otherwise with `briefcase new`. I've created a new project (which still has the same issue) and I've attached it's [pyproject.toml](https://github.com/beeware/briefcase/files/5011923/pyproject.toml.txt).
