### ISSUE TITLE
briefcase not using conda environment

### ISSUE THREAD

**Issue by KODeKarnage** [beeware/briefcase#464]
Briefcase version 0.3.3

I use conda environments on Windows with nothing important installed in the base environment. Followed the tutorial walk-through to start a new briefcase project, copied my code into app.py and ran dev, but got the following error.

```
`[projecttimelinebuilder] Starting in dev mode...
Traceback (most recent call last):
  File "c:\users\maiden\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\maiden\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Temp\ProjectTimelineBuilder\projecttimelinebuilder\src\projecttimelinebuilder\__main__.py", line 1, in <module>
    from projecttimelinebuilder.app import main
  File "C:\Temp\ProjectTimelineBuilder\projecttimelinebuilder\src\projecttimelinebuilder\app.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

Unable to start application 'projecttimelinebuilder'`

I am running `briefcase dev` from the command line in the conda environment with pandas installed.

I installed a little package into the base conda environment, added the import at the top of the app.py, and retried the dev. The error skipped that line and threw on the next line, importing pandas.

**Comment by freakboy3742** [comment]
`briefcase dev` uses whatever is in your currently active environment; so if `import pandas as pd` isn't working, then either your currently active environment doesn't have pandas installed, or briefcase isn't running inside the environment you think it is.

Internally, `briefcase dev` is not much more than:
```
import os
import subprocess
import sys

env = os.environ.copy()
env['PYTHONPATH'] = os.pathsep.join(...)
subprocess.run([sys.executable, '-m', app_name], env=env, check=True) 
```
where `PYTHONPATH` is being set to the set of paths required by your app (the list of paths defined by `sources` for the app).

I can only think of 2 things that could be going on here:
 
1. Confusion over whether you're using the base Conda environment or a specific project environment. If Pandas is installed in one, but the code is running in the other, then the app won't be able to find Pandas, even though it is, technically, installed.

2. Some sort of `PYTHONPATH` dependency in your environment that is being overwritten.

The best way to diagnose this I can think of is to try that snippet of code in your own environment. Wherever you're running briefcase - open a Python prompt and try running the code above (adding in a path to your app module). Hopefully, that will make it a little clearer where the failure is occurring.

**Comment by KODeKarnage** [comment]
Thanks. Found it.

I had briefcase installed in the base env, not my project env I had activated. It was using the base env, despite being called from the command line in the project env.

Working fine after I ran `pip install briefcase` in the project env.
