### ISSUE TITLE
`briefcase package --no-sign` fails in Github Action CI

### ISSUE THREAD

**Issue by saroad2** [beeware/briefcase#469]
**Describe the bug**
I added a CI workflow to create MSI and DMG files in the release process of my project.
Yesterday when I implemented this workflow it worked great and I could upload both MSI and DMG assets to the release (for example [this](https://github.com/EddLabs/eddington-gui/releases/tag/v0.0.2.dev16))

Today when I re-ran the CI process, `briefcase package` got stuck for a few minutes in the job that creates the DMG file, so I had to abort it. When I did, the following errors were printed:
```
hdiutil: attach: WARNING: ignoring IDME options (obsolete)
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
```

I think it's not a *Briefcase* error per-say, but I'm wondering why it stopped working today after it worked yesterday.

Any ideas?

**To Reproduce**
Run `briefcase package` on a mac machine in Github Actions.
Here is [my workflow](https://github.com/EddLabs/eddington-gui/blob/master/.github/workflows/release.yml) for reference

**Expected behavior**
One should be able to create DMG files using *Briefcase* in CI processes, such as Github Actions

**Environment:**
 - Operating System: macos-latest
 - Python version: 3.7.2
 - Software versions:
   - Briefcase: latest
   - Toga: latest

**Comment by saroad2** [comment]
Edit: After a few re-runs, it worked normally.

Nevertheless, I think it's something worth checking.

**Comment by freakboy3742** [comment]
Hrm... the fact that it "self-resolved" does make me wonder if it might have been a transient hardware problem on the Actions host itself. As you say, it's definitely worth keeping an eye on; if this starts happening reliably, we'll need to dig deeper.

**Comment by GenevieveBuckley** [comment]
FYI, we're seeing this happen over at napari too ([there's a copy of one such build log here](https://github.com/napari/napari/issues/1611#issue-691592445)). So far it's affected release 0.3.7 (September 3rd) and 0.3.8 (today, September 23rd). 

I agree it's probably a hardware problem on the Actions host. Our next move is to try using the [Retry Step](https://github.com/marketplace/actions/retry-step) github action. Maybe that could be useful for @saroad2 as well.

**Comment by saroad2** [comment]
Thanks for the share! At the moment, the package command has its own retry attempts, and most of the time it's enough to make the command work again. Even though this step now became very lengthy, it's working and we can create the dmg files needed.

I hope that GitHub will fix this issue soon.

**Comment by saroad2** [comment]
So, even though the build process passes, it takes a PRETTY LONG WHILE to do so: in my last build, the Windows packaging stage took 1m 22sec while the Mac packaging stage tool 6m 46sec!

We clearly have to do something about it. I have no idea what.

**Comment by freakboy3742** [comment]
I've been doing some testing in #700, and I'm not having any problems invoking `briefcase package`; so I'm inclined to call this "magically fixed by itself".
