### ISSUE TITLE
Django: Executing migrations for the users

### ISSUE THREAD

**Issue by elyak123** [beeware/briefcase#47]
It may be useful to execute the migrations for the user once the setup has been successful. There might be some inconveniences so I will like to discuss the pros and cons of this option.

**Comment by freakboy3742** [comment]
Agreed that this would be desirable. This should probably be integrated into the "update" functionality that has been added in v0.3. However, the Django backend needs to be completely rebuilt (as does Toga for Django), so I'm going to close this for now.
