### ISSUE TITLE
briefcase package -u returns unrecognized arguments: -u

### ISSUE THREAD

**Issue by johnoscott** [beeware/briefcase#473]
**Describe the bug**
Beeware Tutorial 4 says that the `briefcase package` command accepts the `-u` option but this does not work on Windows when attempting to build the MSI  

**To Reproduce**

1. Complete the Tutorial 4 to the end 
https://docs.beeware.org/en/latest/tutorial/tutorial-4.html#update-and-run-in-one-step

See the error returned:

```
usage: briefcase package windows msi [-h] [-v] [-V] [--no-input]
briefcase package windows msi: error: unrecognized arguments: -u
```

**Environment:**
 - Operating System: Windows 10 Pro, Version 2004 
 - Python version: Python 3.7.7
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: 0.3.0.dev22

**Comment by ekdnam** [comment]
@freakboy3742 Can you assign me to this issue?

**Comment by freakboy3742** [comment]
@ekdnam Go right ahead! Procedurally, we don't use Github's ability to formally assign tickets - we use comments like yours to flag that you're looking into the issue. You've expressed an interest in tackling the bug, and nobody else has expressed an interest - so go right ahead and start coding!

**Comment by ekdnam** [comment]
@freakboy3742 Okay!
