### ISSUE TITLE
failed to briefcase build android

### ISSUE THREAD

**Issue by Chongxuan23** [beeware/briefcase#482]
**Describe the bug**
I added a sklearn module in requires[] in pyproject.toml, and then failed to build android in the terminal showing Task :app:mergeDebugAssets FAILED. There is no problem when I'm in dev mode or run mode.

**Here's detailed description of the error:**
> Task :app:mergeDebugAssets FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.util.zip.ZipException: Not in GZIP format

**Environment:**
 - Operating System:Windows 10
 - Python version: 3.8.5
 - Software versions:
   - Briefcase:0.3.3

**Comment by freakboy3742** [comment]
This is a manifestation of #471. Briefcase can't currently package Python modules that have binary components. This is because pip/PyPI doesn't currently support mobile platforms.
