### ISSUE TITLE
Selection().items = NEW_ITEM_LIST issue with Android Emulator

### ISSUE THREAD

**Issue by chrislrobson** [beeware/briefcase#490]
**Describe the bug**
After creating a Selection() widget with a list, updating the list with the following code snippet will crash the app.
code snippet:  Selection.items = ['val0', 'val1']

**To Reproduce**
1. Create app using Selection()
2. Within the app create a button to update Selection().items
3. run app (briefcase run android) and click on button
4. App crashes, Android emulator reports "App keeps stopping"

**Expected behavior**
Selection() drop down displaying update list

**Screenshots**
N/A

**Environment:**
 - Operating System:  Mac OS X running Android emulator
 - Python version: 3.8.5
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: 0.2.15
- toga-cocoa:  0.3.0.dev22
- toga-core: 0.3.0.dev22
   - ...

**Additional context**
Function works fine in iOS emulator

**Comment by freakboy3742** [comment]
I can't reproduce this issue; given the age, I'm assuming it was triggering a bug in toga that has since been resolved.
