### ISSUE TITLE
Cannot building docker container on Fedora 32

### ISSUE THREAD

**Issue by RastaDill** [beeware/briefcase#493]
Hello. I stuck in Tutoria 3 (from BeeWare documentation). I tryit confguration files and other scaffolding, but have problem:
**Command:**
briefcase create

**Error:**
```
Installing collected packages: gbulb, pycairo, pygobject, travertino, toga-core, toga-gtk
Successfully installed gbulb-0.6.1 pycairo-1.19.1 pygobject-3.38.0 toga-core-0.3.0.dev23 toga-gtk-0.3.0.dev23 travertino-0.1.3
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/pip-target-6f2ah_xw/lib/python/toga_core-0.3.0.dev23.dist-info' -> '/app/Hello World/Hello World.AppDir/usr/app_packages/toga_core-0.3.0.dev23.dist-info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/commands/install.py", line 455, in run
    self._handle_target_dir(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/commands/install.py", line 512, in _handle_target_dir
    shutil.move(
  File "/usr/lib/python3.8/shutil.py", line 798, in move
    copytree(src, real_dst, copy_function=copy_function,
  File "/usr/lib/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 455, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/Hello World/Hello World.AppDir/usr/app_packages/toga_core-0.3.0.dev23.dist-info'
Unable to install dependencies. This may be because one of your dependencies is invalid, or because pip was unable to connect to the PyPI server.
```

I stuck on '[helloworld] Building Docker container image...' after 16 step

**Comment by freakboy3742** [comment]
Thanks for the report. From the look of it, there is something going on with file permissions. This might be related to your Docker daemon setup, or possibly related to the permissions of the user running the build.

The first test: Can you use Docker at all? Try starting a bash shell in a Python docker container:

    $ docker run -it python:3.8 /bin/bash

Once inside that container, can you run `pip install toga-core`? If that doesn't work, then the problem almost certainly lies with your Docker configuration.

**Comment by RastaDill** [comment]
I execute yours command and not have errors.
Run the command in virtual env and without - all works.
I tried connect to briefcase docker:
`docker run -it briefcase/com.example.helloworld:py3.8 /bin/bash`
and run
`pip install toga-core`
After i have error:
```
WARNING: The directory '/home/brutus/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
Collecting toga-core
  Downloading toga_core-0.2.15-py3-none-any.whl (413 kB)
     |████████████████████████████████| 413 kB 757 kB/s 
Collecting colosseum>=0.1.6
  Downloading colosseum-0.2.0-py3-none-any.whl (261 kB)
     |████████████████████████████████| 261 kB 4.5 MB/s 
Installing collected packages: colosseum, toga-core
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/brutus'
Check the permissions.
```

**Comment by freakboy3742** [comment]
Are you running briefcase as a normal login user, or as root? 

When inside the briefcase container, which user is shown as the user of `/home/brutus`?

**Comment by RastaDill** [comment]
I run briefcase from localuser. First time briefcase not running because docker needed root privileges (sudo briefcase - not started), after i add my user to docker group - all normal started.
no brutus folder:
```
docker run -it briefcase/com.example.helloworld:py3.8 /bin/bash
brutus@b25a5c0ecab8:/app$ ls -all /home
total 8
drwxr-xr-x. 2 root root 4096 Apr 12  2016 .
drwxr-xr-x. 1 root root 4096 Sep 29 09:48 ..
brutus@b25a5c0ecab8:/app$ echo $HOME
/home/brutus
```

Inside container from root:
```
docker run -u 0 -it briefcase/com.example.helloworld:py3.8 /bin/bash
root@900fd7b23e23:/app# ls -all /home/
total 8
drwxr-xr-x. 2 root root 4096 Apr 12  2016 .
drwxr-xr-x. 1 root root 4096 Sep 29 10:01 ..
root@900fd7b23e23:/app# echo $HOME
/root
root@900fd7b23e23:/app# 
```

**Comment by freakboy3742** [comment]
Ok - that is as expected; next step is to see what happens with the mount that is installed:

    docker run -it --volume "/home/RastaDill/.briefcase:/home/brutus/.briefcase" briefcase/com.example.helloworld:py3.8 /bin/bash

Substituting your own home directory in the first part of the `--volume` argument. 

Also: What version of Docker are you running?

**Comment by RastaDill** [comment]
In container:
```
docker run -it --volume "/home/rastaukropchik/.briefcase:/home/brutus/.briefcase" briefcase/com.example.helloworld:py3.8 /bin/bash
brutus@c1b50ef8cd19:/app$ ls -all /home/
total 24
drwxr-xr-x. 1 root root 4096 Sep 29 11:46 .
drwxr-xr-x. 1 root root 4096 Sep 29 11:46 ..
drwxr-xr-x. 3 root root 4096 Sep 29 11:46 brutus
```
container id different, because i reconnected )
```
brutus@4250bce6ddd5:/app$ ls -all /home/brutus/
total 20
drwxr-xr-x. 3 root   root      4096 Sep 29 11:53 .
drwxr-xr-x. 1 root   root      4096 Sep 29 11:53 ..
drwxrwxr-x. 3 brutus briefcase 4096 Sep 22 13:55 .briefcase
```
In machine:
`drwxrwxr-x.  3 rastaukropchik rastaukropchik  4096 сен 22 16:55  .briefcase
`
About docker:
```
docker --version
Docker version 19.03.11, build 42e35e6
```

**Comment by randomunrandom** [comment]
Hi, I'm new to briefcase, but I have some experience working with python in docker on Fedora. This issue is caused by SELinux and can be easily solved with a flag to volume creation. I already submited PR #500, but as a workaround you can temporarily disable SELinux until the next reboot with this comand:
```shell
sudo setenforce Permissive 
```
**Beware that this might cause other issues and is generally a security vulnerability.**

**Comment by RastaDill** [comment]
Unfortantly this command not helped me. I received the same error.
Tryed removed container and images but not successed. Although I assume that it is not necessary to delete it since briefcase create will still overwrite the current container
