### ISSUE TITLE
Winows: installation per-machine over per-user

### ISSUE THREAD

**Issue by saroad2** [beeware/briefcase#498]
At the moment, when packaging an MSI using Briefcase, the installation is **per-user**. I need to have the ability to make the installation **per-machine**.

Right now, the program is currently installed in the %appdata% folder - which is a per-user folder. the env variable translates into something that includes the username in it, and because we are deploying to "fresh" installs - no users have logged in yet. I want to be able to install the program regardless of whether the user that is going to use the program is logged in or not - so in the very least, the program needs to be installed in the "program files" folder.

**Comment by freakboy3742** [comment]
Agreed this is something we should support; #382 has some related discussion.

**Comment by saroad2** [comment]
In order to solve this issue, beeware/briefcase-windows-msi-template#6 first needs to be merged. Let me know if you need any help explaining the change.

**Comment by saroad2** [comment]
Also requires beeware/briefcase-windows-msi-template#8

**Comment by ventorvar** [comment]
https://github.com/avast/pe_tools might help - does require python >= 3.6
