### ISSUE TITLE
Android emulator was unable to start!

### ISSUE THREAD

**Issue by alishah79** [beeware/briefcase#510]
Hello
First of all thank you so much for your amazing project ,unfortunately android emulator is not working for me and gvm was not installed which I don't know how to install.
I was going along with your tutorial but every thing like creating android and running it(configuring part) took so long and at the end it didn't work .I would totally appreciate any help.
![help](https://user-images.githubusercontent.com/42653235/96847764-3e516300-145c-11eb-88f6-0e229056cf5f.PNG)

**Comment by alishah79** [comment]
I think I've completely solved the problem !
I just enabled hyper-v on windows(i got the idea of enabling it from here:https://stackoverflow.com/questions/60219313/how-to-make-avd-x86-work-with-windows-hypervisor-platform) and did it from windows power shell.
If anyone has the same problem (cpu:amd) can follow instructions from this link: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

**Comment by laminecadz** [comment]
work for me too thanks
