### ISSUE TITLE
Curses missing from support packages lib

### ISSUE THREAD

**Issue by SamSchott** [beeware/briefcase#516]
**Is your feature request related to a problem? Please describe.**
I realise that the beeware project is focused on cross-platform GUIs. Still, some GUI programs, especially desktop programs written for developers, like to bundle command line tools. Examples include the excellent [Fork](https://fork.dev) app and the less-excellent github desktop app. Some of those command line tools would like to use the curses module and the ncurses library. However, the curses module is missing at least in the `python-apple-support` package.

**Describe the solution you'd like**
Include Python's curses module and bundle ncurses if required (many platforms, including macOS, already have some version of ncurses installed).

**Describe alternatives you've considered**
Open to suggestions.

**Comment by SamSchott** [comment]
And maybe to provide some pros / cons:

Con:

* The curses module and dynamic libs will roughly add another 0.4 MB to the bundle size.

Pro:

* Some GUI apps may want to bundle a CLI which uses curses.
* Unlike other Python modules which have been excluded (Tk / Tcl), there is no reasonable expectation that curses won't be available.

**Comment by SamSchott** [comment]
Sorry, closed this accidentally.

**Comment by freakboy3742** [comment]
Ideally, we'd be able to support all the packages that exist in the standard library, including curses and tkinter. Ideally, this would be in conjunction with fixes for #413 so that a Toga GUI app doesn't need to carry around the weight of Tkinter and curses.

**Comment by SamSchott** [comment]
I was hoping that it's possible to use the ncurses that ships with macOS - at least homebrew Python seems to do so. The overhead to `python-apple-support` would then reduce to around 0.3 MB for the Python module and the extension modules. For other apple platforms like iOS it will make less sense to include to include this of course.

To be fair, I am a bit biased because I am trying to using briefcase to bundle an app that does use curses...

**Comment by freakboy3742** [comment]
If a macOS install comes with curses libraries (and there's absolutely no opt-in features - it's *just there*), then we don't have to package all curses itself - on that basis, I could be convinced to include curses as part of the macOS support package. If you want to try your hand at working out how to include the equivalent of [this line](https://github.com/beeware/Python-Apple-support/blob/3.8/patch/Python/Setup.embedded#L110) into [this overrides file](https://github.com/beeware/Python-Apple-support/blob/3.8/patch/Python/Setup.macOS-x86_64), I could be convinced to merge that patch...

**Comment by freakboy3742** [comment]
This has been resolved.
