### ISSUE TITLE
Can we make an android app using django and briefcae packaging?

### ISSUE THREAD

**Issue by alishah79** [beeware/briefcase#517]
@freakboy3742 Hi.
Can we make an android app using django and briefcae packaging? I mean use django as its gui framework and make an android apk installer using briefcase.

**Comment by freakboy3742** [comment]
It should be *possible* to do this - however, there's no "ready to use" version of this at present. You could probably build it with the pieces that Briefcase and Toga currently provides - Toga has a WebView, and you should be able to start a server thread and connect the webview to that thread.

**Comment by alishah79** [comment]
Thank you very much Mr.Keith-Magee.
I suppose your second suggestion will be something like a  Website into App ,right?

**Comment by freakboy3742** [comment]
Yes; it would be very similar to what PhoneGap provides, but using Python. My experience is that doesn't yield a *great* app experience, but you have a web app already, it might be a viable "quick and dirty" option.
