### ISSUE TITLE
Wrong NSBundle information for packaged app

### ISSUE THREAD

**Issue by SamSchott** [beeware/briefcase#523]
**Describe the bug**
When packaging an app with briefcase on macOS, the information returned by `NSBundle` at runtime is incorrect. This seems to be because the actual executable is `Contents/Resources/Support/bin` while `Contents/MacOS/Hello World` is only a wrapper script.

This has significant implications for the capabilities of the resulting app. Notably, sending desktop notifications with either `NSUnserNotificationCenter` or `UNUsernotificationCenter` will not work because neither can correctly identify the app from which it is used. In fact, calling `UNUsernotificationCenter.currentNotificationCenter()` results in a segfault with an assertion error.

**To Reproduce**
Run through the beeware tutorial to create a sample app and modify app.py as follows:

```Python
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW

from toga_cocoa.libs import NSBundle


class HelloWorld(toga.App):

    def startup(self):

        l0 = toga.Label(f"Bundle ID: {NSBundle.mainBundle.bundleIdentifier}")
        l1 = toga.Label(f"Bundle path: {NSBundle.mainBundle.bundlePath}")
        l2 = toga.Label(f"Resource path: {NSBundle.mainBundle.resourcePath}")

        main_box = toga.Box(children=[l0, l1, l2], style=Pack(direction=COLUMN))

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return HelloWorld()

```

This gives the following bundle info:

| Key             | Value                                                                                                     |
|-----------------|-----------------------------------------------------------------------------------------------------------|
| Bundle ID:      | None                                                                                                                                     |
| Bundle path:         | ~/beeware-tutorial/helloworld/macOS/Hello World/Hello World.app/Contents/Resources/Support/bin|
| Resource path:  | ~/beeware-tutorial/helloworld/macOS/Hello World/Hello World.app/Contents/Resources/Support/bin                     |

**Expected behavior**
This is expected:

| Key             | Value                                                                                                     |
|-----------------|-----------------------------------------------------------------------------------------------------------|
| Bundle ID:      | com.example.helloworld                                                                                    |
| Bundle path:         | ~/beeware-tutorial/helloworld/macOS/Hello World/Hello World.app |
| Resource path:  | ~/beeware-tutorial/helloworld/macOS/Hello World/Hello World.app/Contents/Resources  |

**Environment:**
 - Operating System: macOS 11
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: 0.3.0.dev25

**Additional context**
This seems to be quite a fundamental problem and I am unaware of a good way to solve it. It may be possible to patch NSBundle at runtime to return the correct values but this is not particularly elegant.

It seems like you are already somewhat aware of the problem, as this hackish workaround to get the resource path shows:

https://github.com/beeware/toga/blob/adac30ba4ce048e333cd5b0f2080582f906cad53/src/cocoa/toga_cocoa/app.py#L118

**Comment by freakboy3742** [comment]
Yeah - I've been aware that this was somewhat of a problem, and the more I poke around, the worse it looks.

I suspect we may need to change the packaging process to do something similar to what we do on iOS - write a bare-bones native binary that links against libPython and starts the app code. 

In addition to solving the bundle/executable identity problem you've reported here, a custom binary would give us the ability to catch the [LSOpenURLsWithRole error](beeware/briefcase-macOS-app-template#1) that is caused when the code for a package has a fundamental problem (like a missing dependency), and display an error dialog to the user, rather than crashing with a useless error code.

If we're *really* lucky, we might even be able to avoid requiring the end-user to compile. The binary itself should be identical for every app, so we should be able to compile it once as part of the template, and rename it as needed for each bundle, prior to signing.

**Comment by SamSchott** [comment]
Yes, I suspect that is the best approach. Hopefully this won't be too much work, given that iOS and macOS apps have quite a lot in common.

**Comment by SamSchott** [comment]
I have been trying a build a test app that would do just that: link against libPython and then start the app code. However, there seem to be number of subtleties involved which I am missing. Could you maybe give some advice?

So far, I have adapted the Python-Apple-Support package to keep the static libraries (libPython, etc) and discard the binaries, similar to the embedded iOS build. I have then created a very simple Xcode project which statically links those libraries and follows a similar route as the iOS Xcode project to run an example Python module.

However, when trying to actually build the app, Xcode throws a whole range of errors for undefined symbols such as `undefined symbol: _deflate`. Am I missing some compile flags here? Or did I make a mistake when building the macOS static libraries? My guess is the first, since the macOS build is basically unchanged, just modifying what is included / excluded in the tarball.

Other possible issues which may come up:

* Multiprocessing support: This relies on `sys.executable` pointing to the Python executable and not some other app. This may require a workaround. Other packages may also show unexpected behaviour. 
* Fat binaries: we might want to have builds for "Apple Silicon" with ARM based Macs coming up soon.

**Comment by SamSchott** [comment]
Never mind the build issues, I just forgot to include libz and libsqlite3. This is my first try at building something with Xcode so there are bound to be hiccups.

**Comment by SamSchott** [comment]
This may be another stupid question, just bear with me: I can see from the iOS builds that Python is statically linked. Any reason why you are not using a dynamic library or framework?

**Comment by freakboy3742** [comment]
Not a stupid question at all - it *is* odd. 

The answer is entirely for historical/hysterical reasons :-) Prior to iOS8, iOS didn't allow dynamic linking in any form. I originally got iOS support working on iOS7, and I've never got around to revisiting the problem.

Revisiting this is *very* high on my list of priorities, as it will allow for simplifying the build process, more aggressive tree-shaking of final iOS binaries, and easier integration of third party binary libraries.

**Comment by SamSchott** [comment]
Ok, that makes sense. I won't revisit how Python is built in #525 since I am not very familiar with building libraries and this would be be change which affects both iOS and macOS bundles.
