### ISSUE TITLE
bad binary format (ELF magic) when building Android packages

### ISSUE THREAD

**Issue by The-Judge** [beeware/briefcase#537]
**Describe the bug**

I created an Android Virtual Device for Android 8.1 in the AVD Manager. This emulator, I am deploying my app to using `briefcase run android`.

When doing so, the application crashes after showing the "Beeware Logo" and `adb logcat` gives the following (find the entire log in attached file):

```
12-03 18:19:58.933 10743 10743 D MainActivity: Replacing old lastUpdateTime = null with actualLastUpdateTime = 1607015987978
12-03 18:19:58.934 10743 10743 D MainActivity: unpackPython() complete
12-03 18:19:58.934 10743 10743 D MainActivity: setPythonEnvVars() start
12-03 18:19:58.934 10743 10743 V MainActivity: pythonHome=/data/user/0/com.example.helloworld/files/python/stdlib
12-03 18:19:58.935 10743 10743 D MainActivity: setPythonEnvVars() complete
12-03 18:19:58.935 10743 10743 D MainActivity: Computing Python version.
12-03 18:19:58.936 10743 10743 D MainActivity: Computed Python version: 3.8
12-03 18:19:58.937 10743 10743 I System.out: LOAD LIBRARY
12-03 18:19:58.939 10743 10743 I Python  : Start Python runtime...
12-03 18:19:58.939 10743 10743 D Python  : PYTHONHOME=/data/user/0/com.example.helloworld/files/python/stdlib
12-03 18:19:58.939 10743 10743 D Python  : PYTHONPATH=/data/user/0/com.example.helloworld/files/python/stdlib/lib/python3.8/:/data/user/0/com.example.helloworld/files/python/user_code/app_packages:/data/user/0/com.example.helloworld/files/python/user_code/app
12-03 18:19:58.939 10743 10743 D Python  : Not setting RUBICON_LIBRARY
12-03 18:19:58.939 10743 10743 I Python  : Adding Android logging module to default modules...
12-03 18:19:58.939 10743 10743 D Python  : Initializing Python runtime...
12-03 18:19:59.023 10743 10743 D Python  : Initializing Python threads...
12-03 18:19:59.023 10743 10743 D Python  : Replacing sys.stdout/sys.stderr with Android log wrappers...
12-03 18:19:59.025 10743 10743 I Python  : sys.stdout/stderr replaced with Android log wrappers.
12-03 18:19:59.025 10743 10743 V Python  : Import rubicon...
12-03 18:19:59.062 10743 10743 V Python  : Got rubicon python module
12-03 18:19:59.062 10743 10743 V Python  : Got method dispatch handler
12-03 18:19:59.062 10743 10743 I Python  : Python runtime started.
12-03 18:19:59.062 10743 10743 D MainActivity: Python.init() complete
12-03 18:19:59.062 10743 10743 D MainActivity: Python.run() start
12-03 18:19:59.062 10743 10743 D Python  : Running 'helloworld' as __main__...
12-03 18:19:59.053 10743 10743 W mple.helloworld: type=1400 audit(0.0:13): avc: denied { read } for name="/" dev="rootfs" ino=2 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
12-03 18:19:59.223  1679  1697 E BatteryExternalStatsWorker: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
12-03 18:19:59.395 10743 10743 E Python  : Application quit abnormally!
12-03 18:19:59.395 10743 10743 E Python  : Traceback (most recent call last):
12-03 18:19:59.395 10743 10743 E Python  :   File "/data/user/0/com.example.helloworld/files/python/stdlib/lib/python3.8/runpy.py", line 194, in _run_module_as_main
12-03 18:19:59.395 10743 10743 E Python  :     return _run_code(code, main_globals, None,
12-03 18:19:59.395 10743 10743 E Python  :   File "/data/user/0/com.example.helloworld/files/python/stdlib/lib/python3.8/runpy.py", line 87, in _run_code
12-03 18:19:59.395 10743 10743 E Python  :     exec(code, run_globals)
12-03 18:19:59.395 10743 10743 E Python  :   File "/data/user/0/com.example.helloworld/files/python/user_code/app/helloworld/__main__.py", line 1, in <module>
12-03 18:19:59.395 10743 10743 E Python  :     from helloworld.app import main
12-03 18:19:59.395 10743 10743 E Python  :   File "/data/user/0/com.example.helloworld/files/python/user_code/app/helloworld/app.py", line 5, in <module>
12-03 18:19:59.395 10743 10743 E Python  :     from PySide2 import QtWidgets
12-03 18:19:59.395 10743 10743 E Python  :   File "/data/user/0/com.example.helloworld/files/python/user_code/app_packages/PySide2/__init__.py", line 51, in <module>
12-03 18:19:59.395 10743 10743 E Python  :     _setupQtDirectories()
12-03 18:19:59.395 10743 10743 E Python  :   File "/data/user/0/com.example.helloworld/files/python/user_code/app_packages/PySide2/__init__.py", line 21, in _setupQtDirectories
12-03 18:19:59.395 10743 10743 E Python  :     import shiboken2
12-03 18:19:59.395 10743 10743 E Python  :   File "/data/user/0/com.example.helloworld/files/python/user_code/app_packages/shiboken2/__init__.py", line 27, in <module>
12-03 18:19:59.396 10743 10743 E Python  :     from .shiboken2 import *
12-03 18:19:59.396 10743 10743 E Python  : ImportError: dlopen failed: "/data/data/com.example.helloworld/files/python/user_code/app_packages/shiboken2/shiboken2.abi3.so" has bad ELF magic
```

**To Reproduce**
1. Install a clean Python 3.8 virtualenv and activate it
2. Install `briefcase` and `pyside2`modules to it
3. Execute `briefcase new` and follow the wizard. Select "PySide2" as a GUI toolkit while accepting the defaults for everything else. cd into `helloworld`.
4. Add `rubicon-java==0.2.4` to the requires list of `tool.briefcase.app.pyside2_demo.android` in `pyproject.toml` (see #536) 
5. Execute `briefcase create android`
6. Execute `briefcase build android`
7. Open a `adb logcat` session in a separate window to show logs of a running emulator or real device.
8. Execute `briefcase run android` to install the app and start it on the (emulated) device.

It will crash.

**Expected behavior**
The app should not crash.

**Environment:**
- Operating System: macOSX 11.0.1
- Python version: 3.8.6
- Software versions:
  - Briefcase: 0.3.3
  - PySide2: 5.15.2
  - rubicon-java: 0.2.4

[ELF_format_error.log](https://github.com/beeware/briefcase/files/5637890/ELF_format_error.log)

**Comment by The-Judge** [comment]
PS: Tried it with a real Android Phone (Moto G 5 Plus) as well with identical results.

**Comment by freakboy3742** [comment]
Unfortunately, Briefcase doesn't currently support PySide/Qt on Android.

**Comment by The-Judge** [comment]
@freakboy3742 : Thank you for your fast reply. But: Isn't it quite missleading or even plain wrong to have PySide2 being one of the selectable GUI toolkits in 'briefcase new' then?

**Comment by freakboy3742** [comment]
@The-Judge Yes and no. PySide2 *does* work for all the desktop platforms. Briefcase supports all the platforms PySide2 supports. 

However, you're not the first person to have this sort of problem, and I agree it would be desirable to flag the platforms that won't work on mobile before someone gets to the end of the process. I've opened #539 to track this as a feature request.

**Comment by bin-san** [comment]
@freakboy3742 pyside6 supports android now for a while.

**Comment by freakboy3742** [comment]
@bin-san PySide6, or Qt? I know that *Qt* has advertised Android support for a couple of years, but I haven't seen anything suggesting that *PySide6* supports Android. The [Qt for Python](https://wiki.qt.io/Qt_for_Python) page definitely doesn't list Android support.

If there's a set of instructions I'm missing, feel free to provide details.

**Comment by bin-san** [comment]
@freakboy3742 have a look at [https://doc.qt.io/qtforpython-6/deployment/deployment-pyside6-android-deploy.html](https://doc.qt.io/qtforpython-6/deployment/deployment-pyside6-android-deploy.html)

It is based on buildozer/p4a developed by people of Kivy.

**Comment by freakboy3742** [comment]
@bin-san Thanks for that. In that case, I guess that means it's *possible*. I don't know what modifications would be required to make that work in Briefcase, but if someone is motivated to look into that, I'm not opposed to making changes to accomodate that use case.

The news that Qt is apparently working on Android wheels for Pyside is encouraging, and would remove the major impediment to a smooth Briefcase deployment.
