### ISSUE TITLE
Provide better warnings when an app *can't* be deployed to mobile platforms

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#539]
At present, PySide2 and PPB appear in Briefcase's new project wizard. However, Briefcase can't deploy PySide2 or PPB to Android or iOS, as those toolkits don't support Android or iOS. This has caused repeated confusion by users who try to deploy PySide2 apps to mobile, and get confusing errors (e.g., #536, #537).

We should add a mechanism that warns users when the platform they've chosen can't be deployed to mobile.

**Describe the solution you'd like**

1) The new project wizard should advise on platform compatibility of GUI toolkits.
2) We should add a platform verification step for iOS/Android that confirms if the GUI toolkit in use is compatible with those platforms. This could be done with a metadata attribute in pyproject.toml that annotates unsupported platforms. For example, the PySide template could generate:

```
[tool.briefcase.app.foobar.iOS]
supported = False
```

If the platform isn't supported, validation would fail during `briefcase create iOS` with an appropriate error message.

**Comment by qlchan24** [comment]
Hi! I'm new here and I'll like to try solving this.

**Comment by freakboy3742** [comment]
@qlchan24 Go right ahead! If you need any pointers or suggestions beyond what is in the ticket, let us know!

**Comment by qlchan24** [comment]
I have edited an extra message for choosing the GUI frameworks in the `new` project wizard and added validation in the `create` command to check for a `supported` metadata attribute in the toml file. This validation will only fail if the attribute exists in the toml file in the first place, so existing projects are unaffected.

However, I'm not sure how to make the `new` command write this additional toml attribute to the toml file when it is created. It seems that the attribute `requires`, which is an existing platform metadata attribute, is processed from the cookiecutter template and not from this codebase itself. I have found this [file](https://github.com/beeware/briefcase-template/blob/505b00010853e84de77ad6933c4753f1172d1790/%7B%7B%20cookiecutter.app_name%20%7D%7D/setup.py) that has the conditionals useful for this case too. Please advise how should I move forward from here.

**Comment by freakboy3742** [comment]
Sounds like you're well on the way to a successful patch! 

Regarding the template - you've found the right place, although the link you've provided isn't for the branch of the template that is currently used. You've linked to the master branch on that repository; that branch is the "old" format that Briefcase used. 

The file you're looking for is [this one](https://github.com/beeware/briefcase-template/blob/v0.3/%7B%7B%20cookiecutter.app_name%20%7D%7D/pyproject.toml) - that version is on the 0.3 branch (which matches the version of Briefcase itself). You can fork the briefcase-template repository, and build your modifications by branching off the current 0.3 branch.

If you're looking to test any template changes, you can pass in a `-t` flag to `briefcase new` and provide the path to your local checkout of the briefcase-template repository. 

When you've got template and code changes that you're ready to submit for review, you can submit a pull request to the briefcase-template repository requesting a merge into the 0.3 branch (if you need pointers on how to do this, let me know). At the same time, you can submit a pull request for your changes to Briefcase itself, adding handling for the `supported` flag. In the Briefcase pull request, mention that it requires the template change, and include a reference to the template.

**Comment by qlchan24** [comment]
Got it. Thanks for the guidance!

**Comment by freakboy3742** [comment]
This was added in Briefcase 0.3.4.
