### ISSUE TITLE
Improve error reporting when architecture isn't supported

### ISSUE THREAD

**Issue by dantes47** [beeware/briefcase#541]
**Describe the bug**
Can't do >> 'briefcase create' ..

Hi Guys! When I try to 'briefcase create' command, I've got -
              [helloworld] Installing support package...
              Using support package https://briefcase-support.org/python? 
              platform=linux&version=3.6&arch=i686
              ... using most recent revision
              Unable to download https://briefcase-support.org/python? 
              platform=linux&version=3.6&arch=i686; is the URL correct?

**Environment:**
 - Operating System: linux mint/xfce(same ubuntu 18.10, but better..))
 - Python version: python 3.6.9
 - Software versions: ThinkPad R60(Yeah, it's alive!))
   - Briefcase: 0.3.3
   - Toga: toga-core==0.3.0.dev25
               toga-gtk==0.3.0.dev25
   - ...

**Additional context**
Hey Guys!) I love your tech, also like one of my old ThinkPad 32 bit, would be appreciated for possibility create apps on 32 bit soft. too, thanks..)

**Comment by Agyey** [comment]
Hi, I am a python developer, I haven't made any open source contributions yet and I would like to pick up this issue.

**Comment by Nico81019** [comment]
I would also like to pick up on this issue.

**Comment by freakboy3742** [comment]
@Nico81019 Someone is already working on the issue, so there probably isn't any need for another pair of hands; I'd suggest picking a different "help wanted" ticket.

**Comment by dr-ghost** [comment]
Hi, I would like to pick up this issue. Can I get the status of the issue if it is not yet solved?

**Comment by freakboy3742** [comment]
@dr-ghost So, there's an initial PR (#543); that PR was getting close, but was missing some tests, and a couple of other cleanups. That PR hasn't been touched since Dec 22, however. I've pinged the author of that PR; if we don't hear from them in a day or two, you should feel free to take that PR and bring the PR to completion.
