### ISSUE TITLE
A little idea

### ISSUE THREAD

**Issue by zhorsex** [beeware/briefcase#551]
Thanks to the author, this is a great framework!!! I see the future of python, support some of the author's ideas, here to mention some of their own immature ideas, beeware on the web side whether to consider wasm way to build, wasm performance is undoubtedly very good, and some components using wasm can speed up the operation, and facilitate cross-platform porting to reduce multi-platform fit workload, feel good, and hope that the author to strengthen beeware advertising work, Let more people understand this framework, support this framework, so conducive to the rapid development of beeware, like this framework very much!! And then there's the briefcase, which's great, a bit like rust's cargo, and can the author, while writing beeware, promote briefcase to a more general area, like python's cargo? Can refer to rust's cargo, thank the author for his efforts!! Come on!!

**Comment by freakboy3742** [comment]
Thanks for the enthusiasm... but... I'm afraid I don't understand what you're proposing here. Have you got a specific suggestion, or is this a "you should promote briefcase" request?

**Comment by July-Z** [comment]
Yes, I look forward to using the beeware 1.0 version as soon as possible, and I decompressed the ".msi" file generated by the briefcase and found a lot of ".pyd" files and "python.exe" environment, the briefcase released program source code security? , will it be recompiled?

**Comment by July-Z** [comment]
Hello, I have another suggestion for briefcase. "briefcase" this command is too long, can you write down such as "bfc" or "bfe" and so on, the initial version can be used in full spelling and abbreviations when we are used to using abbreviations, you can gradually eliminate the full spelling of the command, the final result may seem like this "bfc run", "bfc build", "bfc package" and so on, which may be more ergonomics, haha. Doesn't this idea work?

**Comment by freakboy3742** [comment]
I disagree that "briefcase" is too long to type. If you find it too long, you can set up a local alias to map a shorter version to the name `briefcase`. 

As for .pyd and python.exe files - those are required as part of how briefcase works, so I'm not sure what you're suggesting as an alternative.

**Comment by July-Z** [comment]
What I want to ask is whether the source code has been compiled by the briefcase, is it encrypted, is there a problem that is easy to decipher, and then the .pyd file is compiled using cython? If so, it should be hard to decipher

**Comment by July-Z** [comment]
我想问的是源代码经过公文包编译之后，是否是加密过了，有没有被容易破译的问题，然后.pyd文件是使用cython编译的吗？如果是的话应该很难被破译了

**Comment by freakboy3742** [comment]
Closing on the basis that it is not clear what enhancement is being proposed.
