### ISSUE TITLE
Openpyxl ModuleNotFoundError - AppImage

### ISSUE THREAD

**Issue by Jacopo986** [beeware/briefcase#552]
hello,

i use: Debian 4.19.160-2
with Python3 installed.

I came across this issue with an AppImage that i created with "briefcase build" command in beeware-venv.
When i try to open this AppImage, i get this error message:

`Traceback (most recent call last):
  File "/tmp/.mount_Sort_tgrL9mn/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_Sort_tgrL9mn/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_Sort_tgrL9mn/usr/app/sort_tlc/__main__.py", line 1, in <module>
    from sort_tlc.app import main
  File "/tmp/.mount_Sort_tgrL9mn/usr/app/sort_tlc/app.py", line 4, in <module>
    from openpyxl import load_workbook
ModuleNotFoundError: No module named 'openpyxl'
`

but when i try to open my program with "briefcase dev", everything is fine. 
I tried something like: "briefcase -u" but i still get the same error message. 
How can i solve this issue? When i try to re-install this openpyxl module, i get and message that tells me this module is already installed.
If you need some others information, just let me know.
Thank you.

**Comment by freakboy3742** [comment]
This is almost certainly caused by either:

1. Not including `openpyxl` in the list of requirements in your pyproject.toml, or
2. Not running `briefcase create` or `briefcase update -d` after adding the dependency to `pyproject.toml`

Installing the package in your virtual environment is completely independent of whether it's packaged with your app. If the dependency isn't declared in pyproject.toml, briefcase won't know to add the library to your packaged app.

**Comment by Jacopo986** [comment]
Thank you for your post, it was very helpful, but now i have another problem.

I did it as you said, i update the pyproject.toml, and i add to file those module: **openpyxl**,**PySimpleGui**,**tkinter**. After that I recreate my app with "briefcase create", but unfortunately it wasn't able to do that, because of tkinter. 
Now, you know how to solve this issue? I know that lack some kind of support with tkinter, i read this post: https://github.com/beeware/briefcase/issues/318, but i don't know yet how to solve. You said: 

> "It is entirely possible to support tkinter - however, you need to provide your own support package that includes tkinter and all it's additional dependencies."

how can i include tkinter and all additional dependencies?
Thank you again!

**Comment by Jacopo986** [comment]
If can help to solve this issue, i post the error code:

`briefcase run

[sort_tlc] Starting app...

Traceback (most recent call last):
  File "/tmp/.mount_Sort_tyIiRqn/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_Sort_tyIiRqn/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_Sort_tyIiRqn/usr/app/sort_tlc/__main__.py", line 1, in <module>
    from sort_tlc.app import main
  File "/tmp/.mount_Sort_tyIiRqn/usr/app/sort_tlc/app.py", line 6, in <module>
    import PySimpleGUI as sg
  File "/tmp/.mount_Sort_tyIiRqn/usr/app_packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/tmp/.mount_Sort_tyIiRqn/usr/app_packages/PySimpleGUI/PySimpleGUI.py", line 110, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
`

**Comment by freakboy3742** [comment]
The Briefcase-provided support package doesn't support tkinter. You'll need to build a custom support package that includes tkinter support. You can use the beeware/Python-Apple-support repo as a starting point if you wish. 

Unfortunately, we don't have any detailed documentation on how to build a custom support package; and adding tkinter support to the support package isn't on our roadmap.

**Comment by Jacopo986** [comment]
hmm i don't know how to install or load tkinter module whith briefcase.
My main purpose is to build and app python in a AppImage, but since i use PySimpleGUI or tkinter, i can't make it.
So i guess it can be considerately close  this post, i appreciated your help.
