### ISSUE TITLE
Bug：(beeware-venv) (base)E:\Code\beeware-tutorial>briefcase create android =》error

### ISSUE THREAD

**Issue by July-Z** [beeware/briefcase#553]
Hello, my environment: win10-64bit, python3.8.5,

 run` (beeware-venv) (base) E: \\Code> beeware-tutorial>briefcase create android`
 Tips:`Briefcase configuration error: configuration file not found, `how to solve it? 
My pip list: Package Version:
--------------- -----------
arrow 0.17.0。
beeware 0.3.0。
binaryornot 0.4.4。
briefcase 0.3.4。
certifi 2020.12.5。
chardet 4.0.0。
click 7.1.2。
cookiecutter 1.7.2。
gitdb 4.0.5。
GitPython 3.1.12。
idna 2.10。
Jinja2 2.11.2。
jinja2-time 0.2.0。
MarkupSafe 1.1.1。
pip 20.3.3。
poyo 0.5.0。
pycparser 2.20。
python-dateutil 2.8.1。
python-slugify 4.0.1。
pythonnet 2.5.1。
requests 2.25.1。
setuptools 47.1.0。
six 1.15.0。
smmap 3.0.4。
text-unidecode 1.3。
toga-core 0.3.0.dev26。
toga-winforms 0.3.0.dev26。
toml 0.10.2。
travertino 0.1.3。
urllib3 1.26.2。
wheel 0.36.2。
-------------------------------
Thank you so much！

**Comment by freakboy3742** [comment]
The error is exactly what it says - it can't find your `pyproject.toml` configuration file. This is probably because you're not running `briefcase create android` where you've got your configuration file.

**Comment by July-Z** [comment]
谢谢您，问题已经解决了， 我应该在项目目录中 使用 创建 安卓的命令
