### ISSUE TITLE
Importing PyOWM causes error (Unable to start app) when executing 'briefcase run'

### ISSUE THREAD

**Issue by Imke7** [beeware/briefcase#554]
**Describe the bug**
I imported PyOWM in my program, which worked fine when executing `briefcase dev`. However, after I followed the steps to build the application (`briefcase create` and `briefcase build`) and tried to run the program with `briefcase run`, I got the following error:
```
[helloworld] Starting app...
 
 Unable to start app helloworld.
```
I tried importing other modules, for example numpy, which didn't cause any problems.

**To Reproduce**
1. Follow the briefcase tutorial at [https://docs.beeware.org/en/latest/tutorial/tutorial-0.html](url) up until tutorial 1.
2. Add `import pyowm` in the app.py file.
3. Move to tutorial 3. Before running `briefcase run`, add pyowm to the dependencies in the pyproject.toml file and update dependencies with `briefcase update -d`.
4. Try the `briefcase run` command.

**Expected behavior**
The program starts running and looks very alike to the program that is seen when excecuting `briefcase dev`.

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.8.7
 - Software versions:
   - Briefcase: 0.3.4
   - Toga: 0.3.0dev26
   - PyOWM: 3.1.1

**Additional context**
I'm very new to Python and Beeware, so maybe I'm forgetting something simple. I'd be very thankful if someone could help.

**Comment by freakboy3742** [comment]
Installing the package in your virtual environment is completely independent of whether it's packaged with your app. If the dependency isn't declared in pyproject.toml, briefcase won't know to add the library to your packaged app.

If you add a dependency after creating your app, you need to 
1. Add the new dependency to the list of requirements in your pyproject.toml, and
2. either re-run `briefcase create`, or run `briefcase update -d`. This forces the new dependencies to be install in the bundled app.

**Comment by Imke7** [comment]
I forgot to mention that step in the 'steps to reproduce', but I did add the dependency in the toml file. That didn't work, so I checked which version I had installed on my computer and compared it with the version briefcase installed. Someone else had pointed out to me that that might fix the problem, but it didn't

**Comment by freakboy3742** [comment]
You've added the dependency to the toml file - but have you run `briefcase update -d`? Dependencies are only installed when the app is created; if you modify dependencies, you need to explicitly tell briefcase to update them.

**Comment by Imke7** [comment]
Yes, I've run `briefcase update - d`. No luck...

**Comment by freakboy3742** [comment]
Checking - is that *literally* what you typed? Because as written, it would be an error.

Regardless - can you re-run `update -d` and post the log?

**Comment by Imke7** [comment]
I sure can

```
(beeware-venv) C:\Users\imkev\beeware-tutorial\helloworld>briefcase update -d

[helloworld] Updating dependencies...
Collecting numpy==1.19.3
  Using cached numpy-1.19.3-cp38-cp38-win_amd64.whl (13.3 MB)
Collecting pyowm==3.1.1
  Using cached pyowm-3.1.1-py3-none-any.whl (3.3 MB)
Collecting scipy==1.5.4
  Using cached scipy-1.5.4-cp38-cp38-win_amd64.whl (31.4 MB)
Collecting toga-winforms>=0.3.0.dev20
  Using cached toga_winforms-0.3.0.dev26-py3-none-any.whl (37 kB)
Collecting toga-core==0.3.0.dev26
  Using cached toga_core-0.3.0.dev26-py3-none-any.whl (487 kB)
Collecting geojson<3,>=2.3.0
  Using cached geojson-2.5.0-py2.py3-none-any.whl (14 kB)
Collecting PySocks<2,>=1.7.1
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting requests<3,>=2.20.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting travertino>=0.1.3
  Using cached travertino-0.1.3-py3-none-any.whl (15 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting geopy
  Using cached geopy-2.1.0-py3-none-any.whl (112 kB)
Collecting geographiclib<2,>=1.49
  Using cached geographiclib-1.50-py3-none-any.whl (38 kB)
Collecting pythonnet
  Using cached pythonnet-2.5.1-cp38-cp38-win_amd64.whl (81 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: urllib3, idna, chardet, certifi, travertino, requests, PySocks, pycparser, toga-core, pythonnet, numpy, geojson, geographiclib, toga-winforms, scipy, pyowm, geopy
Successfully installed PySocks-1.7.1 certifi-2020.12.5 chardet-4.0.0 geographiclib-1.50 geojson-2.5.0 geopy-2.1.0 idna-2.10 numpy-1.19.3 pycparser-2.20 pyowm-3.1.1 pythonnet-2.5.1 requests-2.25.1 scipy-1.5.4 toga-core-0.3.0.dev26 toga-winforms-0.3.0.dev26 travertino-0.1.3 urllib3-1.26.2

[helloworld] Updating application code...
Installing src/helloworld...

[helloworld] Application updated.

(beeware-venv) C:\Users\imkev\beeware-tutorial\helloworld>briefcase run

[helloworld] Starting app...


Unable to start app helloworld.

(beeware-venv) C:\Users\imkev\beeware-tutorial\helloworld>
```

**Comment by freakboy3742** [comment]
Based on that log, it looks like the issue isn't packaging; it's something in the app itself. Unfortunately, because of the way we're starting the app, any console logs are being swallowed. 

Your best bet from here is to *deactivate* the virtual environment, and then start the app from the command line and see what errors are being raised:

    C:\...> "windows\Hello World\src\python\python.exe" -m helloworld

This is effectively exactly what Briefcase is doing, except it allows you to see the console when the app starts. If we're lucky, you'll see the error that is occurring at runtime that is causing the app to fail at startup.

**Comment by Imke7** [comment]
It worked! When I tried it, I got the following error:

```
C:\Users\imkev\beeware-tutorial\helloworld\windows\Hello World\src\python>python.exe -m helloworld
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\imkev\beeware-tutorial\helloworld\windows\Hello World\src\\app\helloworld\__main__.py", line 1, in <module>
    from helloworld.app import main
  File "C:\Users\imkev\beeware-tutorial\helloworld\windows\Hello World\src\\app\helloworld\app.py", line 9, in <module>
    import pyowm
  File "C:\Users\imkev\beeware-tutorial\helloworld\windows\Hello World\src\\app_packages\pyowm\__init__.py", line 4, in <module>
    from pyowm.owm import OWM
  File "C:\Users\imkev\beeware-tutorial\helloworld\windows\Hello World\src\\app_packages\pyowm\owm.py", line 13, in <module>
    from pyowm.commons import cityidregistry
  File "C:\Users\imkev\beeware-tutorial\helloworld\windows\Hello World\src\\app_packages\pyowm\commons\cityidregistry.py", line 5, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
```
It turned out that `pkg_resouces` is part of setuptools, so I added setuptools to the dependencies, updated them and now everything works fine :) 

Thanks a lot for your help!
