### ISSUE TITLE
Add PySide6 Support

### ISSUE THREAD

**Issue by Daveismus** [beeware/briefcase#560]
**Is your feature request related to a problem? Please describe.**
PySide6 was released

**Describe the solution you'd like**
Make it possible to create Pyside6 applications

**Describe alternatives you've considered**
-

**Additional context**

**Comment by freakboy3742** [comment]
Absolutely! We'd love to support as many backends as possible. 

If anyone wants to work this issue, the change will be primarily in the [v0.3 branch of the briefcase-template project](https://github.com/beeware/briefcase-template/tree/v0.3) project, adding the stub code for a PySide6 project. Bringing #392 (initial PR in #414) to completion would also be helpful.

**Comment by Noir-** [comment]
Is there any progress on this? Looks like all python distribution frameworks currently fail with pyside6 :/

**Comment by freakboy3742** [comment]
@Noir- No, there hasn't been any progress. I'll also add that it's not an especially high priority for me personally; I don't use Qt or PySide. 

That said - Briefcase's "support" for GUI toolkits is almost 100% related to the wizard template. There's nothing in the packaging process itself that is tied to the GUI toolkit. As long as you can `pip install pyside6` (or whatever the invocation is), and the install is self contained, Briefcase should work - you just won't get the full templated start-of-project experience.

**Comment by Noir-** [comment]
@freakboy3742 Ok I see. The GUI toolkit isn't necessary. Thanks for pointing that out. Is there anything of what I should take care? I suspect that the basic project structure from `birefcase new` is mandatory. Just trying to integrate my application into this but it fails, gonna open a new issue for that.

**Comment by freakboy3742** [comment]
If you run `briefcase new` and specify "no GUI toolkit", you can use that as a base and add your own PySide6 code.

The stretch goal beyond that is to take whatever modifications you make to the "no GUI toolkit" template, and add those changes as a "pyside6" option in that template.

**Comment by freakboy3742** [comment]
Closing as this was added in Briefcase 0.3.6.
