### ISSUE TITLE
Unable to create app with a Russian name

### ISSUE THREAD

**Issue by osintalex** [beeware/briefcase#566]
I tried to create an app with a Russian name but the Cyrillic characters caused some problems when naming the app that led to an error.

Here's the full traceback:

    ➜ briefcase new
    
    Let's build a new Briefcase app!
    
    
    First, we need a formal name for your application. This is the name that will
    be displayed to humans whenever the name of the application is displayed. It
    can have spaces and punctuation if you like, and any capitalization will be
    used as you type it.
    
    Formal Name [Hello World]: здравствуйте мир
    Traceback (most recent call last):
      File "/Applications/PycharmProjects/beeware-venv/venv/bin/briefcase", line 8, in <module>
        sys.exit(main())
      File "/Applications/PycharmProjects/beeware-venv/venv/lib/python3.8/site-packages/briefcase/__main__.py", line 11, in main
        command(**options)
      File "/Applications/PycharmProjects/beeware-venv/venv/lib/python3.8/site-packages/briefcase/commands/new.py", line 523, in __call__
        state = self.new_app(template=template, **options)
      File "/Applications/PycharmProjects/beeware-venv/venv/lib/python3.8/site-packages/briefcase/commands/new.py", line 461, in new_app
        context = self.build_app_context()
      File "/Applications/PycharmProjects/beeware-venv/venv/lib/python3.8/site-packages/briefcase/commands/new.py", line 320, in build_app_context
        class_name = self.make_class_name(formal_name)
      File "/Applications/PycharmProjects/beeware-venv/venv/lib/python3.8/site-packages/briefcase/commands/new.py", line 84, in make_class_name
        if class_name[0].isdigit():
    IndexError: string index out of range

**To Reproduce**
After typing briefcase new, try giving your app a Russian name - you could copy what I wrote which means hello world in Russian - здравствуйте мир

**Environment:**
 - Operating System: MacOS Big Sur 11.1
 - Python version: 3.8.1
 - Software versions:
   - Briefcase: 0.3.4

**Possible solution**

In this file https://github.com/beeware/briefcase/blob/master/src/briefcase/commands/new.py at line 83 it looks like the re.sub method is causing a problem to me? I think the regex [^0-9a-zA-Z_]+ matches a Cyrillic word and so replaces the whole thing with a blank string. 

I tested this in a python console and got the below:

    >>> import re
    >>> re.sub('[^0-9a-zA-Z_]+', '', 'hello')
    'hello'
    >>> re.sub('[^0-9a-zA-Z_]+', '', 'здравсвтвуйте мир')
    ''

If I add some Cyrillic characters into this then that seems to fix it:

    re.sub('[^0-9a-zA-Z_\u0400-\u0500]+', '', 'здравсвтвуйте мир')
    'здравсвтвуйтемир'

**Comment by freakboy3742** [comment]
Thanks for the report! We definitely want to be able to support Cyrillic (and any other character set that people want to use in their app names), so this is a bug we need to fix.

The "make class name" method is trying to create a candidate class name for the Python class defining the app; so we need to include a few more characters than just the Cyrillic subrange. [PEP3131](https://www.python.org/dev/peps/pep-3131/) describes what is legal. It may not be possible to solve this with an update to the regex; we may need to iterate over the string, filtering each character based on whether it's in the legal XID set.

**Comment by freakboy3742** [comment]
Doing some housekeeping, this is a duplicate of #612. Although this is the earlier report, the description on #612 is more complete.
