### ISSUE TITLE
Cannot build with --no-docker

### ISSUE THREAD

**Issue by moridius** [beeware/briefcase#568]
**Describe the bug**
```briefcase --no-docker build linux``` gives a parameter error.

**To Reproduce**
1. Use the helloworld app from the tutorial on Arch Linux
2. ```briefcase --no-docker build linux```
3. "Flag could not be matched: deploy-deps-only"

**Environment:**
 - Operating System: Arch Linux
 - Python version: 3.9.1
 - Software versions:
   - Briefcase: 0.3.4

**Additional context**
It seems to be a parameter error with linuxdeploy.
```
~/s/helloworld$ briefcase --no-docker build linux

[helloworld] Building AppImage...

/tmp/appimage_extracted_f245a3802a63e38cd53c54f2b2817e3e/.DirIcon
(...)
/tmp/appimage_extracted_f245a3802a63e38cd53c54f2b2817e3e/usr/share/icons/hicolor/scalable/apps
Flag could not be matched: deploy-deps-only
  /tmp/appimage_extracted_f245a3802a63e38cd53c54f2b2817e3e/AppRun {OPTIONS}

    linuxdeploy -- create AppDir bundles with ease

  OPTIONS:

      -h, --help                        Display this help text
      -V, --version                     Print version and exit
      -v[verbosity],
      --verbosity=[verbosity]           Verbosity of log output (0 = debug, 1 =
                                        info (default), 2 = warning, 3 = error)
      --appdir=[appdir]                 Path to target AppDir
      -l[library...],
      --library=[library...]            Shared library to deploy
      -e[executable...],
      --executable=[executable...]      Executable to deploy
      -d[desktop file...],
      --desktop-file=[desktop file...]  Desktop file to deploy
      --create-desktop-file             Create basic desktop file that is good
                                        enough for some tests
      -i[icon file...],
      --icon-file=[icon file...]        Icon to deploy
      --custom-apprun=[AppRun path]     Path to custom AppRun script
                                        (linuxdeploy will not create a symlink
                                        but copy this file instead)
      --list-plugins                    Search for plugins, print them to stdout
                                        and exit
      -p[name...], --plugin=[name...]   Input plugins to run (check whether they
                                        are available with --list-plugins)
      -o[name...], --output=[name...]   Output plugins to run (check whether
                                        they are available with --list-plugins)


Error while building app helloworld.
```

**Comment by freakboy3742** [comment]
Thanks for the report - can I ask what version of `linuxdeploy` you've got? You should be able to find the version Briefcase is using in `~/.briefcase/tools/linuxdeploy-x86_64.AppImage`. I'm wondering if you've somehow got an old version, or if the AppImage team has released a new version of linuxdeploy and removed/changed the `--deploy-deps-only` option.

**Comment by moridius** [comment]
```
$ ~/.briefcase/tools/linuxdeploy-x86_64.AppImage --version
linuxdeploy version 1-alpha (git commit ID f24c167), <local dev build> built on 2020-05-03 16:36:41 UTC
```
I'm running briefcase in a venv so I'm not sure why there is stuff in ~/.briefcase at all.

**Comment by freakboy3742** [comment]
~/.briefcase is the cache directory that is used by Briefcase - rather than download 100MB support packages for each virtual environment, Briefcase will download the file once, and put it in a location that has shared between virtualenvs. 

From the look of it, you're running a *very* old version of linuxdeploy - I'm guessing you used Briefcase for something around May last year, and haven't touched it since. The version that is currently cached predates the introduction of the --deploy-deps-only option; you'll need to run `briefcase upgrade` to download the new version of linuxdeploy (along with any other tools that might be stale)

**Comment by moridius** [comment]
I had created a fresh venv and didn't expect that ~/.briefcase is used for caching. Now when I deleted ~/.briefcase and reinstalled Briefcase in a fresh venv it worked just fine. Thank you!
