### ISSUE TITLE
python/bin/python not found. Should be python/bin/python3

### ISSUE THREAD

**Issue by mankoff** [beeware/briefcase#57]
When running **Tutorial 0** with target `macos` and Python 3.4 (i.e. `python setup.py macos --support-pkg=/path/to/Python-3.4-macOS-support.b2.tar.gz`), the app cannot be run, and gives the following error:

    $ open macOS/Tutorial\ 0.app
    LSOpenURLsWithRole() failed with error -10810 for the file /path/to/tutorial_0/macOS/Tutorial 0.app.

The problem seems to be that it is looking for `python/bin/python` when that binary does not exist, but `python/bin/python3` does exist. There are two fixes:

1) Change the last line of `macOS/Tutorial 0.app/Contents/MacOS/Tutorial 0` to `python/bin/python3 -m tutorial_0`, OR

2) `ln -s python3 python` in `tutorial_0/macOS/Tutorial 0.app/Contents/Resources/python/bin`

**Comment by freakboy3742** [comment]
This has been corrected in the macOS app template. Thanks for the report!
