### ISSUE TITLE
Add a confirm to the end of the bootstrapping dialogue

### ISSUE THREAD

**Issue by Viridescence** [beeware/briefcase#570]
**Is your feature request related to a problem? Please describe.**
Currently, Briefcase has no way to stop bootstrapping a project with `$ briefcase new` (that I know of). Once you press it, you need to go through the whole process (Formal name, name, website, etc), set up the project, hunt the directory, and delete it (if you do not want to terminate the process and ruin your venv). 

**Describe the solution you'd like**
It would be very simple to implement a confirm message at the end of the detail input - a multiple choice function, which has been defined, can be used. If this is found to be a good idea, I'd definitely like to try to implement it myself!

**Describe alternatives you've considered**
This is the simplest solution: Others include adding a cancel option at every step which could be a problem in terms of input, and confirming after every step which would be tedious. This way, after a mistake has been made and entered, all the user needs to do is skip to the end by pressing enter all the time, and pressing "cancel" at the end.

**Comment by freakboy3742** [comment]
Thanks for the suggestion - however, it's not clear to me what problem you're trying to solve.

At any point in the wizard process, you can hit CTRL-C to cancel. Nothing is generated until you've answered all the questions, so as long as there are still questions to answer, there's an opportunity to cancel.

Briefcase new is also a purely templating activity, so it has no impact on your virtual environment. It's not until you run `briefcase dev` that anything is installed in your virtualenv. In fact, if you *never* run `briefcase dev`, you'll never have anything added to your virtual environment.

So - what problem is it that you're trying to solve here? I can maybe see value in adding a final confirmation before the project template is unrolled - a final "here's what you entered, are you sure you want to create this project" confirmation - is this what you're suggesting?

**Comment by Viridescence** [comment]
Yes - I was not aware the process could be stopped with ctrl-c. A confirm screen might still add some polish, but this method negates all need for it: it might be worth adding to the tutorial.
