### ISSUE TITLE
briefcase cant unpack support package

### ISSUE THREAD

**Issue by ALEX-PETROU** [beeware/briefcase#571]
```
Application someapp already exists; overwrite [y/N]? y

[someapp] Removing old application bundle...

[someapp] Generating application template...
Using app template: https://github.com/beeware/briefcase-android-gradle-template.git, branch 3.8
Using existing template (sha 08db9d6eb9e5dcd706b054f830982f659845d683, updated Wed Sep  9 14:16:07 2020)

[someapp] Installing support package...
Using support package https://briefcase-support.org/python?platform=android&version=3.8
... using most recent revision
Python-3.8-Android-support.b3.zip already downloaded
Unpacking support package...

Unable to unpack support package 'https://briefcase-support.org/python?platform=android&version=3.8'``
```

**Comment by freakboy3742** [comment]
Thanks for the report. My suspicion is that something has gone wrong with your download of the support package; I've just confirmed that the package on the server is fine. 

The cached version of the package will be in  ~/.briefcase/support/Python-3.8-Android-support.b3.zip. Can I get you to check if you can unzip that file? If you can't, that will be the source of the problem. Delete the file and re-run `briefcase create` and it will re-download the support package. If that isn't the problem, we'll need to investigate further.

**Comment by ALEX-PETROU** [comment]
I really appreciate the quick response! I was not able to unpack the file manually. Deleting the zip folder and running "briefcase create android" solved the issue!
