### ISSUE TITLE
Subprocess output does not appear to be encoded as cp1250

### ISSUE THREAD

**Issue by DawidGrzejek** [beeware/briefcase#578]
**Describe the bug**
I'm following step by step this guide: https://docs.beeware.org/en/latest/tutorial/tutorial-1.html. I'm at Run the app in developer mode section.

**To Reproduce**
1. Go to beeware-tutorial folder
2. Write `briefcase new`
3. Go to helloworld folder
4. Write `briefcase dev`
5. Error occurs
6. 
**Error**

> C:\Users\PC\beeware-tutorial\helloworld>briefcase dev
> 
> [helloworld] Installing dependencies...
> Collecting toga-winforms>=0.3.0.dev20
>   Using cached toga_winforms-0.3.0.dev26-py3-none-any.whl (37 kB)
> Requirement already satisfied: toga-core==0.3.0.dev26 in c:\users\pc\appdata\local\programs\python\python39\lib\site-packages (from toga-winforms>=0.3.0.dev20) (0.3.0.dev26)
> Collecting pythonnet
>   Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
> Requirement already satisfied: travertino>=0.1.3 in c:\users\pc\appdata\local\programs\python\python39\lib\site-packages (from toga-core==0.3.0.dev26->toga-winforms>=0.3.0.dev20) (0.1.3)
> Requirement already satisfied: pycparser in c:\users\pc\appdata\local\programs\python\python39\lib\site-packages (from pythonnet->toga-winforms>=0.3.0.dev20) (2.20)
> Building wheels for collected packages: pythonnet
>   Building wheel for pythonnet (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'c:\users\pc\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-5q9whs1_\\pythonnet_655b5f803acc44058594134ed9f55e2d\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-5q9whs1_\\pythonnet_655b5f803acc44058594134ed9f55e2d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\PC\AppData\Local\Temp\pip-wheel-r49b6qo9'
>        cwd: C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\
>   Complete output (32 lines):
>   running bdist_wheel
>   running build
>   running build_ext
>   Checking for updates from https://www.nuget.org/api/v2/.
>   Currently running NuGet.exe 4.1.0.
>   Updating NuGet.exe to 5.8.1.
>   Update successful.
>   Cannot find the specified version of msbuild: '14'
>   MSBuild auto-detection: using msbuild version '16.9.0.11203' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin'.
>   Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
>   Restoring NuGet package UnmanagedExports.1.2.7.
>   Restoring NuGet package NUnit.3.12.0.
>   Restoring NuGet package System.ValueTuple.4.5.0.
>   Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\packages'
>   Adding package 'NUnit.3.12.0' to folder 'C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\packages'
>   Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\packages'
>   Adding package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\packages'
>   Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\packages'
>   Added package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\packages'
>   Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\packages'
>   Added package 'NUnit.3.12.0' to folder 'C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\packages'
> 
>   NuGet Config files used:
>       C:\Users\PC\AppData\Roaming\NuGet\NuGet.Config
> 
>   Feeds used:
>       C:\Users\PC\.nuget\packages\
>       https://api.nuget.org/v3/index.json
> 
>   Installed:
>       4 package(s) to packages.config projects
>   error: [WinError 2] The system cannot find the file specified
>   ----------------------------------------
>   ERROR: Failed building wheel for pythonnet
>   Running setup.py clean for pythonnet
> Failed to build pythonnet
> Installing collected packages: pythonnet, toga-winforms
>     Running setup.py install for pythonnet ... error
>     ERROR: Command errored out with exit status 1:
>      command: 'c:\users\pc\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-5q9whs1_\\pythonnet_655b5f803acc44058594134ed9f55e2d\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-5q9whs1_\\pythonnet_655b5f803acc44058594134ed9f55e2d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC\AppData\Local\Temp\pip-record-1jhkd469\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\pc\appdata\local\programs\python\python39\Include\pythonnet'
>          cwd: C:\Users\PC\AppData\Local\Temp\pip-install-5q9whs1_\pythonnet_655b5f803acc44058594134ed9f55e2d\
>     Complete output (6 lines):
>     usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>        or: setup.py --help [cmd1 cmd2 ...]
>        or: setup.py --help-commands
>        or: setup.py cmd --help
> 
>     error: option --single-version-externally-managed not recognized
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: 'c:\users\pc\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-5q9whs1_\\pythonnet_655b5f803acc44058594134ed9f55e2d\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-5q9whs1_\\pythonnet_655b5f803acc44058594134ed9f55e2d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC\AppData\Local\Temp\pip-record-1jhkd469\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\pc\appdata\local\programs\python\python39\Include\pythonnet' Check the logs for full command output.
> Unable to install dependencies. This may be because one of your dependencies is invalid, or because pip was unable to connect to the PyPI server.

**Expected behavior**
[hello-world] Installing dependencies...
...
[helloworld] Starting in dev mode...
This should open a GUI window
![image](https://user-images.githubusercontent.com/42537540/111048685-a295b300-844d-11eb-8b95-80ffe36bb815.png)

**Environment:**
 - Operating System: Windows 10
 - Python version: Python 3.9.2
 - Software versions (from `pip list`) :
   - Briefcase: briefcase        0.3.5
   - Toga: toga-core        0.3.0.dev26
  I was installing that step b ystep with the guide at 13.03.2021

**Additional context**

**Comment by freakboy3742** [comment]
Thanks for the report!

There's two things going on here. One is definitely a problem outside our control; the other might be - but we'll need some help to narrow it down.

The first problem is that you're using Python 3.9 and Windows. Toga's support for Windows uses a library called Python.net, and Python.net doesn't support Python 3.9 yet. There's not much we can do about this - it's a separate project with it's own release schedule. It's not even something where we can improve the error reporting, because the only manifestation of the error is what you're seeing - an inability to install one of the dependencies of Toga. 

When most people see this problem, they get what is reported as #557. In your case, you're getting a slightly different presentation because you have enough of a C compiler environment present that the build starts, and *then* fails. 

The second problem is the cp1250 issue that is mentioned in the subject of this ticket. You've evidently edited this ticket since it was first posted, because the stack trace in the body of the ticket no longer contains any reference to cp1250. In an earlier version of the ticket (which I received by email), it looks like you were using a Polish locale. *That* problem may not actually be Briefcase's problem either - the output at that phase of execution is literally the output of `pip`, so I think the problem may lie there. 

To confirm this: If you run `pip install pythonnet` on your Polish locale machine - do you still get the cp1250 warning? If so, it's a pip problem, not a Briefcase problem.

**Comment by DawidGrzejek** [comment]
Hey,

Thanks for fast replay. Seems like, what you saying is in fact the problem.

Firstly I changed my Windows language to English to avoid further problems
Secondly I install Python 3.8

After those changes it ended up working
