### ISSUE TITLE
Case sensitive filesystem issues w/ BZip2 and XZ

### ISSUE THREAD

**Issue by mankoff** [beeware/briefcase#58]
After using `briefcase` to generate an iOS project from `toga`, I try to build in in XCode. I get the following errors:

    ld: framework not found BZip2
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

This appears to be a case sensitivity issue. In `./iOS/BZip2.framework`, I see the following:

```
Headers -> Versions/Current/Headers
Versions
bzip2 -> Versions/Current/bzip2
```

But it should be `BZip2`. I can make the error go away with `ln -s bzip2 BZip2`.

The same error and fix are needed for `XZ`. Then the project compiles.

**Comment by freakboy3742** [comment]
I believe this has been addressed in recent updates to the iOS support packages. If it hasn't let us know.
