### ISSUE TITLE
Unable to package NumPy >= 1.17.3 on linux

### ISSUE THREAD

**Issue by davidfokkema** [beeware/briefcase#583]
**Describe the bug**
When using precompile NumPy wheels (available since version 1.17.3) `briefcase run` fails on linux. The problem is with the dynamic libraries:
```
Deploying dependencies for ELF file /app/appimage/Hello World/Hello World.AppDir/usr/app_packages/numpy/.libs/libopenblasp-r0-34a18dc3.3.7.so 
ERROR: Could not find dependency: libgfortran-ed201abd.so.3.0.0 
WARNING: Failed to deploy dependencies for ELF file /app/appimage/Hello World/Hello World.AppDir/usr/app_packages/numpy/.libs/libopenblasp-r0-34a18dc3.3.7.so, skipping 
```
I checked that the libraries are present when installing locally, but `ldd` does report some weirdness:
```
lib/python3.8/site-packages/numpy/.libs$ ldd libopenblasp-r0-34a18dc3.3.7.so 
	linux-vdso.so.1 (0x00007ffdc9f35000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f339369c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3393679000)
	libgfortran-ed201abd.so.3.0.0 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3393487000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f339558f000)
```
I checked, the libgfortran lib is present. I'm not sure how NumPy tells the system to look for the library in the local folder, but if I remove the file I can't locally `import numpy` anymore. Maybe briefcase (via linuxdeploy) can ignore the 'missing dependency'?

**To Reproduce**
1. Create new briefcase project (`briefcase new`)
2. Add `numpy==1.17.3` in the `requires` field.
3. `briefcase create` on linux
4. `briefcase run` on linux
5. See error.

**Expected behavior**
I expect briefcase to package the app and `briefcase run` to just complete normally.

**Environment:**
 - Operating System: Ubuntu 20.04
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.5

**Additional context**
I suspect the problem to lie with the way linuxdeploy builds the appimage. When I have the time, I'll try to figure out how to use linuxdeploy or appimage and try to package NumPy without briefcase. Maybe the problem lies not with briefcase itself.

**Comment by davidfokkema** [comment]
The current version of NumPy, 1.20.2, fails with a very similar error (libgfortran requires libquadmath). I think the problem is exactly the same, but another library fails first.

**Comment by zili55** [comment]
@freakboy3742 please assign this task to me

**Comment by davidfokkema** [comment]
There is some progress on this issue. If you follow the above (empty app, create, run) with NumPy version 1.21.2, it creates and runs the (empty) app just fine. If you add `import numpy` however, there is a new error:
```python
Traceback (most recent call last):
  File "/tmp/.mount_Hello_G29OJt/usr/app_packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/tmp/.mount_Hello_G29OJt/usr/app_packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/tmp/.mount_Hello_G29OJt/usr/app_packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned
```
This, apparently, has to do with stripping the libraries. I've patched briefcase to try and fix the issue:
```patch
--- a/src/briefcase/platforms/linux/appimage.py
+++ b/src/briefcase/platforms/linux/appimage.py
@@ -171,7 +171,8 @@ class LinuxAppImageBuildCommand(LinuxAppImageMixin, BuildCommand):
             # For some reason, the version has to be passed in as an
             # environment variable, *not* in the configuration...
             env = {
-                'VERSION': app.version
+                'VERSION': app.version,
+                'NO_STRIP': 1
             }
 
             # Find all the .so files in app and app_packages,
```
And then the app runs and imports NumPy just fine. I don't know if NumPy should be fixed to allow stripping, if linuxdeploy should be fixed to do stripping right, or that briefcase should be patched to not do stripping. Hope this helps in any way.

**Comment by zili55** [comment]
This is an issue with a shared object what comes with `numpy` - `libgfortran-2e0d59d6.so.5.0.0`. If we strip that file, then we can't import numpy anymore:
```
strip ~/venv/lib/python3.9/site-packages/numpy.libs/libgfortran-2e0d59d6.so.5.0.0
python
import numpy
```
then I get error: `Original error was: libgfortran-2e0d59d6.so.5.0.0: ELF load command address/offset not properly aligned`

numpy version: 1.21.2

**Comment by freakboy3742** [comment]
I'm going to close this issue to consolidate the general problem of "Linux AppImage deployment has problems" under a single issue (#718).
