### ISSUE TITLE
briefcase build android>>Task :app:stripDebugDebugSymbols FAILED

### ISSUE THREAD

**Issue by plr0201** [beeware/briefcase#602]
**Describe the bug**
-----------------------------------------------------------------------------------------
(beeware-venv) C:\Users\xxx1\beeware-tutorial\helloworld>briefcase build android
[helloworld] Building Android APK...

> Task :app:externalNativeBuildDebug
Build native-lib_armeabi-v7a
ninja: no work to do.
Build native-lib_arm64-v8a
ninja: no work to do.
Build native-lib_x86
ninja: no work to do.
Build native-lib_x86_64
ninja: no work to do.

> Task :app:stripDebugDebugSymbols FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stripDebugDebugSymbols'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 27s
27 actionable tasks: 3 executed, 24 up-to-date

Error while building project.
-----------------------------------------------------------------------------------------
**Expected behavior**
No error

**Screenshots**

**Environment:**
 - Operating System: WIN10 pro x64
 - Python version: 3.8.9
   - Briefcase:0.3.5
   - Toga:0.3.0.dev28

**Additional context**
Just repeat the beware tutorial, and everything worked fine till the last step "briefcase build android"

**Comment by amaj1407** [comment]
Hey @plr0201, did you solve it? If so, what did you do?

**Comment by freakboy3742** [comment]
@amaj1407 This appears to be caused by a change to the Android toolchain - see #607 for details.

**Comment by amaj1407** [comment]
Thank you @freakboy3742 for notifying me, you are correct new NDK has a different way of using the toolchains. Anyways as a workaroud, downgrading the NDK version by adding/editing the following in app/build.gradle

```
android {
    ndkVersion '19.2.5345600'
}
```

The project can be built after this.

**Comment by jakub-vesely** [comment]
@amaj1407: proposed workaround does not work for me. 

"No version of NDK matched the requested version 19.2.5345600. Versions available locally: 23.0.7599858"

Is is necessary to clean the project somehow to be version  23.0.7599858 removed?

I try to call "briefcase create android" but the issue is still there.

**Comment by alemdisso** [comment]
same results here. Beeware tutorial worked fine until the briefcase build android step. As it was a new installation, I don't have version 19.2.5345600 available locally.
I have downloaded the zip with older NDK version, but not sure how to configure gradle (or briefcase) to find it.

**Comment by freakboy3742** [comment]
@jakub-vesely @alemdisso Thanks - that confirms the issue is with the Android project definition itself, not something platform specific. We're looking into it; see #607 for progress updates.

**Comment by plr0201** [comment]
![image](https://user-images.githubusercontent.com/16219779/130343792-867d54a9-30b8-4e41-a750-db62023165f6.png) @alemdisso See above for the locally downloaded ndk, and add the version number to app/build.gradle before build.

**Comment by amaj1407** [comment]
@jakub-vese, I am sorry for not being clearer. I already had NDK version 19 locally downloaded under $Android_SDK/ndk/android-ndk-r19c, then I get the version string from the file **source.properties** inside android-ndk-r19c.

After that the build was successful and I was able to run my app on oy device.

**Comment by alemdisso** [comment]
Txs @plr0201

I am having problem to find where is this .briefcase...

I was trying the Beeware tutorial on a Windows10 system (in a conda environment). I called briefcase build android, but it didn't complete the task due to this NDK issue and I can't figure out where are the files that were downloaded during the process. 

Just thinking if I should go two steps back and install Android Studio.

**Comment by plr0201** [comment]
You should have the folder in your account folder, where you have your desktop, one drive folder. 

> Txs @plr0201
> 
> I am having problem to find where is this .briefcase...
> 
> I was trying the Beeware tutorial on a Windows10 system (in a conda environment). I called briefcase build android, but it didn't complete the task due to this NDK issue and I can't figure out where are the files that were downloaded during the process.
> 
> Just thinking if I should go two steps back and install Android Studio.
You should have the folder in your account folder, where you have your desktop, one drive folder.

**Comment by alemdisso** [comment]
Thank you again @plr0201. This worked for me

**Comment by plr0201** [comment]
You are welcome
