### ISSUE TITLE
"briefcase build iOS" fails with "Xcode is not installed. You can install it......." on MacOS Big Sur with Xcode 12.5 installed and working.

### ISSUE THREAD

**Issue by gsim** [beeware/briefcase#622]
Following the beeware "Hello World" online tutorial ends in failure at the final stage of trying to build for iOS, stating that Xcode is not installed, despite Xcode being installed and working ,as well as the Xcode command line tools. In my case I installed Xcode 12.5

It turn out the error is 100% due to the line where the Xcode location is hard coded :  **xcode_location='/Applications/Xcode.app'**. This is in _/beeware-tutorial/beeware-venv/lib/python3.8/site-packages/briefcase/integrations/xcode.py_.

I had downloaded Xcode using the Apple Installer and installed it on a different drive, i.e. not in /Applications, the default.

Simply changing the **xcode_location** to my real location fixed the problem, and it compiled 100% with 'briefcase build iOS' and ran with 'briefcase run iOS'.

**Comment by freakboy3742** [comment]
Thanks for the report. This is an edge case, but definitely one that we should account for.

One detail to confirm as part of release testing: what happens on a clean machine when Xcode isn't installed yet. macOS dev tools have an unfortunate habit of *always* existing in stub form, but if you invoke the tool when it hasn't been installed, it throws up a prompt to trigger the installation process. We need to make sure this case is caught when you invoke `xcode-select -p`.

**Comment by gsim** [comment]
All good, so as things stand the message to install xcode should also include instructions to run `xcode-select --switch /location` string if installed in a different location to default.

To complicate things slightly, I installed xcode 13 also using the Downloader App, and also to the second hdd. Sadly trying to run xcode 13 aborts with a crash report about missing libraries so I still need to figure that one out. However, from what I can tell you can have xcode 12 and xcode 13 on the same machine. In light of the crash I need to confirm this still. If it is the case we would have to assume the `--switch` has already being used and the user has selected the default version required correct? This is assuming the build script did find xcode using `xcode-select -p`.

**Comment by gsim** [comment]
Just FYI. I downloaded Xcode from the app store after setting up a new VM, and this time it actually finished downloading. It then installed some extra stuff, and Xcode 13 is now working. So it seems the version in the downloaded app is at fault.

Ok that is enough info to go on to get things done. I am a bit pressed for time at the mo, so will get to dealing with this again in a day or three. Blessed for work lately :)
