### ISSUE TITLE
Add option to fallback for using different Python version

### ISSUE THREAD

**Issue by eliasdorneles** [beeware/briefcase#63]
Currently, we only use the template and support package for the user's running Python version.
It would be nice to allow users to override this, making it easier for people using the most recent Python versions (and maybe even the release candidates) to try things out.

It would be great to be able to do `python setup.py ios --use-python-version=3.6` =)

**Comment by dasdachs** [comment]
I'd love to give it a go. I understand how to add the flag, but I have yet to wrap my head around the idea how the Python interpreter is passed. Does it rely on the `_python_version`method?

**Comment by freakboy3742** [comment]
@dasdachs I'm not entirely sure which `_python_version` method you're referring to; but there are two key problems that need to be solved here. The first is selecting the right template (`generate_app_template()`) and support package (`find_support_package()`). The second is to download and install packages from PyPI that are version/platform appropriate (`install_app_requirements()` and `install_platform_requirements()`). You need to account for Python version (3.5 or 3.6), platform (mac? iOS? windows?), and Python build type (Python 3.6 or 3.6m) when requesting the package from PyPI.

**Comment by eliasdorneles** [comment]
The `_python_version` referred to is probably [this one](https://github.com/pybee/briefcase/blob/dd31aed871e4ad25cfa2c580ef665207d8596592/briefcase/app.py#L178-L180) that was introduced recently, it's used for selecting the right template.

**Comment by dasdachs** [comment]
@eliasdorneles That is it, thank you.

@freakboy3742 Thank you for the clarification. I think I have a better understanding of the process. I'll give it my best, write some tests and return the favour with a decent pull request.

**Comment by loganasherjones** [comment]
I'm at the PyCon sprints and will be attempting to solve this problem

**Comment by loganasherjones** [comment]
Ok, I happen to be working on Linux, which makes this a little bit odder. 

Right now, the linux distribution command (`python setup.py linux`) will generate a bash script that points to a python3 environment that should just be installed. 

So, for me to test this personally, it would be better to first start tackling flatpak distrubtion (#2). Others on apple/Windows might have more success testing this.

**Comment by freakboy3742** [comment]
On reflection, I'm not convinced this is necessarily a good idea - it has the potential to cause all sorts of problems when installing support packages, as the version of pip used to install dependencies will mis-identify the package versions that are valid.
