### ISSUE TITLE
Adding documentation for packaging a MacOS app for distribution

### ISSUE THREAD

**Issue by LinasNas** [beeware/briefcase#639]
**Is your feature request related to a problem? Please describe.**
Beeware's documentation currently stops short of guiding users through the process of signing and notarizing a MacOS app for distribution. These steps are quite essential for users to share the apps they had built using briefcase commands. Based on my own experience, figuring out this process isn't an easy task, especially if one is new to the whole workflow of using Apple's signing identities. 

**Describe the solution you'd like**
It would be great to add documentation that:
1. Introduces users to Apple's Code Signing identities, and guides them through the process of creating one. The documentation currently seems to be [empty](https://briefcase.readthedocs.io/en/latest/how-to/code-signing/macOS.html).
2. Explains the code signing procedure with the command ```briefcase package -i <identity>```. Based on the [source code](https://github.com/beeware/briefcase/blob/16635da7ca06cf3c08cca224270d85bf45cb7e23/src/briefcase/commands/package.py) this seems to be the preferred command on briefcase, which worked in my case.
3. Explains the notarization procedure. Signing the app isn't sufficient to distribute it to others, as the resulting app isn't notarized. Notarization can be implemented relatively easily with the ```xcrun notarytool``` command, and the resulting ticket stapled with ```xcrun stapler staple``` to the dmg file. 

I've tested this workflow by packaging, signing and notarizing the Hello World app, and it seems to work well. I could submit a pull request that adds these instructions to the documentation.

**Comment by freakboy3742** [comment]
Completely agreed - that's why it's already logged as #365. See also #626 for some related changes needed for code signing. 

At the very least, we should document the process; but ideally we'd have an automated (or at least semi-automated) integration into the `package` command.
