### ISSUE TITLE
Provide an increased verbosity debug option

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#640]
When Briefcase works well, it's great. However, sometimes, things go wrong - and it's often difficult to diagnose why.

However, Briefcase is only a wrapper around a variety of command line calls. For diagnostic purposes, it would be helpful to be able to ask a user to turn up the verbosity setting, so they can see *exactly* what commands are being issued, in what environment, and what is being returned.

**Describe the solution you'd like**

A user can invoke:

    $ briefcase <command> --debug

To start Briefcase in debugging mode. This doesn't change anything about how Briefcase actually works; but every time it calls `subprocess.run()` or equivalent, it prints to the console:

* the full command line that was executed, in a way that can be copy-and-pasted to a terminal to reproduce the same effect
* the value of all environment variables at the time the command was executed
* the return value of the command
* if possible/appropriate, any console output that is hidden from the user in "normal" operation.

Debugging console output should be clearly differentiated from "normal" briefcase output; for example, by prefixing any debug command with `>>>`, and providing annotations to differentiate between environment variables, command line, output and return codes:
```
$ briefcase run android --debug
Starting emulator beePhone...
>>> Environment: 
>>>     ANDROID_SDK_ROOT=/Users/someone/.briefcase/...
>>>     JAVA_HOME=/Users/someone/.briefcase...
>>> Run:
>>>      /Users/someone/.briefcase/tools/android/emulator @emulator-5554 -dns-server 8.8.8.8
>>> Output:
>>>      ... some command output...
>>>      ... some command output...
>>> Return code: 0
```

**Additional context**

Linux commands can be issued inside Docker; we will need the output of the full Docker command line, not just the command that is executed inside docker.

**Comment by tusharjayaram** [comment]
I'm a first timer and would like to contribute tot his code update for the project. I've read the contributing guidelines and plan to fork a repo locally in the next day or so. Let me know if there's anything else I need to do. Thanks!

**Comment by freakboy3742** [comment]
@tusharjayaram Welcome! There's nothing else specific you need to do, other than "add the feature" :-) If you need any pointers or suggestions, yell out and we'll do what we can to help!

**Comment by devdev29** [comment]
Is this issue still open to PRs? The feature seems to have been implemented already in the subprocess.py file.

**Comment by freakboy3742** [comment]
@devdev29 Yes, it's still open; the runtime environment and return code isn't currently output as part of the current implementation.

**Comment by freakboy3742** [comment]
Clarifying the feature request in this ticket - `-vv` already exists, which dumps the contents of the command line; however, the contents of the environment, the command output, and the return code are not not output.
