### ISSUE TITLE
Remove previous install artefacts when updating app_packages

### ISSUE THREAD

**Issue by samschott** [beeware/briefcase#644]
**Describe the bug**
When running `briefcase update -d`, all `app_packages` are reinstalled. However, old metadata folders (dist-info) and .so files will linger on in the `app_packages` directory. They will eventually accumulate.

**To Reproduce**
Run `briefcase update -d` after one of the dependencies has had a new release.

**Expected behavior**
It would be nice to prune such unwanted files.

**Additional context**
I can see two obvious solutions to this:

1. Completely clear the `app_packages` folder before installing updated dependencies.
2. Explicitly run a `pip uninstall` on the current dependencies first. This has the disadvantage of not removing any dependencies which are no longer required in `pyproject.toml`.

Maybe there are other options as well.

**Comment by freakboy3742** [comment]
Absolutely agreed - this sort of cleanup is something we should definitely be doing - if only to avoid unexpected surprises when a package is no longer in `pyproject.toml`, but *is* referenced in code. It should be a relatively straightforward cleanup - we need to purge the `app_packages` folder before installing dependencies.

**Comment by SamSchott** [comment]
I did not see the "first-timers-only" label before submitting a PR. Sorry!

**Comment by freakboy3742** [comment]
Heh - no worries! I thought this might be a nice easy win for a first-timer. If it's causing you enough problems that you're motivated to fix it, I'm not going to turn down a PR :-)
