### ISSUE TITLE
fail 'briefcase create' on xubuntu.

### ISSUE THREAD

**Issue by binooetomo** [beeware/briefcase#651]
**Describe the bug**
Fail 'briefcase create' on xubuntu
**To Reproduce**
1. go to https://docs.beeware.org/en/latest/index.html
2. Follow tuttorial 0-2, make sure it run without problem
3. follow tutorial 3

**Expected behavior**
producing linux app image

**Screenshots**

**Environment:**
 - Operating System: Xubuntu focal
 - Python version: 3.8.10
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: I don't know
   - ...

**Additional context**

error code :
...
```
Step 7/18 : RUN apt-add-repository ppa:deadsnakes/ppa
 ---> Running in 0e978b500b62
Cannot add PPA: 'ppa:~deadsnakes/ubuntu/ppa'.
The team named '~deadsnakes' has no PPA named 'ubuntu/ppa'
Please choose from the following available PPAs:
 * 'nightly':  nightly python builds
 * 'ppa':  New Python Versions
The command '/bin/sh -c apt-add-repository ppa:deadsnakes/ppa' returned a non-zero code: 1

Error building Docker container for helloworld.

```...

**Comment by freakboy3742** [comment]
I can only assume this was a transitory error with the Deadsnakes repo, or something particularly unusual about Xubuntu or your local connection. Deadsnakes definitely exists, and I can confirm the docker container currently builds.
