### ISSUE TITLE
Unhelpful --help for "briefcase package linux --formats"

### ISSUE THREAD

**Issue by phlummox** [beeware/briefcase#654]
**Describe the bug**

The only output format `briefcase` supports for Linux is, in fact, appimage. That being so, the output of `briefcase package linux --formats` is misleading, since it holds out the false hope that briefcase might support the following

```
Available formats for linux: appimage, deb, flatpak, rpm, snap
```

This is, obviously, not correct. If the tool doesn't support a format, please don't say it does! That just irritates users.

**To Reproduce**
1. Install briefcase somehow
2. Run `briefcase package linux --formats`. Observe that it lists 5 different formats.
3. Run `briefcase package linux *[format]*` for every single format except appimage.
4. Observe that all of them give the output
   ```
   The package command for the linux *[format]* format has not been implemented (yet!).
   ```

**Expected behavior**

An accurate list of what formats are supported.

**Environment:**
 - Operating System: Linux
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev30

**Comment by freakboy3742** [comment]
Fair call - this is an example of something where the backend *exists*, and has been registered, but hasn't been fully implemented. deb/flatpak etc are *legal* from the perspective of the command line... they just won't do anything (yet!).

This should be a fairly straightforward fix - we just need to comment out the registration of these backends until they actually exist. The relevant code is in the setup.cfg file for Briefcase if anyone wants to try their hand at a patch.

**Comment by euhidaman** [comment]
I am a beginner, and I was trying to make this patch.

So, after commenting out the not-yet-working formats in `setup.cfg`.
I was thinking about changing the prompt, which shows the various formats for `Linux`, other than `appimage`.
i.e, I was hoping to show only `appimage`, for the command : `briefcase package linux --formats`

Any help would be really appreciated, as this is my time trying to contribute to a big project.

**Comment by freakboy3742** [comment]
@euhidaman It sounds like you've found the right code to patch; however, to make that change take effect, you need to re-run the pip install so that the hooks re-register themselves. If you run `pip install -e .` on your modified code checkout, you should discover that the entry points are removed.

**Comment by euhidaman** [comment]
@freakboy3742 
I have tried to fix this issue, and created a necessary pull request #655  with my changes.
Please have a look.
