### ISSUE TITLE
AppImage's window is not associated with its .desktop file

### ISSUE THREAD

**Issue by jhakonen** [beeware/briefcase#661]
**Describe the bug**
AppImage built with briefcase and installed to desktop environment does not have its .desktop file associated with the app's window.
In Gnome if you add the app to favorites and then start the app, it will have two icons in dock, one for .desktop file and another for app's window.

**To Reproduce**
1. Create new Toga project using default answers with:
```bash
cd ~
briefcase new
cd helloworld
```
2. Then build AppImage:
```bash
briefcase build
```
3. Install built AppImage to your desktop enviroment using [Appimaged](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md) by copying the AppImage to a folder that Appimaged watches:
```bash
cp linux/Hello_World-0.0.1-x86_64.AppImage ~/Applications/
```
4. Find the installed "Hello World" from Gnome's app launcher, right click it, and add it to favorites.
5. In the dock (I'm using [Dash to Dock](https://github.com/micheleg/dash-to-dock) which comes preinstalled with Pop!_OS) click "Hello World"'s item and the app will launch, but it spawns another icon to the dock instead of showing the favorited item as having an window open (small dot below the icon). The favorited app item and app's window item have different context menus:

![desktop-item](https://user-images.githubusercontent.com/1950698/151229694-abf3fa74-ceaf-4967-a0b1-da1ea9297242.png)

![window-item](https://user-images.githubusercontent.com/1950698/151229711-f70ac2f0-3a93-4e64-97f1-daaa2ebe262b.png)

**Expected behavior**
When the app is launched the dock should just add the small dot below app's icon, instead of spawning new item for app's window:

![associated-item](https://user-images.githubusercontent.com/1950698/151229735-0ee95063-7a31-4aac-acf7-1b4d5f7a8d75.png)

**Workaround**
1. Download and extract appimage template:
```bash
cd ~/helloworld
wget https://github.com/beeware/briefcase-linux-appimage-template/archive/refs/heads/3.8.zip -O briefcase-linux-appimage-template-0.8.zip
unzip briefcase-linux-appimage-template-0.8.zip
```
2. Add the template to `pyproject.toml` under section `[tool.briefcase.app.helloworld]`:
```
template = 'briefcase-linux-appimage-template-3.8'
```
3. Add `StartupWMClass` option to `.desktop` file within the template folder:
```
StartupWMClass={{ cookiecutter.formal_name }}
```
4. Remove old `linux` folder (see bug: https://github.com/beeware/briefcase/issues/660):
```bash
rm -rf linux
```
5. Build and install the app again:
```bash
briefcase build
cp linux/Hello_World-0.0.1-x86_64.AppImage ~/Applications/
```
6. Launch the app, by clicking its icon in the dock, and now there's only one icon visible, like in the screenshot at "Expected behavior".

**Environment:**
 - Operating System: Pop!_OS 20.04
 - Python version: 3.8.10
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev30

**Comment by freakboy3742** [comment]
Thanks for the report! Definitely appears to be undesirable behavior; any assistance in correcting the config or build to avoid the problem would be appreciated. If you need any assistance or pointers on the Briefcase side of things, let us know and I'm happy to assist.

**Comment by jhakonen** [comment]
Thanks, I could try fixing this

**Comment by jhakonen** [comment]
alright, I've created two PRs which should fix this:
- change to `briefcase-linux-appimage-template` sets project's formal name to `StartupWMClass` just like in the workaround above, and
- change to `briefcase-template` adds template code for PySide2 and PursuedPyBear projects for setting their WMCLASS to app's formal name so that the .desktop association would work for those projects too.
