### ISSUE TITLE
When following Tutorial, Git connection fails..

### ISSUE THREAD

**Issue by oha0** [beeware/briefcase#666]
**Describe the bug**
After installing Git, briefcase,
See error ; Briefcase requires git, but it s not installed (or is not on your PATH). 

**To Reproduce**
1. after installing python -m venv myvenv
               myvenv\scripts\activate.bat
        and (myvenv)D:\...>python -m pip install briefcase
2. when entered ; (myvenv) D:\...>briefcase new
3. See error ; Briefcase requires git, but it s not installed (or is not on your PATH). ...

**Expected behavior**
Briefcase will ask us for some details of our new application. For the purposes of this tutorial, use the following: tutorial1
**Screenshots**
![image](https://user-images.githubusercontent.com/76195167/152906363-6e7fc618-c940-45d6-8af0-394a747b6168.png)

**Environment:**
 - Operating System: Windows 10 professional
 - Python version: 3.9
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: ?
   - ...

**Additional context**
git path has no problem.
![image](https://user-images.githubusercontent.com/76195167/152907096-4addcfb0-a84b-42dd-b3f0-382cf8515055.png)
When I use git from cmd window, it works well.
![image](https://user-images.githubusercontent.com/76195167/152907372-dd0717ea-3772-4671-a8a3-6ea08dfdb3ee.png)

**Comment by freakboy3742** [comment]
Thanks for the report! The issue here is the autodetection that briefcase does to autodetect git; I'm guessing something about your locale is causing a problem.

The test is being performed by the `GitPython` library; you can reproduce the test by opening a Python prompt inside your active virtual environment (i.e., the same environment where Briefcase is installed) and running:

```
import git
```

This will raise an `ImportError`; it should also provide a little more detail about exactly what isn't working. Can I get you to run that and post the stack trace/error log that you see?

**Comment by oha0** [comment]
> 
Thank you for your fast reply. When I tried below,

D:\gitdata\a>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import git
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'git'
>>>

I think git for windows is installed by [ Git-2.35.1.2-64-bit.exe ]. Is there any

**Comment by freakboy3742** [comment]
If `import git` is failing, then `GitPython` isn't installed. Did you run python from within the *active* Briefcase virtual environment? the `D:\gitdata\a>` prompt suggests you didn't.

**Comment by oha0** [comment]
> If `import git` is failing, then `GitPython` isn't installed. Did you run python from within the _active_ Briefcase virtual environment? the `D:\gitdata\a>` prompt suggests you didn't.
I was confused.. I tried again ; 

(myvenv) D:\gitdata\a>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import git
Traceback (most recent call last):
  File "D:\gitdata\a\myvenv\lib\site-packages\git\__init__.py", line 87, in <module>
    refresh()
  File "D:\gitdata\a\myvenv\lib\site-packages\git\__init__.py", line 78, in refresh
    if not FetchInfo.refresh():
  File "D:\gitdata\a\myvenv\lib\site-packages\git\remote.py", line 304, in refresh
    if Git().version_info[:2] >= (2, 10):
  File "D:\gitdata\a\myvenv\lib\site-packages\git\cmd.py", line 678, in version_info
    return self._version_info
  File "D:\gitdata\a\myvenv\lib\site-packages\git\cmd.py", line 637, in __getattr__
    return LazyMixin.__getattr__(self, name)
  File "D:\gitdata\a\myvenv\lib\site-packages\gitdb\util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "D:\gitdata\a\myvenv\lib\site-packages\git\cmd.py", line 658, in _set_cache_
    version_numbers = process_version.split(' ')[2]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\gitdata\a\myvenv\lib\site-packages\git\__init__.py", line 89, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: list index out of range
>>>

Then, what should I do?

**Comment by oha0** [comment]
> GitPython
In the active Briefcase virtual environment, when I tried below, it says it is installed.
(myvenv) D:\gitdata\a>python -m pip install gitpython
Requirement already satisfied: gitpython in d:\gitdata\a\myvenv\lib\site-packages (3.1.26)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\gitdata\a\myvenv\lib\site-packages (from gitpython) (4.0.9)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\gitdata\a\myvenv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.0)

**Comment by freakboy3742** [comment]
It looks like your version of `git` is returning a unexpected version string in code. Looking closer the `git version 2.35.1.windows.2` looks a little unusual - Is this an official release of git? Or have you got it from a different source?

**Comment by oha0** [comment]
> 
it is from git-scm/download page.. for win64 system. Should I download different version?

![image](https://user-images.githubusercontent.com/76195167/152924299-e495a00f-a75a-4c9b-8e17-e6e394af1e5a.png)

**Comment by freakboy3742** [comment]
That version of Git should be OK; and I've just confirmed that the version string being returned is consistent with what I'm seeing on my installs. However, I can't reproduce the problem you're seeing.

The best debugging advice I can provide at this point is to set a breakpoint where the exception is occurring (` File "D:\gitdata\a\myvenv\lib\site-packages\git\cmd.py", line 658, in _set_cache_`), and see what the contents of process version is. I assume there is something going on with the way git is being invoked; my guess will be that it has something to do with your language locale.

**Comment by freakboy3742** [comment]
We've just added improved logging when things break; could I ask you to 
1. Install Briefcase 0.3.8, 
2. Re-run your example, and
3. Send us the .log file that is generated by that run?

**Comment by freakboy3742** [comment]
Closing due to lack of response; if you are able to provide the requested diagnostic details, we can reopen.
