### ISSUE TITLE
Question (docs bug?) - release APK?

### ISSUE THREAD

**Issue by waynew** [beeware/briefcase#683]
Hi - first off, definitely loving beeware, it's ridiculously cool being able to use Python to write an actual Android app.

I've looked at [the tutorial for building for android](https://docs.beeware.org/en/latest/tutorial/tutorial-5/android.html#), I've ran the `-h`elp message for:

- `briefcase build -h`
- `briefcase build android -h`
- `briefcase -h publish`
- `briefcase -h package`
- `briefcase build android gradle -h`

Among several other commands/options. I've spent quite a bit of time searching Google and came across https://github.com/beeware/Python-Android-support/pull/12 which has this comment: https://github.com/beeware/Python-Android-support/pull/12#pullrequestreview-417241028

I don't know if it's just me, but my pretty basic "hello world" app produces a 50M apk (under app/build/outputs/apk/debug/my-app.apk) which doesn't seem very in line with the 6MB or 20MB support package, unless there's just a whole extra 30-44MB of "other stuff".

My assumption is that given the directory name it's building a debug apk with a whole bunch of debugging symbols and code added, which is definitely cool for debugging, but my question:

**Is it possible to generate a smaller APK, and if so, how?**

As mentioned, I've gone looking in a ton of places and have failed to find anything. I did discover that I could `briefcase package android` but that looks to have just built an `.aab` ffile (which is 66MB), but it doesn't appear to have built any slimmer APK.

**Comment by freakboy3742** [comment]
Yes with an if, no with a but :-) 

It *is* possible to make a smaller APK, but it's not easy (or a simple "just pass the `--make-it-smaller` flag). That said, the problem may not be as bad as you think it is.

First off - yes, you can make the APK smaller. The Python support package includes a *full* Python install. Does your app make use of the `shelve` module? `multiprocessing`? How about `aifc`? Well, those modules are included in the standard library, and as a result, they're in your app as well. A little bit at a time, those modules all add up - especially when they involve a binary component. However, those modules *don't* technically need to exist for Python to start. If you want, you can delete the module from the standard library, and your app will be smaller as a result. 

At present, the way you'd do this is to make a custom build of the support package that does a "delete the stuff I don't need" phase as a final step before zipping the package. (You could also do this by manually post-processing the official support package). This is something that needs to be done on an app-by-app basis - your app will have unique requirements. 

Longer term, there are two possible approaches that we could take. 

The first is a "Minimum Viable Python" - the idea of a Python distribution where the only part of the standard library that is provided out of the box are the parts that *must* exist (like `sys`); and everything else (all the batteries that are normally included) are provided as PyPI packages. This would be my preferred solution, but it needs some cooperation from the core Python team, as they would need to publish all the standard library to PyPI as individual modules. This has been discussed at various times, but the conversations have stalled for various reasons.

The second option is "Tree shaking" - a process that looks at the code for an app, does a static analysis, and deletes all the code that isn't being used. This is obviously a little dangerous - if you dynamically load a module using a string name, for example,  it won't be easy to identify from static analysis that the module is used - but it's a solvable problem if you allow for manually defined inclusion/exclusion lists.

However - the problem may not be as bad as you think it is. Yes, your app is 66MB. What you may not realise is that internally, that AAB file is actually *4* apps - one for each CPU architecture that is supported (386, x86_64, ARMv7 and ARM64). You need to upload all 4 to the App Store, but when the app is delivered to your device, only the one that matches your device's native architecture is sent. So, while the AAB file is 66MB, the actual delivered file is likely closer to 18-20MB. That's still bigger than I'd like it to be... but it's 1/4 the size you originally thought.

**Comment by freakboy3742** [comment]
Closing on the basis the question has been answered.
