### ISSUE TITLE
Briefcase installs 64-bit app to C:\Program Files(x86)\

### ISSUE THREAD

**Issue by t-arn** [beeware/briefcase#688]
**Describe the bug**
My Windows app with system_installer = true is installed in a subdirectory of C:\Program Files(x86)\

**To Reproduce**
1. set system_installer = true in Windows section of pyproject.toml
2. briefcase package winforms
3. install the msi package

**Expected behavior**
Since the Python support package is 64-bit, the app should be installed in a subdirectory of C:\Program Files\

**Environment:**
 - Operating System: Windows
 - Python version: 3.9
 - Software versions:
   - Briefcase: 0.3.6

**Comment by freakboy3742** [comment]
Thanks for the report; from [a quick poke around](https://stackoverflow.com/questions/4304253/how-do-i-get-wix-to-generate-a-64-bit-msi), it appears that the underlying cause are some options in the WIX configuration file that are needed to flag the install product as being 64 bit; plus possibly an extra flag needed when invoking `candle`.

**Comment by freakboy3742** [comment]
Fixed In #775.
