### ISSUE TITLE
Windows 11 Briefcase create Android application fails

### ISSUE THREAD

**Issue by Felix3qH4** [beeware/briefcase#693]
**Describe the bug**
I followed the tutorial on www.docs.beeware.org on how to 1) create a new project for a GUI application and 2) how to package it for Android (create an apk).
I didn't change anything on the application, I tried to create the apk immediately after creating a new application.
But instead of packaging the application, I get the error "java.nio.file.FileAlreadyExistsException"

**To Reproduce**
1. in cmd: "briefcase new"
2. enter all the information and let it create a new project
3. then enter "briefcase create android"
4. then "briefcase build android"
5. Error occurs at around 50%

**Expected behavior**
Package the newly created application for Android.

**Environment:**
 - Operating System: Windows 11 Enterprise x64
 -  OS Version: 21H2
 - OS Build: 22000.556
 - Processor: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz  3.70 GHz
 - RAM: 16GB
 - Python version: Python 3.9.10
 - Software versions:
   - Briefcase: 0.3.6
   - Toga: 0.2.15
   - git version 2.35.1.windows.2
   - pip 22.0.4 from python 3.9

**Additional context**
Short version of the error is as follows and long version can be found in file.
```
> Task :app:mergeDebugAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$RunnableWrapperWorkAction
   > java.nio.file.FileAlreadyExistsException: G:\Meine Ablage\OCOPY\Python\BeeWare\Moyenn\v3\moyenne\android\gradle\Moyenne\app\build\intermediates\merged_assets\debug\out\python

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
14 actionable tasks: 14 executed

Error while building project.


```
COMPLETE ERROR:
[output.txt](https://github.com/beeware/briefcase/files/8382324/output.txt)

**Comment by freakboy3742** [comment]
Thanks for the report! That's a very unusual error - I can't say I've seen that one before. 

My best guess is that something is happening with the way that Gradle is resolving which tasks can be run in parallel; this is it's failing, and multiple tasks are trying to write over themselves.

As for why that's happening... I don't know. My only guess here is that it might be about where your project is located. Based on the full log, your project code is on a G: drive. This suggests it may not be a local drive - Is there anything notable about the G drive? If it is a network drive, filesystem operations may not be operating in a way that Gradle expects. You may have more success running on a local drive.

Another approach is to try an work around the problem by disabling Gradle's parallelisation. After you run `briefcase create android`, try adding the following two lines to the end of the `gradle.properties` file that is in the root of the `android` folder:
```
org.gradle.parallel=false
org.gradle.workers.max=1
```

and then run `briefcase build android`. This should disable parallel builds, which may avoid the issue.

**Comment by Felix3qH4** [comment]
Thank you for your quick answer.
The G: drive is a network drive which is created by the Google Drive application to sync my files on different computers.
So I tried running it on my local C: drive and it worked as expected, so no errors.
You may be right with the assumption that Gradle does not like network drives as I didn't change anything but it worked on my local drive.
So thanks for your help and also for this amazing project. Its nice to see people committing to open source projects and creating amazing applications. It makes it so much easier to build applications for mobile devices without having to learn Java or Swift, especially for not too advanced programmers like me, so I really appreciate your work.
