### ISSUE TITLE
ModuleNotFoundError: No module named 'test'

### ISSUE THREAD

**Issue by tusharhero** [beeware/briefcase#711]
**Describe the bug**
Can't import any python scripts as modules

**To Reproduce**
1. run 'briefcase new' and continue with defaults
2. create test.py in helloword/src/helloword and add a dummy function 
`def help():
    print("help me")`
3. edit app.py and add `from test import help`
4. run `briefcase dev`
**Expected behavior**
Runs peacefully without errors and prints "help me" in the terminal

**Screenshots**

**Environment:**
 - Operating System: Garuda Linux
 - Python version: 3.10.4
 - Software versions:
   - Briefcase: 0.3.6
   - Toga: 0.3.0.dev32
   - ...

**Additional context**

**Comment by freakboy3742** [comment]
Based on those details: If you're creating a `test.py` inside `src/helloworld`, the module isn't called `test`, it's `helloworld.test`. On that basis, `from helloworld import test` or `import helloworld.test` should work.
