### ISSUE TITLE
Can not approve Google license terms

### ISSUE THREAD

**Issue by SMErfanMoosaviM** [beeware/briefcase#712]
**Describe the bug**
I installed the Android SDK manually by setting the ANDROID_SDK_ROOT variable to point to the folder containing 'tools' folder  and it worked and I passed the SDK downloading part. But after that it prints out the following message and stuck:
```
(venv) C:\Users\uname\path\beeware-tutorial\helloworld>briefcase create android

    The Android tools provided by Google have license terms that you must accept
    before you may use those tools.

[=========                              ] 25% Fetch remote repository...   
```
It is worth mentioning that I can not connect to Google servers due to some restrictions, so I download everything that needed from those server manually and put them to the correct location (Like the ANDROID_SDK). I think this issue caused by those restrictions too, so is there any workaround to fetch the file needed manually? From which URL I can download them? Where can I put the downloaded files?

**To Reproduce**
run: briefcase create android

**Expected behavior**
Asks me whether I accept or not.

**Environment:**
 - Operating System: Windows 11
 - Python version: 3.10.1
 - Software versions:
   - Briefcase: 0.3.6
   - Toga: 0.3.0.dev32
   - SDK: sdk-tools-windows-4333796

**Comment by freakboy3742** [comment]
While I'm very much sympathetic to your request, I'm not sure there are any real options here. Android's tooling is built assuming that you have access to an open network connection, especially during initial setup. 

To the best of my knowledge, it isn't possible to set up in an entirely offline manner. You could manually perform the initial download, but this download is really just a bootstrap; the bootstrap then performs various update checks and dependency downloads at largely unpredictable times. 

As a result, this isn't a bug, it's a feature request; and I'm going to close this as a "won't fix" - although it's more of a "I don't think this *can* be fixed". If anyone were to make a *specific* suggestion of ways that offline operation could be improved (e.g., #388 is already tracking template access while offline - something that *is* under Briefcase's control), I'm open to those suggestions - but as it stands, Android's tooling is fundamentally incompatible to offline operation, and I don't think there's much we can do about that. Briefcase is ultimately a wrapper around the tools that native platforms provide, so if the native platform tooling doesn't support a feature, there's nothing we can do to rectify that.
