### ISSUE TITLE
Briefcase run command not workind

### ISSUE THREAD

**Issue by adetobi22** [beeware/briefcase#730]
### Discussed in https://github.com/beeware/briefcase/discussions/729

<div type='discussions-op-text'>

<sup>Originally posted by **adetobi22** May  3, 2022</sup>
Briefcase run command not working, unable to start app.
I have listed the required dependencies in the pyproject.toml  ( in my case it's just httpx) , i ran update update -d and build again. but the run command still doesn't work , it keeps displaying " unable to start app.</div>

**Comment by freakboy3742** [comment]
There's no need to open both a ticket and a discussion for the same problem. Closing on the basis that I'm fairly certain this will be an error of usage; if it turns out not to be, we can open a ticket.
