### ISSUE TITLE
Android emulator on M1 doesn't display skin

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#736]
When you run an Android emulator on M1 hardware, the device skin is not displayed.

**To Reproduce**
1. Generate a "hello world" app 
2. `briefcase run android`
3. Emulator starts, but does not display the device skin.

<img width="563" alt="Screen Shot 2022-05-11 at 9 18 49 am" src="https://user-images.githubusercontent.com/37345/167749853-d3653635-7917-45bb-b50c-62c9cc32b569.png">

**Expected behavior**

The emulator should display the device skin:

<img width="483" alt="Screen Shot 2022-05-11 at 9 16 38 am" src="https://user-images.githubusercontent.com/37345/167749679-ac6fdd1c-0543-4b83-aa4c-08b1251bdb1e.png">

**Screenshots**

**Environment:**
 - Operating System:
 - Python version:
 - Software versions:
   - Briefcase:
   - Toga:
   - ...

**Additional context**

If you run the emulator on x86_64 hardware, the skin *is* displayed. On M1, the skin has been downloaded, and appears to be configured the same as it is on x86_64.

If you start the emulator with the -skin and -skindir arguments, the skin is displayed. However, these arguments are deprecated; they are also problematic to include at time of execution, because the emulator could be configured at a size that is incompatible with a specific skin.

It is possible this is a limitation of the Android tools themselves. The M1 emulator is a recent addition to the Android toolchain. However, I have been unable to find any official statement that skins aren't a supported feature, or that this is a known bug.

**Comment by rmartin16** [comment]
I think Google claims to have resolved this with emulator v32.1.9.

https://issuetracker.google.com/issues/255333760
