### ISSUE TITLE
When importing module clipboard or pyperclip, briefcase run can't start the application

### ISSUE THREAD

**Issue by foxopop** [beeware/briefcase#826]
When you import clipboard, or pyperclip in your application, the command "briefcase dev" is OK, but the command "briefcase run -u" fails with the message "Unable to start app helloworld."

**To Reproduce**

1. Set up a hello world application

2. Import pyperclip :
        import toga
        from toga.style import Pack
        from toga.style.pack import COLUMN, ROW
        **import pyperclip**
 

**Expected behavior**
The command "briefcase run -u" should start the application

**Screenshots**
![image](https://user-images.githubusercontent.com/95481331/185098195-826911f8-f1bb-4740-ad75-910b661812c2.png)

**Environment:**
 - Operating System: Windows-10-10.0.19043-SP0
 - Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
 - Software versions:
   - Briefcase: 0.3.8
   - Toga: 0.3.0.dev35

**Additional context**

**Comment by mhsmith** [comment]
Briefcase 0.3.9 was released yesterday and significantly improves Windows error logging, so please try upgrading to that.

`briefcase dev` runs the app within your current virtual environment, so it has access to every package installed there. But `briefcase run` uses a separate environment, so you'll need to add the pyperclip package to the [`requires`](https://briefcase.readthedocs.io/en/latest/reference/configuration.html#requires) section of your pyproject.toml file, and then run `briefcase update -d`.
