### ISSUE TITLE
The Commits for the v0.3.9 Release are not in `main`

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#828]
**Describe the bug**
I noticed the `main` branch is still advertising itself as v0.3.8. Github is reporting the two commits that prepared the release aren't in the beeware/briefcase repo. I'm not sure I understand what happened or if github is lagging....but seemed worth a report.

https://github.com/beeware/briefcase/commit/1f321486061b7b4b7c93da526e214e138d173dff
https://github.com/beeware/briefcase/commit/d4dc16ddaa4dc2bd2e173aea002a5c88e9e8b0dd

**To Reproduce**
See https://github.com/beeware/briefcase/blob/main/src/briefcase/__init__.py

**Expected behavior**
I was expecting `main` to be advertising v0.3.9.

**Comment by freakboy3742** [comment]
Well that's just weird... Not sure what I missed on my release script (or how I can miss that step in my release script and still end up with a formal release that includes the 0.3.9 code), but I've corrected the problem now.

**Comment by mhsmith** [comment]
This is probably because the [release checklist](https://briefcase.readthedocs.io/en/latest/how-to/internal/release.html) contains a push for the tag but not for the branch.
