### ISSUE TITLE
Retaining pythonw.exe -m app functionality

### ISSUE THREAD

**Issue by MosGeo** [beeware/briefcase#838]
**Is your feature request related to a problem? Please describe.**
Sometimes, some users cannot run arbitrary executables but they are able to run python.exe and pythonw.exe without issues. The new stub app for windows is great (e.g., for displaying the crash error box) for providing these users with the last version of the software but it is hard to provide them with multiple test versions that they have to whitelist every time.

**Describe the solution you'd like**
1. Retain the ability to run the app through `python.exe -m app` and `pythonw.exe -m app`. 
2. Something extra would be to have a switch/option to define the shortcut type (shortcut to the exe or to the pythonw.exe).

**Describe alternatives you've considered**
These specific users would have to whitelist generated executables every time there is a new version.

**Additional context**
This might be considered as an edge case and I don't know how much effort is it to maintain/retain the old style.

**Comment by freakboy3742** [comment]
I'm not sure I understand what you mean by "whitelisted executables". 

The whole purpose of an MSI is to install software. In almost every language, this means installing an executable. Python using a consistent "python.exe" is an aberration, not the norm. 

Briefcase's stub app is an executable, packaged by the MSI, that starts the app. It is, functionally, indistinguishable (AFAICT) from "word.exe" or "excel.exe". 

What sort of "whitelist" are you using that requires specific flagging of executables that are being installed using the operating system-recommended tool for installing new software?

**Comment by MosGeo** [comment]
Completely agree with everything you mentioned here :) including the fact that python.exe is an aberration.

Whitelisting: some companies would prevent the execution of any .exe files unless it is in a 'whitelist' list. So they have to whitelist word.exe, excel.exe and so on. It is basically the opposite of blacklist. Everything is prevented from executing by default unless it is in a special list.

As I mentioned, it is an edge case.
