### ISSUE TITLE
Modify build image of AppImage template to use Ubuntu 20.04

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#839]
According to Github, by Dec 1 2022 they will [formally deprecate the Ubuntu-18.04 Actions runner](https://github.com/actions/runner-images/issues/6002). 

This puts Briefcase in an interesting situation. On the one hand Briefcase as used by end users is (mostly) unaffected - we encourage the use of Docker for building AppImages, and the Ubuntu 18.04 image will continue to exist. 

However, as a project, *we* have a problem. Due to historical issues using Docker in CI, we run our CI in `--no-docker` mode - which means that in December, we'll no longer be able to run CI for Linux. 

**Describe the solution you'd like**

Update the template and documentation to use Ubuntu 20.04 as the base image. 

This is something we've done before ([transitioning from 16.04 to 18.04 as the base image](https://github.com/beeware/briefcase-linux-appimage-template/commit/a172088d46f86b0a95799e8f03bc04149741c765). Interestingly, this was almost 2 years ago to the day, which matches the 2 year LTS release cadence of Ubuntu.

In addition to continued CI support, this has the added benefit that we'll have access to more recent packages in the base image.

**Describe alternatives you've considered**

1. Remove AppImages from our testing setup, but otherwise do nothing. Ubuntu 18.04 AppImage images will continue to work; they'll just be untested.
2. Modify CI to use Docker, but continue to use 18.04 as the base image. 
3. Deprecate the AppImage backend in favour of Flatpak.

**Additional context**

This may have some overlap with #824 - a switch of this magnitude requires some sort of control from a user perspective.

**Comment by mhsmith** [comment]
If possible, I think we should stop using `--no-docker` mode in the CI. It's not representative of what users will experience by default, and it's allowed at least one bug to slip through the CI testing (briefcase-template [#31](https://github.com/beeware/briefcase-template/pull/31) and [#32](https://github.com/beeware/briefcase-template/pull/32)).

**Comment by mhsmith** [comment]
Previous discussion: https://github.com/beeware/briefcase/issues/400#issuecomment-650800145.
