### ISSUE TITLE
Add ability to refresh support package

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#856]
The `briefcase update` command updates the user's code in a project, with options to also update dependencies (`-d`), and resources (`-r`). However, there is no ability to update the support package. This need doesn't arise often, but for completeness, it would be desirable to have this option.

**Describe the solution you'd like**

A new option `-s`/`--update-support` that updates the support package in an existing app.

**Describe alternatives you've considered**

The current workaround is to rebuild the app if you need to update the support package. This works, but is a sledgehammer approach.

**Additional context**

The general behavior will be very close to the behavior of the `-d` update dependencies option, so that implementation can be used as a point of comparison.

The code installing the support package will need to delete the existing support folder prior to unpacking the support package. This will need to check if the project *has* a support package - if the template doesn't define a `support_path`, then `update -s` will be a no-op.

**Comment by RHas** [comment]
Hi! I'm new to open source but would like to take a try at this problem. Would that be alright with you?

**Comment by freakboy3742** [comment]
@RHas Absolutely! If you need any pointers beyond what is on this ticket already, don't hesitate to ask!

**Comment by RHas** [comment]
@freakboy3742 Thank you! I'll be sure to reach out if there's anything I need clarification on or help with!

**Comment by freakboy3742** [comment]
#1240 has a really good implementation of the feature as described by this ticket... which then failed CI because the proposed design has a problem.

On Windows, and Linux AppImages (and potentially other platforms), the support package is co-mingled with the actually app. On Windows, the app binary is in the same folder that the support package is unpacked into. On AppImage, the support folder is `/AppImage/usr`; deleting `/AppImage/usr` predictably breaks everything.

I can think of a couple of approaches here:
1. Raise an error on platforms that can't support `--update-support`
2. Warn the user if the platform has a problem with `--update-support`, skip the "delete old support package" step, and just unpack into the existing folder. This should work in most cases, but could have some interesting side effects if a file is deleted between two generations of the support package.
3. Do a "best effort cleanup" before unpacking the new support package. Instead of just deleting the support folder, use the incoming support archive, look for all directories mentioned in the support archive, and delete *those* prior to unpacking the new support package. This won't be infallible, but should avoid the most common problems - i.e., a stray file that was removed between iterations.

My gut tells me that (2) is probably the best approach - "do your best but warn about problems".
