### ISSUE TITLE
Flatpak: Installing Python Dependencies in to the Flatpak uses the Host's pip Cache

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#858]
**Describe the bug**
Python packages that were built for the host system can be used and installed when building the Flatpak.

For instance, if a wheel was previously built for `pygobject` on my host system, it gets built using `libffi.so.8`. But if later a Flatpak is built that depends on `pygobject`, that same wheel is being reused instead of building a new one; this ultimately bombs out on my system since `org.gnome.Platform` only contains `libffi.so.7`.

**To Reproduce**
Verified for Ubuntu 22.04
1. `rm -rf ~/.cache/pip`
2. `python -m pip install --force --upgrade pygobject`
3. `briefcase new --no-input && cd helloworld && briefcase run linux flatpak`

```
[empty] Starting app...

>>> Running Command:
>>>     flatpak run com.example.empty
>>> Working Directory:
>>>     /home/user/tmp/beeware/empty
PYTHONHOME: /app
PYTHONPATH:
- /app/lib/python310.zip
- /app/lib/python3.10
- /app/lib/python3.10/lib-dynload
- /app/briefcase/app
Configure argc/argv...
Initializing Python runtime...
Application quit abnormally (Exit code -6)!
Traceback (most recent call last):
  File "/app/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/app/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/briefcase/app/empty/__main__.py", line 4, in <module>
    main().main_loop()
  File "/app/briefcase/app/empty/app.py", line 27, in main
    return empty()
  File "/app/lib/python3.10/site-packages/toga/app.py", line 278, in __init__
    self.factory = get_platform_factory(factory)
  File "/app/lib/python3.10/site-packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/app/lib/python3.10/site-packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/app/lib/python3.10/site-packages/toga_gtk/app.py", line 13, in <module>
    from .keys import gtk_accel
  File "/app/lib/python3.10/site-packages/toga_gtk/keys.py", line 3, in <module>
    from .libs import Gdk
  File "/app/lib/python3.10/site-packages/toga_gtk/libs/__init__.py", line 1, in <module>
    from .gtk import *  # noqa: F401, F403
  File "/app/lib/python3.10/site-packages/toga_gtk/libs/gtk.py", line 1, in <module>
    import gi
  File "/app/lib/python3.10/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libffi.so.8: cannot open shared object file: No such file or directory
>>> Return code: 250

Unable to start app empty.
```
You can also see in the log where a cached wheel for `pygobject` is being used.

**Expected behavior**
Wheels should only be installed in to the Flatpak sandbox if they were built in the sandbox.

**Environment:**
 - Operating System: Ubuntu 22.04
 - Python version: 3.10.7
 - Software versions:
   - Briefcase: 3e0e0c03b0c94b9b5be515f1f4d566289521367c

**Additional context**
[briefcase.2022_09_12-20_45_48.run.log](https://github.com/beeware/briefcase/files/9552647/briefcase.2022_09_12-20_45_48.run.log)

**Comment by rmartin16** [comment]
As best I can tell, this is rooted in the fact the host filesystem is being exposed to the sandbox for installing Python dependencies.

```
  - name: app_packages
    buildsystem: simple
    build-options:
      build-args:
        - --filesystem=host  # For local requirements.
        - --share=network  # For downloaded requirements.
    build-commands:
      - pip3 install -r requirements.txt
    sources:
      - type: file
        path: requirements.txt
```

**Comment by freakboy3742** [comment]
Whelp... that's annoying. Would passing in a `--cache-dir` argument to pip call in the manifest, using a location that is on the sandbox filesystem (or in the bundle folder) address this problem?

**Comment by freakboy3742** [comment]
`--no-cache-dir` would also be an option - and might be a good idea on AppImages as well, as it might avoid the cache directory permission warning...

**Comment by rmartin16** [comment]
Yeah; I tried `--no-cache-dir` after I realized the issue and that forced `pip` to rebuild the wheel each time it is installed. However, I also get a flatpak-builder cache hit after it runs the first time. This would likely be the simplest solution.

**Comment by freakboy3742** [comment]
Yeah - I agree that requiring a rebuild is less than ideal; however:

1. Working but requiring a recompile is better than fast but not working :-)
2. We have to recompile all of CPython every time anyway, so it's not like Flatpak has a particularly time-optimised experience to start with. 

A faster build is definitely preferable - but I'm happy to accept a slightly slower when the "fast" behavior is, at best, problematic.
