### ISSUE TITLE
Remove the `--no-sign` option and warn the user about `--adhoc-sign` on macOS applications

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#865]
The `package` command provides `--no-sign` and `--adhoc-sign` options. 

This is only used on macOS. Previously, macOS allowed completely unsigned apps and DMGs. However, as of macOS 12 (Monterey), apps *must* be signed to be able to run at all; and adhoc-signed apps won't be usable on any computer other than the one that created the app. Adhoc signing is useful for local testing, but completely unsigned apps are no longer possible on macOS.

**Describe the solution you'd like**

The `--no-sign` option should be removed. AdHoc signing should become the default signing option for all packaging on all platforms. This should be interpreted as "perform the minimal signing necessary to allow this app to run" - on Windows and Linux, this means "no signing".

Using the `--adhoc-sign` option on macOS should prominently warn the user that the app will work, but will not be re-distributable. 

**Describe alternatives you've considered**

We could retain the `--no-sign` option and make it raise an error; however, that's not a great user experience. As macOS is the only platform that performs signing at present, it makes sense to repurpose "adhoc" signing as "do the minimum legal signing".

**Comment by mhsmith** [comment]
> macOS is the only platform that performs signing at present

Signing support should also be added for Android. This isn't necessary for *running* an app, because Gradle will just sign it with an [auto-generated key](https://developer.android.com/studio/publish/app-signing#debug-mode) which is different for each build machine. But for [releasing on Google Play](https://developer.android.com/studio/publish/app-signing#sign-apk), you need to settle on one key and then use it consistently.

How about replacing `--no-sign`, `--adhoc-sign` and `--identity` with a single `--sign` option?
* When `--sign` is not provided, Briefcase will "perform the minimal signing necessary to allow this app to run".
* When `--sign` is provided, it takes one argument which is interpreted in a platform-specific way. On macOS this is "either the 40-digit hex checksum, or the full name of the identity". On Android, this would be the path to the keystore file.

**Comment by freakboy3742** [comment]
Completely agreed that we need to expand signing support onto all other platforms. There's analogous support needed on iOS (which will be a pre-requisite for #860); Windows and Linux both have signing conventions as well.

I think the UX cleanup you've suggested makes sense as well. "adhoc" signing is very macOS-loaded language; "minimal viable signing" is something every platform can support (with warnings if necessary if the resulting binary won't be redistributable); and having a single option would map to the end-user's understanding of something that is being done to the build/packaging step. 

The only question/alternative I'd offer is whether to add a new `--sign` or use the existing `--identity` to drive this functionality. To my reading, `--sign` semi-implies that signing is optional - if you don't use the option, the app won't be signed. This won't be true on macOS, or on any signing-required platform (such as Android or iOS for app release). `--identity` implies that signing will be performed as required by a platform, but the identity that will be used is configurable (with adhoc/fallback identities being used by default). As an added bonus, the `--identity` option already exists, so the migration path is a little cleaner (we only need to make `--adhoc-sign` and `--no-sign` no-ops).

**Comment by mhsmith** [comment]
Yes, that all sounds reasonable.

**Comment by fedelibre** [comment]
> The `package` command provides `--no-sign` and `--adhoc-sign` options.
> 
> This is only used on macOS. Previously, macOS allowed completely unsigned apps and DMGs. However, as of macOS 12 (Monterey), apps _must_ be signed to be able to run at all

@freakboy3742 Any chance to get the `--no-sign` option back?

Unsigned apps *can be run* on macOS. Open source applications, especially small projects, don't want to spend $99 per year to join the Apple Developer Program.

I'm trying to use briefcase to build Windows and macOS packages for [this application](https://github.com/frescobaldi/frescobaldi/pull/1859), but this seems a showstopper.

**Comment by freakboy3742** [comment]
> Unsigned apps _can be run_ on macOS. 

Is it *technically* possible? Sure - but you have turn off layers of protection at the operating system level; and even then, your first run isn't a "just click to run" - you need to start the app in a specific way, select and option, click OK...

This isn't how any reasonable end-user would expect to be able to run an app.

Also -  be aware that this *might* not be apparent if you're testing a build on your own machine. *Some* of these security measures don't exist for apps that are running on the platform where they were built. They also tend to be less strict on older x86-64 hardware. 

There's also every indication that these security checks are getting *more* restrictive with every release - going from "no checks" to "checked, but you can right click when starting the app to accept the risk",  to "You need to disable security checks at the operating system level *and* right click the app"... it doesn't seem that much of a stretch that at some point in the not too distant future *all* options for 

> Open source applications, especially small projects, don't want to spend $99 per year to join the Apple Developer Program.

They may not *want* to; but Apple sets the rules for their platform. It doesn't matter what ideological objections they may have - the rules are the rules.

> Any chance to get the --no-sign option back?

I'm not *fundamentally* opposed to re-introducing `--no-sign` as an option. However:
* It will need to be *explicitly* opt in, not the default as it was previously
* The help and documentation for the option must explicitly advise *against* using the option,
* Actually using the option must generate a *big* warning that the app will result in an app that is unrunable for most users without taking extraordinary steps.
* I'm not going to write the patch myself. It's up to a motivated user (like yourself) to do the work.
