### ISSUE TITLE
`briefcase new` should show which repository and branch it's using

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase#880]
`briefcase create` logs the repository and branch it's using:
```
[tmp] Generating application template...
Assigning tmp an application GUID of 000e29b3-1909-5d18-a892-2515bd585f58
Using app template: https://github.com/beeware/briefcase-windows-app-template.git, branch v0.3.10
Using existing template (sha f0d27880768f39f22c639a9e1abd8c7864072f0a, updated Tue Sep 20 15:53:52 2022)
```

But `briefcase new` doesn't include this information, which makes it inconvenient to verify whether it's doing the right thing:
```
Generating a new application 'tmp'
Using existing template (sha 46a68c2daad0c3b1c53e4b04e105cefa2586c9af, updated Tue Sep 27 14:18:02 2022)
```

Maybe the log line that gives the repository and branch could be moved into the lower-level `generate_template` function. Not only would that fix this issue, it would also make it clear what's happening when briefcase falls back to the `main` branch.

**Comment by freakboy3742** [comment]
That's a good idea. It might also be work including the Briefcase version as a comment in the `pyproject.toml` file that is generated;

**Comment by CuriousLearner** [comment]
I'm trying to work on this one.
