### ISSUE TITLE
Write logs to a subdirectory

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase#883]
**Is your feature request related to a problem? Please describe.**
As discussed in #760, we currently put log files directly in the top-level project folder. However, after a few failed runs this starts to get cluttered and obscure the view of the other files. So the user will probably delete the logs to get them out of the way, potentially losing useful information.

**Describe the solution you'd like**
How about writing the logs to a "logs" subdirectory of the project folder? Since this is a directory the user won't constantly be navigating through, they'll be under no pressure to delete the logs prematurely.

This directory should also be added to the default .gitignore file. `briefcase.*.log` is currently in the *top-level* .gitignore file in https://github.com/beeware/briefcase-template, but not in the .gitignore file within the template itself, which I guess is a mistake.

**Comment by freakboy3742** [comment]
This is a really elegant (and obvious) solution; +1!

**Comment by mhsmith** [comment]
If BeeWare fails to find a project because it's running in the wrong directory, then there's no obvious place to write a log file, but I don't think a log file would be useful in that situation anyway.

**Comment by freakboy3742** [comment]
Agreed - I've got stray `briefcase.*.log` files all over my filesystem in locations where there isn't a project to operate upon; in those situations, *not* producing a log file at all would seem the appropriate behavior.
