### ISSUE TITLE
Output streaming doesn't work on `briefcase dev`

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#891]
`print()` (and other stdout content) isn't reflected in the console when running `briefcase dev`.

**To Reproduce**
1. Run toga tutorial0 with `briefcase dev`
2. Click the button several times

There's no error, but:
* On Windows and Linux, the output isn't flushed until you quit the app
* On macOS, the output isn't visible at all.

stderr content *is* printed to the console.

**Expected behavior**

`print()` statements should be reflected in the console.

**Environment:**
 - Operating System: Linux, macOS, Windows
 - Python version: 3.10
 - Software versions:
   - Briefcase: 0.3.10
   - Toga: 0.3.0.dev38

**Additional context**

Possibly introduced by 390ccb36?
 
If you disable `stream_output=True` on the invocation that starts the dev process, console output is restored; however, you lose the contents of stdout in the log file.

This doesn't appear to impact `briefcase run`, as full apps have very different processes for managing logs.

**Comment by mhsmith** [comment]
> Possibly introduced by https://github.com/beeware/briefcase/commit/390ccb36c78337291fb08735e10d9f58b65f8112?

I'm pretty sure I saw it before that on Windows. Specifically, I was trying to run `briefcase dev` in an Emacs compilation window, but I found that when exceptions were caught by the main loop, they didn't appear until after the process exited.

**Comment by richstokes** [comment]
Ran into this with the BeeWare tutorial (https://docs.beeware.org/en/latest/tutorial/tutorial-2.html) 

Nothing happens when you send a `print` command (MacOS).


`PYTHONUNBUFFERED=1 briefcase dev` fixes it

**Comment by freakboy3742** [comment]
@richstokes Yeah - that's effectively the fix that we've applied in #892. Apologies for the confusion during the BeeWare tutorial.
