### ISSUE TITLE
Packaged Apps: handle multiple entrypoints

### ISSUE THREAD

**Issue by andrewleech** [beeware/briefcase#90]
Multiple apps in the one codebase are possible to define using setuptools entrypoints.
On Windows and Linux this produces multiple shortcuts / executables in the installed distribution.
On other platforms where apps are fully packaged (macOS, iOS, tvOS, Android) this is not possible.

It would be better to be able to produce multiple packaged apps for each defined entrypoint. 

This means duplication of the codebase / python executable bot for most applications this should be a negligible overhead.

Previously discussed in https://github.com/pybee/briefcase/pull/75#discussion_r145683701

**Comment by freakboy3742** [comment]
This has been addressed in the 0.3 branch; it is now possible to package multiple apps inside a briefcase project.
