### ISSUE TITLE
Add command summary to `briefcase --help`

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase#907]
**Is your feature request related to a problem? Please describe.**

When I was first learning how to use Briefcase, I had trouble remembering what all the commands did. A brief overview in one place would have been very useful.

**Describe the solution you'd like**

`briefcase --help` should give a 1-line summary of what each command does, in the same style as `git --help`:
```
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index
   ...
```

It would also be useful to have this in the documentation, e.g. [here](https://briefcase.readthedocs.io/en/latest/reference/index.html).

**Comment by freakboy3742** [comment]
+1. The list of available commands is shown, but it definitely wouldn't hurt to have a short description of each command rather than requiring `briefcase create --help`, `briefcase build --help` etc just to work out what the commands are.
