### ISSUE TITLE
Add new packageing target macOS-Xcode project

### ISSUE THREAD

**Issue by Ocupe** [beeware/briefcase#91]
At the moment you can easily create a macOS app with `python setup.py macos` and it works nice.
As a addition to that it would be super nice to have the ability to build to a macOS/cocoa/Xcode project with a command like `python setup.py macos-xcode`. 

I know we can go directly from python to a executable app but I think there are benefits/possibilities for including macos/xcode as a possible packaging target.

Benefits:
* We could use the build in Xcode UITesing framework XCTest to perform unit as well as UITests.
* Uploading apps to the macOS app store?(not sure if there is a other way)?

**Comment by freakboy3742** [comment]
The 0.3 branch now allows for different output formats, so this is notionally possible. It's also possible to add a new output format as a third-party extension.

**Comment by freakboy3742** [comment]
This has now been addressed through the introduction of the Xcode backend for macOS.
