### ISSUE TITLE
Briefcase `v0.3.12.dev0+xxx` is not Treated as a Dev Version

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#926]
**Describe the bug**
The `dev` attribute of a `packaging.version.Version` object is the number from `dev#` in the version. When the number is `0`, the version is not treated as a dev version.

`create.py`
```python
            # If we're on a development branch, and the template branch was *not*
            # provided explicity, we can use a fallback development template.
            # Otherwise, re-raise the exception about the unsupported template version.
            if version.dev and app.template_branch is None:
```

`new.py`
```python
            # If we're *not* on a development branch, raise an error about
            # the missing template branch.
            if not version.dev:
                raise
```

```python
❯ python
Python 3.10.7 (main, Sep 28 2022, 17:55:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from packaging.version import Version
>>> Version('0.3.12.dev1+gf0e822f.d20221016').dev
1
>>> Version('0.3.12.dev0+gf0e822f.d20221016').dev
0
```

**To Reproduce**
Run `briefcase create` or `briefcase new` with a `dev0` version.

**Expected behavior**
`dev0` versions are dev versions.

**Environment:**
 - Operating System: Ubuntu 22
 - Python version: 3.10
 - Software versions:
   - Briefcase: `0.3.12.dev0+gf0e822f.d20221016`

**Comment by freakboy3742** [comment]
Ah - I saw this, and 🤦 . The irony is that by applying this patch, the problem goes away... because you're no longer on dev0+ :-)
