### ISSUE TITLE
Error while building project. ANDROID

### ISSUE THREAD

**Issue by Bodzio122333** [beeware/briefcase#941]
**Describe the bug**

Error while building project.

Log saved to C:\Users\Admin\beeware-tutorial\helloworld\logs\briefcase.2022_10_24-13_41_35.build.log

(beeware-venv) C:\Users\Admin\beeware-tutorial\helloworld>briefcase run android

[helloworld] Building Android APK...

FAILURE: Build failed with an exception.

**Expected behavior**

**Screenshots**

**Environment:**
 OS Release:      Windows 10
OS Version:      10.0.19044
Architecture:    AMD64
Platform:        Windows-10-10.0.19044-SP0

Python exe:      c:\users\admin\beeware-tutorial\beeware-venv\scripts\python.exe
Python version:  3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Virtual env:     True
Conda env:       False

Briefcase:       0.3.11
Target platform: android
Target format:   gradle

**Comment by Bodzio122333** [comment]
(beeware-venv) C:\Users\Admin\beeware-tutorial\helloworld>briefcase build android

[helloworld] Building Android APK...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: NDK at C:\Users\Admin\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\ndk\21.4.7075529 did not have a source.properties file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Building...

Error while building project.

Log saved to C:\Users\Admin\beeware-tutorial\helloworld\logs\briefcase.2022_10_25-08_45_28.build.log


(beeware-venv) C:\Users\Admin\beeware-tutorial\helloworld>


![image](https://user-images.githubusercontent.com/21276867/197702513-d38f959b-421f-47a1-bef4-6dd51f1f5ce1.png)

**Comment by freakboy3742** [comment]
The error message says: 
```
C:\Users\Admin\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\ndk\21.4.7075529 did not have a source.properties file
```
Can you show us what *is* in that folder?

**Comment by Bodzio122333** [comment]
![image](https://user-images.githubusercontent.com/21276867/197707291-aab785c0-d51b-49de-a449-07feaddeed2b.png)

**Comment by freakboy3742** [comment]
This indicates you've got an incomplete NDK installation - an installation has started, but it is incomplete; but this incomplete download state is confusing the Android toolchain.

Deleting the `21.4.7075529` folder and re-running `briefcase build android` should be enough to correct the problem.

**Comment by mhsmith** [comment]
@Bodzio122333: I hope that was enough to help you solve the problem. If you still need help, please post a comment below.

**Comment by Bodzio122333** [comment]
Thanks for All. Everything work correct :)
