### ISSUE TITLE
"must supply either home or prefix/exec-prefix -- not both")

### ISSUE THREAD

**Issue by jhavens12** [beeware/briefcase#95]
When running the simple helloworld tutorial on OSX, i get the error when running the command 

`python setup.py ios -s`

The app gets installed on the virtual iphone but the app just crashes when opened, does not display the "hello world text"

Also get the following error at the same time:

`Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/9g/d1z5c7lx74z35rd_yshmtv_h0000gq/T/pip-rt3s9ur7-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/9g/d1z5c7lx74z35rd_yshmtv_h0000gq/T/pip-3xyqi48k-record/install-record.txt --single-version-externally-managed --compile --home=/var/folders/9g/d1z5c7lx74z35rd_yshmtv_h0000gq/T/tmp8sx0itp9" failed with error code 1 in /private/var/folders/9g/d1z5c7lx74z35rd_yshmtv_h0000gq/T/pip-rt3s9ur7-build/`

**Comment by cepages** [comment]
Same here but without any error in the command line. Just a white screen

**Comment by freakboy3742** [comment]
I believe this was a problem with the Python 3.6 template at the time; AFAIK, this problem has since been resolved.
