### ISSUE TITLE
Remove need to install Android NDK

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase#950]
The current Android template requires the NDK in order to build the stdout/stderr redirection code in app/src/main/cpp/native-lib.cpp. This significantly slows down the first build (https://github.com/beeware/toga/issues/1144), and consumes several GB of disk space, so I think this feature should be merged into Chaquopy so the user doesn't need to compile it themselves (https://github.com/chaquo/chaquopy/issues/725).

When I wrote:

> We shouldn't enable this by default, because it might conflict with other native code that's doing the same thing.

That applies to Chaquopy, which could be used in any kind of app. But Briefcase is a higher-level tool with control over the entire app, so we know that enabling the redirection is safe.

**Comment by freakboy3742** [comment]
@mhsmith This was effectively achieved in the changes in Briefcase 0.3.12, correct?

**Comment by mhsmith** [comment]
Yes, it was.
