### ISSUE TITLE
briefcase package not working

### ISSUE THREAD

**Issue by rajatanand86** [beeware/briefcase#968]
I am following the tutorial: https://docs.beeware.org/en/latest/tutorial/tutorial-3.html
When I run briefcase package, I get the following error.
heat.exe-The application could not be started.

I have already installed the latest  .net [framework,](url) but doesnt seem to help.
Screenshot attached.

![beeware](https://user-images.githubusercontent.com/63897455/201304681-65badd4b-3f8c-49c2-b74a-b7c7f27fc496.png)
**Environment:**

 - Operating System: Windows 10
 - Python version is 3.9.13
Attaching the log file, if it helps.
[briefcase.2022_11_11-14_52_30.package.log](https://github.com/beeware/briefcase/files/9988927/briefcase.2022_11_11-14_52_30.package.log)

**Comment by rmartin16** [comment]
Hello @rajatanand86,
Can you check if you're affected by https://github.com/beeware/briefcase/issues/922?

I'd also check that .NET 3.5 is installed/enabled.

**Comment by freakboy3742** [comment]
Closing due to lack of response.
