### ISSUE TITLE
"Unable to download pixel_3a device skin; is your computer offline?"

### ISSUE THREAD

**Issue by xiaolinpeter** [beeware/briefcase#976]
hi , when briefcase run android, i get a error, the error is Unable to download pixel_3a device skin; is your computer offline? i hope someone give me suggestion, thank you very much, the detail as follw

<img width="540" alt="1669292771761" src="https://user-images.githubusercontent.com/27184803/203785827-33a2abb0-d19c-494b-9942-470e8286e06f.png">

briefcase.2022_11_24-20_02_28.run.log as follow:
![image](https://user-images.githubusercontent.com/27184803/203785334-5c8ea3b4-a6fb-4881-a2e7-acace06a8ca8.png)
![image](https://user-images.githubusercontent.com/27184803/203785532-3c8c2b50-9d52-4525-865d-98c5e3bc9917.png)

**Comment by mhsmith** [comment]
According to some of [these tools](https://www.google.com/search?q=china+firewall+test), https://android.googlesource.com is blocked in China. Try using a VPN.

**Comment by mhsmith** [comment]
However, it does seem strange that we're downloading these skins from a Git repository: I doubt that's what Android Studio does. So perhaps there's some other non-blocked site we could use instead.

**Comment by freakboy3742** [comment]
FWIW, the Git repository is the only place I've been able to find an archive of these resources; if there's another (more official) source, I'd definitely prefer to use that. 

See also #388 for the general problem of being able to run Briefcase while offline.

**Comment by xiaolinpeter** [comment]
> 根据其中一些[工具](https://www.google.com/search?q=china+firewall+test)，[https](https://android.googlesource.com) ://android.googlesource.com 在中国被屏蔽了。尝试使用 VPN。
thanks your reply, but the same error Appear
![image](https://user-images.githubusercontent.com/27184803/204117578-4bf22cb9-acee-44e9-82fe-259bf4398c36.png)
[briefcase.2022_11_27-11_08_44.run.log](https://github.com/beeware/briefcase/files/10097447/briefcase.2022_11_27-11_08_44.run.log)

**Comment by xiaolinpeter** [comment]
> FWIW，Git 存储库是我唯一能够找到这些资源存档的地方；如果有另一个（更官方的）来源，我肯定更愿意使用它。
> 
> 另请参阅#388，了解在离线时能够运行公文包的一般问题。

thansk your reply, but the same error appear
![image](https://user-images.githubusercontent.com/27184803/204117715-626bff57-4f9a-45bf-9abc-8191da4d575d.png)

[briefcase.2022_11_27-11_08_44.run.log](https://github.com/beeware/briefcase/files/10097448/briefcase.2022_11_27-11_08_44.run.log)

**Comment by xiaolinpeter** [comment]
> > 根据其中一些[工具](https://www.google.com/search?q=china+firewall+test)，https://android.googlesource.com在中国被屏幕骗了。尝试使用VPN。

![image](https://user-images.githubusercontent.com/27184803/204117724-1f3e827c-ac73-45ab-9676-b3e703158be2.png)

**Comment by rmartin16** [comment]
The underlying error suggests that `requests` (but really `urllib`) is [inheriting](https://requests.readthedocs.io/en/latest/user/advanced/?highlight=proxy#proxies) proxy settings from the Windows configuration.
```
│ ┌───────────────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────────────┐                                             │
│ │    cert = None                                                                                                                   │                                             │
│ │ chunked = False                                                                                                                  │                                             │
│ │    conn = <urllib3.connectionpool.HTTPSConnectionPool object at 0x00000236F8261F70>                                              │                                             │
│ │ proxies = OrderedDict([('http', 'http://127.0.0.1:4780'), ('https', 'https://127.0.0.1:4780'), ('ftp', 'ftp://127.0.0.1:4780')]) │                                             │
│ │ request = <PreparedRequest [GET]>                                                                                                │                                             │
│ │    self = <requests.adapters.HTTPAdapter object at 0x00000236F8229F10>                                                           │                                             │
│ │  stream = True                                                                                                                   │                                             │
│ │ timeout = Timeout(connect=None, read=None, total=None)                                                                           │                                             │
│ │     url = '/platform/tools/adt/idea/+archive/refs/heads/mirror-goog-studio-main/artwork/res'+43                                  │                                             │
│ │  verify = True                                                                                                                   │                                             │
│ └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘                                             │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ProxyError: HTTPSConnectionPool(host='android.googlesource.com', port=443): Max retries exceeded with url: /platform/tools/adt/idea/+archive/refs/heads/mirror-goog-studio-main/artwork/resources/device-art-resources/pixel_3a.tar.gz (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
```

I don't think I knew that `urllib` would [attempt to use](https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies) system configured proxies.

Nonetheless, python is erroring during the SSL handshake.
```
│ C:\Users\admin\.conda\envs\py385\lib\ssl.py:1309 in do_handshake                                                                                                                 │
│                                                                                                                                                                                  │
│   1306 │   │   try:                                                                                                                                                              │
│   1307 │   │   │   if timeout == 0.0 and block:                                                                                                                                  │
│   1308 │   │   │   │   self.settimeout(None)                                                                                                                                     │
│ > 1309 │   │   │   self._sslobj.do_handshake()                                                                                                                                   │
│   1310 │   │   finally:                                                                                                                                                          │
│   1311 │   │   │   self.settimeout(timeout)                                                                                                                                      │
│   1312                                                                                                                                                                           │
│                                                                                                                                                                                  │
│ ┌─────────────────────────────────────────────────── locals ───────────────────────────────────────────────────┐                                                                 │
│ │   block = False                                                                                              │                                                                 │
│ │    self = <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0> │                                                                 │
│ │ timeout = None                                                                                               │                                                                 │
│ └──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘                                                                 │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
OSError: [Errno 0] Error
```

Shortly after Python 3.8.5, this `OSError: [Errno 0]` exception was [replaced](https://bugs.python.org/issue31122) with a `SSLEOFError` exception.

Given this error is only happening now when trying to download the Android emulator skin, I'm assuming the other requisite downloads used this proxy successfully.

A few things perhaps worth trying:
- Can you download the [skin](https://android.googlesource.com/platform/tools/adt/idea/+archive/refs/heads/mirror-goog-studio-main/artwork/resources/device-art-resources/pixel_3a.tar.gz) manually?
  - If so, it can be manually unzipped into `C:/Users/admin/AppData/Local/BeeWare/briefcase/Cache/tools/android_sdk/skins/pixel_3a`
- Reviewing logs in the proxy for why the connection is being seemingly rejected.
- Removing the system configuration for a proxy at `127.0.0.1:4780`.
- Alternatively, [setting](https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler) an environment variable named `no_proxy` to `android.googlesource.com` may prevent this request from using this proxy setting.

**Comment by xiaolinpeter** [comment]
> The underlying error suggests that `requests` (but really `urllib`) is [inheriting](https://requests.readthedocs.io/en/latest/user/advanced/?highlight=proxy#proxies) proxy settings from the Windows configuration.
> 
> ```
> │ ┌───────────────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────────────┐                                             │
> │ │    cert = None                                                                                                                   │                                             │
> │ │ chunked = False                                                                                                                  │                                             │
> │ │    conn = <urllib3.connectionpool.HTTPSConnectionPool object at 0x00000236F8261F70>                                              │                                             │
> │ │ proxies = OrderedDict([('http', 'http://127.0.0.1:4780'), ('https', 'https://127.0.0.1:4780'), ('ftp', 'ftp://127.0.0.1:4780')]) │                                             │
> │ │ request = <PreparedRequest [GET]>                                                                                                │                                             │
> │ │    self = <requests.adapters.HTTPAdapter object at 0x00000236F8229F10>                                                           │                                             │
> │ │  stream = True                                                                                                                   │                                             │
> │ │ timeout = Timeout(connect=None, read=None, total=None)                                                                           │                                             │
> │ │     url = '/platform/tools/adt/idea/+archive/refs/heads/mirror-goog-studio-main/artwork/res'+43                                  │                                             │
> │ │  verify = True                                                                                                                   │                                             │
> │ └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘                                             │
> └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> ProxyError: HTTPSConnectionPool(host='android.googlesource.com', port=443): Max retries exceeded with url: /platform/tools/adt/idea/+archive/refs/heads/mirror-goog-studio-main/artwork/resources/device-art-resources/pixel_3a.tar.gz (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
> ```
> 
> I don't think I knew that `urllib` would [attempt to use](https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies) system configured proxies.
> 
> Nonetheless, python is erroring during the SSL handshake.
> 
> ```
> │ C:\Users\admin\.conda\envs\py385\lib\ssl.py:1309 in do_handshake                                                                                                                 │
> │                                                                                                                                                                                  │
> │   1306 │   │   try:                                                                                                                                                              │
> │   1307 │   │   │   if timeout == 0.0 and block:                                                                                                                                  │
> │   1308 │   │   │   │   self.settimeout(None)                                                                                                                                     │
> │ > 1309 │   │   │   self._sslobj.do_handshake()                                                                                                                                   │
> │   1310 │   │   finally:                                                                                                                                                          │
> │   1311 │   │   │   self.settimeout(timeout)                                                                                                                                      │
> │   1312                                                                                                                                                                           │
> │                                                                                                                                                                                  │
> │ ┌─────────────────────────────────────────────────── locals ───────────────────────────────────────────────────┐                                                                 │
> │ │   block = False                                                                                              │                                                                 │
> │ │    self = <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0> │                                                                 │
> │ │ timeout = None                                                                                               │                                                                 │
> │ └──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘                                                                 │
> └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> OSError: [Errno 0] Error
> ```
> 
> Shortly after Python 3.8.5, this `OSError: [Errno 0]` exception was [replaced](https://bugs.python.org/issue31122) with a `SSLEOFError` exception.
> 
> Given this error is only happening now when trying to download the Android emulator skin, I'm assuming the other requisite downloads used this proxy successfully.
> 
> A few things perhaps worth trying:
> 
> * Can you download the [skin](https://android.googlesource.com/platform/tools/adt/idea/+archive/refs/heads/mirror-goog-studio-main/artwork/resources/device-art-resources/pixel_3a.tar.gz) manually?
>   
>   * If so, it can be manually unzipped into `C:/Users/admin/AppData/Local/BeeWare/briefcase/Cache/tools/android_sdk/skins/pixel_3a`
> * Reviewing logs in the proxy for why the connection is being seemingly rejected.
> * Removing the system configuration for a proxy at `127.0.0.1:4780`.
> * Alternatively, [setting](https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler) an environment variable named `no_proxy` to `android.googlesource.com` may prevent this request from using this proxy setting.

thanks your reply

**Comment by mhsmith** [comment]
![image](https://user-images.githubusercontent.com/27184803/204117578-4bf22cb9-acee-44e9-82fe-259bf4398c36.png)

Yes, that's what the first result says (http://www.chinafirewalltest.com/), but the next 3 all say it's blocked:

* https://www.dotcom-tools.com/china-firewall-test - python.org also fails, so the service is probably broken
* https://www.vpnmentor.com/tools/test-the-great-china-firewall/ - python.org is OK
* https://www.websitepulse.com/tools/china-firewall-test - python.org is OK

**Comment by FarrellWilson** [comment]
楼主问题解决了吗？我也遇到这种问题了，在参考beeware教程时安装安卓虚拟机时出错
![Uploading 1.png…]()

**Comment by mhsmith** [comment]
I don't think anything has changed on our side.
