### ISSUE TITLE
when i run briefcase bulid andriod, the detail as follw ( cannot install mediapipe in androidavd)

### ISSUE THREAD

**Issue by xiaolinpeter** [beeware/briefcase#979]
1.  the bug as follow
![image](https://user-images.githubusercontent.com/27184803/204137537-5a70bd11-13c3-435e-b913-5a385729bf03.png)
2 the pyproject.toml as follow
![image](https://user-images.githubusercontent.com/27184803/204137456-8a53825b-119a-433c-9572-f7775c6c815e.png)

I hope someone give me suggesition, thank you very much

**Comment by mhsmith** [comment]
Unfortunately mediapipe isn't supported on Android yet. For more information, see https://github.com/chaquo/chaquopy/issues/479.
