### ISSUE TITLE
What is it ??  "Unable to download support package; is your computer offline? "

### ISSUE THREAD

**Issue by zeroche72** [beeware/briefcase#980]
I succeeded until the Hello World window.
However, the following error occurred in briefcase create.
What is the cause.. please help..

-----------------------------------------------------------

(beeware-venv) C:\0beeware\beeware-tutorial\helloworld>briefcase create

[helloworld] Generating application template...
Assigning helloworld an application GUID of 93bbf2ae-12d0-580c-aeb0-965dc4c04b69
Using app template: https://github.com/beeware/briefcase-windows-app-template.git, branch v0.3.11
Using existing template (sha 1af3081cbe8ac48e04972d64cecab04487f78ff5, updated Tue Nov 1 12:56:54 2022)

[helloworld] Installing support package...
Using support package https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip

Unable to download support package; is your computer offline?

Log saved to C:\0beeware\beeware-tutorial\helloworld\logs\briefcase.2022_11_28-15_13_09.create.log

**Comment by rmartin16** [comment]
Can you upload `C:\0beeware\beeware-tutorial\helloworld\logs\briefcase.2022_11_28-15_13_09.create.log` to this issue?

**Comment by zeroche72** [comment]
The file requires administrator permission.
But some of them are below.
The file will be resent when permitted.
Thank you.
-----------------------------------------------------
~~~~~
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)

During handling of the above exception, another exception occurred:
~~~~~
MaxRetryError: HTTPSConnectionPool(host='www.python.org', port=443): Max retries exceeded with url: /ftp/python/3.8.10/python-3.8.10-embed-amd64.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:
~~~~~
SSLError: HTTPSConnectionPool(host='www.python.org', port=443): Max retries exceeded with url: /ftp/python/3.8.10/python-3.8.10-embed-amd64.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:
~~~~~
NetworkFailure: Unable to download support package; is your computer offline?

**Comment by mhsmith** [comment]
It looks like you have a proxy server interfering with your connection. Check your network settings, or consult your system administrator.

**Comment by zeroche72** [comment]
Thank you first
I use the corporate network.
So it seems to be a network configuration problem.
But we will find the answer as always.
I would be grateful if you could give me even a little bit of information.

**Comment by freakboy3742** [comment]
@zeroche72 Unfortunately, we're not in a position to tell you anything about how *your* network is configured. All we can tell you is that it appears that something is inserting itself into the "normal" process of requesting the URL - a proxy server would be the obvious candidate.

Briefcase is trying to download the file `https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip`. You need to speak to your network administrator to ensure that URL can be accessed from your machine.

**Comment by zeroche72** [comment]
Enter the address below in Chrome
The file is downloaded.
Is it still a network problem?

https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip.

Result: python-3.8.10-embed-amd64.zip

**Comment by freakboy3742** [comment]
Yes, It's still a network problem - because that's what the error message you've posted is telling us. It's entirely likely that Chrome isn't configured to use the same network configuration as Python. 

The real test is whether the following works from inside a Python shell:
```
import requests
response = requests.get('https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip')

print(response.status_code)
print(len(response.content))
```
This is effectively what Briefcase is doing internally; unless this works on your machine, Briefcase won't work.

**Comment by zeroche72** [comment]
Thank you everyone.
This issue was a permission issue of the company network.
so i did it at home.
No problem.
Thank you again.

**Comment by freakboy3742** [comment]
Glad you were able to resolve the problem.
