### ISSUE TITLE
Purge (or don't copy) `__pycache__` folders when installing app sources

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#986]
When application sources are installed, the complete contents of the named folders are copied.

If the application has previously been executed in dev mode, there will be `__pycache__` folders in the copied code. This won't *break* anything, but it can lead to very confusing stack traces, as the code location named in the cached byte code files won't match the location of the installed code that is being executed.

**Describe the solution you'd like**

When application sources are installed, the install process should either:

1. Purge `__pycache__` folders as a final step
2. Not copy `__pycache__` folders in the first place; or

Option (1) will likely be easiest - it could be as simple as adding a default `**/__pycache__` glob to the paths that are automatically cleaned up during `cleanup_app_content()`.

Option (2) potentially has conceptual overlap with #975; if we're tackling that ticket, it may be worth adding automated `__pycache__` exclusion to the feature set of that change.

**Describe alternatives you've considered**

Do nothing. Stack traces (and pytest logs) will be a little confusing; but nothing will *break*.

**Comment by Matheus920** [comment]
Hello, I would like to contribute on this issue.

**Comment by freakboy3742** [comment]
@Matheus920 Go right ahead! A PR covering option (1) will be more than acceptable as a first pass; if you need any pointers or assistance, let us know!

**Comment by tuhinmallick** [comment]
Is this issue still available then I would like to give it a try.

**Comment by freakboy3742** [comment]
@tuhinmallick AFAIK it's still available; @Matheus920 expressed an interest last week, but we haven't seen any PR resulting from that work. @Matheus920 if you're still working on this, leave a comment to let us know that you're still working on this.

**Comment by tuhinmallick** [comment]
@freakboy3742 Okay

**Comment by freakboy3742** [comment]
FYI - Option (1) has been implemented as part of #1081.

**Comment by freakboy3742** [comment]
I'm going to close this as a specific feature request; as previously noted, it's functionally implemented as of Briefcase 0.3.13. Moving to option (2) would be part of a more comprehensive "What is copied for install" enhancement described by #975.
